"""
Brand Metrics Database for Home / Bedding / Organizer DTC Brands
================================================================
Contains engagement metrics, pricing estimates, and category defaults
for 200+ DTC brands in the home, bedding, and organizer space.

Sources: SimilarWeb-style traffic estimates, public financial data,
product catalog pricing, and category benchmarks.
"""

BRAND_METRICS = {
    # =====================================================================
    # BEDDING & SHEETS
    # =====================================================================
    "Brooklinen": {
        "founded": 2014,
        "traffic": 2400000,
        "bounce_pct": 38.5,
        "pages_visit": 4.2,
        "session_sec": 215,
        "aov": 145,
        "product_count": 120,
        "good_upsell": True,
    },
    "Parachute Home": {
        "founded": 2014,
        "traffic": 1600000,
        "bounce_pct": 40.2,
        "pages_visit": 3.8,
        "session_sec": 200,
        "aov": 160,
        "product_count": 200,
        "good_upsell": True,
    },
    "Boll & Branch": {
        "founded": 2014,
        "traffic": 1100000,
        "bounce_pct": 42.0,
        "pages_visit": 3.6,
        "session_sec": 190,
        "aov": 195,
        "product_count": 80,
        "good_upsell": True,
    },
    "Cozy Earth": {
        "founded": 2007,
        "traffic": 1800000,
        "bounce_pct": 39.0,
        "pages_visit": 3.9,
        "session_sec": 210,
        "aov": 200,
        "product_count": 70,
        "good_upsell": True,
    },
    "Riley Home": {
        "founded": 2019,
        "traffic": 350000,
        "bounce_pct": 44.0,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 120,
        "product_count": 40,
        "good_upsell": True,
    },
    "Ettitude": {
        "founded": 2014,
        "traffic": 320000,
        "bounce_pct": 43.5,
        "pages_visit": 3.5,
        "session_sec": 180,
        "aov": 130,
        "product_count": 55,
        "good_upsell": True,
    },
    "Sijo": {
        "founded": 2019,
        "traffic": 250000,
        "bounce_pct": 44.5,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 140,
        "product_count": 35,
        "good_upsell": True,
    },
    "Cultiver": {
        "founded": 2014,
        "traffic": 180000,
        "bounce_pct": 45.0,
        "pages_visit": 3.6,
        "session_sec": 195,
        "aov": 180,
        "product_count": 60,
        "good_upsell": False,
    },
    "Rough Linen": {
        "founded": 2011,
        "traffic": 90000,
        "bounce_pct": 48.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 175,
        "product_count": 40,
        "good_upsell": False,
    },
    "Linoto": {
        "founded": 2007,
        "traffic": 60000,
        "bounce_pct": 50.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 160,
        "product_count": 30,
        "good_upsell": False,
    },
    "MagicLinen": {
        "founded": 2017,
        "traffic": 400000,
        "bounce_pct": 42.5,
        "pages_visit": 3.7,
        "session_sec": 190,
        "aov": 130,
        "product_count": 100,
        "good_upsell": True,
    },
    "Piglet in Bed": {
        "founded": 2017,
        "traffic": 280000,
        "bounce_pct": 43.0,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 150,
        "product_count": 70,
        "good_upsell": True,
    },
    "Tekla": {
        "founded": 2017,
        "traffic": 350000,
        "bounce_pct": 41.0,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 170,
        "product_count": 45,
        "good_upsell": False,
    },
    "Cariloha": {
        "founded": 2007,
        "traffic": 450000,
        "bounce_pct": 43.0,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 140,
        "product_count": 90,
        "good_upsell": True,
    },
    "Bamboo Bay": {
        "founded": 2018,
        "traffic": 80000,
        "bounce_pct": 48.0,
        "pages_visit": 3.0,
        "session_sec": 150,
        "aov": 85,
        "product_count": 20,
        "good_upsell": False,
    },
    "PeachSkinSheets": {
        "founded": 2016,
        "traffic": 200000,
        "bounce_pct": 45.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 80,
        "product_count": 25,
        "good_upsell": True,
    },
    "Quince": {
        "founded": 2018,
        "traffic": 2000000,
        "bounce_pct": 37.0,
        "pages_visit": 4.5,
        "session_sec": 230,
        "aov": 90,
        "product_count": 300,
        "good_upsell": True,
    },
    "Sunday Citizen": {
        "founded": 2018,
        "traffic": 180000,
        "bounce_pct": 44.0,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 135,
        "product_count": 40,
        "good_upsell": True,
    },
    "Miracle Brand": {
        "founded": 2017,
        "traffic": 350000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 110,
        "product_count": 30,
        "good_upsell": True,
    },
    "Pact": {
        "founded": 2009,
        "traffic": 500000,
        "bounce_pct": 42.0,
        "pages_visit": 3.6,
        "session_sec": 185,
        "aov": 65,
        "product_count": 150,
        "good_upsell": True,
    },
    "Authenticity50": {
        "founded": 2014,
        "traffic": 50000,
        "bounce_pct": 50.0,
        "pages_visit": 2.8,
        "session_sec": 140,
        "aov": 185,
        "product_count": 15,
        "good_upsell": False,
    },
    "Coyuchi": {
        "founded": 1991,
        "traffic": 250000,
        "bounce_pct": 44.0,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 170,
        "product_count": 100,
        "good_upsell": True,
    },
    "Snowe Home": {
        "founded": 2015,
        "traffic": 120000,
        "bounce_pct": 46.0,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 130,
        "product_count": 60,
        "good_upsell": True,
    },
    "Silk & Snow": {
        "founded": 2017,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.4,
        "session_sec": 180,
        "aov": 150,
        "product_count": 25,
        "good_upsell": True,
    },
    "Buffy": {
        "founded": 2017,
        "traffic": 600000,
        "bounce_pct": 41.0,
        "pages_visit": 3.5,
        "session_sec": 180,
        "aov": 140,
        "product_count": 20,
        "good_upsell": True,
    },
    "Eucalypso": {
        "founded": 2017,
        "traffic": 45000,
        "bounce_pct": 49.0,
        "pages_visit": 3.0,
        "session_sec": 150,
        "aov": 110,
        "product_count": 15,
        "good_upsell": False,
    },
    "Bedfolk": {
        "founded": 2019,
        "traffic": 200000,
        "bounce_pct": 43.5,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 140,
        "product_count": 35,
        "good_upsell": True,
    },
    "Crisp Sheets": {
        "founded": 2017,
        "traffic": 60000,
        "bounce_pct": 47.0,
        "pages_visit": 3.1,
        "session_sec": 160,
        "aov": 125,
        "product_count": 20,
        "good_upsell": False,
    },
    "Italic": {
        "founded": 2018,
        "traffic": 300000,
        "bounce_pct": 43.0,
        "pages_visit": 3.8,
        "session_sec": 195,
        "aov": 100,
        "product_count": 200,
        "good_upsell": True,
    },
    "Citizenry": {
        "founded": 2014,
        "traffic": 350000,
        "bounce_pct": 42.0,
        "pages_visit": 3.6,
        "session_sec": 190,
        "aov": 175,
        "product_count": 250,
        "good_upsell": True,
    },
    "Kassatex": {
        "founded": 2004,
        "traffic": 150000,
        "bounce_pct": 45.0,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 95,
        "product_count": 120,
        "good_upsell": True,
    },
    "Crane & Canopy": {
        "founded": 2012,
        "traffic": 180000,
        "bounce_pct": 44.0,
        "pages_visit": 3.5,
        "session_sec": 180,
        "aov": 140,
        "product_count": 80,
        "good_upsell": True,
    },
    "Flaneur": {
        "founded": 2020,
        "traffic": 35000,
        "bounce_pct": 49.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 155,
        "product_count": 15,
        "good_upsell": False,
    },
    "Gryphon Home": {
        "founded": 2019,
        "traffic": 40000,
        "bounce_pct": 49.0,
        "pages_visit": 3.0,
        "session_sec": 150,
        "aov": 130,
        "product_count": 20,
        "good_upsell": False,
    },
    "Lunya": {
        "founded": 2014,
        "traffic": 600000,
        "bounce_pct": 40.0,
        "pages_visit": 3.7,
        "session_sec": 195,
        "aov": 140,
        "product_count": 60,
        "good_upsell": True,
    },
    "Lake Pajamas": {
        "founded": 2017,
        "traffic": 400000,
        "bounce_pct": 41.0,
        "pages_visit": 3.6,
        "session_sec": 190,
        "aov": 120,
        "product_count": 70,
        "good_upsell": True,
    },

    # =====================================================================
    # MATTRESSES & SLEEP
    # =====================================================================
    "Casper": {
        "founded": 2014,
        "traffic": 5500000,
        "bounce_pct": 40.0,
        "pages_visit": 3.8,
        "session_sec": 220,
        "aov": 950,
        "product_count": 40,
        "good_upsell": True,
    },
    "Purple": {
        "founded": 2015,
        "traffic": 4800000,
        "bounce_pct": 39.5,
        "pages_visit": 3.9,
        "session_sec": 230,
        "aov": 1200,
        "product_count": 35,
        "good_upsell": True,
    },
    "Saatva": {
        "founded": 2010,
        "traffic": 4200000,
        "bounce_pct": 38.0,
        "pages_visit": 4.1,
        "session_sec": 245,
        "aov": 1500,
        "product_count": 30,
        "good_upsell": True,
    },
    "Nolah": {
        "founded": 2015,
        "traffic": 800000,
        "bounce_pct": 42.5,
        "pages_visit": 3.5,
        "session_sec": 200,
        "aov": 1000,
        "product_count": 20,
        "good_upsell": True,
    },
    "DreamCloud": {
        "founded": 2018,
        "traffic": 2200000,
        "bounce_pct": 41.0,
        "pages_visit": 3.6,
        "session_sec": 210,
        "aov": 800,
        "product_count": 15,
        "good_upsell": True,
    },
    "Bear Mattress": {
        "founded": 2015,
        "traffic": 500000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 190,
        "aov": 900,
        "product_count": 15,
        "good_upsell": True,
    },
    "Nest Bedding": {
        "founded": 2011,
        "traffic": 400000,
        "bounce_pct": 43.5,
        "pages_visit": 3.5,
        "session_sec": 195,
        "aov": 850,
        "product_count": 30,
        "good_upsell": True,
    },
    "Eight Sleep": {
        "founded": 2014,
        "traffic": 1200000,
        "bounce_pct": 39.0,
        "pages_visit": 3.8,
        "session_sec": 225,
        "aov": 2300,
        "product_count": 10,
        "good_upsell": True,
    },
    "Helix Sleep": {
        "founded": 2015,
        "traffic": 1500000,
        "bounce_pct": 41.0,
        "pages_visit": 3.7,
        "session_sec": 215,
        "aov": 1000,
        "product_count": 20,
        "good_upsell": True,
    },
    "Leesa": {
        "founded": 2014,
        "traffic": 900000,
        "bounce_pct": 42.0,
        "pages_visit": 3.5,
        "session_sec": 200,
        "aov": 950,
        "product_count": 15,
        "good_upsell": True,
    },
    "Tuft & Needle": {
        "founded": 2012,
        "traffic": 1200000,
        "bounce_pct": 41.5,
        "pages_visit": 3.6,
        "session_sec": 205,
        "aov": 750,
        "product_count": 20,
        "good_upsell": True,
    },
    "Avocado Green Mattress": {
        "founded": 2015,
        "traffic": 900000,
        "bounce_pct": 41.0,
        "pages_visit": 3.7,
        "session_sec": 215,
        "aov": 1400,
        "product_count": 25,
        "good_upsell": True,
    },
    "Birch Living": {
        "founded": 2019,
        "traffic": 300000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 185,
        "aov": 1300,
        "product_count": 10,
        "good_upsell": True,
    },
    "Awara Sleep": {
        "founded": 2019,
        "traffic": 250000,
        "bounce_pct": 44.0,
        "pages_visit": 3.3,
        "session_sec": 180,
        "aov": 1000,
        "product_count": 10,
        "good_upsell": True,
    },
    "Nectar Sleep": {
        "founded": 2016,
        "traffic": 3000000,
        "bounce_pct": 40.5,
        "pages_visit": 3.6,
        "session_sec": 205,
        "aov": 700,
        "product_count": 15,
        "good_upsell": True,
    },
    "WinkBed": {
        "founded": 2016,
        "traffic": 350000,
        "bounce_pct": 44.0,
        "pages_visit": 3.4,
        "session_sec": 190,
        "aov": 1100,
        "product_count": 10,
        "good_upsell": True,
    },
    "PlushBeds": {
        "founded": 2008,
        "traffic": 250000,
        "bounce_pct": 44.5,
        "pages_visit": 3.3,
        "session_sec": 185,
        "aov": 1200,
        "product_count": 15,
        "good_upsell": True,
    },
    "Brooklyn Bedding": {
        "founded": 1995,
        "traffic": 600000,
        "bounce_pct": 42.5,
        "pages_visit": 3.5,
        "session_sec": 195,
        "aov": 900,
        "product_count": 25,
        "good_upsell": True,
    },
    "Amerisleep": {
        "founded": 2010,
        "traffic": 400000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 190,
        "aov": 1100,
        "product_count": 15,
        "good_upsell": True,
    },
    "Layla Sleep": {
        "founded": 2016,
        "traffic": 350000,
        "bounce_pct": 43.5,
        "pages_visit": 3.4,
        "session_sec": 185,
        "aov": 850,
        "product_count": 15,
        "good_upsell": True,
    },

    # =====================================================================
    # PILLOWS
    # =====================================================================
    "Pillow Cube": {
        "founded": 2019,
        "traffic": 500000,
        "bounce_pct": 43.0,
        "pages_visit": 3.2,
        "session_sec": 170,
        "aov": 70,
        "product_count": 15,
        "good_upsell": True,
    },
    "Coop Home Goods": {
        "founded": 2013,
        "traffic": 400000,
        "bounce_pct": 43.5,
        "pages_visit": 3.3,
        "session_sec": 175,
        "aov": 75,
        "product_count": 25,
        "good_upsell": True,
    },
    "Pluto Pillow": {
        "founded": 2019,
        "traffic": 150000,
        "bounce_pct": 45.0,
        "pages_visit": 3.1,
        "session_sec": 165,
        "aov": 95,
        "product_count": 10,
        "good_upsell": True,
    },
    "Purple Pillow": {
        "founded": 2015,
        "traffic": 300000,
        "bounce_pct": 42.0,
        "pages_visit": 3.3,
        "session_sec": 175,
        "aov": 110,
        "product_count": 8,
        "good_upsell": True,
    },
    "Sleepgram": {
        "founded": 2018,
        "traffic": 100000,
        "bounce_pct": 46.0,
        "pages_visit": 2.8,
        "session_sec": 145,
        "aov": 50,
        "product_count": 5,
        "good_upsell": False,
    },
    "Hullo": {
        "founded": 2012,
        "traffic": 80000,
        "bounce_pct": 47.0,
        "pages_visit": 2.9,
        "session_sec": 150,
        "aov": 65,
        "product_count": 5,
        "good_upsell": False,
    },
    "Ostrichpillow": {
        "founded": 2012,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 70,
        "product_count": 15,
        "good_upsell": True,
    },
    "Purple Harmony Pillow": {
        "founded": 2020,
        "traffic": 150000,
        "bounce_pct": 44.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 160,
        "product_count": 5,
        "good_upsell": True,
    },

    # =====================================================================
    # WEIGHTED BLANKETS & COMFORTERS
    # =====================================================================
    "Bearaby": {
        "founded": 2018,
        "traffic": 450000,
        "bounce_pct": 42.0,
        "pages_visit": 3.4,
        "session_sec": 180,
        "aov": 220,
        "product_count": 25,
        "good_upsell": True,
    },
    "Gravity Blanket": {
        "founded": 2017,
        "traffic": 350000,
        "bounce_pct": 43.0,
        "pages_visit": 3.2,
        "session_sec": 170,
        "aov": 170,
        "product_count": 20,
        "good_upsell": True,
    },
    "Luna Weighted": {
        "founded": 2018,
        "traffic": 120000,
        "bounce_pct": 46.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 80,
        "product_count": 10,
        "good_upsell": False,
    },
    "Baloo Living": {
        "founded": 2018,
        "traffic": 100000,
        "bounce_pct": 46.5,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 150,
        "product_count": 10,
        "good_upsell": True,
    },
    "Nuzzie": {
        "founded": 2019,
        "traffic": 60000,
        "bounce_pct": 48.0,
        "pages_visit": 2.9,
        "session_sec": 150,
        "aov": 180,
        "product_count": 8,
        "good_upsell": False,
    },
    "Hush Blankets": {
        "founded": 2017,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 160,
        "product_count": 15,
        "good_upsell": True,
    },
    "Layla Weighted Blanket": {
        "founded": 2018,
        "traffic": 80000,
        "bounce_pct": 47.0,
        "pages_visit": 2.9,
        "session_sec": 150,
        "aov": 130,
        "product_count": 5,
        "good_upsell": False,
    },

    # =====================================================================
    # WEARABLE BLANKETS
    # =====================================================================
    "The Oodie": {
        "founded": 2018,
        "traffic": 3000000,
        "bounce_pct": 38.0,
        "pages_visit": 3.5,
        "session_sec": 180,
        "aov": 75,
        "product_count": 80,
        "good_upsell": True,
    },
    "Comfy": {
        "founded": 2017,
        "traffic": 800000,
        "bounce_pct": 42.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 50,
        "product_count": 40,
        "good_upsell": True,
    },
    "Wearable X": {
        "founded": 2014,
        "traffic": 100000,
        "bounce_pct": 46.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 120,
        "product_count": 15,
        "good_upsell": False,
    },
    "BigBlanket Co": {
        "founded": 2019,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.1,
        "session_sec": 160,
        "aov": 130,
        "product_count": 10,
        "good_upsell": True,
    },
    "Snuggie": {
        "founded": 2008,
        "traffic": 150000,
        "bounce_pct": 48.0,
        "pages_visit": 2.8,
        "session_sec": 140,
        "aov": 30,
        "product_count": 20,
        "good_upsell": False,
    },

    # =====================================================================
    # BABY BEDDING & SWADDLES
    # =====================================================================
    "Kyte Baby": {
        "founded": 2015,
        "traffic": 1500000,
        "bounce_pct": 38.0,
        "pages_visit": 4.2,
        "session_sec": 225,
        "aov": 75,
        "product_count": 200,
        "good_upsell": True,
    },
    "Dreamland Baby": {
        "founded": 2019,
        "traffic": 500000,
        "bounce_pct": 41.0,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 90,
        "product_count": 25,
        "good_upsell": True,
    },
    "Aden + Anais": {
        "founded": 2006,
        "traffic": 700000,
        "bounce_pct": 40.5,
        "pages_visit": 3.8,
        "session_sec": 200,
        "aov": 55,
        "product_count": 150,
        "good_upsell": True,
    },
    "Nested Bean": {
        "founded": 2014,
        "traffic": 250000,
        "bounce_pct": 43.5,
        "pages_visit": 3.3,
        "session_sec": 175,
        "aov": 60,
        "product_count": 20,
        "good_upsell": True,
    },
    "Woolino": {
        "founded": 2013,
        "traffic": 180000,
        "bounce_pct": 44.0,
        "pages_visit": 3.2,
        "session_sec": 170,
        "aov": 80,
        "product_count": 30,
        "good_upsell": True,
    },
    "Copper Pearl": {
        "founded": 2015,
        "traffic": 300000,
        "bounce_pct": 42.5,
        "pages_visit": 3.5,
        "session_sec": 180,
        "aov": 35,
        "product_count": 80,
        "good_upsell": True,
    },
    "Little Unicorn": {
        "founded": 2014,
        "traffic": 200000,
        "bounce_pct": 43.5,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 45,
        "product_count": 60,
        "good_upsell": True,
    },
    "Solly Baby": {
        "founded": 2013,
        "traffic": 250000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 178,
        "aov": 65,
        "product_count": 30,
        "good_upsell": True,
    },
    "SNOO (Happiest Baby)": {
        "founded": 2016,
        "traffic": 800000,
        "bounce_pct": 39.0,
        "pages_visit": 3.9,
        "session_sec": 220,
        "aov": 1400,
        "product_count": 15,
        "good_upsell": True,
    },

    # =====================================================================
    # RUGS
    # =====================================================================
    "Ruggable": {
        "founded": 2017,
        "traffic": 4500000,
        "bounce_pct": 37.5,
        "pages_visit": 4.5,
        "session_sec": 240,
        "aov": 230,
        "product_count": 500,
        "good_upsell": True,
    },
    "Tumble": {
        "founded": 2020,
        "traffic": 350000,
        "bounce_pct": 43.0,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 250,
        "product_count": 60,
        "good_upsell": True,
    },
    "Loloi": {
        "founded": 2004,
        "traffic": 1200000,
        "bounce_pct": 40.0,
        "pages_visit": 4.0,
        "session_sec": 210,
        "aov": 200,
        "product_count": 2000,
        "good_upsell": False,
    },
    "Boutique Rugs": {
        "founded": 2014,
        "traffic": 600000,
        "bounce_pct": 42.0,
        "pages_visit": 3.8,
        "session_sec": 200,
        "aov": 180,
        "product_count": 3000,
        "good_upsell": True,
    },
    "RugsUSA": {
        "founded": 2000,
        "traffic": 3000000,
        "bounce_pct": 39.0,
        "pages_visit": 4.2,
        "session_sec": 220,
        "aov": 160,
        "product_count": 5000,
        "good_upsell": True,
    },
    "Revival Rugs": {
        "founded": 2017,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 350,
        "product_count": 300,
        "good_upsell": False,
    },
    "Lulu and Georgia": {
        "founded": 2012,
        "traffic": 700000,
        "bounce_pct": 41.0,
        "pages_visit": 3.7,
        "session_sec": 200,
        "aov": 280,
        "product_count": 500,
        "good_upsell": True,
    },
    "Lorena Canals": {
        "founded": 1984,
        "traffic": 300000,
        "bounce_pct": 43.0,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 200,
        "product_count": 150,
        "good_upsell": True,
    },
    "Hook & Loom": {
        "founded": 2008,
        "traffic": 80000,
        "bounce_pct": 47.0,
        "pages_visit": 3.1,
        "session_sec": 160,
        "aov": 250,
        "product_count": 100,
        "good_upsell": False,
    },

    # =====================================================================
    # CANDLES & HOME FRAGRANCE
    # =====================================================================
    "Otherland": {
        "founded": 2018,
        "traffic": 300000,
        "bounce_pct": 42.0,
        "pages_visit": 3.5,
        "session_sec": 180,
        "aov": 70,
        "product_count": 35,
        "good_upsell": True,
    },
    "Boy Smells": {
        "founded": 2016,
        "traffic": 500000,
        "bounce_pct": 40.5,
        "pages_visit": 3.6,
        "session_sec": 185,
        "aov": 55,
        "product_count": 40,
        "good_upsell": True,
    },
    "Homesick Candles": {
        "founded": 2016,
        "traffic": 600000,
        "bounce_pct": 41.0,
        "pages_visit": 3.5,
        "session_sec": 180,
        "aov": 40,
        "product_count": 80,
        "good_upsell": True,
    },
    "Apotheke": {
        "founded": 2011,
        "traffic": 200000,
        "bounce_pct": 43.5,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 50,
        "product_count": 50,
        "good_upsell": True,
    },
    "P.F. Candle Co.": {
        "founded": 2008,
        "traffic": 400000,
        "bounce_pct": 41.0,
        "pages_visit": 3.5,
        "session_sec": 180,
        "aov": 40,
        "product_count": 60,
        "good_upsell": True,
    },
    "Voluspa": {
        "founded": 1999,
        "traffic": 500000,
        "bounce_pct": 40.0,
        "pages_visit": 3.6,
        "session_sec": 190,
        "aov": 45,
        "product_count": 100,
        "good_upsell": True,
    },
    "Brooklyn Candle Studio": {
        "founded": 2013,
        "traffic": 100000,
        "bounce_pct": 45.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 35,
        "product_count": 25,
        "good_upsell": True,
    },
    "Byredo": {
        "founded": 2006,
        "traffic": 1500000,
        "bounce_pct": 38.0,
        "pages_visit": 3.8,
        "session_sec": 210,
        "aov": 90,
        "product_count": 80,
        "good_upsell": True,
    },
    "Diptyque": {
        "founded": 1961,
        "traffic": 2000000,
        "bounce_pct": 37.0,
        "pages_visit": 4.0,
        "session_sec": 220,
        "aov": 80,
        "product_count": 100,
        "good_upsell": True,
    },
    "Vitruvi": {
        "founded": 2015,
        "traffic": 200000,
        "bounce_pct": 43.0,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 85,
        "product_count": 25,
        "good_upsell": True,
    },
    "Keap Candles": {
        "founded": 2015,
        "traffic": 50000,
        "bounce_pct": 48.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 40,
        "product_count": 15,
        "good_upsell": False,
    },
    "Paddywax": {
        "founded": 1996,
        "traffic": 250000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 35,
        "product_count": 100,
        "good_upsell": True,
    },

    # =====================================================================
    # TRAVEL & LUGGAGE
    # =====================================================================
    "Away": {
        "founded": 2015,
        "traffic": 3000000,
        "bounce_pct": 38.5,
        "pages_visit": 3.8,
        "session_sec": 210,
        "aov": 295,
        "product_count": 40,
        "good_upsell": True,
    },
    "Cadence": {
        "founded": 2019,
        "traffic": 150000,
        "bounce_pct": 44.0,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 60,
        "product_count": 15,
        "good_upsell": True,
    },
    "Peak Design": {
        "founded": 2010,
        "traffic": 1200000,
        "bounce_pct": 39.5,
        "pages_visit": 3.9,
        "session_sec": 220,
        "aov": 150,
        "product_count": 60,
        "good_upsell": True,
    },
    "July": {
        "founded": 2018,
        "traffic": 500000,
        "bounce_pct": 42.0,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 275,
        "product_count": 20,
        "good_upsell": True,
    },
    "Monos": {
        "founded": 2018,
        "traffic": 600000,
        "bounce_pct": 41.5,
        "pages_visit": 3.6,
        "session_sec": 190,
        "aov": 260,
        "product_count": 25,
        "good_upsell": True,
    },
    "Paravel": {
        "founded": 2016,
        "traffic": 300000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 180,
        "aov": 285,
        "product_count": 20,
        "good_upsell": True,
    },
    "CALPAK": {
        "founded": 1989,
        "traffic": 1500000,
        "bounce_pct": 39.0,
        "pages_visit": 3.8,
        "session_sec": 205,
        "aov": 120,
        "product_count": 80,
        "good_upsell": True,
    },
    "Dagne Dover": {
        "founded": 2013,
        "traffic": 400000,
        "bounce_pct": 42.0,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 140,
        "product_count": 50,
        "good_upsell": True,
    },
    "Beis": {
        "founded": 2018,
        "traffic": 1800000,
        "bounce_pct": 38.5,
        "pages_visit": 3.9,
        "session_sec": 210,
        "aov": 120,
        "product_count": 50,
        "good_upsell": True,
    },
    "Roam Luggage": {
        "founded": 2018,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.4,
        "session_sec": 180,
        "aov": 425,
        "product_count": 15,
        "good_upsell": True,
    },

    # =====================================================================
    # STORAGE, ORGANIZERS & CONTAINERS
    # =====================================================================
    "Stasher": {
        "founded": 2016,
        "traffic": 600000,
        "bounce_pct": 41.0,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 35,
        "product_count": 40,
        "good_upsell": True,
    },
    "SimpleHuman": {
        "founded": 2000,
        "traffic": 1500000,
        "bounce_pct": 39.5,
        "pages_visit": 3.7,
        "session_sec": 200,
        "aov": 80,
        "product_count": 80,
        "good_upsell": True,
    },
    "Open Spaces": {
        "founded": 2019,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 90,
        "product_count": 25,
        "good_upsell": True,
    },
    "Modular Closets": {
        "founded": 2016,
        "traffic": 250000,
        "bounce_pct": 43.5,
        "pages_visit": 3.5,
        "session_sec": 195,
        "aov": 500,
        "product_count": 30,
        "good_upsell": True,
    },
    "Elfa": {
        "founded": 1948,
        "traffic": 400000,
        "bounce_pct": 42.0,
        "pages_visit": 3.6,
        "session_sec": 200,
        "aov": 350,
        "product_count": 100,
        "good_upsell": True,
    },
    "California Closets": {
        "founded": 1978,
        "traffic": 1200000,
        "bounce_pct": 40.0,
        "pages_visit": 3.7,
        "session_sec": 210,
        "aov": 3000,
        "product_count": 50,
        "good_upsell": True,
    },
    "The Container Store": {
        "founded": 1978,
        "traffic": 5000000,
        "bounce_pct": 38.0,
        "pages_visit": 4.2,
        "session_sec": 225,
        "aov": 55,
        "product_count": 5000,
        "good_upsell": True,
    },
    "mDesign": {
        "founded": 2011,
        "traffic": 300000,
        "bounce_pct": 43.5,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 35,
        "product_count": 500,
        "good_upsell": True,
    },
    "Yamazaki Home": {
        "founded": 2018,
        "traffic": 250000,
        "bounce_pct": 43.0,
        "pages_visit": 3.5,
        "session_sec": 180,
        "aov": 45,
        "product_count": 100,
        "good_upsell": True,
    },
    "iDesign": {
        "founded": 2017,
        "traffic": 150000,
        "bounce_pct": 45.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 30,
        "product_count": 300,
        "good_upsell": True,
    },
    "Closet Factory": {
        "founded": 1983,
        "traffic": 400000,
        "bounce_pct": 43.0,
        "pages_visit": 3.5,
        "session_sec": 195,
        "aov": 2500,
        "product_count": 40,
        "good_upsell": True,
    },
    "EasyClosets": {
        "founded": 2002,
        "traffic": 300000,
        "bounce_pct": 43.5,
        "pages_visit": 3.5,
        "session_sec": 195,
        "aov": 800,
        "product_count": 30,
        "good_upsell": True,
    },

    # =====================================================================
    # TOWELS & BATH
    # =====================================================================
    "Dock & Bay": {
        "founded": 2015,
        "traffic": 350000,
        "bounce_pct": 42.5,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 40,
        "product_count": 60,
        "good_upsell": True,
    },
    "Weezie": {
        "founded": 2018,
        "traffic": 200000,
        "bounce_pct": 43.5,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 70,
        "product_count": 25,
        "good_upsell": True,
    },
    "Onsen": {
        "founded": 2018,
        "traffic": 120000,
        "bounce_pct": 45.0,
        "pages_visit": 3.1,
        "session_sec": 160,
        "aov": 65,
        "product_count": 15,
        "good_upsell": True,
    },
    "Baina": {
        "founded": 2020,
        "traffic": 80000,
        "bounce_pct": 46.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 90,
        "product_count": 15,
        "good_upsell": False,
    },
    "Havly": {
        "founded": 2020,
        "traffic": 40000,
        "bounce_pct": 48.0,
        "pages_visit": 2.9,
        "session_sec": 150,
        "aov": 55,
        "product_count": 10,
        "good_upsell": False,
    },
    "Riley Home Towels": {
        "founded": 2019,
        "traffic": 80000,
        "bounce_pct": 46.0,
        "pages_visit": 3.1,
        "session_sec": 160,
        "aov": 60,
        "product_count": 15,
        "good_upsell": True,
    },
    "Turkish Towel Co": {
        "founded": 2013,
        "traffic": 100000,
        "bounce_pct": 45.5,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 45,
        "product_count": 30,
        "good_upsell": True,
    },

    # =====================================================================
    # SLEEP TECH & ACCESSORIES
    # =====================================================================
    "Hatch": {
        "founded": 2014,
        "traffic": 1500000,
        "bounce_pct": 39.0,
        "pages_visit": 3.7,
        "session_sec": 200,
        "aov": 130,
        "product_count": 10,
        "good_upsell": True,
    },
    "Manta Sleep": {
        "founded": 2017,
        "traffic": 350000,
        "bounce_pct": 43.0,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 45,
        "product_count": 20,
        "good_upsell": True,
    },
    "Loftie": {
        "founded": 2018,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.2,
        "session_sec": 170,
        "aov": 130,
        "product_count": 8,
        "good_upsell": True,
    },
    "Oura Ring": {
        "founded": 2013,
        "traffic": 3000000,
        "bounce_pct": 37.0,
        "pages_visit": 3.9,
        "session_sec": 230,
        "aov": 350,
        "product_count": 10,
        "good_upsell": True,
    },
    "ChiliSleep (Sleepme)": {
        "founded": 2007,
        "traffic": 400000,
        "bounce_pct": 42.5,
        "pages_visit": 3.5,
        "session_sec": 190,
        "aov": 450,
        "product_count": 10,
        "good_upsell": True,
    },
    "Dodow": {
        "founded": 2015,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 50,
        "product_count": 3,
        "good_upsell": False,
    },

    # =====================================================================
    # HOME DECOR & GENERAL HOME
    # =====================================================================
    "Brooklinen Home": {
        "founded": 2014,
        "traffic": 250000,
        "bounce_pct": 41.0,
        "pages_visit": 3.6,
        "session_sec": 185,
        "aov": 100,
        "product_count": 50,
        "good_upsell": True,
    },
    "Burrow": {
        "founded": 2016,
        "traffic": 600000,
        "bounce_pct": 41.0,
        "pages_visit": 3.7,
        "session_sec": 205,
        "aov": 1200,
        "product_count": 40,
        "good_upsell": True,
    },
    "Article": {
        "founded": 2011,
        "traffic": 3500000,
        "bounce_pct": 37.5,
        "pages_visit": 4.3,
        "session_sec": 240,
        "aov": 800,
        "product_count": 300,
        "good_upsell": True,
    },
    "Floyd": {
        "founded": 2014,
        "traffic": 400000,
        "bounce_pct": 42.0,
        "pages_visit": 3.5,
        "session_sec": 190,
        "aov": 700,
        "product_count": 30,
        "good_upsell": True,
    },
    "Allform": {
        "founded": 2019,
        "traffic": 200000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 185,
        "aov": 1500,
        "product_count": 15,
        "good_upsell": True,
    },
    "Interior Define": {
        "founded": 2014,
        "traffic": 400000,
        "bounce_pct": 42.0,
        "pages_visit": 3.6,
        "session_sec": 200,
        "aov": 1800,
        "product_count": 40,
        "good_upsell": True,
    },
    "Maiden Home": {
        "founded": 2017,
        "traffic": 150000,
        "bounce_pct": 44.5,
        "pages_visit": 3.5,
        "session_sec": 195,
        "aov": 2500,
        "product_count": 20,
        "good_upsell": True,
    },
    "Joybird": {
        "founded": 2014,
        "traffic": 1200000,
        "bounce_pct": 39.5,
        "pages_visit": 4.0,
        "session_sec": 225,
        "aov": 1500,
        "product_count": 200,
        "good_upsell": True,
    },
    "Apt2B": {
        "founded": 2010,
        "traffic": 500000,
        "bounce_pct": 42.0,
        "pages_visit": 3.7,
        "session_sec": 200,
        "aov": 1300,
        "product_count": 150,
        "good_upsell": True,
    },
    "Dims": {
        "founded": 2020,
        "traffic": 80000,
        "bounce_pct": 47.0,
        "pages_visit": 3.2,
        "session_sec": 170,
        "aov": 600,
        "product_count": 15,
        "good_upsell": False,
    },
    "Thuma": {
        "founded": 2018,
        "traffic": 500000,
        "bounce_pct": 41.0,
        "pages_visit": 3.5,
        "session_sec": 190,
        "aov": 850,
        "product_count": 15,
        "good_upsell": True,
    },
    "Blu Dot": {
        "founded": 1997,
        "traffic": 500000,
        "bounce_pct": 41.5,
        "pages_visit": 3.7,
        "session_sec": 200,
        "aov": 700,
        "product_count": 200,
        "good_upsell": False,
    },
    "Arhaus": {
        "founded": 1986,
        "traffic": 2000000,
        "bounce_pct": 38.5,
        "pages_visit": 4.0,
        "session_sec": 220,
        "aov": 1200,
        "product_count": 1000,
        "good_upsell": True,
    },

    # =====================================================================
    # KITCHEN HOME / FOOD STORAGE
    # =====================================================================
    "Caraway Home": {
        "founded": 2019,
        "traffic": 1000000,
        "bounce_pct": 40.0,
        "pages_visit": 3.6,
        "session_sec": 190,
        "aov": 200,
        "product_count": 25,
        "good_upsell": True,
    },
    "Our Place": {
        "founded": 2019,
        "traffic": 1500000,
        "bounce_pct": 39.0,
        "pages_visit": 3.7,
        "session_sec": 200,
        "aov": 130,
        "product_count": 30,
        "good_upsell": True,
    },
    "Great Jones": {
        "founded": 2018,
        "traffic": 200000,
        "bounce_pct": 43.5,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 120,
        "product_count": 15,
        "good_upsell": True,
    },
    "Made In Cookware": {
        "founded": 2016,
        "traffic": 700000,
        "bounce_pct": 41.0,
        "pages_visit": 3.6,
        "session_sec": 195,
        "aov": 140,
        "product_count": 50,
        "good_upsell": True,
    },
    "Misen": {
        "founded": 2015,
        "traffic": 350000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 180,
        "aov": 85,
        "product_count": 30,
        "good_upsell": True,
    },
    "Material Kitchen": {
        "founded": 2018,
        "traffic": 150000,
        "bounce_pct": 44.5,
        "pages_visit": 3.3,
        "session_sec": 175,
        "aov": 75,
        "product_count": 20,
        "good_upsell": True,
    },
    "Anyday": {
        "founded": 2020,
        "traffic": 120000,
        "bounce_pct": 45.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 55,
        "product_count": 10,
        "good_upsell": True,
    },
    "HexClad": {
        "founded": 2017,
        "traffic": 1200000,
        "bounce_pct": 40.0,
        "pages_visit": 3.6,
        "session_sec": 195,
        "aov": 200,
        "product_count": 30,
        "good_upsell": True,
    },
    "W&P Design": {
        "founded": 2012,
        "traffic": 300000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 35,
        "product_count": 60,
        "good_upsell": True,
    },

    # =====================================================================
    # CLEANING & HOME CARE
    # =====================================================================
    "Blueland": {
        "founded": 2019,
        "traffic": 600000,
        "bounce_pct": 41.0,
        "pages_visit": 3.4,
        "session_sec": 180,
        "aov": 40,
        "product_count": 25,
        "good_upsell": True,
    },
    "Grove Collaborative": {
        "founded": 2012,
        "traffic": 2500000,
        "bounce_pct": 38.5,
        "pages_visit": 4.0,
        "session_sec": 210,
        "aov": 45,
        "product_count": 300,
        "good_upsell": True,
    },
    "Branch Basics": {
        "founded": 2012,
        "traffic": 350000,
        "bounce_pct": 43.0,
        "pages_visit": 3.3,
        "session_sec": 175,
        "aov": 50,
        "product_count": 15,
        "good_upsell": True,
    },
    "Supernatural": {
        "founded": 2019,
        "traffic": 100000,
        "bounce_pct": 46.0,
        "pages_visit": 3.1,
        "session_sec": 160,
        "aov": 35,
        "product_count": 10,
        "good_upsell": True,
    },

    # =====================================================================
    # CURTAINS & WINDOW
    # =====================================================================
    "Loom Decor": {
        "founded": 2014,
        "traffic": 150000,
        "bounce_pct": 44.0,
        "pages_visit": 3.5,
        "session_sec": 195,
        "aov": 300,
        "product_count": 200,
        "good_upsell": True,
    },
    "Barn & Willow": {
        "founded": 2013,
        "traffic": 100000,
        "bounce_pct": 45.0,
        "pages_visit": 3.4,
        "session_sec": 190,
        "aov": 250,
        "product_count": 40,
        "good_upsell": True,
    },
    "Wovn Home": {
        "founded": 2019,
        "traffic": 40000,
        "bounce_pct": 48.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 180,
        "product_count": 20,
        "good_upsell": False,
    },

    # =====================================================================
    # WALL ART & PRINTS
    # =====================================================================
    "Minted": {
        "founded": 2007,
        "traffic": 3000000,
        "bounce_pct": 38.0,
        "pages_visit": 4.2,
        "session_sec": 225,
        "aov": 70,
        "product_count": 10000,
        "good_upsell": True,
    },
    "Desenio": {
        "founded": 2010,
        "traffic": 2500000,
        "bounce_pct": 39.0,
        "pages_visit": 4.0,
        "session_sec": 215,
        "aov": 55,
        "product_count": 3000,
        "good_upsell": True,
    },
    "Juniper Print Shop": {
        "founded": 2016,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 45,
        "product_count": 200,
        "good_upsell": True,
    },
    "Society6": {
        "founded": 2009,
        "traffic": 4000000,
        "bounce_pct": 40.0,
        "pages_visit": 3.8,
        "session_sec": 200,
        "aov": 40,
        "product_count": 50000,
        "good_upsell": True,
    },
    "Framebridge": {
        "founded": 2014,
        "traffic": 600000,
        "bounce_pct": 41.0,
        "pages_visit": 3.5,
        "session_sec": 190,
        "aov": 100,
        "product_count": 50,
        "good_upsell": True,
    },

    # =====================================================================
    # PLANTS & PLANTERS
    # =====================================================================
    "The Sill": {
        "founded": 2012,
        "traffic": 700000,
        "bounce_pct": 41.0,
        "pages_visit": 3.6,
        "session_sec": 190,
        "aov": 55,
        "product_count": 100,
        "good_upsell": True,
    },
    "Bloomscape": {
        "founded": 2018,
        "traffic": 500000,
        "bounce_pct": 42.0,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 80,
        "product_count": 80,
        "good_upsell": True,
    },
    "Lively Root": {
        "founded": 2019,
        "traffic": 150000,
        "bounce_pct": 44.5,
        "pages_visit": 3.3,
        "session_sec": 175,
        "aov": 50,
        "product_count": 60,
        "good_upsell": True,
    },

    # =====================================================================
    # LIGHTING
    # =====================================================================
    "Schoolhouse": {
        "founded": 2003,
        "traffic": 400000,
        "bounce_pct": 42.0,
        "pages_visit": 3.6,
        "session_sec": 195,
        "aov": 180,
        "product_count": 150,
        "good_upsell": True,
    },
    "Cedar & Moss": {
        "founded": 2012,
        "traffic": 100000,
        "bounce_pct": 45.0,
        "pages_visit": 3.3,
        "session_sec": 175,
        "aov": 250,
        "product_count": 40,
        "good_upsell": False,
    },
    "Mitzi Lighting": {
        "founded": 2018,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.4,
        "session_sec": 180,
        "aov": 200,
        "product_count": 200,
        "good_upsell": False,
    },
    "Lumens": {
        "founded": 2004,
        "traffic": 1500000,
        "bounce_pct": 39.5,
        "pages_visit": 3.9,
        "session_sec": 215,
        "aov": 300,
        "product_count": 5000,
        "good_upsell": True,
    },

    # =====================================================================
    # ADDITIONAL HOME BRANDS
    # =====================================================================
    "Brooklinen Bath": {
        "founded": 2014,
        "traffic": 200000,
        "bounce_pct": 41.0,
        "pages_visit": 3.5,
        "session_sec": 180,
        "aov": 75,
        "product_count": 30,
        "good_upsell": True,
    },
    "Parachute Baby": {
        "founded": 2019,
        "traffic": 150000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 178,
        "aov": 85,
        "product_count": 20,
        "good_upsell": True,
    },
    "Tuft & Needle Sheets": {
        "founded": 2016,
        "traffic": 200000,
        "bounce_pct": 43.5,
        "pages_visit": 3.3,
        "session_sec": 175,
        "aov": 90,
        "product_count": 15,
        "good_upsell": True,
    },
    "Lacoste Home": {
        "founded": 2005,
        "traffic": 300000,
        "bounce_pct": 42.0,
        "pages_visit": 3.5,
        "session_sec": 180,
        "aov": 80,
        "product_count": 50,
        "good_upsell": True,
    },
    "West Elm": {
        "founded": 2002,
        "traffic": 8000000,
        "bounce_pct": 35.0,
        "pages_visit": 4.8,
        "session_sec": 260,
        "aov": 180,
        "product_count": 5000,
        "good_upsell": True,
    },
    "CB2": {
        "founded": 2000,
        "traffic": 4000000,
        "bounce_pct": 37.0,
        "pages_visit": 4.5,
        "session_sec": 245,
        "aov": 200,
        "product_count": 3000,
        "good_upsell": True,
    },
    "Anthropologie Home": {
        "founded": 2009,
        "traffic": 5000000,
        "bounce_pct": 36.0,
        "pages_visit": 4.6,
        "session_sec": 250,
        "aov": 120,
        "product_count": 2000,
        "good_upsell": True,
    },
    "Serena & Lily": {
        "founded": 2003,
        "traffic": 1500000,
        "bounce_pct": 39.0,
        "pages_visit": 4.0,
        "session_sec": 220,
        "aov": 250,
        "product_count": 800,
        "good_upsell": True,
    },
    "Pottery Barn": {
        "founded": 1949,
        "traffic": 12000000,
        "bounce_pct": 34.0,
        "pages_visit": 5.0,
        "session_sec": 280,
        "aov": 160,
        "product_count": 8000,
        "good_upsell": True,
    },
    "Crate & Barrel": {
        "founded": 1962,
        "traffic": 10000000,
        "bounce_pct": 35.0,
        "pages_visit": 4.8,
        "session_sec": 265,
        "aov": 180,
        "product_count": 6000,
        "good_upsell": True,
    },
    "RH (Restoration Hardware)": {
        "founded": 1979,
        "traffic": 5000000,
        "bounce_pct": 36.5,
        "pages_visit": 4.5,
        "session_sec": 250,
        "aov": 500,
        "product_count": 4000,
        "good_upsell": True,
    },
    "Ethan Allen": {
        "founded": 1932,
        "traffic": 2000000,
        "bounce_pct": 39.0,
        "pages_visit": 4.0,
        "session_sec": 220,
        "aov": 600,
        "product_count": 2000,
        "good_upsell": True,
    },

    # =====================================================================
    # THROWS & BLANKETS (NON-WEIGHTED)
    # =====================================================================
    "Pendleton": {
        "founded": 1863,
        "traffic": 1200000,
        "bounce_pct": 39.5,
        "pages_visit": 3.8,
        "session_sec": 205,
        "aov": 120,
        "product_count": 200,
        "good_upsell": True,
    },
    "Rumpl": {
        "founded": 2013,
        "traffic": 400000,
        "bounce_pct": 42.0,
        "pages_visit": 3.4,
        "session_sec": 180,
        "aov": 100,
        "product_count": 40,
        "good_upsell": True,
    },
    "ChappyWrap": {
        "founded": 2016,
        "traffic": 250000,
        "bounce_pct": 43.0,
        "pages_visit": 3.3,
        "session_sec": 175,
        "aov": 105,
        "product_count": 50,
        "good_upsell": True,
    },
    "Kashwere": {
        "founded": 2001,
        "traffic": 100000,
        "bounce_pct": 45.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 130,
        "product_count": 30,
        "good_upsell": True,
    },
    "Brahms Mount": {
        "founded": 1983,
        "traffic": 50000,
        "bounce_pct": 48.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 200,
        "product_count": 30,
        "good_upsell": False,
    },
    "Thula Tula": {
        "founded": 2019,
        "traffic": 40000,
        "bounce_pct": 48.0,
        "pages_visit": 2.9,
        "session_sec": 150,
        "aov": 45,
        "product_count": 15,
        "good_upsell": False,
    },

    # =====================================================================
    # ROBES & LOUNGEWEAR (HOME-ADJACENT)
    # =====================================================================
    "Parachute Robe": {
        "founded": 2017,
        "traffic": 120000,
        "bounce_pct": 43.0,
        "pages_visit": 3.3,
        "session_sec": 172,
        "aov": 100,
        "product_count": 10,
        "good_upsell": True,
    },
    "Eberjey": {
        "founded": 1996,
        "traffic": 400000,
        "bounce_pct": 41.5,
        "pages_visit": 3.6,
        "session_sec": 190,
        "aov": 90,
        "product_count": 80,
        "good_upsell": True,
    },
    "Natori": {
        "founded": 1977,
        "traffic": 300000,
        "bounce_pct": 42.5,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 85,
        "product_count": 100,
        "good_upsell": True,
    },

    # =====================================================================
    # HARDWARE & SMART HOME (ORGANIZER-ADJACENT)
    # =====================================================================
    "Ring": {
        "founded": 2013,
        "traffic": 8000000,
        "bounce_pct": 36.0,
        "pages_visit": 4.2,
        "session_sec": 230,
        "aov": 150,
        "product_count": 30,
        "good_upsell": True,
    },
    "Nest (Google)": {
        "founded": 2010,
        "traffic": 5000000,
        "bounce_pct": 37.0,
        "pages_visit": 4.0,
        "session_sec": 220,
        "aov": 180,
        "product_count": 20,
        "good_upsell": True,
    },

    # =====================================================================
    # MORE BEDDING / SHEETS (TO REACH 200+)
    # =====================================================================
    "Southshore Fine Linens": {
        "founded": 2014,
        "traffic": 100000,
        "bounce_pct": 46.0,
        "pages_visit": 3.1,
        "session_sec": 160,
        "aov": 55,
        "product_count": 40,
        "good_upsell": True,
    },
    "Nollapelli": {
        "founded": 2018,
        "traffic": 30000,
        "bounce_pct": 50.0,
        "pages_visit": 2.8,
        "session_sec": 145,
        "aov": 120,
        "product_count": 8,
        "good_upsell": False,
    },
    "Mellanni": {
        "founded": 2014,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 40,
        "product_count": 30,
        "good_upsell": True,
    },
    "Luxome": {
        "founded": 2020,
        "traffic": 100000,
        "bounce_pct": 45.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 130,
        "product_count": 15,
        "good_upsell": True,
    },
    "Cozy Blanket": {
        "founded": 2019,
        "traffic": 50000,
        "bounce_pct": 48.0,
        "pages_visit": 2.9,
        "session_sec": 150,
        "aov": 60,
        "product_count": 10,
        "good_upsell": False,
    },
    "Panda London": {
        "founded": 2017,
        "traffic": 300000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 178,
        "aov": 95,
        "product_count": 30,
        "good_upsell": True,
    },
    "Slumber Cloud": {
        "founded": 2014,
        "traffic": 120000,
        "bounce_pct": 45.5,
        "pages_visit": 3.1,
        "session_sec": 160,
        "aov": 110,
        "product_count": 20,
        "good_upsell": True,
    },
    "Sheets & Giggles": {
        "founded": 2018,
        "traffic": 200000,
        "bounce_pct": 43.5,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 130,
        "product_count": 15,
        "good_upsell": True,
    },
    "Bedsure": {
        "founded": 2016,
        "traffic": 500000,
        "bounce_pct": 42.5,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 35,
        "product_count": 100,
        "good_upsell": True,
    },
    "Brentwood Home": {
        "founded": 1987,
        "traffic": 250000,
        "bounce_pct": 43.5,
        "pages_visit": 3.4,
        "session_sec": 180,
        "aov": 200,
        "product_count": 30,
        "good_upsell": True,
    },
    "Sleep Number": {
        "founded": 1987,
        "traffic": 4000000,
        "bounce_pct": 38.5,
        "pages_visit": 4.0,
        "session_sec": 230,
        "aov": 2000,
        "product_count": 20,
        "good_upsell": True,
    },
    "Tempur-Pedic": {
        "founded": 1992,
        "traffic": 5000000,
        "bounce_pct": 37.5,
        "pages_visit": 4.1,
        "session_sec": 235,
        "aov": 2200,
        "product_count": 30,
        "good_upsell": True,
    },
    "Emma Sleep": {
        "founded": 2015,
        "traffic": 3000000,
        "bounce_pct": 39.0,
        "pages_visit": 3.7,
        "session_sec": 205,
        "aov": 700,
        "product_count": 15,
        "good_upsell": True,
    },
    "Zinus": {
        "founded": 2004,
        "traffic": 1500000,
        "bounce_pct": 41.0,
        "pages_visit": 3.5,
        "session_sec": 190,
        "aov": 300,
        "product_count": 40,
        "good_upsell": True,
    },
    "Simba Sleep": {
        "founded": 2015,
        "traffic": 1000000,
        "bounce_pct": 40.5,
        "pages_visit": 3.6,
        "session_sec": 195,
        "aov": 800,
        "product_count": 20,
        "good_upsell": True,
    },
    "GhostBed": {
        "founded": 2015,
        "traffic": 400000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 185,
        "aov": 900,
        "product_count": 15,
        "good_upsell": True,
    },
    "Cocoon by Sealy": {
        "founded": 2016,
        "traffic": 300000,
        "bounce_pct": 43.5,
        "pages_visit": 3.3,
        "session_sec": 180,
        "aov": 650,
        "product_count": 10,
        "good_upsell": True,
    },
    "Allswell": {
        "founded": 2018,
        "traffic": 400000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 180,
        "aov": 300,
        "product_count": 20,
        "good_upsell": True,
    },
    "Vaya Sleep": {
        "founded": 2019,
        "traffic": 80000,
        "bounce_pct": 47.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 500,
        "product_count": 5,
        "good_upsell": False,
    },
    "SONU Sleep": {
        "founded": 2020,
        "traffic": 60000,
        "bounce_pct": 47.5,
        "pages_visit": 3.0,
        "session_sec": 160,
        "aov": 1200,
        "product_count": 5,
        "good_upsell": True,
    },

    # =====================================================================
    # ADDITIONAL ORGANIZER & STORAGE BRANDS
    # =====================================================================
    "Closetmaid": {
        "founded": 1965,
        "traffic": 800000,
        "bounce_pct": 41.0,
        "pages_visit": 3.5,
        "session_sec": 190,
        "aov": 120,
        "product_count": 200,
        "good_upsell": True,
    },
    "Rev-A-Shelf": {
        "founded": 1978,
        "traffic": 300000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 185,
        "aov": 100,
        "product_count": 300,
        "good_upsell": True,
    },
    "Prepac": {
        "founded": 1979,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.3,
        "session_sec": 175,
        "aov": 200,
        "product_count": 100,
        "good_upsell": False,
    },
    "Neatfreak": {
        "founded": 2005,
        "traffic": 80000,
        "bounce_pct": 47.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 35,
        "product_count": 80,
        "good_upsell": True,
    },
    "YouCopia": {
        "founded": 2009,
        "traffic": 150000,
        "bounce_pct": 44.5,
        "pages_visit": 3.2,
        "session_sec": 170,
        "aov": 30,
        "product_count": 40,
        "good_upsell": True,
    },

    # =====================================================================
    # PILLOWCASES & SILK/SATIN SPECIALTY
    # =====================================================================
    "Slip": {
        "founded": 2004,
        "traffic": 700000,
        "bounce_pct": 40.5,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 85,
        "product_count": 30,
        "good_upsell": True,
    },
    "Blissy": {
        "founded": 2018,
        "traffic": 500000,
        "bounce_pct": 42.0,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 70,
        "product_count": 20,
        "good_upsell": True,
    },
    "LilySilk": {
        "founded": 2010,
        "traffic": 600000,
        "bounce_pct": 41.5,
        "pages_visit": 3.5,
        "session_sec": 185,
        "aov": 100,
        "product_count": 150,
        "good_upsell": True,
    },

    # =====================================================================
    # OUTDOOR HOME / PATIO
    # =====================================================================
    "Outer": {
        "founded": 2018,
        "traffic": 500000,
        "bounce_pct": 42.0,
        "pages_visit": 3.6,
        "session_sec": 200,
        "aov": 3000,
        "product_count": 20,
        "good_upsell": True,
    },
    "Yardbird": {
        "founded": 2017,
        "traffic": 300000,
        "bounce_pct": 43.0,
        "pages_visit": 3.5,
        "session_sec": 195,
        "aov": 2500,
        "product_count": 25,
        "good_upsell": True,
    },
    "Neighbor": {
        "founded": 2020,
        "traffic": 80000,
        "bounce_pct": 46.0,
        "pages_visit": 3.2,
        "session_sec": 175,
        "aov": 2200,
        "product_count": 10,
        "good_upsell": True,
    },

    # =====================================================================
    # ADDITIONAL DTC HOME BRANDS
    # =====================================================================
    "Snowe": {
        "founded": 2015,
        "traffic": 120000,
        "bounce_pct": 45.0,
        "pages_visit": 3.3,
        "session_sec": 170,
        "aov": 120,
        "product_count": 60,
        "good_upsell": True,
    },
    "Brooklinen Down": {
        "founded": 2017,
        "traffic": 150000,
        "bounce_pct": 42.0,
        "pages_visit": 3.4,
        "session_sec": 175,
        "aov": 170,
        "product_count": 10,
        "good_upsell": True,
    },
    "Nest Bedding Sheets": {
        "founded": 2014,
        "traffic": 100000,
        "bounce_pct": 45.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 120,
        "product_count": 15,
        "good_upsell": True,
    },
    "Comphy": {
        "founded": 2002,
        "traffic": 50000,
        "bounce_pct": 48.0,
        "pages_visit": 2.9,
        "session_sec": 150,
        "aov": 140,
        "product_count": 15,
        "good_upsell": False,
    },
    "Red Land Cotton": {
        "founded": 2016,
        "traffic": 80000,
        "bounce_pct": 46.0,
        "pages_visit": 3.1,
        "session_sec": 160,
        "aov": 120,
        "product_count": 20,
        "good_upsell": False,
    },
    "Marialma": {
        "founded": 2015,
        "traffic": 40000,
        "bounce_pct": 49.0,
        "pages_visit": 2.9,
        "session_sec": 150,
        "aov": 140,
        "product_count": 20,
        "good_upsell": False,
    },
    "Scooms": {
        "founded": 2017,
        "traffic": 100000,
        "bounce_pct": 45.0,
        "pages_visit": 3.2,
        "session_sec": 165,
        "aov": 160,
        "product_count": 25,
        "good_upsell": True,
    },
    "Bedgear": {
        "founded": 2009,
        "traffic": 200000,
        "bounce_pct": 44.0,
        "pages_visit": 3.3,
        "session_sec": 175,
        "aov": 130,
        "product_count": 40,
        "good_upsell": True,
    },
    "Malouf": {
        "founded": 2003,
        "traffic": 300000,
        "bounce_pct": 43.0,
        "pages_visit": 3.4,
        "session_sec": 180,
        "aov": 100,
        "product_count": 80,
        "good_upsell": True,
    },
    "Parachute Duvet": {
        "founded": 2016,
        "traffic": 200000,
        "bounce_pct": 42.0,
        "pages_visit": 3.5,
        "session_sec": 182,
        "aov": 200,
        "product_count": 10,
        "good_upsell": True,
    },
    "Primary Goods": {
        "founded": 2020,
        "traffic": 80000,
        "bounce_pct": 46.0,
        "pages_visit": 3.1,
        "session_sec": 160,
        "aov": 75,
        "product_count": 15,
        "good_upsell": True,
    },
    "Sunday Home": {
        "founded": 2019,
        "traffic": 60000,
        "bounce_pct": 47.0,
        "pages_visit": 3.0,
        "session_sec": 155,
        "aov": 85,
        "product_count": 20,
        "good_upsell": False,
    },
    "Haven (Mattress)": {
        "founded": 2018,
        "traffic": 150000,
        "bounce_pct": 44.5,
        "pages_visit": 3.3,
        "session_sec": 178,
        "aov": 800,
        "product_count": 10,
        "good_upsell": True,
    },
    "SleepFoundation Essentials": {
        "founded": 2020,
        "traffic": 40000,
        "bounce_pct": 48.0,
        "pages_visit": 2.9,
        "session_sec": 150,
        "aov": 60,
        "product_count": 10,
        "good_upsell": False,
    },
}


# =========================================================================
# CATEGORY-LEVEL AOV DEFAULTS (Turkish category names from Yuvacim dataset)
# =========================================================================
CATEGORY_AOV_DEFAULTS = {
    "Yatak Çarşafı & Nevresim": 95,
    "Yorgan & Dolgulu Ürünler": 120,
    "Yastık": 65,
    "Yatak & Şilte": 900,
    "Yatak Koruyucu & Ped": 55,
    "Bebek Uyku & Kundak": 60,
    "Ağırlıklı Battaniye": 170,
    "Giyilebilir Battaniye": 60,
    "Battaniye & Örtü": 90,
    "Bornoz & Ev Giyim": 85,
    "Havlu & Banyo Tekstili": 50,
    "Halı & Kilim": 200,
    "Perde & Pencere": 180,
    "Ev Tekstili (Genel)": 80,
    "Mum & Oda Kokusu": 45,
    "Uyku Teknolojisi": 200,
    "Bavul & Seyahat": 200,
    "Saklama & Organizasyon": 60,
    "Dolap & Giyinme Odası": 500,
    "Mutfak & Pişirme": 120,
    "Aydınlatma": 200,
    "Duvar Sanatı & Baskı": 55,
    "Bitki & Saksı": 50,
    "Temizlik & Ev Bakım": 35,
    "Mobilya & Dekorasyon": 600,
}


# =========================================================================
# HELPER FUNCTIONS
# =========================================================================

def get_metrics(brand_name):
    """Get metrics for a brand, returns None if not found."""
    return BRAND_METRICS.get(brand_name)


def get_category_aov(category_name):
    """Get default AOV for a category, returns 80 (general default) if not found."""
    return CATEGORY_AOV_DEFAULTS.get(category_name, 80)


def get_all_brands():
    """Return a list of all brand names in the database."""
    return list(BRAND_METRICS.keys())


def get_brands_by_aov_range(min_aov, max_aov):
    """Return brands with AOV in the given range."""
    return {
        name: data
        for name, data in BRAND_METRICS.items()
        if min_aov <= data["aov"] <= max_aov
    }


def get_high_traffic_brands(min_traffic=1000000):
    """Return brands with monthly traffic above the given threshold."""
    return {
        name: data
        for name, data in BRAND_METRICS.items()
        if data["traffic"] >= min_traffic
    }


def get_brands_with_good_upsell():
    """Return brands flagged as having good bundling/upsell strategies."""
    return {
        name: data
        for name, data in BRAND_METRICS.items()
        if data.get("good_upsell", False)
    }


if __name__ == "__main__":
    print(f"Total brands in database: {len(BRAND_METRICS)}")
    print(f"Total categories with AOV defaults: {len(CATEGORY_AOV_DEFAULTS)}")
    print(f"\nHigh-traffic brands (1M+ visits): {len(get_high_traffic_brands())}")
    print(f"Brands with good upsell: {len(get_brands_with_good_upsell())}")
    avg_aov = sum(d['aov'] for d in BRAND_METRICS.values()) / len(BRAND_METRICS)
    print(f"Average AOV across all brands: ${avg_aov:.0f}")
