"""
Third supplementary batch - filling thin categories and adding more niche brands.
"""

COSMETICS_EXTRA_3 = {
    "Saç Bakımı - Renk & Boyama": [
        ("Madison Reed", "madison-reed.com", "AI Renk Danışmanı", "Salon kalitesi ev boyası; Color Advisor AI; 400+ ton; $22; temiz bileşen"),
        ("Overtone", "overtone.co", "Direkt Renk Saç Kremi", "Yarı kalıcı renk kondisyoner; canlı renkler; hasarsız; ev boyama kolaylaştırıldı"),
        ("Arctic Fox", "arcticfoxhaircolor.com", "Vegan Canlı Renk", "%100 vegan; canlı renkler; hayvan testine karşı; Kristen Leanne; cruelty-free"),
        ("Manic Panic", "manicpanic.com", "Punk Saç Rengi OG", "1977'den beri; punk + goth saç boyası; Tish & Snooky Bellomo; NYC CBGB kültürü"),
        ("Lime Crime Unicorn Hair", "limecrime.com", "Fantastik Saç Rengi", "Unicorn Hair direkt renk; pastel + neon; vegan; fantastik renkler"),
        ("Good Dye Young", "gooddyeyoung.com", "Hayley Williams Renk", "Paramore'un Hayley Williams; yarı kalıcı canlı renk; rock + müzik kültürü"),
        ("dpHUE", "dphue.com", "Salon Arası Bakım", "Apple Cider Vinegar Hair Rinse; Gloss+ ev renklendirme; salon arası renk bakımı"),
        ("Iroiro", "iroirocolors.com", "Japon Premium Renk", "Japon yarı kalıcı renk; doğal bileşen; %100 vegan; premium kalite"),
        ("oVertone Purple", "overtone.co", "Mor Şampuan", "Purple for Brown Hair; sarı tonları nötralize; koyu saçlar için özel; erişilebilir"),
        ("Clairol Natural Instincts", "clairol.com", "Doğal Görünüm Boya", "Demi-permanent; %80 doğal kaynak; amonyaksız; doğal görünüm ev boyası"),
        ("Revlon ColorSilk", "revlon.com", "Erişilebilir Ev Boyası", "$3.50 ev boyası; Keratin bileşen; en çok satan ev boyası; ultra erişilebilir"),
        ("L'Oréal Colorista", "lorealfrpfrris.com", "Semi-Permanent Renk", "Washout + semi-permanent renk; genç hedef; mavi, pembe, mor; erişilebilir trend"),
        ("Schwarzkopf Got2b", "got2b.com", "Metalik Renk", "Metallics saç boyası; metalik tonlar; Alman kalite; trend renkler"),
        ("Garnier Nutrisse", "garnierusa.com", "Besleyici Boya", "Avokado + zeytin + shea yağları; boyarken besler; erişilebilir; geniş ton"),
        ("Wella Color Charm", "wella.com", "Salon Formülü Evde", "Salon formülü ev kullanımı; demi + permanent; profesyonel tonlar; erişilebilir"),
        ("Punky Colour", "punky.com", "Semi-Permanent Renkli", "3-in-1 Color Depositing Shampoo; renkli şampuan + saç kremi; punk renkler"),
        ("Hally Hair", "hallyhair.com", "Gen Z Renk Mousse", "Color Cloud köpük; geçici renkli mousse; yıkanabilir; Gen Z; eğlenceli"),
        ("Josh Wood Colour", "joshwoodcolour.com", "İngiliz Salon Renk", "Londra salon renk uzmanı; kişisel renk danışmanlığı; ev hattı; premium İngiliz"),
        ("eSalon", "esalon.com", "Kişisel Renk Formülü", "Quiz bazlı kişisel saç renk formülü; 11K+ formül; kolorist destekli; özel"),
        ("Color&Co by L'Oréal", "colorandco.com", "Kişisel Renk Kutusu", "L'Oréal kişisel renk; video konsültasyon; kolorist ile renk formülü; $20"),
    ],

    "Parfüm & Koku - Vücut Spreyi & Mist": [
        ("Sol de Janeiro Body Mist", "soldejaneiro.com", "Brezilya Vücut Mist", "Brazilian Bum Bum Body Mist; Cheirosa koku serisi; tropikal; #62 ikonik"),
        ("Ouai Body Mist", "theouai.com", "Saç + Vücut Sprey", "North Bondi; saç + vücut mist; Jen Atkin; hafif günlük koku; çok amaçlı"),
        ("Touchland Mist", "touchland.com", "Parfümlü Dezenfektan", "Power Mist parfümlü el dezenfektanı; 'dezenfektanı güzel yaptı'; tasarımcı koku"),
        ("Victoria's Secret Body", "victoriassecret.com", "Klasik Vücut Mist", "Bombshell body mist; en çok satan vücut spreyi; nostalji + günlük koku"),
        ("Bath & Body Works Mist", "bathandbodyworks.com", "ABD Vücut Spreyi", "Japanese Cherry Blossom; A Thousand Wishes; mevsimsel koleksiyonlar; ikonik"),
        ("Body Fantasies", "bodyfrntasies.com", "Bütçe Vücut Sprey", "Coconut Fantasy; $5 altı vücut spreyi; erişilebilir günlük koku; nostalji"),
        ("Clean Reserve Skin", "cleanbeauty.com", "Temiz Cilt Kokusu", "Skin parfüm + vücut mist; temiz formül; pijama kokusu konsepti"),
        ("Skylar Body Mist", "skylar.com", "Hipoalerjenik Mist", "Hipoalerjenik vücut mist; hassas cilt güvenli; temiz bileşen; kişisel"),
        ("Le Monde Gourmand", "lfrmondefrgourmand.com", "Gurme Vücut Mist", "Crème Brûlée, Matcha Latte koku; tatlı gurme kokular; Target'ta; erişilebilir"),
        ("Fine'ry", "finery.com", "Target Premium Vücut", "Target'ın premium vücut koku markası; $11; lüks hissi uygun fiyat; zarif ambalaj"),
        ("Being Frenshe", "beingfrenshe.com", "Ashanti Koku", "Ashley Tisdale; aromaterapi ilham; lavanta, okaliptüs; wellness koku"),
        ("Tree Hut Body Mist", "treehut.com", "Scrub'dan Mist'e", "Shea Sugar Scrub markasından vücut mist; tropikal kokular; erişilebilir"),
        ("Ariana Grande Cloud", "arianagrande.com", "Ünlü Vücut Mist", "Cloud parfüm + vücut mist; Baccarat Rouge 540 alternatifi; erişilebilir niş koku"),
        ("Billie Eilish Eilish", "billieeilish.com", "Şeker-Amber Koku", "Eilish parfüm; kakao + amber + vanilya; göğüs figür şişesi; sanatsal tasarım"),
        ("Phlur Body Mist", "phlur.com", "TikTok Viral Mist", "Missing Person vücut mist versiyonu; 'sevdiğin kişinin kokusu'; yumuşak"),
        ("Replica by MMM Mist", "maisonmargiela.com", "Anı Vücut Spreyi", "By the Fireplace, Beach Walk vücut spreyi; anı kokuları hafif formatta"),
        ("Nest Body Mist", "nestnewyork.com", "Lüks Ev Koku Mist", "Turkish Rose vücut mist; ev kokusundan vücuda; lüks günlük"),
        ("Tocca Body Mist", "tocca.com", "İtalyan Romantik Mist", "Florence vücut mist; İtalyan romantizm; hafif; günlük lüks; gardenia"),
        ("Ellis Brooklyn Body Mist", "ellisbrooklyn.com", "Temiz Lüks Mist", "SALT vücut mist; temiz formül; hafif; günlük; deniz kokusu"),
        ("Nest Mist Set", "nestnewyork.com", "Mini Mist Seti", "Mini vücut mist keşif seti; 5 farklı koku; hediye seti; deneme"),
    ],

    "Vücut Bakımı - Peeling & Scrub": [
        ("Tree Hut", "treehut.com", "Şeker Scrub Kralı", "Shea Sugar Scrub; tropikal kokular; $9; TikTok duş rutini viral; Target bestseller"),
        ("Frank Body", "frankbody.com", "Kahve Peeling OG", "Orijinal kahve vücut peelingi; Avustralya; 2M+ ürün; esprili marka sesi; viral"),
        ("Kopari Coconut Crush", "koparibeauty.com", "Hindistan Cevizi Scrub", "Coconut Crush Scrub; hindistan cevizi yağı + şeker; tropikal peeling"),
        ("Truly Beauty", "trulybeauty.com", "Renkli Vücut Bakımı", "Unicorn Fruit Body Butter + scrub; renkli; TikTok viral; Gen Z vücut bakımı"),
        ("Sol de Janeiro Bum Bum", "soldejaneiro.com", "Brezilya Scrub", "Bum Bum Body Scrub; Cupuaçu + hindistan cevizi yağı; Brezilya tropikal peeling"),
        ("Lush Scrubs", "lush.com", "Taze El Yapımı Peeling", "Ocean Salt scrub; taze limon + deniz tuzu; el yapımı; her mağazada taze"),
        ("Herbivore Coco Rose", "herbivorebotanicals.com", "Gül + Hindistan Cevizi", "Coco Rose Body Polish; gül suyu + hindistan cevizi; pembe; güzel koku; doğal"),
        ("Nécessaire The Body Exfoliator", "necessaire.com", "Lüks Vücut Peeling", "Bamboo Charcoal exfoliator; lüks vücut peelingi; $30; Sephora; premium"),
        ("KP Bump Eraser by First Aid", "firstaidbeauty.com", "KP Tedavi Peelingi", "KP Bump Eraser; keratosis pilaris tedavisi; glikolik + laktik asit; çözüm odaklı"),
        ("Soft Services Smoothing Solution", "softservices.com", "Vücut Cilt Sorunları", "KP + kuru cilt tedavi peelingi; vücuda özel aktif formül; hedefli çözüm"),
        ("Aesop Body Scrub", "aesop.com", "Lüks Botanik Peeling", "Geranium Leaf Body Scrub; botanik formül; pumice + bitki; lüks deneyim"),
        ("Palmer's Cocoa Butter Scrub", "palmers.com", "Kakao Yağı Scrub", "Cocoa Butter Formula Scrub; kakao yağı nemlendirme; erişilebilir; $8"),
        ("Dove Exfoliating Scrub", "dove.com", "Nazik Peeling", "Pomegranate Seeds + Shea Butter; nazik günlük peeling; erişilebilir; $7"),
        ("St. Ives Scrub", "stives.com", "Klasik Kayısı Peeling", "Apricot Scrub; Amerika'nın klasik peelingi; fiziksel eksfoliasyon; $4; nostaljik"),
        ("Dermalogica Daily Microfoliant", "dermalogica.com", "Toz Peeling", "Pirinç bazlı enzim toz peeling; suyla aktive; salon profesyonel; günlük nazik"),
    ],

    "Vücut Bakımı - Tüy Dökücü & Epilasyon": [
        ("Ulike", "ulike.com", "IPL Safir Soğutma", "Safir soğutma IPL; FDA onaylı; TikTok viral; $300 salon alternatifi; anında sonuç"),
        ("Nood", "trynood.com", "En Ucuz IPL", "Flasher 2.0 IPL $170; en ucuz etkili cihaz; 'tıraşla ayrıl'; TikTok reklam"),
        ("RoseSkinCo", "roseskinco.com", "Gül Altın IPL", "Rose gold IPL cihaz; influencer pazarlama; $300; $3K salon tedavisi yerine"),
        ("SmoothSkin", "smoothskin.com", "İngiliz IPL Teknoloji", "Pure IPL; İngiliz IPL uzmanı; 10 yıl tecrübe; hızlı tedavi; evde lazer"),
        ("Braun Silk-Expert", "brfraunfrr.com", "Alman IPL Mühendisliği", "Silk-Expert Pro 5; SensoAdapt cilt tonu algılama; Alman mühendisliği; güvenli"),
        ("Philips Lumea", "philips.com", "Hollanda IPL", "Lumea Prestige; akıllı cilt sensörü; 4 başlık; Hollanda teknoloji; güvenilir"),
        ("Kenzzi", "kenzzi.com", "Kompakt IPL", "Kompakt IPL cihazı; seyahat dostu boyut; 300K flash; $229; erişilebilir"),
        ("Tria Beauty", "triabeauty.com", "Ev Lazer Öncüsü", "İlk FDA onaylı ev lazer epilasyon cihazı; diod lazer; klinik sonuç evde"),
        ("Silk'n", "silkn.com", "İsrail eHPL", "eHPL teknolojisi; Infinity cihazı sınırsız atış; İsrail inovasyonu; profesyonel"),
        ("Nair", "nair.com", "Kimyasal Tüy Dökücü", "Klasik tüy dökücü krem; 80+ yıl; bakım bileşenli modern formüller; erişilebilir"),
        ("Veet", "veet.com", "Global Tüy Dökücü", "Wax şeritleri + krem; global lider; Reckitt; hızlı ev epilasyonu; erişilebilir"),
        ("Flamingo", "shopflamingo.com", "Kadın Tıraş Ekosistemi", "Harry's kadın; tıraş + balmumu + vücut bakımı; güzel tasarım; Target"),
        ("Athena Club", "athenaclub.com", "Abonelik Tıraş + Bakım", "Kadın tıraş abonelik; vücut bakımı genişleme; temiz bileşen; Target"),
        ("Leaf Shave", "leafshave.com", "Plastisiz Tıraş", "Plastik olmayan pivotlu tıraş makinesi; standart çift kenar bıçak; sürdürülebilir; $85"),
        ("oui the people", "ouithepeople.com", "Kıvırcık Tüy Çözümü", "Tek bıçak güvenlik tıraş makinesi; kıvırcık tüy batması çözümü; kapsayıcı"),
    ],

    "Saç Bakımı - Styling & Isı Koruma": [
        ("Color Wow Dream Coat", "colorwowhair.com", "Nem Bariyeri Sprey", "Dream Coat Anti-Humidity Treatment; nem bariyeri; 3 gün kabarma önleme; viral"),
        ("Oribe Dry Texturizing", "oribe.com", "Kült Doku Spreyi", "Dry Texturizing Spray; kült ürün; altın ambalaj; kokusu bağımlılık; lüks styling"),
        ("Moroccanoil Treatment", "moroccanoil.com", "Argan Yağı Orijinal", "Treatment orijinal argan yağı; saç bakımı kategorisini başlattı; çok amaçlı; ikonik"),
        ("Bumble & Bumble Surf", "bumbleandbumble.com", "Plaj Dalgası Spreyi", "Surf Spray; plaj dalgası kategorisini yarattı; NYC salon; tuz spreyi ikonik"),
        ("IGK", "igkhair.com", "Sosyal Medya Saç", "Good Behavior spirulina protein smoothing spray; Miami salon; sosyal medya adlı ürünler"),
        ("Ouai Wave Spray", "theouai.com", "Influencer Dalga", "Wave Spray bestseller; Jen Atkin; parmakla taranmış dalgalar; hafif; günlük"),
        ("Kenra", "kenraprofessional.com", "Salon Sprey Uzmanı", "Volume Spray 25; salon profesyonel sabitleyici; güçlü tutuş; $18"),
        ("Verb Ghost Oil", "verbproducts.com", "Hafif Saç Yağı", "Ghost Oil; ultra hafif; ağırlaştırmayan saç yağı; moringa; erişilebilir salon"),
        ("Chi Silk Infusion", "chi.com", "İpek Protein Koruma", "Silk Infusion; ısı koruması + parlaklık; ipek protein; salon profesyonel; ikonik"),
        ("TRESemmé Keratin Smooth", "tresemme.com", "Eczane Keratin", "Keratin Smooth; buklü/kabarık saç düzleştirme; erişilebilir salon hissi; $6"),
        ("Schwarzkopf OSiS+", "schwarzkopf.com", "Profesyonel Styling", "Dust It mattifying powder; 35+ styling ürünü; Alman profesyonel; salon"),
        ("Amika Perk Up", "loveamika.com", "Kuru Şampuan", "Perk Up Dry Shampoo; renkli ambalaj; hacim + tazeleme; profesyonel kalite"),
        ("Batiste Dry Shampoo", "batiste.com", "Kuru Şampuan Öncüsü", "Kuru şampuan kategorisi yaratıcısı; anında hacim; saç yıkama arası çözüm; $8"),
        ("Living Proof PhD", "livingproof.com", "Mükemmel Saç Günü", "Perfect Hair Day (PhD); MIT bilimi; her gün mükemmel saç; çoklu bileşen"),
        ("R+Co", "randco.com", "Boutique Salon Styling", "Death Valley Dry Shampoo; butik salon; koku + performans; sanatsal ambalaj"),
        ("Drybar", "thedrybar.com", "Fön Stüdyosu Ürünleri", "Buttercup Blow Dryer; fön stüdyosünden ürün; detangling fırça; styling uzmanı"),
        ("T3 Micro", "t3micro.com", "Teknoloji Styling Araçları", "Cura Luxe IonAir kurutma makinesi; SinglePass düzleştirici; teknoloji + saç"),
        ("ghd", "ghd.com", "Salon Standart Düzleştirici", "Gold Styler düzleştirici; salon profesyonel standart; İngiliz; $200; optimal ısı"),
        ("Bio Ionic", "bioionic.com", "NanoIonic Mineral", "NanoIonic mineral teknoloji; nemlendiren ısı; saç kurutma makinesi + düzleştirici"),
        ("BaByliss Pro", "babylisspro.com", "İtalyan Profesyonel", "Nano Titanium düzleştirici; titanyum plakalar; İtalyan tasarım; salon kalitesi"),
    ],

    "Saç Bakımı - Saç Maskesi & Onarım": [
        ("K18", "k18hair.com", "4 Dakika Onarım", "Leave-In Molecular Repair Mask; patentli biyoaktif peptit; 4 dakikada hasar onarım; devrim"),
        ("Olaplex No.3", "olaplex.com", "Bağ Onarım Tedavisi", "Hair Perfector No.3; bağ onarım öncüsü; salon teknolojisi evde; kült ürün"),
        ("Briogeo Don't Despair", "briogeohair.com", "Umutsuz Saç Maskesi", "Don't Despair, Repair! Deep Conditioning Mask; temiz + etkili; B-vitaminleri"),
        ("Moroccanoil Restorative", "moroccanoil.com", "Argan Onarım Maskesi", "Restorative Hair Mask; argan yağı + protein; derin onarım; salon kalitesi"),
        ("Christophe Robin Scrub", "christopherobin.com", "Tuz Saç Peelingi", "Cleansing Purifying Scrub with Sea Salt; Paris salon; saç derisi peeling; lüks"),
        ("Philip Kingsley Elasticizer", "philipkingsley.com", "Saç Esneklik Tedavisi", "Elasticizer pre-shampoo tedavi; 1970'lerden beri; Audrey Hepburn kullanırdı; İngiliz"),
        ("Davines Oi", "davines.com", "İtalyan Çok Amaçlı", "OI All in One Milk; roucou yağı; 12 fayda tek üründe; İtalyan sürdürülebilir"),
        ("Kérastase Résistance", "kerastase.com", "Salon Lüks Onarım", "Masque Force Architecte; lüks salon maskesi; L'Oréal Professional; yoğun onarım"),
        ("Redken All Soft", "redken.com", "Protein Nem Dengesi", "All Soft Mega Curls Mask; argan yağı; protein + nem dengesi; salon profesyonel"),
        ("Pureology Hydrate", "pureology.com", "Renk Koruma Maske", "Hydrate Superfood Treatment; renk korumalı nemlendirme; sülfatsız; vegan"),
        ("Aussie 3 Minute Miracle", "aussie.com", "3 Dakika İkonik", "3 Minute Miracle ikonik saç maskesi; Avustralya botanik; erişilebilir; hızlı"),
        ("Garnier Fructis", "garnier.com", "Meyve Protein Maske", "Hair Food 3-in-1 maske; muz, avokado, papaya; $5; erişilebilir protein"),
        ("Coco & Eve Like a Virgin", "cocoandeve.com", "Bali Saç Maskesi", "Like a Virgin Hair Masque; Bali estetiği; güzel ambalaj; viral; $40"),
        ("It's a 10", "itsa10haircare.com", "10 Fayda Tek Ürün", "Miracle Leave-In Product; 10 fayda tek üründe; salon profesyonel; çok amaçlı"),
        ("Mielle Babassu Oil", "mielleorganics.com", "Doğal Saç Maske", "Babassu Oil & Mint Deep Conditioner; doğal saç; brezilya fındığı yağı; derin bakım"),
    ],

    "Cilt Cihazları - Temizleme Cihazı": [
        ("Foreo Luna", "foreo.com", "Silikon Temizleme", "LUNA 4; silikon yüz temizleme; hijyenik (fırça başlığı yok); İsveç; 8000 titreşim/dk"),
        ("Foreo UFO", "foreo.com", "Akıllı Maske Cihazı", "UFO 2 maske cihazı; 90 saniye maske tedavisi; LED + ısı + soğutma; inovatif"),
        ("PMD Clean", "pmdbeauty.com", "SonicGlow Temizleme", "Clean Pro; SonicGlow teknoloji; ActiveWarmth ısı; masaj + temizleme; FDA"),
        ("LUNA play by Foreo", "foreo.com", "Mini Temizleme", "LUNA play plus 2; mini boyut; $49; giriş seviye sonic temizleme; seyahat"),
        ("Michael Todd Beauty", "michaeltoddbeauty.com", "Soniclear Titreşim", "Soniclear Petite; antimikrobiyal fırça başlığı; 3 hız; erişilebilir sonic"),
        ("AENO", "aeno.com", "Ultrasonik Temizleme", "Ultrasonik cilt temizleme; derin gözenek temizliği; spatula format; Avrupa"),
        ("Refa", "rfrfa.com", "Japon Mikro-Akım Roller", "Carat Face roller; mikro-akım; Japon güzellik cihazı; platin kaplama"),
        ("YA-MAN", "ya-man.com", "Japon Güzellik Teknoloji", "Photo PLUS EX; RF + LED + EMS; Japon güzellik cihaz lideri; çok fonksiyonlu"),
        ("NuSkin ageLOC", "nuskin.com", "Anti-Aging Cihaz", "ageLOC LumiSpa; temizleme + anti-aging tek cihazda; silikon başlık; çift etki"),
        ("Panasonic Beauty", "panasonic.com", "Japon Buhar Cihazı", "Nanoe Steamer; nano-boyut buhar; Japon ev güzellik cihazı; derin nemlendirme"),
        ("Philips VisaPure", "philips.com", "Hollanda Temizleme Fırça", "VisaPure Advanced; hassas + yağlı + karma cilt başlıkları; kişiselleştirilmiş"),
        ("Olay Regenerist", "olay.com", "Micro-Sculpting Cihaz", "Regenerist Face Cleansing Device; titreşimli; erişilebilir; $30 cilt cihazı"),
        ("GESKE", "gefrske.com", "Alman MicroCurrent Sonic", "SmartAppGuided cihazlar; mikro-akım + sonic; Alman tasarım; app rehberli"),
        ("Derma Dream", "derfrmadream.com", "LED + Ultrasonik", "LED maske + ultrasonik peeling; ev estetik kombo; erişilebilir cihaz seti"),
        ("Vanity Planet", "vanityplanet.com", "Erişilebilir Cilt Cihaz", "Raedia Facial Cleansing Brush; $50 altı; erişilebilir cilt cihazları; geniş ürün"),
    ],

    "Makyaj - Fondöten & BB/CC Krem": [
        ("Sheglam Skin Focus", "sheglam.com", "Ultra Uygun Fondöten", "Skin Focus Foundation $5; TikTok viral; Shein güzellik; Gen Z; geniş ton"),
        ("Revolution Pro", "revolutionbeauty.com", "İngiliz Dupe Fondöten", "Skin Finish Foundation; lüks dupe; İngiliz; uygun fiyat + kalite; 40+ ton"),
        ("Catrice True Skin", "catrice.eu", "Alman Doğal Fondöten", "True Skin Foundation $9; doğal bitişli; Alman kalite; 30 ton; erişilebilir"),
        ("Essence Pretty Natural", "essence.eu", "Avrupa En Ucuz", "Pretty Natural Foundation $5; hyaluronik asit; Alman; ultra uygun; kaliteli"),
        ("L.A. Girl Pro Coverage", "lagirlusa.com", "LA İllüzyon Fondöten", "Pro Coverage Illuminating Foundation; geniş ton; $8; profesyonel kalite erişilebilir"),
        ("Wet n Wild Photo Focus", "wetnwild.com", "Fotojeik $6 Fondöten", "Photo Focus Foundation; $6 fotojerik; mat; geniş ton; PETA sertifikalı"),
        ("Maybelline Fit Me", "maybelline.com", "En Çok Satan Fondöten", "Fit Me Matte + Poreless; dünyada en çok satan fondöten; 40+ ton; $8"),
        ("L'Oréal True Match", "loreal.com", "Ton Eşleştirme", "True Match Super-Blendable; altton eşleştirme (sıcak/soğuk/nötr); geniş ton; $11"),
        ("NYX Can't Stop", "nyxcosmetics.com", "24 Saat Fondöten", "Can't Stop Won't Stop 24HR Foundation; mat; uzun kalıcı; 45 ton; $15"),
        ("Milani Conceal+Perfect", "milani.com", "İtalyan Kapatıcı Fondöten", "Conceal + Perfect 2-in-1 Foundation; 45 ton; İtalyan ilham; $10; kapatıcı + fondöten"),
        ("ColourPop Pretty Fresh", "colourpop.com", "Hyaluronik Fondöten", "Pretty Fresh Hyaluronic Acid Tinted Moisturizer; HA + SPF; $14; dewy"),
        ("Flower Beauty Light Illusion", "flowerbeauty.com", "Drew Barrymore Fondöten", "Light Illusion Foundation; ışık difüzyon; doğal; erişilebilir temiz; $12"),
        ("bareMinerals Original", "bareminerals.com", "Mineral Fondöten Öncüsü", "Original Loose Powder Foundation; mineral makyaj kategorisi yaratıcısı; SPF; temiz"),
        ("Fenty Eaze Drop", "fentybeauty.com", "Blurring Cilt Tint", "Eaze Drop Blurring Skin Tint; hafif; 25 ton; bulanıklaştırma etkisi; $32"),
        ("Il Makiage Woke Up Like This", "ilmakiage.com", "AI Ton Eşleştirme", "PowerMatch AI algoritması ile ton eşleştirme; quiz bazlı; 50 ton; İsrail; $44"),
    ],

    "Cilt Bakımı - Dudak Bakımı": [
        ("Laneige Lip Sleeping", "laneige.com", "Gece Dudak Maskesi", "Lip Sleeping Mask dünyada #1; Berry lezzet ikonik; her 2 saniyede bir satılıyor"),
        ("Dior Lip Glow", "dior.com", "Lüks Dudak Balmı", "$40 lüks renkli balm; doğal dudak rengini canlandırır; her makyaj çantasının parçası"),
        ("Summer Fridays Lip Butter", "summerfridays.com", "TikTok Viral Balm", "Lip Butter Balm; vanilya + shea; TikTok viral nemlendirici dudak balmı"),
        ("Rhode Peptide Lip", "rhodeskin.com", "Peptid Dudak Tedavisi", "Peptide Lip Treatment; Hailey Bieber; hemen tükeniyor; telefon kılıfı aksesuarı"),
        ("Aquaphor Lip Repair", "aquaphor.com", "Klasik Onarım", "Lip Repair ointment; SOS dudak onarımı; kışın olmazsa olmaz; $5"),
        ("Burt's Bees", "burtsbees.com", "Arı Balmı OG", "Beeswax Lip Balm; arı balmumu ikonik; 30+ yıl; en çok satılan doğal dudak balmı"),
        ("Jack Black Lip Balm", "getjackblack.com", "Erkek SPF Dudak", "Intense Therapy Lip Balm SPF 25; erkek dudak bakımı; mint; SPF koruma"),
        ("Fresh Sugar Lip", "fresh.com", "Şeker Dudak Tedavisi", "Sugar Lip Treatment SPF 15; şeker bazlı; renkli; SPF; lüks günlük dudak"),
        ("Glossier Balm Dotcom", "glossier.com", "Çok Amaçlı Balm", "Balm Dotcom universal skin salve; dudak + parmak + dirsek; 8 koku; $12"),
        ("Kiehl's Lip Balm", "kiehls.com", "NYC Eczane Dudak", "Lip Balm #1; 1851 NYC eczane; squalane + vitamin E; klasik"),
        ("Tatcha Kissu Lip Mask", "tatcha.com", "Japon Dudak Maske", "Kissu Lip Mask; Japon şeftali + squalane; gece dudak maskesi; lüks"),
        ("Caudalie Lip Conditioner", "caudalie.com", "Fransız Üzüm Dudak", "Lip Conditioner; üzüm polifenol; Fransız eczane; besleyici dudak bakımı"),
        ("Nuxe Rêve de Miel", "nuxe.com", "Fransız Bal Dudak", "Rêve de Miel Lip Balm; Fransız bal balmı; her 16 saniyede bir satılıyor; ikonik"),
        ("Weleda Skin Food Lip", "weleda.com", "Doğal Yoğun Dudak", "Skin Food Lip Butter; yoğun nemlendirme; biyodinamik bileşenler; $10"),
        ("Dr. Lipp Original Nipple Balm", "drlipp.com", "Meme Ucu Balmı → Dudak", "Lanolin bazlı; meme ucu balmı dudak balmı olarak viral; çok amaçlı"),
        ("Drunk Elephant Lippe", "drunkelephant.com", "Peptid Dudak Bakımı", "Lippe Balm; peptid + marula; temiz dudak bakımı; gece onarım"),
        ("Tower 28 ShineOn", "tower28beauty.com", "Hassas Dudak Jelly", "ShineOn Lip Jelly; hassas dudaklar için; NEA onaylı; renkli parlak; temiz"),
    ],

    "Cilt Bakımı - Hassas Cilt": [
        ("La Roche-Posay Toleriane", "laroche-posay.com", "Fransız Hassas Standart", "Toleriane serisi; hassas cilt altın standardı; termal su; minimal bileşen"),
        ("Avène", "eau-thermale-avene.com", "Termal Su Hassas", "Thermal Spring Water; 270 yıllık termal kaynak; ultra hassas cilt; Pierre Fabre"),
        ("First Aid Beauty", "firstaidbeauty.com", "Acil Hassas Bakım", "Ultra Repair Cream; FAB; SOS hassas cilt bakımı; koloidal yulaf; erişilebilir"),
        ("Vanicream", "vanicream.com", "Dermatolojist Saf", "Moisturizing Cream; sıfır koku, sıfır boya, sıfır formaldehit; ultra saf; eczane"),
        ("Eucerin", "eucerin.com", "Alman Eczane Hassas", "Original Healing Cream 1900'den beri; dermatolojist önerisi; Beiersdorf; güvenilir"),
        ("Cetaphil", "cetaphil.com", "Nazik Temizleme Öncüsü", "Gentle Skin Cleanser 1947'den beri; dermatolojist reçetesi; hassas cilt standardı"),
        ("Bioderma Sensibio", "bioderma.com", "Fransız Misel Hassas", "Sensibio H2O; hassas cilt misel su; Fransız eczane; MUA favorisi"),
        ("Simple Skincare", "simpleskincare.com", "Hassas Basit", "Kind to Skin; hassas cilt için basit formüller; parfümsüz; İngiliz"),
        ("Pai Rosehip", "paiskincare.com", "UK Organik Hassas", "Rosehip BioRegenerate Oil; UK hassas cilt organik; kuşburnu yağı; sertifikalı"),
        ("Klairs Soothing", "klairs.com", "Kore Hassas Tonik", "Supple Preparation Unscented Toner; kokusuz versiyon; hassas cilt Kore"),
        ("Etude SoonJung", "etude.com", "Kore pH Hassas", "SoonJung 5-Panthensoside Cica Balm; pH 5.5; hassas cilt Kore; panthenol"),
        ("Illiyoon Ceramide", "illiyoon.com", "Kore Atopik Bakım", "Ceramide Ato Lotion; atopik dermatit bakımı; bebek + yetişkin; AmorePacific"),
        ("Aveeno Calm + Restore", "aveeno.com", "Yulaf Hassas", "Calm + Restore Oat Gel Moisturizer; yulaf + feverfew; hassas cilt sakinleştirme"),
        ("Drunk Elephant Protini", "drunkelephant.com", "Protein Nemlendirici", "Protini Polypeptide Cream; peptid + amino asit; hassas uyumlu; temiz"),
        ("Dr. Jart Cicapair", "drjart.com", "Kaplan Otu Hassas", "Cicapair Tiger Grass; Kore cica klasiği; kızarıklık + hassasiyet; renk düzeltici"),
    ],

    "Cilt Bakımı - Hiperpigmentasyon": [
        ("Topicals", "mytopicals.com", "Cilt Sorunları Normalleştirme", "Faded serum; hiperpigmentasyon + sikatris; cilt sorunlarını normalleştirme; Gen Z"),
        ("Good Molecules Discoloration", "goodmolecules.com", "Uygun Fiyat Leke Serumu", "Discoloration Correcting Serum; traneksemik asit; $12; The Ordinary alternatifi"),
        ("Naturium Azelaic", "naturium.com", "Azelaic Asit Emülsiyon", "Azelaic Acid Emulsion %10; leke + kızarıklık; erişilebilir aktif tedavi"),
        ("Paula's Choice Niacinamide", "paulaschoice.com", "Niacinamide Güçlendirici", "%10 Niacinamide Booster; gözenek + leke; bilim bazlı; 30+ yıl güvenilirlik"),
        ("Murad Rapid Age Spot", "murad.com", "Hızlı Leke Tedavisi", "Rapid Age Spot and Pigment Lightening Serum; hidrokinon + glikolik asit; agresif"),
        ("SkinCeuticals Discoloration", "skinceuticals.com", "Klinik Leke Serum", "Discoloration Defense; traneksemik + niacinamide + kojik; klinik kanıtlı; $98"),
        ("Dr. Dennis Gross Vitamin C", "drdennisgross.com", "C Vitamini Leke", "C+ Collagen Brighten & Firm; C vitamini + kolajen; aydınlatma + sıkılaştırma"),
        ("Melano CC Intensive", "rohto.com", "Japon C Vitamini Leke", "Intensive Anti-Spot Essence; Japon stabil C vitamini; erişilebilir leke tedavisi"),
        ("Klairs Vitamin C", "klairs.com", "Kore Hassas C Vitamin", "Freshly Juiced Vitamin Drop; %5 hassas cilt C vitamini; Kore; nazik aydınlatma"),
        ("COSRX Vitamin C", "cosrx.com", "Kore Saf C Serum", "The Vitamin C 23 Serum; %23 saf askorbik asit; Kore güçlü C vitamini"),
        ("Beauty of Joseon Glow", "beautyofjoseon.com", "Kore Ginseng Aydınlatma", "Glow Serum; propolis + ginseng; Kore aydınlatma; TikTok viral"),
        ("Some By Mi AHA BHA PHA", "somebymi.com", "Kore 30 Gün Aydınlatma", "30 Days Miracle Serum; AHA + BHA + PHA; 30 günde sonuç; Kore viral"),
        ("Alpha Arbutin by Ordinary", "theordinary.com", "Uygun Fiyat Arbutin", "Alpha Arbutin 2% + HA; $9; arbutin leke tedavisi; ultra erişilebilir"),
        ("Faded by Topicals", "mytopicals.com", "Traneksemik Leke Serum", "Faded gel-krem; traneksemik asit + azelaic asit + niacinamide; çoklu aktif"),
        ("Geek & Gorgeous C-Glow", "geekandgorgeous.com", "Macar C Vitamini", "C-Glow %15 Ethylated Ascorbic Acid; stabil + etkili; €10; Avrupa DTC"),
    ],
}
