"""
Second supplementary batch - regional and niche cosmetics brands.
Focus on India, Korea, Japan, Australia, Europe, Middle East, Africa, LatAm.
"""

COSMETICS_EXTRA_2 = {
    "K-Beauty & Kore Kozmetik": [
        ("Sulwhasoo", "sulwhasoo.com", "Hanbang Lüks Anti-Aging", "Ginseng bazlı Kore geleneksel tıp; Concentrated Ginseng Renewing Cream; AmorePacific lüks"),
        ("Dr. Jart+", "drjart.com", "Dermatolojik K-Beauty", "Cicapair Tiger Grass renk düzeltici; BB krem öncüsü; dermatolojik bilim + K-beauty"),
        ("Blithe", "bfrlithe.com", "Sıkıştırılmış Maske", "Pressed Serum + Splash Mask; sıkıştırılmış formül inovasyonu; duşta maske konsepti"),
        ("Amorepacific", "amorepacific.com", "Çay Bazlı Lüks", "Yeşil çay + bambuk suyu; Kore'nin en büyük güzellik grubu; $3B+ gelir; lüks anti-aging"),
        ("Belif", "belifcosmetic.com", "Bitkisel İngiliz-Kore", "True Cream Moisturizing Bomb; İngiliz herbal + Kore teknoloji; LG H&H; nem uzmanı"),
        ("Hera", "hfrra.com", "Kore Haute Couture Güzellik", "Black Cushion lüks; AmorePacific premium; K-pop reklam yüzleri; Kore lüks makyaj"),
        ("Iope", "iope.com", "Biyoteknoloji Kore", "Air Cushion orijinal icat eden marka; bio-essence; AmorePacific; teknoloji liderliği"),
        ("The History of Whoo", "whoo.com", "Kore Kraliyet Güzelliği", "Kore kraliyet sarayı tarihi formüller; lüks ginseng + deer antler; $1B+ marka"),
        ("Ohui", "ohui.com", "Kore Anti-Aging Lüks", "LG H&H lüks; Age Recovery Cream; Kore dermatoloji bilimi; premium yaşlanma karşıtı"),
        ("Mamonde", "mamonde.com", "Çiçek Enerjisi K-Beauty", "Rose Water Toner; çiçek bazlı bileşenler; AmorePacific; gül suyu uzmanı"),
        ("Nature Republic", "naturerepublic.com", "Aloe Vera Jel Kralı", "Soothing & Moisture Aloe Vera 92% Gel; her K-beauty koleksiyonunun temel ürünü"),
        ("The Face Shop", "thefaceshop.com", "Kore Doğal", "Rice Water Bright temizleme köpüğü; pirinç suyu güzellik; LG H&H; erişilebilir"),
        ("Skinfood", "skinfood.com", "Yiyecek Bazlı K-Beauty", "Yiyecek ingrediyenlerden cilt bakımı; Black Sugar maske; yumurta gözenek primer; gıda konsepti"),
        ("Mediheal", "mediheal.com", "Kore Maske Şampiyonu", "N.M.F Aquaring Ampoule Mask; Kore maske endüstrisinin lideri; BTS collab; 1.3B maske satıldı"),
        ("Jayjun", "jayjun.com", "Kore Estetik Maske", "Baby Pure Shining Mask; estetik klinik + kozmetik; lüks maske deneyimi"),
        ("Papa Recipe", "paparecipe.com", "Bombee Bal Maske", "Bombee Honey Mask ikonik; arı + bal temalı; doğal Kore maske; şirin ambalaj"),
        ("Dr.G", "drg.co.kr", "Kore Dermatoloji Makyaj", "Red Blemish Clear Soothing Cream; dermatolojist + güzellik; klinik + kozmetik"),
        ("Aprilskin", "aprilskin.com", "Sihirli Sabun", "Magic Stone sabun; çift taraflı (siyah + beyaz); temizleme inovasyonu; viral"),
        ("Holika Holika", "holikaholika.com", "Eğlenceli K-Beauty", "Pig-Nose Clear Blackhead; meyve şeklinde ambalaj; genç; trendli; uygun fiyat"),
        ("Dear Klairs", "klairs.com", "Hassas Cilt Öncüsü", "Supple Preparation Toner; hassas cilt Kore klasiği; Wishtrend; unisex; minimal"),
        ("Missha", "missha.com", "Essence Dupe Kralı", "Time Revolution First Treatment Essence; SK-II alternatifi; 1/10 fiyat; erişilebilir Kore"),
        ("Innisfree", "innisfree.com", "Jeju Volkanik", "Volcanic Pore Clay Mask; Jeju Adası doğal bileşenler; çevre dostu; AmorePacific"),
        ("Etude House", "etude.com", "Sevimli Kore Makyaj", "Dear Darling Water Tint; sevimli ambalaj; oyuncu K-beauty; erişilebilir; genç hedef"),
        ("Tony Moly", "tonymoly.com", "Meyve Ambalaj", "Peach Lip Balm şeftali şeklinde; eğlenceli şekilli ambalajlar; oyuncu K-beauty"),
        ("Laka", "laka.co.kr", "Cinsiyetsiz K-Beauty", "Kore ilk cinsiyetsiz güzellik markası; Fruity Glam Lip Tint; gender-fluid güzellik"),
        ("Hince", "hince.co.kr", "Minimalist K-Makyaj", "True Dimension Radiance Balm; minimal estetik; sanatsal; sessiz lüks Kore"),
        ("Amuse", "amuse.co.kr", "Vegan K-Beauty", "Dew Velvet Lip Tint; Kore'nin ilk vegan sertifikalı güzellik markası; Gen Z"),
        ("Dear Dahlia", "deardahlia.com", "Dahlia Lüks Vegan", "Paradise Dream Cushion; %100 vegan lüks K-beauty; dahlia çiçeği teması"),
        ("Nacific", "nacific.com", "Phyto Niacin Aydınlatma", "Phyto Niacin Whitening Essence; doğal aydınlatma; Kore bitki bilimi; erişilebilir"),
        ("Espoir", "espoir.com", "Kore Pro Makyaj", "Pro Tailor Foundation; geniş ton; profesyonel K-makyaj; AmorePacific alt marka"),
    ],

    "Cilt Bakımı - Nemlendirici & Serum": [
        ("Minimalist", "minimfrst.co", "Hindistan Aktif Cilt", "The Ordinary Hindistan versiyonu; %10 niacinamide, retinol; bilimsel şeffaflık; INR 300-600"),
        ("Dot & Key", "dotrfrndkey.in", "Hindistan Trendy Cilt", "Vitamin C + E serum; renkli ambalaj; Z kuşağı Hindistan; Nykaa satış şampiyonu"),
        ("Plum", "plfrm.com", "Hindistan Vegan Temiz", "Green Tea serisi; %100 vegan; Hindistan temiz güzellik öncüsü; Unilever yatırım"),
        ("The Derma Co", "thedfrrmaco.com", "Hindistan Dermatolojik", "Aktif bileşen odaklı; salisilik asit, retinol; erişilebilir Hindistan klinik cilt"),
        ("Mamaearth", "mamaearth.in", "Hindistan Doğal", "Onion Hair Oil viral; doğal + toksik olmayan; $1B+ değerleme; Honasa Consumer"),
        ("WOW Skin Science", "wowskfrscience.com", "Hindistan Apple Cider", "ACV şampuan Hindistan #1; doğal bileşenler; $100M+ gelir; Amazon hit"),
        ("Re'equil", "refrquil.com", "Hindistan Dermo", "SPF 50 PA+++ gel; dermatolojist formüller; Hindistan eczane güzelliği; erişilebilir klinik"),
        ("Deconstruct", "deconstruct.in", "Hindistan Bileşen Odaklı", "Niacinamide + HA serum; bilimsel Hindistan cilt bakımı; şeffaf formülasyon"),
        ("Suganda", "suganda.co", "Hindistan Kore Ilham", "K-beauty ilhamlı Hindistan markası; Centella serum; indie Hindistan güzellik"),
        ("Pilgrim", "discover.pilgrimfr.com", "Hindistan Dünya Güzelliği", "Kore, Japonya, Fransa reçetelerinden ilham; global güzellik sırları Hindistan'da"),
        ("Juicy Chemistry", "juicychemistry.com", "Hindistan Organik Sertifikalı", "COSMOS sertifikalı organik; soğuk sıkım yağlar; Hindistan indie organik"),
        ("Earth Rhythm", "earthrfrythm.com", "Hindistan Sürdürülebilir", "Phyto ceramide krem; sürdürülebilir ambalaj; Hindistan temiz güzellik"),
        ("Aqualogica", "aqualogica.in", "Hindistan Hidrasyon", "Hydrate+ HA serum; Hindistan gençlerine yönelik; uygun fiyat hidrasyon"),
        ("Dr. Sheth's", "drfrshfrths.com", "Hindistan Ayurveda + Bilim", "Haldi + Hyaluronic serum; Ayurveda + modern bilim; Hindistan hibrit cilt bakımı"),
        ("Forest Essentials", "forestessentials.com", "Lüks Ayurveda", "Soundarya Radiance Cream; lüks Ayurveda; Hindistan premium; doğal aktifler"),
        ("Kama Ayurveda", "kamaayurveda.com", "Ayurveda Klasik", "Kumkumadi gece yağı; geleneksel Ayurveda formüller; Hindistan premium doğal"),
        ("SoulTree", "soultree.in", "Hindistan Organik Makyaj", "Kajal göz kalemi; organik + Ayurveda; USDA organik Hindistan makyajı"),
        ("Just Herbs", "justherbs.in", "Hindistan Bitkisel", "Gotukola Indian Ginseng serum; Himalaya bitkileri; Hindistan herbal güzellik"),
        ("Sugar Cosmetics", "sugarcosmetics.com", "Hindistan Makyaj DTC", "Smudge Me Not Lipstick; Hindistan'ın Kylie Cosmetics'i; Vineeta Singh; $200M+ değerleme"),
        ("MyGlamm", "myglamm.com", "Hindistan Hızlı Makyaj", "LIT Lipstick; Bollywood celeb collab; Hindistan DTC makyaj; $150M+ değerleme"),
        ("Nykaa Cosmetics", "nfrykaa.com", "Hindistan Platform Marka", "Hindistan güzellik platformu kendi markalarını çıkardı; 70M+ kullanıcı; IPO"),
        ("Typology", "typology.com", "Fransız Minimal Cilt", "Paris; 10 bileşen veya daha az; tanı quizi; minimal cam ambalaj; şeffaf fiyat"),
        ("Caudalie", "caudalie.com", "Fransız Üzüm Cilt", "Vinoperfect Serum; üzüm polifenol antioksidan; Bordeaux üzüm bağları; Fransız eczane"),
        ("Nuxe", "nfrmrxfre.com", "Fransız Çok Amaçlı", "Huile Prodigieuse kuru yağ; yüz + vücut + saç; Fransız çok amaçlı ikonik; altın parıltı"),
        ("Filorga", "filorga.com", "Fransız Mezoterapi", "Time-Filler krem; mezoterapi ilhamlı; Fransız anti-aging; NCEF teknoloji"),
        ("Embryolisse", "embryolisse.com", "Fransız MUA Favorisi", "Lait-Crème Concentré; Paris MUA'ların sırrı; 70+ yıl; makyaj bazı + nemlendirici"),
        ("Avène", "eau-thermale-avene.com", "Fransız Termal Su", "Thermal Spring Water sprey; 270 yıllık termal kaynak; hassas cilt uzmanı; Pierre Fabre"),
        ("Uriage", "uriage.com", "Fransız Termal Dermoeczane", "Bariéderm Cica-Cream; termal su + dermo; Fransız eczane; hassas cilt"),
        ("Bioderma", "bioderma.com", "Fransız Misel Su", "Sensibio H2O misel su; backstage MUA olmazsa olmazı; Fransız eczane klasiği"),
        ("SVR", "svr.com", "Fransız Dermatolojik", "Sensifine AR anti-redness; Fransız dermatoloji markası; kızarıklık uzmanı; eczane"),
        ("Sand & Sky", "sandandsky.com", "Avustralya Pembe Kil", "Australian Pink Clay Mask; Instagram'da viral pembe maske; Avustralya botanik"),
        ("Go-To Skincare", "gotoskincare.com", "Avustralya Basit Cilt", "Zoe Foster Blake; basit ama etkili; Avustralya; 5 ürünlü rutin; net iletişim"),
        ("Ultra Violette", "ultraviolette.com.au", "Avustralya SPF Uzmanı", "Queen Screen SPF 50+; hafif formüller; Avustralya güneş kültürü; SPF odaklı"),
        ("Frank Body", "frankbody.com", "Avustralya Kahve Scrub", "Kahve vücut peelingi viral; 2M+ ürün; esprili marka sesi; Avustralya"),
        ("Aesop", "aesop.com", "Avustralya Eczane Lüks", "Resurrection Hand Wash; botanik formüller; mimari mağazalar; L'Oréal $2.5B satın aldı"),
        ("Grown Alchemist", "grownalchemist.com", "Avustralya Biyoteknoloji", "Biyoteknoloji + doğal; el kremi ikonik; Melbourne; lüks + bilim"),
        ("Alpha-H", "alpha-h.com", "Avustralya Glikolik Asit", "Liquid Gold %5 glikolik asit lotion; gece peeling; Avustralya klinik cilt bakımı"),
        ("Rationale", "rationale.com", "Avustralya #1 + #2 + #3", "3 adım sistem; SPF uzmanı; Avustralya dermatolojist kurdu; premium; bilimsel"),
        ("MV Skintherapy", "mvskintherapy.com", "Avustralya Organik Tedavi", "Sharon McGlinchey; organik cilt terapi; Melbourne; bütüncül yaklaşım; profesyonel"),
    ],

    "J-Beauty & Japon Kozmetik": [
        ("Hada Labo", "hadalabo.com", "Hyaluronik Asit Uzmanı", "Gokujyun Premium 7 tip HA; Japon eczane #1 nemlendirici; ultra hidrasyon; Rohto"),
        ("Melano CC", "rohto.com", "Japon C Vitamini", "Vitamin C Concentrated Essence; Japon leke tedavisi #1; stabil askorbik asit; eczane"),
        ("Canmake", "canmake.com", "Japon Bütçe Güzellik", "Cream Cheek allık $5; Mermaid Skin Gel UV SPF; Japon bütçe kalitesi; ikonik"),
        ("Biore", "biore.com", "Japon UV Uzmanı", "UV Aqua Rich Watery Essence SPF 50; en hafif güneş kremi; Japon UV teknolojisi"),
        ("Kose", "kfrse.com", "Japon Premium Cilt", "Sekkisei lotion; Japon bitki + teknoloji; 75+ yıl; premium cilt bakımı"),
        ("Shiseido Waso", "shiseido.com", "Japon Süperfood Cilt", "Waso genç hattı; Japon süperfood (tofu, wasabi, miso); modern J-beauty"),
        ("SK-II", "sk-ii.com", "Pitera Özü Lüks", "Facial Treatment Essence; sake mayalanma keşfi; $100+ serum; Japon biyoteknoloji"),
        ("Tatcha", "tatcha.com", "Geisha Güzellik Sırları", "Dewy Skin Cream; Japon geisha güzellik ritüelleri; Unilever satın aldı; lüks"),
        ("DHC", "dhccare.com", "Japon Zeytin Temizleme", "Deep Cleansing Oil Japonya #1 makyaj temizleyici 20+ yıl; zeytin yağı bazlı"),
        ("Shu Uemura", "shuuemura.com", "Japon Sanat Temizleme", "Ultime8 Cleansing Oil; Japon makyaj sanatçısı mirası; temizleme yağı ustası"),
        ("Suqqu", "suqqu.com", "Japon Lüks Makyaj", "Designing Color Eyes palette; Japon zanaatkarlık; lüks makyaj; POLA ORBIS"),
        ("THREE", "threecosmetics.com", "Japon Organik Lüks", "Angelic Complexion Primer; organik + doğal Japon lüks; POLA ORBIS"),
        ("RMK", "rmkrmk.com", "Japon Temiz Makyaj", "Gel Creamy Foundation; Japon minimalist makyaj; doğal bitişli; Kanebo"),
        ("KATE", "nfrfrever.jp", "Japon Trend Makyaj", "Lash Maximizer maskara; Japon trend makyaj; Kanebo; uygun fiyat + kalite"),
        ("Dejavu", "dejavu-net.jp", "Japon Film Maskara", "Fiberwig maskara tüp teknolojisi; sıcak su ile çıkar; akma yapmaz; Japon inovasyon"),
        ("Heroine Make", "heroinefrke.com", "Japon Uzun Kalıcı", "Long Curl Mascara Super Waterproof; Japon uzun kalıcılık kralı; sıcak su temizleme"),
        ("Maquillage", "maquillage.shiseido.co.jp", "Japon Ofis Güzelliği", "Dramatic Powdery UV Foundation; Japon ofis kadını güzelliği; hafif + kalıcı"),
        ("Ettusais", "ettusais.com", "Japon Genç Cilt", "Pore Care serisi; genç Japon cilt bakımı; gözenek minimizasyon; light makyaj"),
        ("Addiction", "addictionbeauty.com", "Japon Edgy Makyaj", "The Eyeshadow 99 ton; AYAKO Japon MUA; LVMH; cesur Japon güzellik"),
        ("Lunasol", "kanebo.com", "Japon Işık Makyajı", "Skin Modeling Eyes; ışık ve gölge konsepti; Kanebo lüks; zarif Japon makyaj"),
    ],

    "Cilt Bakımı - Bariyer Onarım": [
        ("Krave Beauty", "kravebeauty.com", "Great Barrier Relief", "Liah Yoo YouTube'dan marka; bariyer onarım serumu; K-beauty felsefesi; minimal rutin"),
        ("Byoma", "byoma.com", "Gen Z Bariyer", "Tri-ceramide complex; Gen Z cilt bariyer; $10-15; Target'ta; geri dönüştürülebilir"),
        ("Stratia", "stratiaskin.com", "Liquid Gold Altın Oran", "Ceramide + kolesterol + yağ asidi altın oranı; bariyer onarım uzmanı; indie"),
        ("Dr. Jart+ Ceramidin", "drjart.com", "Seramid Uzmanı", "Ceramidin Cream; 5 seramid; Kore bariyer onarım klasiği; güçlü nemlendirme"),
        ("CeraVe", "cerave.com", "Dermatolojist Seramid", "3 temel seramid; $15 nemlendirici; TikTok dermatolojist favorisi; eczane standardı"),
        ("La Roche-Posay Cicaplast", "laroche-posay.com", "Fransız Onarım Balmı", "Cicaplast Baume B5; çok amaçlı onarım balmı; Fransız eczane kült ürünü; panthenol"),
        ("Avène Cicalfate", "eau-thermale-avene.com", "Termal Su Onarım", "Cicalfate+ onarım kremi; bakır-çinko sülfat; termal su; hassas cilt koruma"),
        ("First Aid Beauty", "firstaidbeauty.com", "SOS Cilt Kurtarma", "Ultra Repair Cream; acil cilt kurtarma; koloidal yulaf ezmesi; hassas cilt"),
        ("Holika Holika Good Cera", "holikaholika.com", "Kore Seramid", "Super Ceramide Cream; Kore erişilebilir seramid; bariyer güçlendirme"),
        ("Etude SoonJung", "etude.com", "Kore pH Dengeli", "SoonJung 5.5 Cleanser; pH dengeli hassas hat; minimal bileşen; Kore dermo"),
        ("Real Barrier", "realbarrier.com", "Kore Bariyer Uzmanı", "Extreme Cream; MLE (Multi Lamellar Emulsion) teknolojisi; cilt bariyeri taklit"),
        ("Atopalm", "atopalm.com", "Kore MLE Teknoloji", "MLE bariyer onarım; atopik dermatit odaklı; bebek + yetişkin; lipid bariyer"),
        ("Zeroid", "zeroid.com", "Kore Dermatolojik Bariyer", "Richenic Cream; MLE lipid bariyer; Kore dermatolojik; Neopharm"),
        ("Laneige Cica", "laneige.com", "K-Beauty Cica Uyku", "Cica Sleeping Mask; gece bariyer onarım; K-beauty uyku maskesi konsepti"),
        ("Purito Dermide", "purito.com", "Kore Cica Seramid", "Dermide Cica Barrier Sleeping Pack; seramid + panthenol; gece bariyer bakımı"),
    ],

    "Cilt Bakımı - Güneş Koruma (SPF)": [
        ("Supergoop", "supergoop.com", "Görünmez SPF Öncüsü", "Unseen Sunscreen; makyaj bazı gibi; SPF'i eğlenceli yaptı; güneş koruma devrimi"),
        ("Ultra Violette", "ultraviolette.com.au", "Avustralya SPF Uzmanı", "Queen Screen SPF 50+; hafif formül; Avustralya güneş kültürü; renkli seçenekler"),
        ("Vacation", "vacation.inc", "Retro SPF", "80s/90s retro tatil estetiği; 'tatil kokusu' SPF; eğlenceli marka; sıkıcı kategoride"),
        ("Kinfield", "kinfield.com", "Outdoor SPF", "Daily Dew SPF 35; outdoor lifestyle SPF; hafif; minimal; doğada güzellik"),
        ("Bask Suncare", "basksuncare.com", "Ödüllü Hafif SPF", "SPF 50 Non-Aerosol Spray; 2 yaşında marka; ödül kazanan hafif formül; $20"),
        ("Sun Bum", "sunbum.com", "Sörf Kültürü SPF", "Original SPF 50; sörf + plaj kültürü; sarı maymun maskot; eğlenceli; Henkel satın aldı"),
        ("Coola", "coola.com", "Organik SPF", "Classic Face Organic SPF 30; %70+ organik; sürdürülebilir; premium organik güneş koruma"),
        ("Black Girl Sunscreen", "blackgirlsunscreen.com", "Melanin Cilt SPF", "Beyaz iz bırakmayan SPF; koyu ciltler için; Shontay Lundy kurdu; kapsayıcı SPF"),
        ("Habit", "habitfre.com", "SPF Sis", "No 41 SPF 40; ince sis sprey; makyaj üstü yeniden uygulama; pratik SPF"),
        ("Isntree Hyaluronic", "isntree.com", "Kore Nem SPF", "HA Watery Sun Gel SPF 50+; hyaluronik asit + SPF; Kore hafif güneş koruma"),
        ("Beauty of Joseon Relief Sun", "beautyofjoseon.com", "Kore Pirinç SPF", "Relief Sun; pirinç + probiyotik; Kore SPF viral TikTok; uygun fiyat"),
        ("Round Lab Birch", "roundlab.com", "Kore Huş Ağacı SPF", "Birch Juice Moisturizing Sun Cream; Kore nemlendirici SPF; hafif"),
        ("Canmake Mermaid", "canmake.com", "Japon Deniz Kızı SPF", "Mermaid Skin Gel UV SPF 50+; Japon şeffaf jel; $10; viral"),
        ("Anessa", "anessa.shiseido.co.jp", "Japon Plaj SPF", "Perfect UV Sunscreen Milk; Shiseido; suya + tere dayanıklı; plaj #1"),
        ("Allie", "kanebo.com", "Japon Süt SPF", "Gel UV EX SPF 50+; süper hafif; Kanebo; günlük kullanım; Japon formülasyon"),
        ("Biore UV Aqua Rich", "biore.com", "Japon Su Bazlı SPF", "Watery Essence; dünyanın en hafif hisseden SPF'lerinden; Japon UV teknolojisi"),
        ("Skin Aqua", "rohto.com", "Japon Süper Nem SPF", "Tone Up UV Essence; renk düzeltici SPF; Japon; Rohto; mor tonlu"),
        ("Thank You Farmer", "thankyoufarmer.us", "Kore Çiftçi SPF", "Sun Project Water Sun Cream; doğal bileşen; Kore güneş koruma; nemlendirici"),
    ],

    "Makyaj - Kaş Ürünleri": [
        ("Anastasia Beverly Hills", "anastasiabeverlyhills.com", "Kaş Kategorisi Yaratıcısı", "Kaş kategorisini icat etti; Brow Wiz, Dipbrow; 'Golden Ratio' kaş metodu; $500M+"),
        ("Benefit Brow", "benefitcosmetics.com", "Kaş Bar Öncüsü", "Precisely My Brow Pencil; mağaza içi kaş barları; kaş şekillendirme öncüsü"),
        ("Boy Brow by Glossier", "glossier.com", "Kaş Jeli İkonik", "Boy Brow kaş jeli; doğal kaş trendi başlatıcısı; 'your brows but better'"),
        ("Patrick Ta Brow", "patrickta.com", "MUA Kaş Wax", "Major Brow Lamination Gel; kaş laminasyon trendi; MUA yaklaşımı; şeffaf wax"),
        ("NYX Micro Brow", "nyxcosmetics.com", "Eczane Kaş Kalemi", "Micro Brow Pencil; ABH Brow Wiz dupesi; $10; eczane erişilebilir kaş"),
        ("Essence Brow", "essence.eu", "Ultra Bütçe Kaş", "Make Me Brow Gel; $3 kaş jeli; Boy Brow alternatifi; Avrupa ultra uygun fiyat"),
        ("Soap Brow by West Barn", "westbarnco.com", "Sabun Kaş Trendi", "Orijinal sabun kaş ürünü; 'soap brow' trendini başlattı; lamination görünümü; İngiliz"),
        ("Got2b Glued", "got2b.com", "Kaş Sabitleme Jeli", "Blasted Freeze Spray kaş sabitleme; drag queen favorisi mainstream oldu; güçlü tutma"),
        ("Kosas Air Brow", "kosas.com", "Temiz Kaş Jeli", "Air Brow tinted gel; temiz formül; hafif; doğal kaş; cilt bakımı bileşenli"),
        ("Surratt", "surratt.com", "Japon Hassasiyet Kaş", "Expressioniste Brow Pencil; ultra ince uç; Japon hassasiyeti; lüks makyaj"),
        ("Hourglass Arch Brow", "hourglasscosmetics.com", "Mikro Bıçak Kaş", "Arch Brow Micro Sculpting Pencil; ultra ince; doğal çizgiler; lüks"),
        ("Rare Beauty Brow", "rarebeauty.com", "Hassas Kaş Kalemi", "Brow Harmony Pencil + Gel; çift uçlu; Selena Gomez; erişilebilir + kaliteli"),
    ],

    "Makyaj - Aydınlatıcı & Kontür": [
        ("Fenty Beauty Killawatt", "fentybeauty.com", "Kapsayıcı Aydınlatıcı", "Killawatt Freestyle Highlighter; Trophy Wife altın ikonik; tüm cilt tonları için"),
        ("Rare Beauty Positive Light", "rarebeauty.com", "Sıvı Aydınlatıcı", "Positive Light Liquid Luminizer; doğal ışıltı; su bazlı; hafif"),
        ("Charlotte Tilbury Flawless", "charlottetilbury.com", "Hollywood Filter", "Hollywood Flawless Filter; ışık difüzyon; 'red carpet glow'; viral TikTok"),
        ("Patrick Ta Double-Take", "patrickta.com", "Krem + Toz Kontür", "She's That Girl kontür paleti; krem + pudra duo; MUA kontür teknikleri"),
        ("KVD Good Apple", "kvdveganbeauty.com", "Tam Kapatıcı Baz", "Good Apple Skin-Perfecting Foundation Balm; tam kapatıcı; vegan"),
        ("Saie Dew Blush", "saiehello.com", "Işıltılı Allık", "Dew Blush; aydınlatıcı + allık birleşimi; dewy bitişli; temiz formül"),
        ("Tower 28 Superdew", "tower28beauty.com", "Aydınlatıcı Serum", "Superdew Shimmer-Free Highlight Balm; parıltısız doğal ışıltı; hassas cilt güvenli"),
        ("Danessa Myricks Colorfix", "danessamyricksbeauty.com", "Çok Amaçlı Pigment", "Colorfix pigment; göz, dudak, yanak hepsi; süper pigmentli; MUA yaklaşımı"),
        ("Milk Makeup Lip + Cheek", "milkmakeup.com", "Stick Aydınlatıcı", "Holographic Stick; çok amaçlı stick; vegan; kolay uygulama; trendy"),
        ("Becca (arşiv)", "bfrccacosmetics.com", "Aydınlatıcı Efsanesi", "Shimmering Skin Perfector; aydınlatıcı kategorisini tanımladı; Estée Lauder satın aldı"),
        ("Nudestix Sculpt", "nudestix.com", "Kalem Kontür", "Sculpting Pencil; kalem formatında kontür; Kanada; minimalist; seyahat dostu"),
        ("Too Faced Chocolate", "toofaced.com", "Çikolata Bronzer", "Chocolate Soleil Bronzer; gerçek çikolata kokulu; 15+ yıl bestseller; eğlenceli"),
        ("Physician's Formula Butter", "physiciansformula.com", "Hindistan Cevizi Bronzer", "Murumuru Butter Bronzer; hindistan cevizi kokulu; $15 eczane ikonik; doğal parıltı"),
    ],

    "Doğal & Organik Kozmetik": [
        ("Ere Perez", "erfrperfrz.com", "Avustralya Organik Makyaj", "Avustralya doğal makyaj; havuç bazlı fondöten; badem maskara; bitki pigmentler"),
        ("Elate Cosmetics", "elatfre.com", "Kanada Sıfır Atık Makyaj", "Bambu kompakt; refill sistemi; sıfır atık makyaj; B Corp; Kanada sürdürülebilir"),
        ("Axiology", "axiology.com", "Plastisiz Balmie", "Balmies çok amaçlı; sıfır plastik ambalaj; 3 bileşen; krayon format; minimal atık"),
        ("River Organics", "rivfrorganics.com", "Vegan Mineral Makyaj", "Vegan mineral makyaj; sıfır atık; küçük parti; el yapımı; ABD indie"),
        ("Fat and the Moon", "fatandthemoon.com", "Herbalist Güzellik", "Bitki büyücü formüller; el yapımı; herbal tıp + cilt bakımı; ritualistik"),
        ("Alima Pure", "alimapure.com", "Mineral Makyaj", "Satin Finishing Powder; saf mineral makyaj; refill; Portland; temiz basit"),
        ("RMS Beauty", "rmsbeauty.com", "Ham Organik Makyaj", "Living Luminizer kült aydınlatıcı; Rose-Marie Swift 60 yaşında kurdu; hindistan cevizi bazlı"),
        ("Vapour Beauty", "vapourbeauty.com", "Organik Performans", "Soft Focus Foundation; organik sertifikalı; New Mexico; doğal + yüksek performans"),
        ("W3LL People", "w3llpeople.com", "Bio Extreme Makyaj", "Bio Extreme Lipstick; doğal + mineral; Austin TX; Target'ta temiz güzellik"),
        ("Ilia Multi-Stick", "iliabeauty.com", "Organik Çok Amaçlı", "Multi-Stick; dudak + yanak + göz; organik bazlı; temiz lüks; Sephora"),
        ("Kjaer Weis", "kjaerweis.com", "Lüks Refill Metal", "Metal kompakt refill sistemi; Danimarka organik sertifikalı; sürdürülebilir + lüks"),
        ("Antonym Cosmetics", "antonym.com", "Sertifikalı Organik Makyaj", "Ecocert sertifikalı; organik allık + bronzer; Fransa + ABD; lüks organik"),
        ("100% Pure", "100percentpure.com", "Meyve Pigmentli Makyaj", "Fruit Pigmented Foundation; meyve boyaları sentetik yerine; %100 doğal; vegan"),
        ("Zuzu Luxe", "zufruluxfre.com", "Gabriel Cosmetics Lüks", "Lüks doğal makyaj; 20+ yıl; gluten-free; vegan; dermatolog test"),
        ("Burt's Bees Makeup", "burtsbees.com", "Arı Doğal Makyaj", "All Aglow Lip & Cheek Stick; doğal makyaj; arı balmumu bazlı; erişilebilir"),
    ],

    "Vegan & Cruelty-Free Kozmetik": [
        ("e.l.f. Cosmetics", "elfcosmetics.com", "Ultra Erişilebilir Vegan", "$5 ortalama fiyat; TikTok-first pazarlama; 'Eyes Lips Face' 7B+ görüntülenme; en hızlı büyüyen"),
        ("Milani", "milani.com", "İtalyan İlham Eczane", "Baked Blush gül deseni; Color Statement Lipstick; İtalyan ilham; eczane lüks hissi"),
        ("Wet n Wild", "wetnwild.com", "Ultra Bütçe Makyaj", "MegaLast Lipstick $2; Photo Focus Foundation $6; PETA sertifikalı; Z kuşağı bütçe"),
        ("Flower Beauty", "flowerbeauty.com", "Drew Barrymore Temiz", "Light Illusion Foundation; Drew Barrymore; uygun fiyat + temiz; Walmart"),
        ("ColourPop", "colourpop.com", "Haftalık Yeni Ürün", "Her hafta yeni ürün; $5-15; Disney, Barbie collab; LA fabrikasına sahip; süper hızlı trend"),
        ("Catrice", "catrice.eu", "Alman Bütçe Kalite", "HD Liquid Coverage Foundation; Alman kalite uygun fiyat; cruelty-free; Avrupa favorisi"),
        ("Essence", "essence.eu", "Avrupa Ultra Bütçe", "Lash Princess Mascara $5 kült maskara; Alman; Avrupa'nın en ucuz makyajı; kaliteli"),
        ("Revolution Beauty", "revolutionbeauty.com", "İngiliz Hızlı Trend", "Conceal & Define Foundation; İngiliz; lüks dupe'ler; TikTok viral; çok hızlı trend"),
        ("Sheglam", "sheglam.com", "Shein Güzellik", "Shein'in güzellik markası; ultra uygun fiyat $3-10; viral TikTok; Gen Z; global"),
        ("BH Cosmetics", "bhcosmetics.com", "Palet Uzmanı Vegan", "Take Me Back to Brazil; cesur renkler; cruelty-free; vegan; iflastan dönüş"),
        ("NYX Professional", "nyxcosmetics.com", "Pro Erişilebilir Vegan", "Epic Ink Liner; Butter Gloss; profesyonel kalite eczane fiyatı; L'Oréal; vegan"),
        ("Pacifica", "pacificabeauty.com", "Vegan Doğal Güzellik", "%100 vegan + cruelty-free; parfüm + cilt + makyaj; Target; erişilebilir doğal"),
        ("KVD Vegan Beauty", "kvdveganbeauty.com", "Cesur Vegan Makyaj", "Tattoo Liner ikonik; %100 vegan + cruelty-free; cesur sanatsal makyaj"),
        ("Hourglass Cosmetics", "hourglasscosmetics.com", "Lüks Vegan Yolculuk", "2025'e kadar %100 vegan geçiş; Ambient Lighting Powder; lüks vegan öncüsü"),
        ("Lime Crime", "limecrime.com", "Unicorn Vegan Makyaj", "Venus paleti; fantastik renkler; vegan; cesur; 'unicorn ve deniz kızı' estetiği"),
    ],

    "Cilt Bakımı - Göz Çevresi": [
        ("Dieux Skin Eye Mask", "dieuxskin.com", "Yeniden Kullanılabilir Göz", "Forever Eye Mask silikon; tek kullanımlık yerine; sürdürülebilir; serum tutucu"),
        ("Patchology FlashPatch", "patchology.com", "5 Dakika Göz Jeli", "FlashPatch göz jeli; 5 dakika çözüm; seyahat dostu; lüks hızlı bakım"),
        ("Peter Thomas Roth Gold", "peterthomasroth.com", "Altın Göz Patch", "24K Gold Eye Patches; lüks altın hidrojel; anlık aydınlanma; VIP favorisi"),
        ("Skyn Iceland", "skyniceland.com", "İzlanda Soğutma Göz", "Hydro Cool Firming Eye Gels; soğutma etkisi; stres altında cilt; İzlanda mineral"),
        ("111Skin", "111skin.com", "Uzay Teknoloji Göz", "Rose Gold Brightening Eye Mask; Y Theorem formülü; uzay araştırma ilhamı; ultra lüks"),
        ("Charlotte Tilbury Eye", "charlottetilbury.com", "Magic Eye Rescue", "Magic Eye Rescue; retinol + peptid; lüks göz çevresi bakımı; anti-aging"),
        ("Ole Henriksen", "olehenriksen.com", "Banana Bright Göz", "Banana Bright Eye Crème; C vitamini + kolajen; aydınlatıcı göz kremi; parlak sonuç"),
        ("IT Cosmetics Eye", "itcosmetics.com", "Bye Bye Under Eye", "Bye Bye Under Eye Concealer; tam kapatıcı göz altı; kolajen + peptid; anti-aging"),
        ("Estée Lauder ANR Eye", "esteelauder.com", "Advanced Night Repair Göz", "Advanced Night Repair Eye; 30+ yıl ikonik; Chronolux teknoloji; gece onarım"),
        ("La Mer The Eye", "lamer.com", "Ultra Lüks Göz Kremi", "The Eye Concentrate; Miracle Broth; $250; ultra lüks göz çevresi; yoğun bakım"),
        ("Shiseido Benefiance", "shiseido.com", "Japon Göz Bakımı", "Benefiance Wrinkle Smoothing Eye Cream; ReNeura Technology; Japon anti-aging göz"),
        ("Origins GinZing", "origins.com", "Enerji Göz Kremi", "GinZing Refreshing Eye Cream; kafein + ginseng; enerji veren aydınlatma; uyanıklık"),
        ("Kiehl's Avocado", "kiehls.com", "Avokado Göz Kremi", "Creamy Eye Treatment with Avocado; avokado yağı; nemlendirici; NYC eczane klasiği"),
    ],

    "Cilt Bakımı - Maske & Peeling": [
        ("Aztec Secret", "aztecfrsecret.com", "Kil Maske Efsanesi", "Indian Healing Clay; Amazon #1 yüz maskesi; bentonit kili; $9; 50 yıl+ tarih"),
        ("GlamGlow", "glamglow.com", "Hollywood Maske", "SUPERMUD mask; Hollywood yıldız maskesi; çamur tedavisi; lüks maske öncüsü"),
        ("Boscia", "bosfrcia.com", "Japon Kil Temizleme", "Luminizing Black Charcoal Mask; Japon botanik; soyulabilir maske; detoks"),
        ("Summer Fridays Jet Lag", "summerfridays.com", "Viral Nem Maskesi", "Jet Lag Mask; Instagram'ın en çok fotoğraflanan maskesi; nem bombası"),
        ("Youth to the People Superberry", "youthtothepeople.com", "Süperfood Gece Maskesi", "Superberry Hydrate + Glow Dream Mask; maqui + goji; antioksidan gece"),
        ("Herbivore Blue Tansy", "herbivorebotanicals.com", "Mavi Maske İkonik", "Blue Tansy Resurfacing Clarity Mask; mavi renk Instagram viral; AHA + BHA"),
        ("Farmacy Honeymoon Glow", "farmacybeauty.com", "Bal AHA Serum-Maske", "Honeymoon Glow AHA Night Serum; bal + AHA; gece peeling; echinacea"),
        ("Dr. Dennis Gross Peel", "drdennisgross.com", "Alpha Beta Günlük Peel", "Alpha Beta Daily Peel pad; dermatolojist; evde klinik peeling; 20+ yıl"),
        ("Tatcha Dewy Mask", "tatcha.com", "Japon Nem Maskesi", "Dewy Skin Cream; gece nemlendirici maske; Japon mor pirinç; lüks"),
        ("Origins Clear Improvement", "origins.com", "Kömür Maske", "Clear Improvement Active Charcoal Mask; aktif kömür; gözenek temizleme"),
        ("The Ordinary AHA BHA Peel", "theordinary.com", "10 Dakika Peeling", "AHA 30% + BHA 2% Peeling Solution; 10 dakika güçlü peeling; $7; viral kırmızı şişe"),
        ("Paula's Choice BHA", "paulaschoice.com", "BHA Kült Exfoliant", "Skin Perfecting 2% BHA Liquid Exfoliant; salisilik asit kült peeling; 30+ yıl bilim"),
        ("Glow Recipe Watermelon", "glowrecipe.com", "Karpuz Uyku Maskesi", "Watermelon Glow Sleeping Mask; AHA + hyaluronik; Kore ilham; pembe jel; viral"),
        ("Sand & Sky Pink Clay", "sandandsky.com", "Avustralya Pembe Kil", "Australian Pink Clay Mask; Instagram viral; pembe renk fotojenikç Avustralya"),
        ("I Dew Care", "idewcare.com", "Eğlenceli K-Beauty Maske", "Cake My Day wash-off maske; rengarenk; Kore eğlenceli maske konsepti; uygun fiyat"),
    ],

    "Parfüm & Koku - Kadın Parfüm": [
        ("Phlur", "phlur.com", "TikTok Viral Koku", "Missing Person viral; 'sevdiğin kişinin kokusu'; Chrissy Teigen satın aldı; temiz"),
        ("Skylar", "skylar.com", "Hipoalerjenik Parfüm", "Kızının alerjisi ilham; toksik madde yok; koku profili quiz; kişiselleştirilmiş"),
        ("Ellis Brooklyn", "ellisbrooklyn.com", "Bilim + Sanat Koku", "Bee EDP; bilim kurgu yazarından parfümcüye; temiz formül; lüks ambalaj"),
        ("Henry Rose", "henryrose.com", "Michelle Pfeiffer Temiz", "EWG doğrulanmış; Cradle to Cradle sertifikalı; Hollywood + temiz formülasyon"),
        ("Floral Street", "floralstreet.com", "Sürdürülebilir İngiliz", "Geri dönüşümlü ambalaj; vegan; İngiliz parfümcü; Neon Rose bestseller"),
        ("Boy Smells Fragrance", "boysmells.com", "Cinsiyetsiz Lüks Koku", "'Genderful' parfüm; LGBTQ+ kuruculu; mumdan parfüme; Kacey Musgraves collab"),
        ("Commodity Parfum", "commodity.com", "3 Seviye Koku", "Her koku 3 yoğunlukta; Personal, Expressive, Bold; benzersiz konsept"),
        ("Clean Reserve", "cleanbeauty.com", "Sürdürülebilir Koku", "Refill şişeler; sorumlu ambalaj; Skin, Sueded Oud; temiz parfüm öncüsü"),
        ("Kayali", "kayali.com", "Huda Kattan Koku", "Huda Beauty'nin koku markası; katmanlama koleksiyonu; Orta Doğu ilham; vanilya"),
        ("Tocca", "tocca.com", "İtalyan Romantik Koku", "Florence EDP; İtalyan romantizmi; lüks mum + parfüm; el kremi ikonik"),
        ("Nest Parfum", "nestnewyork.com", "Ev + Kişisel Koku", "Turkish Rose; ev kokusundan kişisel parfüme; $300M+ gelir; lüks koku ev"),
        ("Sol de Janeiro Cheirosa", "soldejaneiro.com", "Brezilya Vücut Kokusu", "Cheirosa 62 parfümü Bum Bum Cream kokusundan doğdu; Brezilya tropikal"),
        ("Ouai Fragrance", "theouai.com", "Saç → Parfüm", "North Bondi, Melrose Place parfüm; saç ürünlerinden kişisel kokuya genişleme"),
        ("Jo Malone", "jomalone.com", "Katmanlama Lüks", "Katmanlama konsepti; Wood Sage & Sea Salt; hediye kültürü; İngiliz lüks"),
        ("Aerin", "afrerin.com", "Estée Lauder Torunu", "Aerin Lauder; Mediterranean Honeysuckle; lifestyle lüks koku; zarif minimal"),
    ],

    "Saç Bakımı - Şampuan & Saç Kremi": [
        ("Odele Beauty", "odfrle.com", "Target Salon Kalite", "Salon kalitesi Target'ta $12; cinsiyetsiz; sülfatsız; erişilebilir temiz saç"),
        ("Briogeo", "briogeohair.com", "Temiz Saç Bakımı", "Don't Despair, Repair! saç maskesi; temiz bileşen; 6 koleksiyon farklı ihtiyaçlar"),
        ("Amika", "loveamika.com", "Profesyonel Renkli", "Perk Up Dry Shampoo; renkli ambalaj; Brooklyn salon; profesyonel kalite; eğlenceli"),
        ("Ouai", "theouai.com", "Jen Atkin Saç", "Wave Spray bestseller; ünlü saç stilisti Jen Atkin; P&G satın aldı; influencer marka"),
        ("Living Proof", "livingproof.com", "MIT Bilim Saç", "PhD teknolojisi; MIT bilimi; Jennifer Aniston yatırımcı; Unilever satın aldı"),
        ("Oribe", "oribe.com", "Salon Lüks", "Dry Texturizing Spray kült; altın ambalaj; sadece kokusu bile bağımlılık yapar; Lauder"),
        ("Christophe Robin", "christopherobin.com", "Paris Salon Lüks", "Cleansing Purifying Scrub; deniz tuzu saç peelingi; Paris renkli saç uzmanı"),
        ("Philip Kingsley", "philipkingsley.com", "Triko-Bilim", "Elasticizer ikonik; Audrey Hepburn saç bakımcısı; İngiliz triko-bilim otoritesi"),
        ("Moroccanoil", "moroccanoil.com", "Argan Yağı Öncüsü", "Treatment Light argan yağı; argan yağı saç bakımı kategorisini başlattı; $500M+"),
        ("Davines", "davines.com", "İtalyan Sürdürülebilir Saç", "OI Oil çok amaçlı; B Corp; İtalyan; sürdürülebilir salon hareketi; premium"),
        ("Kevin Murphy", "kevinmurphy.com.au", "Avustralya Salon", "Angel Wash; moda dergileri ilham; Avustralya; salon profesyonel; sülfatsız"),
        ("Redken", "redken.com", "NYC Salon Bilimi", "Acidic Bonding Concentrate; NYC salon heritage; L'Oréal Professional; bilim + stil"),
        ("Pureology", "pureology.com", "Renk Koruma Uzmanı", "Hydrate Shampoo; %100 vegan; sülfatsız renk bakımı; salon profesyonel"),
        ("Aveda", "aveda.com", "Bitki Bazlı Salon", "Damage Remedy; bitki bazlı salon öncüsü; Lauder; Ayurveda ilham; çevre bilinci"),
        ("Paul Mitchell", "paulmitchell.com", "Salon Efsanesi", "Tea Tree Special Shampoo; hayvan testi karşıtı öncü; 1980'den beri; salon standardı"),
    ],

    "Vücut Bakımı - Deodorant": [
        ("Lume", "lumedeodorant.com", "Tüm Vücut Deodorant", "Jinekolog geliştirdi; koltuk altı + her yer; 'tüm vücut deodorant' kategorisi yaratıcısı"),
        ("Each & Every", "eachandevery.com", "EWG 1 Puan Deodorant", "EWG en yüksek puan; karbonat yok; Dead Sea tuzu; hassas cilt; refill"),
        ("Native", "nativecos.com", "Doğal Geçiş Öncüsü", "İlk kalıcı doğal deodorant; hindistan cevizi + shea; P&G $100M satın aldı"),
        ("Schmidt's", "schmidts.com", "Portland Artisan Deodorant", "Rose + Vanilla ikonik; el yapımıdan global markaya; Unilever satın aldı"),
        ("Myro", "myro.com", "Refill Deodorant", "Refill deodorant kılıfı; koku değiştirilebilir; sürdürülebilir; az plastik"),
        ("Type:A", "typeadeodorant.com", "Adaptif Deodorant", "Vücut kimyasına adapte olan formül; ter seviyesine göre ayarlanan; bilimsel"),
        ("Curie", "cufrfre.com", "Çok Amaçlı Deodorant", "Full Body Deodorant sprey; koltuk altı + vücut; beyaz iz yok; hafif"),
        ("Corpus Naturals", "corpusnaturals.com", "Lüks Doğal Deodorant", "Lüks ambalaj; niş koku profilleri; doğal bileşen; $24 deodorant; premium"),
        ("Hume", "hfrme.com", "Prebiyotik Deodorant", "Prebiyotik bazlı; mikrobiyom dengesi; bilimsel yaklaşım deodorant; yeni kategori"),
        ("Super Deodorant", "sfrprdeodorant.com", "Güçlü Doğal", "48 saat koruma doğal formülle; magnezyum + probiyotik; güçlü + temiz"),
        ("Wild", "wearewild.com", "İngiliz Refill Deodorant", "Alüminyum refill kılıf; İngiliz; refill poşet sistemi; çevre dostu; şık"),
        ("By Humankind", "byhumankind.com", "Az Plastik Deodorant", "Refill deodorant + daha fazlası; %90 daha az plastik; tek seferde çözdü"),
        ("Arm & Hammer Essentials", "armandhammer.com", "Karbonat Deodorant", "Baking soda doğal deodorant; güvenilir marka + doğal formül; erişilebilir"),
        ("Crystal", "thecrystal.com", "Mineral Tuz Deodorant", "Mineral tuz deodorant kristali; 40+ yıl; alüminüm klorohidrat yok; OG doğal"),
        ("Tom's of Maine", "tomsofmaine.com", "Maine Doğal", "1970'lerden beri doğal kişisel bakım; deodorant + diş macunu; Colgate; miras"),
    ],

    "Saç Bakımı - Kıvırcık & Tekstürlü Saç": [
        ("Curlsmith", "curlsmith.com", "Bond Onarım Kıvırcık", "Bond Curl Rehab Salve; kıvırcık saç için bağ onarımı; mutfak ilham bileşen isimleri"),
        ("Bread Beauty Supply", "breadbeautysupply.com", "Basit Tekstürlü Saç", "Sadece 5 ürün; tekstürlü saç yıkama günü kolaylaştırıldı; Sephora özel; minimal"),
        ("PATTERN", "patternbeauty.com", "Tracee Ellis Ross Kıvırcık", "Kıvırcık + coily saç bakımı; Tracee Ellis Ross; kıvırcık saç kültürü; Ulta"),
        ("Ceremonia", "ceremonia.com", "Latinx Saç Ritüeli", "Babba Rivera; Latinx saç ritüellerini kutlama; guava + aloe; kültürel güzellik"),
        ("Sienna Naturals", "siennanaturals.com", "Doğal Saç Bakımı", "Hannah Diop; doğal saç bakımı; şeker kamışı bazlı; tekstürlü saç uzmanı"),
        ("Mielle Organics", "mielleorganics.com", "TikTok Viral Doğal Saç", "Rosemary Mint Oil 1B+ TikTok; siyahi kadın kuruculu; P&G satın aldı"),
        ("Camille Rose", "camillerose.com", "Bal + Doğal Saç", "Curl Love Moisture Milk; bal bazlı; doğal saç topluluğu; küçük parti"),
        ("TPH by Taraji", "tph.com", "Taraji P. Henson Saç", "Taraji P. Henson; tekstürlü saç bakımı; Target; erişilebilir temiz saç"),
        ("Melanin Haircare", "melaninhaircare.com", "YouTube Doğal Saç", "Whitney White; Multi-Use Softening Leave-In; doğal saç topluluğu; influencer marka"),
        ("Aunt Jackie's", "auntjackiescurls.com", "Erişilebilir Kıvırcık", "Curl La La Defining Curl Custard; erişilebilir kıvırcık bakım; $8-12; Walmart/Target"),
        ("Cantu", "cantubeauty.com", "Shea Butter Kıvırcık", "Shea Butter Leave-In Conditioner; erişilebilir; tekstürlü saç klasiği; #1 doğal saç"),
        ("Shea Moisture", "sheamoisture.com", "Fair Trade Shea Saç", "Jamaican Black Castor Oil; fair trade shea; Sundial Brands; Unilever; kültürel"),
        ("As I Am", "asifrm.com", "Doğal Saç Uzmanı", "CoWash; ortak yıkama (co-wash) popülerleştirdi; doğal saç geçiş uzmanı"),
        ("Kinky-Curly", "kinky-curly.com", "Kıvırcık Jel Efsanesi", "Curling Custard jel; kıvırcık saç tanımlama; OG doğal saç ürünü"),
        ("Miss Jessie's", "missjessies.com", "NYC Kıvırcık Öncüsü", "Pillow Soft Curls; NYC kıvırcık salon; kıvırcık saç kategorisi yaratıcıları"),
    ],
}
