"""
Supplementary cosmetics brands to push toward 5000+ total.
Each brand: (name, website, subniche_tr, insight_tr)
"""

COSMETICS_EXTRA = {
    "Cilt Bakımı - Nemlendirici & Serum": [
        ("The INKEY List", "theinkeylist.com", "Eğitimsel Cilt Bakımı", "Her ürün bileşeni öğretiyor; %1 hyaluronik asit; erişilebilir aktif cilt bakımı; $10 altı"),
        ("COSRX", "cosrx.com", "Kore Snail Mucin", "Advanced Snail 96 Mucin Power Essence 60K+ 5 yıldız; K-beauty başlangıç; erişilebilir Kore cilt"),
        ("Purito", "purito.com", "Kore Centella", "Centella Green Level Buffet Serum; hassas cilt uzmanı; vegan Kore cilt bakımı"),
        ("mixsoon", "mixsoon.com", "Tek Bileşen Serum", "Bean Essence TikTok viral; tek bileşen felsefesi; Kore minimal; fermente soya"),
        ("numbuzin", "numbuzin.com", "No.5 Vitamin C", "Numaralı ürün sistemi; No.5 Vitamin C serum viral; Kore yeni nesil; erişilebilir"),
        ("Haruharu WONDER", "haruharu.co.kr", "Pirinç Serum", "Black Rice Hyaluronic Toner; Kore pirinç fermantasyonu; nem uzmanı; TikTok viral"),
        ("Isntree", "isntree.com", "Kore Hyaluronik", "Hyaluronic Acid Toner 8 tip HA; Kore dermoeczane; hassas cilt; erişilebilir fiyat"),
        ("Needly", "needly.co.kr", "Kore Bariyer", "Daily Toner Pad; hassas cilt bariyeri; Kore yeni marka; TikTok keşfi"),
        ("Torriden", "torriden.com", "Düşük Moleküllü HA", "DIVE-IN 5 tip hyaluronik asit; Kore nemlendirme uzmanı; düşük molekül ağırlığı"),
        ("Illiyoon", "illiyoon.com", "Kore Seramid", "Ceramide Ato Concentrate Cream; AmorePacific; bebek + yetişkin; seramid uzmanı"),
        ("ma:nyo", "manyo-factory.com", "Bifida Ferment", "Bifida Biome Complex Serum; fermente probiyotik cilt; Kore mikrobiyom"),
        ("Heimish", "heimish.co.kr", "Kore Temizleme Balm", "All Clean Balm ünlü; çok temizleme; Kore çift temizleme öncüsü"),
        ("Benton", "bentoncosmetic.com", "Kore Doğal", "Snail Bee High Content Essence; doğal + etkili; Kore yavaş güzellik"),
        ("Round Lab", "roundlab.com", "Kore Dokdo", "Dokdo Toner; Kore adası mineral suyu; hassas cilt; pH dengeli temizleme"),
        ("Some By Mi", "somebymi.com", "30 Günde Mucize", "AHA BHA PHA 30 Days Miracle Toner; akne tedavisi; Kore viral; 30 gün challenge"),
        ("Klairs", "klfrairs.com", "Kore Hassas", "Supple Preparation Toner; hassas cilt Kore klasiği; minimal; cruelty-free"),
        ("Banila Co", "banilaco.com", "Temizleme Balm Kraliçesi", "Clean It Zero #1 Kore temizleme balm; yağ temizleme trendi başlatıcısı; erişilebilir"),
        ("SKIN1004", "skin1004.com", "Madagaskar Centella", "Madagascar Centella Ampoule; hassas cilt uzmanı; temiz bileşen; erişilebilir klinik"),
        ("Goodal", "goodal.co.kr", "Yeşil Mandarin", "Green Tangerine Vita C Serum; Kore vitamin C; erişilebilir aydınlatma"),
        ("Laneige", "laneige.com", "Su Uyku Maskesi", "Water Sleeping Mask gece nemlendiricisi; Lip Sleeping Mask dünyada #1; K-beauty gateway"),
        ("Aestura", "aestura.com", "Kore Dermo", "A-Cica serisi; Kore dermatolojik; eczane markası; hassas + duyarlı cilt"),
        ("Dr.G", "drg.co.kr", "Kore Dermatolojist", "Red Blemish Clear Soothing Cream; dermatolojist kurdu; Kore medikal cilt bakımı"),
        ("CNP Laboratory", "cnp.co.kr", "Kore Lab", "Propolis Energy Ampule; arı propolisi; Kore klinik cilt bakımı; LG H&H"),
        ("VT Cosmetics", "vtcosmetics.com", "BTS Collab", "Cica serisi; BTS colaborasyonu ile viral; cica uzmanı; Kore"),
        ("Axis-Y", "axis-y.com", "Kore Yeşil Çay", "Dark Spot Correcting Glow Serum; birden fazla aktif; Kore leke tedavisi"),
        ("By Wishtrend", "bfrywfrshtrend.com", "Kore Propolis", "Propolis Energy Calming Ampoule; KLAIRS sister brand; aktif bileşen odaklı"),
        ("I'm From", "imfrom.kr", "Kore Doğal Kaynak", "Mugwort Essence; doğal kaynaklı (pirinç, bal, armut); Kore tek bileşen"),
        ("Hada Labo", "hfrda-labo.com", "Japon Hyaluronik", "Gokujyun Premium Lotion; 7 tip HA; Japon eczane #1; ultra nemlendirme"),
        ("Melano CC", "rohto.com", "Japon Vitamin C", "Vitamin C Essence; Japon leke tedavisi #1; erişilebilir; stabil C vitamini"),
        ("Rohto", "rohto.com", "Japon Göz Damlası", "Skin Aqua UV SPF; göz damlasından cilt bakımına; Japon çok yönlü eczane"),
        ("Biore", "biore.com", "Japon Gözenek", "UV Aqua Rich SPF 50; Japon hafif güneş kremi; gözenek temizleme şeritleri"),
        ("Canmake", "canmake.com", "Japon Bütçe Makyaj", "Cream Cheek allık ikonik; Japon $5-10 kozmetik; kaliteli ucuz"),
        ("Kiku-Masamune", "kikumasamune.com", "Japon Sake Cilt", "High Moist Lotion sake bazlı; 500ml dev boy; Japon fermente cilt"),
        ("Naturie", "imju.com", "Japon Hatomugi", "Skin Conditioner Hatomugi; Japon inci arpa; 500ml ultra uygun; günlük nem"),
    ],

    "Cilt Bakımı - Akne & Leke Tedavisi": [
        ("Starface", "starface.world", "Yıldız Akne Patch", "Yıldız şeklinde akne patchleri; akneyi eğlenceli hale getirdi; Gen Z ikonik; $5"),
        ("Hero Cosmetics", "herocosmetics.com", "Mighty Patch", "Mighty Patch Amazon #1; Church & Dwight $630M satın aldı; hidrokoloid teknoloji"),
        ("Topicals", "mytopicals.com", "Kronik Cilt Sorunları", "Hiperpigmentasyon + egzama; cilt sorunlarını normalleştirme hareketi; renkli ambalaj"),
        ("Peace Out", "peaceoutskincare.com", "Akne Çözüm Patchleri", "Salisilik asit + hidrokoloid patch; acil akne müdahale; hedefli tedavi"),
        ("ZitSticka", "zitsticka.com", "Mikro İğne Patch", "Mikro dart teknolojisi ile deriye nüfuz eden akne patchleri; kyst akne hedefli"),
        ("Mighty Patch", "herocosmetics.com", "Gece Akne Çözümü", "12 saat gece patch; dev boy; ağız çevresi versiyonu; $13"),
        ("Avarelle", "avarelle.com", "Çay Ağacı Patch", "Çay ağacı yağı + calendula akne patch; Kore teknoloji; doğal bileşen"),
        ("Patchology", "patchology.com", "Lüks Patch", "FlashPatch göz altı jeli; 5 dakika çözüm; lüks patch uzmanı; hediye favorisi"),
        ("Rael", "getrael.com", "K-Beauty Akne", "Kore teknoloji akne patch + cilt bakımı; 8 farklı patch tipi; çok yönlü"),
        ("Alba Botanica", "albafrbotanica.com", "Doğal Akne", "Acnedote serisi; salisilik asit + doğal; erişilebilir doğal akne bakımı"),
        ("Mario Badescu", "mariobadescu.com", "NYC Eczane Akne", "Drying Lotion pink spot treatment; 1967 NYC; kült ürün; Martha Stewart favorisi"),
        ("Kate Somerville", "katesomerville.com", "Hollywood Akne Lüks", "EradiKate spot treatment; Hollywood dermatolojist; sulfur bazlı; ünlü müşteriler"),
        ("Murad", "murad.com", "Dermatolojist Akne", "Rapid Relief Spot Treatment; Dr. Howard Murad; klinik akne tedavisi"),
        ("La Roche-Posay Effaclar", "laroche-posay.com", "Fransız Eczane Akne", "Effaclar Duo+ akne tedavisi; Fransız eczane; dermatolojist önerisi #1"),
        ("Differin", "differin.com", "OTC Retinoid Akne", "İlk reçetesiz adapalene jel; eczane akne devrimi; $15; klinik kanıtlı"),
        ("AcneFree", "acnefree.com", "Benzoil Peroksit Kit", "Benzoil peroksit 3 adım sistem; eczane erişilebilir; Proactiv alternatifi"),
        ("Blume", "blfrme.com", "Genç Cilt Akne", "Meltdown akne yağı; genç cilt sorunları; blue tansy + tea tree; Gen Z"),
        ("Renée Rouleau", "reneerouleau.com", "Cilt Tipi Uzmanı", "Anti Bump Treatment; 9 cilt tipi sistemi; kişiselleştirilmiş akne bakımı"),
        ("Dr. Dennis Gross", "dfrrdennisgross.com", "Asit Peel Akne", "Alpha Beta Daily Peel; dermatolojist; evde klinik peeling; akne + aging çift etki"),
        ("Tula", "tula.com", "Probiyotik Akne", "So Poreless Deep Exfoliating Blackhead Serum; probiyotik bazlı akne bakımı"),
    ],

    "Cilt Bakımı - Anti-Aging & Kırışıklık": [
        ("Medik8", "medik8.com", "İngiliz CSA Felsefesi", "C vitamini + SPF + A vitamini felsefesi; Crystal Retinal stabilize retinaldehit; İngiliz klinik"),
        ("Allies of Skin", "alliesofskin.com", "Singapur Lüks Aktif", "Multi peptide + HA serum; Singapur; yoğun aktif konsantrasyonları; lüks performans"),
        ("Dr. Barbara Sturm", "drsturm.com", "Kan Krem", "Molecular Cosmetics; Vampire Facial öncüsü; $300+ ürünler; A-list müşteriler; plazma bilimi"),
        ("Augustinus Bader", "augustinusbader.com", "Kök Hücre Bilimi", "TFC8 teknolojisi; $265 krem; Hailey Bieber favorisi; kök hücre profesörü; lüks aktif"),
        ("SkinCeuticals", "skinceuticals.com", "C E Ferulic Altın Standart", "C E Ferulic serum C vitamini altın standardı; $180/şişe; dermatolojist ofislerinde"),
        ("iS Clinical", "isclinical.com", "Medikal Estetik", "Active Serum kutsal kase; eczacılık sınıfı; estetisyenler tarafından kullanılır"),
        ("Revision Skincare", "revisionskincare.com", "Doktor Dağıtım", "Intellishade SPF #1 doktor dağıtımlı renkli nemlendirici; klinik anti-aging"),
        ("PCA Skin", "pcaskin.com", "Profesyonel Peeling", "Peeling markası; 60K+ estetisyen kullanıyor; HA Boosting Serum; evde profesyonel"),
        ("Environ", "environ.com", "Vitamin A Sistem", "Vitamin A kademeli artış sistemi; Güney Afrika; retinol tolerans programı"),
        ("DefenAge", "defenage.com", "Defensin Teknoloji", "Age-Repair Defensin yeni cilt hücresi üretimi stimüle; patentli teknoloji"),
        ("Obagi", "obagi.com", "Tretinoin Sistem", "Nu-Derm tretinoin bazlı sistem; dermatolojist reçeteli; agresif anti-aging"),
        ("ZO Skin Health", "zoskinhealth.com", "Dr. Obagi Yeni Marka", "Dr. Zein Obagi'nin ikinci markası; Growth Factor serum; medikal dağıtım"),
        ("Jan Marini", "janmarini.com", "Bioglycolic Peeling", "Bioglycolic serisi; glikolik asit uzmanı; klinik anti-aging; profesyonel peeling"),
        ("Neocutis", "neocutis.com", "Bio-Restoratif", "PSP (İşlenmiş Cilt Hücre Proteinleri); yara iyileştirme teknolojisi anti-aging'e uygulandı"),
        ("AlumierMD", "alumiermd.com", "Kanada Medikal", "Eczacılık sınıfı; doktor kanalı; kişiselleştirilebilir rejimler; Kanada"),
        ("SkinBetter Science", "skinbetter.com", "InterFuse Teknoloji", "InterFuse iletim teknolojisi; aktif maddeleri derine taşır; medikal dağıtım"),
        ("EltaMD", "eltamd.com", "Dermatolojist SPF", "UV Clear SPF #1 dermatolojist önerisi güneş kremi; niacinamid + çinko; hassas"),
    ],

    "Makyaj - Fondöten & BB/CC Krem": [
        ("Saie", "saiehello.com", "Dewdrop SPF", "Glowy Super Gel 100M+ TikTok; Slip Tint SPF; dewy her şey; temiz günlük makyaj"),
        ("Merit", "meritbeauty.com", "5 Dakika Fondöten", "The Minimalist Complexion Stick; 5 dakika makyaj felsefesi; minimal ürün portföyü"),
        ("Kosas", "kosas.com", "Cilt Bakımı Fondöten", "Revealer Skin-Improving Foundation SPF 25; cilt bakımı + fondöten; 15+ ödül"),
        ("Jones Road", "jonesroadbeauty.com", "What The Foundation", "Bobbi Brown'ın yeni markası; What The Foundation tinted nemlendirici; 50+ yaş hedef"),
        ("Tower 28", "tower28beauty.com", "Hassas Cilt Fondöten", "SunnyDays SPF 30 tinted SPF; NEA onaylı; hassas cilt güvenli fondöten"),
        ("Ami Colé", "amicole.com", "Melanin Fondöten", "Skin-Enhancing Tint; melanin zengini ciltler için; Senegalli-Amerikan kuruculu"),
        ("MENTED", "mentedcosmetics.com", "WOC Fondöten", "Skin by MENTED; kadınlar-of-color için; Harvard MBA kurucular; nude lipstick öncüsü"),
        ("Iris & Romeo", "irisandromeo.com", "40+ Fondöten", "Best Skin Days SPF 30; 5-in-1 hibrit; 40+ cilt için tasarlandı; ex-bareMinerals CEO"),
        ("Rose Inc", "roseinc.com", "Model Cilt Fondöten", "Tinted Serum Concealer; Rosie HW; model cilt etkisi; temiz lüks"),
        ("About Face", "aboutface.com", "Cesur Fondöten", "The Performer Skin-Focused Foundation; Halsey'nin markası; punk estetik; $15-30"),
        ("Em Cosmetics", "emcosmetics.com", "Michelle Phan BB", "Daydream Cushion; Michelle Phan YouTube güzellik öncüsü; Asya güzellik ilhamı"),
        ("Danessa Myricks", "danessamyricksbeauty.com", "MUA Fondöten", "Vision Cream Cover; makyaj sanatçısı formülleri; çok amaçlı pigmentler"),
        ("Westman Atelier", "westman-atelier.com", "Lüks Temiz Fondöten", "Vital Skincare Complexion Drops; Gucci Westman; lüks temiz makyaj; $68"),
        ("Vapour Beauty", "vapourbeauty.com", "Organik Fondöten", "Soft Focus Foundation; organik sertifikalı; New Mexico doğal güzellik"),
        ("Kjaer Weis", "kjaerweis.com", "Refill Lüks Fondöten", "Invisible Touch Foundation; Danimarka; metal kompakt refill sistemi; sürdürülebilir lüks"),
        ("W3LL People", "w3llpeople.com", "Bio Tint Fondöten", "Bio Tint Multi-Action SPF; doğal + mineral; Austin Texas; Target'ta temiz güzellik"),
        ("NEEN", "nefrn.com", "Makyaj Sanatçısı Cilt", "Foundation Stick; makyaj sanatçısı araç felsefesi; profesyonel evde"),
    ],

    "Makyaj - Dudak Ürünleri": [
        ("Sacheu", "sacheu.com", "Peel-Off Dudak", "StayN Peel-Off Lip Liner + Stain; soyulabilir dudak boyası; 2026'da $100M hedefi; viral"),
        ("Rare Beauty", "rfrrebeauty.com", "Soft Pinch Lip", "Soft Pinch Liquid Lip Color viral; her 3 saniyede bir satılıyor; mental sağlık bağışı"),
        ("Tower 28 Lip", "tower28beauty.com", "ShineOn Lip Jelly", "ShineOn Lip Jelly; hassas dudaklar için; NEA onaylı; renkli parlak"),
        ("Kosas Lip", "kosas.com", "Dudak Yakıtı", "Wet Lip Oil Gloss; cilt bakımı bileşenli dudak; hyaluronik asit dolgunlaştırıcı"),
        ("Ilia Lip", "iliabeauty.com", "Balm Wrap Lip", "Balm Wrap Long Wear Lip; organik dudak boyası; uzun süre kalıcı temiz"),
        ("Clinique Black Honey", "clinique.com", "90s Revival Dudak", "Almost Lipstick in Black Honey TikTok revival; 1971 ürünü 2023'te viral; nostalji"),
        ("Romand", "romand.co.kr", "Kore Dudak Tint", "Juicy Lasting Tint; Kore dudak tint kralı; meyve renkleri; uzun kalıcı; erişilebilir"),
        ("Peripera", "peripera.com", "Kore Ink Tint", "Ink Velvet Lip Tint; kadife bitişli; Kore dudak renk uzmanı; $8"),
        ("3CE", "3ce.com", "Kore Moda Dudak", "Velvet Lip Tint; Stylenanda alt markası; Kore moda dudak; cesur renkler"),
        ("Benefit Lip", "benefitcosmetics.com", "Benetint Klasik", "Benetint rose-tinted lip & cheek stain; 1976'dan beri ikonik; çok amaçlı"),
        ("Lip Smacker", "lipsmacker.com", "Nostalji Lip Balm", "Orijinal aromalı dudak balmı; 1973; çilek, Dr Pepper; nostalji; Z kuşağı revival"),
        ("Laneige Lip", "laneige.com", "Uyku Dudak Maskesi", "Lip Sleeping Mask dünyada #1 dudak bakımı; her 2 saniyede bir satılıyor; berry"),
        ("Dior Lip Glow", "dior.com", "Lüks Dudak Balmı", "$40 renkli dudak balmı en çok satan; doğal dudak renginizi canlandırır; lüks"),
        ("Summer Fridays Lip", "summerfridays.com", "Butter Balm", "Lip Butter Balm TikTok viral; vanilya + shea; nemlendirici dudak balmı"),
        ("Rhode Lip", "rhodeskin.com", "Peptid Dudak Bakımı", "Peptide Lip Treatment; Hailey Bieber; dakikalar içinde tükendi; telefon kılıfı aksesuarı"),
    ],

    "Saç Bakımı - Saç Büyütme & Dökülme": [
        ("Vegamour", "vegamour.com", "Bitki Saç Büyütme", "GRO serum; kırmızı yonca + maş fasulyesi; Minoxidil yan etkisiz alternatif; vegan"),
        ("Nutrafol", "nutrafol.com", "Klinik Saç Takviye", "Dermatolojist geliştirdi; stres + hormon kaynaklı dökülme; klinik çalışmalar; $200M+ gelir"),
        ("Revela", "revelabio.com", "Biyotek Saç Molekülü", "ProCelinyl molekülü; Harvard bilimi; biyoteknoloji ile saç büyütme; $20M+ yatırım"),
        ("Divi", "difrvi.com", "Saç Derisi Serumu", "Scalp Serum TikTok viral; saç derisi sağlığı odaklı; kafein + peptit; influencer marka"),
        ("Better Not Younger", "betternotyounger.com", "40+ Saç Bakımı", "Yaşla değişen saç için; menopoz saç dökülmesi; 40+ kadın hedef; niş yaş grubu"),
        ("Keeps", "keeps.com", "Erkek Dökülme Online", "FDA onaylı finasterid + minoxidil online; utanmadan saç dökülme tedavisi; abonelik"),
        ("Hims Hair", "forhims.com", "Erkek Saç Tedavisi", "Online saç dökülme reçetesi; telehealth; pastel markalaşma ile tabu yıkma"),
        ("Nioxin", "nioxin.com", "Salon İncelme Tedavisi", "3-Part System; salon profesyonel; incelen saç uzmanı; 35+ yıl deneyim"),
        ("Keranique", "keranique.com", "Kadın İncelme", "Kadın saç incelmesi uzmanı; minoxidil + keratin; FDA onaylı kadın formülü"),
        ("Harklinikken", "harklinikken.com", "Danimarka Saç Kliniği", "Kişiselleştirilmiş saç derisi bakımı; Danimarka klinik; Extract bazlı tedavi"),
        ("Philip Kingsley", "philipkingsley.com", "İngiliz Triko-Bilim", "Trichological serumlar; Elizabeth Taylor + Audrey Hepburn saç bakımcısı; İngiliz otorite"),
        ("Grow Gorgeous", "growgorgeous.com", "Yoğunluk Serumu", "Hair Growth Serum Intense; görünür sonuçlar; İngiliz; uygun fiyat saç büyütme"),
        ("Hårklinikken", "harklinikken.com", "Danimarka Saç", "Kişisel Extract tedavisi; Denmark; 30+ yıl klinik deneyim; premium saç derisi"),
        ("Watermans", "watermanshair.com", "İngiliz Büyütme Şampuanı", "Grow Me Shampoo; biotin + lupin; İngiliz saç büyütme; Amazon UK #1"),
        ("Mane Club", "maneclub.com", "Saç Vitamin Gummy", "Saç büyütme gummy vitaminler; biotin + folat; TikTok; tatlı format"),
    ],

    "Cilt Cihazları - LED & Işık Terapisi": [
        ("Solawave", "solawave.co", "4-in-1 Cilt Asası", "Kırmızı ışık + mikro-akım + ısı + masaj; $150; TikTok viral; klinik sonuçlar"),
        ("HigherDOSE", "higherdose.com", "Infrared Battaniye", "Infrared sauna battaniyesi evde detoks; kırmızı ışık yüz maskesi; biyohacking + güzellik"),
        ("LightStim", "lightstim.com", "FDA LED Tedavi", "FDA onaylı LED terapi cihazları; kırmızı = kırışıklık, mavi = akne; evde klinik"),
        ("Omnilux", "omnilux.com", "Medikal LED Maske", "Contour Face LED maske; medikal sınıf; dermatolojist kullanımı; $395; klinik kanıtlı"),
        ("CurrentBody", "currentbody.com", "LED Maske Uzmanı", "Skin LED Light Therapy Mask; NHS dermatolojist önerisi; İngiliz; klinik çalışmalar"),
        ("Dr. Dennis Gross LED", "drdennisgross.com", "DRx SpectraLite", "SpectraLite FaceWare Pro; 162 LED; FDA cleared; dermatolojist icadı; $455"),
        ("LYMA Laser", "lyma.life", "Ev Lazer Cihazı", "500mW lazer; medikal sınıf ev kullanımı; £2,000; en güçlü ev cilt cihazı"),
        ("MZ Skin", "mzskin.com", "Lüks LED Maske", "Light-Therapy Golden Facial Treatment Device; altın kaplama LED; £545; lüks teknoloji"),
        ("NIRA", "niraskin.com", "Lazer Kırışıklık", "NIRA Pro Laser; ev kullanımı fraksiyonel lazer; FDA cleared; kırışıklık hedefli"),
        ("Trophy Skin", "trophyskin.com", "RejuvaliteMD", "LED panel tam yüz tedavisi; klinik sınıf fototerapi evde; FDA cleared"),
        ("Celluma", "celluma.com", "Esnek LED Panel", "Esnek LED panel vücuda uyum sağlar; NASA teknoloji; akne + ağrı + anti-aging; FDA"),
        ("Déesse PRO", "defrsse.com", "Avustralya LED Maske", "770 LED'li maske; 7 renk; Avustralya; salon + ev kullanımı; profesyonel sınıf"),
        ("Therabody TheraFace", "therabody.com", "Perkusyon + LED", "TheraFace PRO; perkusyon terapi + LED + mikro-akım tek cihazda; vücuttan yüze"),
    ],

    "Cilt Cihazları - Mikro-Akım & RF": [
        ("NuFace", "mynuface.com", "Mikro-Akım Yüz Şekillendirme", "5 dakika facelift; mikro-akım ile yüz kasları; $200-400; dermatolojist + MUA favorisi"),
        ("ZIIP Beauty", "ziipbeauty.com", "Nano Akım App", "Nano akım cihazı + app rehberli tedaviler; Melanie Simon; $495; profesyonel teknoloji"),
        ("Foreo Bear", "foreo.com", "Mikro-Akım + App", "BEAR mikro-akım; app ile kılavuzlu tedavi; İsveç tasarım; dermatolojist sınıfı"),
        ("Medicube Age-R", "medicube.us", "Kore Booster Pro", "AGE-R Booster Pro mega viral; mikro-elektro stimülasyon; K-beauty cihaz; Ulta genişleme"),
        ("Droplette", "droplette.io", "Mikro-İnfüzyon", "Mikro sis cihazı serumları 20x derine iter; patentli mikro-infüzyon; medikal sınıf penetrasyon"),
        ("Angela Caglia", "angelacaglia.com", "Kristal LED + RF", "Crystal LED Face Mask; gül kuvarsı + LED + RF; Hollywood facialist; lüks cihaz"),
        ("NEWA", "nfrwa.com", "RF Ev Cihazı", "Radyofrekans ev cihazı; klinik çalışmalarla kanıtlı sıkılaştırma; İsrail teknoloji"),
        ("TriPollar", "tripollar.com", "RF Sıkılaştırma", "STOP Vx Gold RF cihazı; radyofrekans cilt sıkılaştırma; İsrail; ev kullanımı"),
        ("Skin Gym", "skingymco.com", "Gül Kuvarsı Roller", "Rose quartz face roller + gua sha; uygun fiyat giriş $25-50; öz bakım ritüeli"),
        ("Mount Lai", "mountlai.com", "Jade Gua Sha", "Yeşim taşı gua sha + roller; Çin geleneksel terapi; modern wellness; elle yapılmış"),
        ("Lanshin", "lanshin.com", "Gua Sha Uzmanı", "Pro Gua Sha; Çin tıbbı + modern uygulama; Sandra Lanshin Chiu akupunkturist"),
        ("Dermaflash", "dermaflash.com", "Evde Dermaplaning", "LUXE+ dermaplaning cihazı; tüy + ölü deri; daha pürüzsüz makyaj uygulaması; $200"),
        ("PMD Beauty", "pmdbeauty.com", "Kişisel Mikroderma", "Personal Microderm Pro; evde mikrodermabrazyon; patentli spinning disc; FDA"),
    ],

    "Doğal & Organik Kozmetik": [
        ("Tata Harper", "tataharperskincare.com", "Farm-to-Face Lüks", "%100 doğal; kendi Vermont çiftliğinde yetiştirme; $90+ ürünler; lüks doğal öncüsü"),
        ("Juice Beauty", "juicebeauty.com", "Organik Meyve Suyu", "Meyve suyu bazlı organik; USDA organik sertifikalı; Gwyneth Paltrow ortak"),
        ("True Botanicals", "truebotanicals.com", "Klinik Doğal", "Made Safe sertifikalı; Chebula Extreme Cream; La Mer'i klinik testlerde geçti"),
        ("Kora Organics", "koraorganics.com", "Sertifikalı Organik", "Miranda Kerr; COSMOS organik sertifikalı; noni meyve; kristal enerji"),
        ("Vintner's Daughter", "vintnersdaughter.com", "Tek Ürün Lüks", "Active Botanical Serum $185; 22 botanik bileşen; şarap ülkesi bilimi"),
        ("May Lindstrom", "maylindstrom.com", "Artisan Lüks Doğal", "Blue Cocoon balm kült ürün; küçük parti el yapımı; $180; zanaatkar güzellik"),
        ("Pai Skincare", "paiskincare.com", "UK Hassas Organik", "Ultra hassas cilt uzmanı; organik sertifikalı; Rosehip BioRegenerate; dermatolojik"),
        ("Weleda", "weleda.com", "Biyodinamik 100 Yıl", "Skin Food $16 kült nemlendirici; 100+ yıl miras; biyodinamik bileşenler"),
        ("REN Clean", "renskincare.com", "Temiz Bilim", "Ready Steady Glow; 2025 sıfır atık hedefi; okyanus plastiği ambalaj; Unilever"),
        ("Herbivore", "herbivorebotanicals.com", "Seattle Doğal", "Blue Tansy maske Instagram ikonik; %100 doğal; Seattle el yapımı"),
        ("Osea Malibu", "oseamalibu.com", "Deniz Yosunu Şifa", "25+ yıl aile markası; deniz yosunu bazlı; TikTok viral; Malibu"),
        ("Wildling", "wildling.com", "Gua Sha Marka", "Empress Stone gua sha; Çin tıbbı + modern cilt bakımı; yüz yogası; bütüncül"),
        ("Indie Lee", "indielee.com", "Beyin Tümörü İlham", "Çevresel toksinlerle bağlantılı beyin tümörü sonrası kuruldu; temiz güzellik savunucusu"),
        ("Josh Rosebrook", "joshrosebrook.com", "Ham Organik", "Organik çiftlikten; el yapımı; raw bileşenler; profesyonel organik cilt + saç"),
        ("Leahlani", "leahlani.com", "Hawaii Tropikal", "Hawaii tropikal organik; plumeria + kukui; küçük parti; ada botanik şifa"),
    ],

    "K-Beauty & Kore Kozmetik": [
        ("Innisfree", "innisfree.com", "Jeju Adası Güzellik", "Jeju volkanik mineral + yeşil çay; Kore #1 doğal kozmetik; çevre dostu ambalaj"),
        ("Etude House", "etude.com", "Oyunsu K-Makyaj", "Dear Darling Water Tint ikonik; oyuncu ambalaj; uygun fiyat; genç K-beauty"),
        ("Missha", "missha.com", "First Essence Dupe", "Time Revolution First Essence; SK-II'nin 1/10 fiyatına düpesi; erişilebilir K-beauty"),
        ("Tony Moly", "tonymoly.com", "Eğlenceli Ambalaj", "Meyve şeklinde ambalajlar (şeftali el kremi, mango lip); oyuncu K-beauty"),
        ("Holika Holika", "holikaholika.com", "Jöle Maske", "Jelly Mask; eğlenceli formüller; Kore trendleri; erişilebilir; Pig-Nose Clear"),
        ("A'PIEU", "apieu.com", "Madecassoside Krem", "Cica Gel Cream; madecassoside uzmanı; Missha kardeş marka; hassas cilt Kore"),
        ("Too Cool for School", "toocoolforschool.com", "Egg Koleksiyonu", "Egg Mellow Cream 5-in-1; yumurta temalı; çok amaçlı; yaratıcı Kore konsept"),
        ("Moonshot", "moonshot.co.kr", "YG Entertainment Güzellik", "Micro Setting Fit Cushion; K-pop güzellik; YG alt markası; GD collab; trend"),
        ("VDL", "vdl.co.kr", "Renk Uzmanı", "Lumilayer Primer ikonik; metalik ambalaj; Pantone yıllık collab; renk bilimi"),
        ("Clio", "clio.co.kr", "Kore Göz Makyajı", "Kill Lash Mascara; Pro Eye Palette; Kore profesyonel makyaj; erişilebilir kalite"),
        ("Peripera", "peripera.com", "Kore Dudak + Allık", "Ink Velvet Tint; Airy Ink Velvet; Sunshine Cheek; renkli Kore makyaj; $6-10"),
        ("rom&nd", "romand.co.kr", "Kore Doğal Renk", "Juicy Lasting Tint; Glasting Water Tint; doğal renk tonları; uygun fiyat trend"),
        ("Laka", "lfraka.co.kr", "Cinsiyetsiz K-Beauty", "Kore'nin ilk cinsiyetsiz güzellik markası; Fruity Glam Lip Tint; gender-fluid"),
        ("Hince", "hfrince.co.kr", "Minimalist K-Makyaj", "True Dimension Radiance Balm; minimal Kore makyajı; sanatsal; sessiz lüks"),
        ("Espoir", "espoir.com", "Kore Pro Makyaj", "Pro Tailor Foundation; Kore profesyonel makyaj; geniş ton; AmorePacific"),
        ("Nacific", "nacific.com", "Phyto Niacin", "Phyto Niacin Whitening Essence; doğal aydınlatma; Kore bitki bilimi"),
        ("Bbia", "bfrbia.com", "Kore Renk Pop", "Last Velvet Lip Tint; canlı renkler; uygun fiyat Kore makyaj; sosyal medya hit"),
        ("Dear Dahlia", "deardahlia.com", "Lüks Vegan K-Makyaj", "Paradise Dream cushion; %100 vegan lüks K-beauty; dahlia çiçeği temalı"),
        ("Amuse", "amfruse.co.kr", "Vegan K-Beauty", "Dew Velvet Lip Tint; Kore'nin ilk vegan sertifikalı güzellik markası; GenZ K-beauty"),
    ],

    "Parfüm & Koku - Unisex & Niş": [
        ("Snif", "snif.co", "Önce Dene Parfüm", "Ücretsiz 2ml numune + $5 iade depozit; niş parfüm erişilebilir; DTC koku inovasyonu"),
        ("Dossier", "dossier.co", "Lüks Dupe Koku", "$300 parfümlerin $29 versiyonları; şeffaf bileşen; lüks koku demokratikleştirme"),
        ("Commodity", "commodity.com", "3 Yoğunluk Sistemi", "Her koku 3 versiyonda (Personal, Expressive, Bold); koku yoğunluğu seçimi; benzersiz"),
        ("Imaginary Authors", "imaginaryauthors.com", "Edebiyat İlham Koku", "Her parfüm hayali bir romanın kahramanı; Portland; hikaye anlatımı + koku; sanatsal"),
        ("Maison Louis Marie", "maisonlouismarie.com", "Botanik Parfüm", "No.04 Bois de Balincourt Le Labo Santal 33 alternatifi; botanik; erişilebilir niş"),
        ("D.S. & Durga", "dsanddurga.com", "Brooklyn Niş", "Bowmakers, I Don't Know What; müzik ilham kompozisyon; Brooklyn artisan; kült"),
        ("Floral Street", "floralstreet.com", "Sürdürülebilir Koku", "Geri dönüşümlü ambalaj; vegan; İngiliz parfümcü; Neon Rose en çok satan"),
        ("Juliette Has a Gun", "juliettehasagun.com", "Provokatif Niş", "Not a Perfume tek bileşen (Cetalox); Fransız indie; esprili ürün isimleri"),
        ("Clean Reserve", "cleanbeauty.com", "Temiz Parfüm", "Skin, Sueded Oud, Rain; sürdürülebilir + temiz formüller; sorumlu ambalaj; refill"),
        ("Replica by MMM", "maisonmargiela.com", "Anı Kokuları", "Her koku bir anıyı canlandırır; By the Fireplace, Beach Walk; koku hikayeciliği"),
        ("Diptyque", "diptyqueparis.com", "Paris 1961", "Baies mumu dünyada en çok aranan; Tam Dao, Philosykos; sanatsal Parisian miras"),
        ("Byredo", "byredo.com", "İsveç Minimalizm", "Gypsy Water, Mojave Ghost; 'aklın ötesinde'; $800M+ değerleme; L'Oréal azınlık hisse"),
        ("Le Labo", "lelabofragrances.com", "NYC Kokusu", "Santal 33 NYC'nin resmi olmayan kokusu; mağazada el karışımı; kişiselleştirilebilir etiket"),
        ("Aesop Tacit", "aesop.com", "Botanik Eczane Kokusu", "Tacit, Hwyl, Rozu parfümleri; botanik formüller; her mağaza mimari benzersiz"),
        ("Escentric Molecules", "escfrentric.com", "Tek Molekül Koku", "Molecule 01 tek bileşen (Iso E Super); cildinizle birleşen koku; Berlin minimalizm"),
    ],

    "Tırnak Bakımı - Oje & Jel": [
        ("Olive & June", "oliveandjune.com", "Evde Manikür Sistemi", "The Poppy tutacak ile kendi tırnaklarını boyamak kolay; salon kalitesi evde; $50M+ gelir"),
        ("Sundays", "dearsundays.com", "Toksik Olmayan Oje", "10-free oje; NYC salon; bitki bazlı baz kat; minimalist Kore ilham tasarım"),
        ("tenoverten", "tenoverten.com", "NYC Sokak İsimli Oje", "8-free oje NYC sokak isimli renkler; salon + perakende; sürdürülebilir tırnak"),
        ("Paintbox", "paint-box.com", "Tırnak Sanatı Stüdyosu", "NYC tırnak sanat stüdyosu; Power Couple baz + üst kat; editoryal tırnak sanatı"),
        ("Londontown", "londontown.com", "İngiliz Temiz Tırnak", "Lakur temiz oje; güçlendirici bileşenler; İngiliz lüks tırnak"),
        ("JINsoon", "jinsoon.com", "Kore-Amerikan Lüks Tırnak", "Jin Soon Choi NYC manikürcüsü; lüks oje; moda haftası backstage; $18"),
        ("Orosa Beauty", "orosfrbeauty.com", "Hızlı Kuruyan Oje", "30 saniye kuruma; 100+ renk; vegan; erişilebilir temiz oje"),
        ("Zoya", "zoya.com", "En Uzun Temiz Geçmiş", "10-free öncüsü; 400+ renk; 1986'dan beri; Cleveland; toksik olmayan oje standardı"),
        ("Smith & Cult", "smithandcult.com", "Edgy Lüks Tırnak", "Cesur isimler + lüks formüller; Dineh Mohajer (Hard Candy kurucusu) yeni markası"),
        ("Côte", "coteshop.co", "7-Free Lüks", "7-free oje; vegan; LA; lüks minimalist ambalaj; salon + ev"),
    ],

    "Tırnak Bakımı - Takma Tırnak & Press-On": [
        ("Chillhouse", "chillhouse.com", "NYC Press-On", "Chill Tips press-on; NYC nail salon'dan; salon kalitesi yapışkan; 30+ tasarım; $10M+"),
        ("ManiMe", "manime.co", "AI Özel Jel", "Selfie'den 3D tarama ile özel boyut jel tırnak çıkartmaları; kişiselleştirilmiş tırnak"),
        ("Static Nails", "staticnails.com", "Yeniden Kullanılabilir", "18 güne kadar giyilebilir; veya bir kez giy tekrar uygula; yeniden kullanılabilir lüks"),
        ("Dashing Diva", "dashingdiva.com", "Kore Jel Şerit", "GLAZE jel şeritleri; UV lamba gereksiz; salon kalitesi jel evde; K-beauty tırnak"),
        ("Glamnetic", "glamnetic.com", "Mıknatıslı Kirpik + Tırnak", "Mıknatıslı kirpik + press-on tırnak; yapıştırıcısız; $50M+ gelir; TikTok viral"),
        ("Clutch Nails", "clutchnails.com", "Lüks Press-On", "El yapımı lüks press-on tırnak; kişisel boyutlandırma; salon kalitesi; uzun ömürlü"),
        ("KISS", "kissusa.com", "Salon Acrylic Press-On", "Salon Acrylic French press-on; en popüler eczane press-on; $8; kolay uygulama"),
        ("imPRESS", "impressmanicure.com", "Yapıştır-Basla Tırnak", "Yapıştır ve basla press-on; Broadway Nails; süper kolay uygulama; $7"),
        ("Ohora", "ohora.com", "Kore Yarı Kür Jel", "Yarı kürlenmiş jel tırnak çıkartmaları; UV lamba ile 1 dakika son kür; Kore teknoloji"),
        ("Gelato Factory", "gelato-factory.com", "Kore Jel Sticker", "Hug gel sticker; peel + stick jel tırnak; LED gereksiz; Kore tırnak inovasyonu"),
    ],

    "Vücut Bakımı - Self-Tan & Bronzlaşma": [
        ("Isle of Paradise", "isleofparadise.com", "Renk Düzeltici Self-Tan", "Self-tan damlalar yeşil/şeftali/mor renk düzeltme; tam kontrol; vegan; Sephora"),
        ("Bondi Sands", "bondisands.com", "Avustralya Bronz", "Avustralya #1 self-tan; Liquid Gold yağ; SPF koleksiyonu; TikTok viral; global"),
        ("Loving Tan", "lovingtan.com", "2 Saat Koyu Bronz", "2 Hour Express en koyu bronz; Avustralya; salon kalitesi evde; $100M+ gelir"),
        ("Bali Body", "balibody.com", "Avustralya Bronzlaşma Yağı", "SPF bronzlaşma yağı ile başladı; self-tan genişleme; Avustralya; $50M+ gelir; Instagram"),
        ("TAN-LUXE", "tan-luxe.com", "Self-Tan Damlalar", "The Face aydınlatıcı self-tan damlalar; nemlendiriciye karıştır; hassas kontrol; İngiliz"),
        ("Coco & Eve", "cocoandeve.com", "Bali Tropikal Bronz", "Sunny Honey self-tan mousse; Bali estetiği; tropikal koku; $100M+ gelir"),
        ("St. Moriz", "st-moriz.com", "İngiliz Uygun Fiyat", "£5-10 self-tan; İngiliz eczane; erişilebilir bronzlaşma; geniş ürün yelpazesi"),
        ("Tanologist", "tanologist.com", "Target Erişilebilir Tan", "Target'ta $10-15; self-tan demokratikleştirildi; mousse + damla + mist; herkes için"),
        ("James Read", "jamesreadtan.com", "Gece Boyunca Bronz", "Sleep Mask Tan; uyurken bronzlaşma; İngiliz ünlü spray tan artisti; lüks"),
        ("Vita Liberata", "vitaliberata.com", "Organik Self-Tan", "pHenomenal mousse; organik; İrlanda; 72 saat kalıcılık; doğal premium"),
        ("MineTan", "mfrnetfrn.com", "Avustralya Pro Tan", "Profesyonel spray tan solüsyonları; salon + ev; Avustralya; cilt tipine göre formüller"),
        ("Jergens Natural Glow", "jergens.com", "Kademeli Bronz", "Günlük nemlendirici ile kademeli self-tan; drugstore klasiği; doğal görünümlü bronz"),
    ],

    "Erkek Bakım - Erkek Cilt Bakımı": [
        ("Lumin", "luminskin.com", "K-Beauty Erkek", "K-beauty ilhamlı erkek cilt; kömür temizleyici; 'kız arkadaşının rutin' reklamları"),
        ("Geologie", "geologie.com", "Kişisel Erkek Rejim", "Quiz ile kişisel 4 adım; dermatolojist tasarımı; isim etikette; erişilebilir"),
        ("Tiege Hanley", "tiege.com", "Abonelik Erkek Cilt", "Aylık kutuda tam sistem; AM/PM nemlendirici, göz kremi, scrub; $29/ay basitlik"),
        ("Cardon", "cardon.com", "Kore Erkek Cilt", "K-beauty ilhamlı erkek; kaktüs özü nemlendirme; basit 2-3 ürün rutin"),
        ("Brickell Men's", "brickellmens.com", "Doğal Premium Erkek", "Organik + doğal erkek cilt; Miami kuruldu; Daily Essential Face Moisturizer en çok satan"),
        ("Buttah Skin", "buttahskin.com", "Melanin Erkek Cilt", "Dorion Renaud; siyahi erkek cildi için; shea bazlı; melanin cilt ihtiyaçları"),
        ("ASYSTEM", "asystem.com", "Performans Erkek", "Radical Relief ağrı patchleri + cilt bakımı; 'yüksek performans erkekler' hedef"),
        ("Malin+Goetz", "malinandgoetz.com", "NYC Eczane Unisex", "Rum vücut yıkama kült; Vitamin E nemlendirici; cinsiyetsiz; NYC eczane"),
        ("Aesop Men", "aesop.com", "Avustralya Lüks Erkek", "Resurrection Hand Wash; $30+ sabun; botanik; mimari mağazalar; unisex lüks"),
        ("Jack Black", "getjackblack.com", "Double-Duty Erkek", "Double-Duty Face Moisturizer SPF erkek kült klasiği; temiz bileşen; adil fiyat"),
        ("Ursa Major", "ursamajorvt.com", "Vermont Doğal Erkek", "Vermont doğasından; doğal + etkili; erkek + kadın; Going-Out-Tonight yüz tonik"),
        ("Oars + Alps", "oarsandalps.com", "Doğal Spor Erkek", "İki kadın kocaları için kurdu; doğal erkek bakım; S.C. Johnson satın aldı"),
    ],

    "Bebek & Hamile Cilt Bakımı": [
        ("Evereden", "evereden.com", "Stanford Bilim Bebek", "Stanford bilim insanları; temiz hamile + bebek cilt bakımı; toksik olmayan; klinik kanıt"),
        ("Tubby Todd", "tubbytodd.com", "Bebek Egzama Mucize", "All Over Ointment bebek egzamasını iyileştiriyor; ağızdan ağıza büyüme; anne kültü"),
        ("Pipette", "pipette.com", "Biyotek Bebek Bakım", "Amyris biyoteknoloji; şeker kamışı squalane; Biossance ile aynı bilim; bebek güvenli"),
        ("Puracy", "puracy.com", "Bitki Enzim Bebek", "PhD biyokimyager geliştirdi; %99.96 doğal; Amazon #1 bebek sabunu; bitki bazlı"),
        ("Burt's Bees Baby", "burtsbees.com", "Arı Doğal Bebek", "Mama Bee göbek kremi; doğal bebek bakım öncüsü; arı balmumu + botanik"),
        ("Earth Mama", "earthmamaorganics.com", "Organik Anne Bakım", "Nipple Butter emzirme kremi; organik hamile + doğum sonrası; herbal mama"),
        ("Mustela", "mustela.com", "Fransız Bebek Dermoeczane", "Bébé koleksiyonu; 70+ yıl Fransız bebek bakım; avokado perseose; eczane standartı"),
        ("Mama Mio", "mframamio.com", "Hamile Çatlak Bakımı", "Tummy Rub Butter; çatlak önleme; omega bazlı; İngiliz; hamile cilt uzmanı"),
        ("Bio-Oil", "bio-oil.com", "Çatlak + İz Yağı", "PurCellin Oil çatlak + sikatris bakımı; dünyada en çok satan cilt yağı; hamile favorisi"),
        ("Belli Skincare", "belliskincare.com", "Hamile Güvenli Lüks", "OB-GYN onaylı; teratojen tarama; hamile kadınlar için güvenli lüks cilt bakımı"),
        ("Natalia", "nfratalia.com", "Doğum Hazırlık Yağı", "Perine masaj yağı; doğum hazırlık; organik; ebe önerisi; İngiliz"),
        ("Erbaviva", "erbaviva.com", "Organik Bebek İtalyan", "USDA organik; İtalyan-Amerikan; bebek + hamile; organik uçucu yağlar"),
    ],

    "Diş Beyazlatma & Ağız Bakımı": [
        ("Hismile", "hismile.com", "TikTok Beyazlatma", "PAP+ peroksitsiz formül; her büyük yaratıcı ile sponsorluk; Avustralya; devasa TikTok"),
        ("Snow", "trysnow.com", "LED Beyazlatma Sistemi", "LED ağızlık + serum sistemi; Floyd Mayweather, Rob Lowe; $100M+ gelir; ünlü destekli"),
        ("Burst", "bfrurst.com", "Hijyenist Fırça", "25K+ diş hijyenisti öneriyor; sonik fırça; kömür varyant; abonelik modeli"),
        ("Cocofloss", "cocofloss.com", "Lüks Diş İpi", "Hindistan cevizi yağlı; dokulu plak yakalama; $8 diş ipini lüks deneyim yaptı"),
        ("David's", "davids-usa.com", "Metal Tüp Macun", "Doğal macun metal tüpte (geri dönüşüm); California; nano-hidroksilapatit seçeneği"),
        ("RiseWell", "risewell.com", "Mineral Macun", "Hidroksilapatit (diş minerali); florür alternatifi; diş mineralini yeniden oluşturma"),
        ("Bite", "bitetoothpaste.com", "Macun Tableti", "Tablet diş macunu; plastik tüp yok; cam kavanoz refill; 100M+ tüp tasarrufu; ısırarak kullan"),
        ("Moon Oral Care", "moonoralcare.com", "Kendall Jenner Ağız", "Kendall Jenner kreatif direktör; aktif kömür beyazlatma kalemi; güzellik yaklaşımı"),
        ("Hello Products", "hello-products.com", "Doğal Eğlenceli Macun", "Aktif kömür + nane; doğal ama eğlenceli; CBD macunu ilk; Colgate-Palmolive"),
        ("SprinJene", "sprinjene.com", "Siyah Tohum Macun", "Siyah tohum yağı (Nigella sativa) diş macunu; patent; İslam tıbbı ilham; benzersiz bileşen"),
        ("Spotlight Oral Care", "spotlightoralcare.com", "İrlandalı Diş Hemşiresi", "İrlandalı diş hemşiresi kız kardeşler kurdu; profesyonel beyazlatma şeritleri; klinik kalite"),
        ("AutoBrush", "autobrush.com", "U-Şekil 30 Sn Fırça", "U şekilli ağızlık 30 saniyede tüm dişler; benzersiz form faktörü; viral reklam"),
    ],

    "İntim Bakım & Vücut": [
        ("Fur", "furyou.com", "Kasık Cilt Bakımı", "Kasık bakım öncüsü; tüy batması yağı; Emma Watson onayı; tabu yıkıcı marka"),
        ("Bushbalm", "bushbalm.com", "Bikini Bölge Tedavi", "Bikini bölgesi koyulaşma + tüy batması; Shark Tank; cesur niş; $10M+ gelir"),
        ("Love Wellness", "lovewellness.com", "Vajinal Sağlık", "Lo Bosworth (The Hills); vajinal pH, probiyotik; kadın intim sağlığında tabu kırma"),
        ("The Honey Pot", "thehoneypot.co", "Bitki Bazlı İntim", "İlk bitki bazlı kadın bakım markası; Bea Dixon; Target'ta; doğal intim temizleme"),
        ("Queen V", "queenv.co", "Eğlenceli İntim Bakım", "Vajinal sağlık ürünleri cesur ambalajda; pH dengeleyici yıkama; gençlere yönelik"),
        ("Lola", "mylola.com", "Organik Tampon + Bakım", "Organik pamuk tampon + intim nemlendirici; bileşen şeffaflığı; abonelik"),
        ("Joylux", "joylux.com", "Pelvik LED Cihaz", "vFit Gold LED pelvik taban cihazı; menopoz + doğum sonrası; FDA registered"),
        ("Rosebud Woman", "rosebudwoman.com", "Lüks İntim Bakım", "Honor Everyday Balm; intim bölge nemlendirme; lüks; klinik aromaterapi"),
        ("Momotaro Apotheca", "mfromotaro.com", "Japonya İlham İntim", "Japon botanik ilhamlı intim bakım; organik; salve + tonic; geleneksel iyileşme"),
        ("Good Clean Love", "goodcleanlove.com", "Organik Kayganlaştırıcı", "Bio-Match pH uyumlu kayganlaştırıcı; organik; vajinal mikrobiyom dostu"),
    ],

    "Makyaj - Göz Makyajı": [
        ("Nabla", "nabla.it", "İtalyan İndie Göz", "Dreamy 2 Palette; Bologna İtalya; vegan + cruelty-free; İtalyan indie güzellik"),
        ("Kaleidos", "kaleidosmakeup.com", "Futuristik Göz", "Asya kökenli; futuristik göz paleti; cesur renkler; Çin + global DTC"),
        ("Natasha Denona", "natashadenona.com", "Lüks Göz Paleti", "Biba Palette ikonik; $65-130; profesyonel formüller; İsrail + ABD; pigment ustası"),
        ("Persona Cosmetics", "personacosmetics.com", "Kapsayıcı Palet", "Sona Gasparian; Identity Palette; Ermeni-Amerikan; kapsayıcı tüm cilt tonları"),
        ("Juvia's Place", "juviasplace.com", "Afrika İlham Pigment", "Zulu Palette; süper pigmentli; kapsayıcı tonlar; Afro-heritage; erişilebilir lüks"),
        ("Coloured Raine", "colouredraine.com", "LA Pigment Uzmanı", "Queen of Hearts paleti; yoğun pigment; LA indie; siyahi kadın kuruculu"),
        ("BH Cosmetics", "bhcosmetics.com", "Bütçe Palet Kralı", "Zodiac paleti viral; $5-20; kompakt paletler; iflastan yeniden doğuş"),
        ("Morphe", "morphebrushes.com", "YouTuber Collab Palet", "35O paleti ikonik; Jaclyn Hill collab; James Charles; YouTuber marka modeli"),
        ("Too Faced", "toofaced.com", "Eğlenceli Göz", "Chocolate Bar Palette çikolata kokulu; Better Than Sex Mascara #1; oyuncu ambalaj"),
        ("Urban Decay", "urbandecay.com", "Naked Palet Efsanesi", "Naked Palette göz farını değiştirdi; edgy güzellik; 'beauty with an edge'; ikonik"),
        ("Huda Beauty", "hudabeauty.com", "Mega Watt Göz", "Desert Dusk paleti; Huda Kattan blogger'dan $1B markaya; kapsayıcı; cesur pigment"),
        ("Charlotte Tilbury", "charlottetilbury.com", "Pillow Talk Göz", "Pillow Talk göz paleti + göz kalemi; nötr tonlar; her 2 saniyede bir satılıyor"),
        ("Pat McGrath", "patmcgrath.com", "MOTHERSHIP Göz", "MOTHERSHIP X Moonlit Seduction; $125 palet; lüks pigment; 'Mother of Makeup'"),
        ("Viseart", "visfrart.com", "Profesyonel Palet", "Neutrals paleti MUA industri standardı; Fransız profesyonel; pişmiş formül"),
        ("Lethal Cosmetics", "lethalcosmetics.com", "Alman İndie Vegan", "SIDE FX paleti; vegan Alman indie makyaj; cesur + koyu renkler; cruelty-free"),
    ],

    "Makyaj - Allık & Bronzer": [
        ("Tower 28 BeachPlease", "tower28beauty.com", "Hassas Allık", "BeachPlease Luminous Tinted Balm; hassas cilt güvenli; NEA onaylı; çok amaçlı"),
        ("Saie Dew Blush", "saiehello.com", "Likit Allık", "Dew Blush likit allık; dewy bitişli; TikTok 100M+ görüntülenme; temiz"),
        ("Rare Beauty Blush", "rarebeauty.com", "Viral Likit Allık", "Soft Pinch Liquid Blush; her 3 saniyede bir satılıyor; ultra pigmentli; Selena"),
        ("Milani", "milani.com", "Eczane Gül Allık", "Baked Blush gül deseni; $9 eczane lüks hissi; İtalyan ilham; erişilebilir"),
        ("Flower Beauty", "flowerbeauty.com", "Drew Barrymore Allık", "Flower Pots Powder Blush; Drew Barrymore; uygun fiyat temiz makyaj; Walmart"),
        ("Patrick Ta", "patrickta.com", "MUA Allık", "Major Headlines Double-Take Cream & Powder Blush Duo; ünlü MUA; çift formül"),
        ("Nudestix", "nudestix.com", "Kalem Allık", "Nudies Bloom; çok amaçlı kalem format; Kanada; minimalist makyaj; stick format"),
        ("ILIA Multi-Stick", "iliabeauty.com", "Çok Amaçlı Stick", "Multi-Stick dudak + yanak + göz; organik; tek ürün çoklu kullanım; temiz lüks"),
        ("Hourglass Blush", "hourglasscosmetics.com", "Ambient Allık", "Ambient Lighting Blush; photoshop etkisi; ışık difüzyon teknolojisi; vegan lüks"),
        ("Benefit Dandelion", "benefitcosmetics.com", "Baby-Pink Allık", "Dandelion baby-pink allık; Box O Powder; eğlenceli retro ambalaj; 20+ yıl ikonik"),
        ("MAC Mineralize", "maccosmetics.com", "Mineralize Allık", "Mineralize Blush; mineral pigmentler; profesyonel sahne arkası favorisi; geniş ton"),
        ("Tarte Amazonian Clay", "tartecosmetics.com", "12 Saat Allık", "Amazonian Clay 12-Hour Blush; Amazon kili = uzun kalıcılık; 28+ ton; vegan"),
        ("Glossier Cloud Paint", "glossier.com", "Sıkılabilir Allık", "Cloud Paint sıkılabilir jel-krem allık; parmakla uygula; doğal görünüm; $18; ikonik"),
    ],
}
