"""
Extra DTC brands to supplement the main database to reach 3000+.
Format: (Brand, Website, Sub-niche, Notable Insight)
"""

EXTRA_BRANDS = {
    "Beauty - K-Beauty & J-Beauty": [
        ("Laneige", "laneige.com", "K-Beauty", "Lip Sleeping Mask is the #1 lip treatment globally; sold one every 2 seconds; K-beauty gateway product"),
        ("Innisfree", "innisfree.com", "K-Beauty", "Jeju Island volcanic minerals and green tea; Korea's #1 natural cosmetics brand; eco-friendly packaging"),
        ("COSRX", "cosrx.com", "K-Beauty", "Snail Mucin Essence has 60K+ 5-star reviews; straightforward packaging; K-beauty for beginners"),
        ("Sulwhasoo", "sulwhasoo.com", "K-Beauty Luxury", "Korean herbal medicine in luxury skincare; Concentrated Ginseng Cream; 50+ year heritage"),
        ("Missha", "misshaus.com", "K-Beauty", "First Essence dupe of SK-II at 1/10th the price; Time Revolution line; affordable K-beauty"),
        ("Banila Co", "banilaco.com", "K-Beauty", "Clean It Zero cleansing balm started the oil-cleansing trend in the West; #1 cleansing balm in Korea"),
        ("Etude House", "etude.com", "K-Beauty", "Playful K-beauty with doll-like packaging; Dear Darling Water Tint; fun, affordable, trendy"),
        ("Shiseido", "shiseido.com", "J-Beauty", "150+ year Japanese beauty heritage; Ultimune serum; $8B+ revenue; blend of tradition and innovation"),
        ("SK-II", "sk-ii.com", "J-Beauty Luxury", "Pitera essence from sake fermentation; $100+ treatment essence; Japanese biotechnology meets luxury"),
        ("DHC", "dhccare.com", "J-Beauty", "Deep Cleansing Oil is Japan's #1 makeup remover for 20+ years; olive oil-based; simple yet effective"),
        ("Tatcha", "tatcha.com", "J-Beauty", "Japanese beauty rituals; Dewy Skin Cream; Victoria Beckham favorite; Unilever acquired"),
        ("Shu Uemura", "shuuemura.com", "J-Beauty", "Art of cleansing oils; Ultime8 cleansing oil; Japanese artistry; makeup artist heritage"),
        ("Canmake", "canmake.com", "J-Beauty Budget", "Japan's #1 budget cosmetics; cream cheek blush is iconic; $5-10 price point; quality at drugstore"),
        ("Cle de Peau", "cledepeaubeaute.com", "J-Beauty Ultra Luxury", "Most expensive lip treatment ($80); Illuminating Enhancer; Shiseido's premium line"),
        ("Anua", "anfrua.us", "K-Beauty", "Heartleaf toner went viral on TikTok; calms redness; #1 toner in Korea; clean K-beauty"),
        ("Beauty of Joseon", "beautyofjoseon.com", "K-Beauty Heritage", "Reviving Joseon Dynasty recipes; Glow Serum (ginseng + snail); massive TikTok virality"),
        ("Torriden", "torriden.com", "K-Beauty", "DIVE-IN Low Molecular Hyaluronic Acid serum; 5 types of hyaluronic acid; hydration specialist"),
        ("Medicube", "medicube.us", "K-Beauty Device", "AGE-R Booster Pro device went mega-viral on TikTok; micro-electro stimulation; clinical K-beauty"),
        ("SKIN1004", "skin1004.com", "K-Beauty", "Madagascar Centella Ampoule; sensitive skin specialist; clean ingredients; affordable clinical care"),
        ("Round Lab", "roundlab.com", "K-Beauty", "Dokdo cleanser (named after Korean island); gentle pH-balanced; ocean mineral skincare"),
    ],

    "Clothing - Plus Size & Inclusive": [
        ("Universal Standard", "universalstandard.com", "Size Inclusive", "Sizes 00-40 in every style; 'Fit Liberty' exchanges if size changes; $100M+ revenue; true inclusivity"),
        ("Eloquii", "eloquii.com", "Plus Fashion", "Fashion-forward plus sizes 14-28; not 'modest' — bold and trendy; Walmart acquired; $100M+ revenue"),
        ("Torrid", "torrid.com", "Plus Size", "Sizes 10-30; $1.3B+ revenue; lingerie, swimwear, fashion; IPO'd; biggest plus-size fashion brand"),
        ("Henning", "henning.com", "Plus Luxury", "Luxury fashion for sizes 12-24; elevated basics and workwear; Lauren Chan (plus model) founded"),
        ("Dia & Co", "dia.com", "Plus Styling", "Stitch Fix for plus sizes; stylist-curated boxes; sizes 14-32; personalized fashion discovery"),
        ("Girlfriend Collective", "girlfriend.com", "Inclusive Active", "Sizes XXS-6XL; recycled water bottle fabric; inclusive from day one, not as an afterthought"),
        ("Good American", "goodamerican.com", "Inclusive Denim", "Khloé Kardashian; launched sizes 00-24 simultaneously; $1M first day; body-positive from launch"),
        ("Savage X Fenty", "savagex.com", "Inclusive Lingerie", "Rihanna; sizes XS-4XL; Savage X Fenty Show; most inclusive lingerie brand ever; VIP model"),
        ("ThirdLove", "thirdlove.com", "Inclusive Bras", "78 sizes including half-cups; Fit Finder ML quiz; challenged Victoria's Secret in open letter NYT ad"),
        ("Skims", "skims.com", "Inclusive Shapewear", "Kim K; sizes XXS-5XL; Fits Everybody collection redefined basics; $4B valuation; size-inclusive from start"),
        ("Summersalt", "summersalt.com", "Inclusive Swim", "Sizes 2-24; The Sidestroke one-piece is bestselling; body-positive campaigns with real women"),
        ("Knix", "knix.com", "Inclusive Intimates", "Sizes XS-XXXL; Kickstarter record; leakproof + wireless; $100M+ revenue; body-positive"),
        ("Lane Bryant", "lanebryant.com", "Heritage Plus", "90+ year heritage in plus sizes; sizes 10-28; lingerie, workwear; $1B+ revenue; Cacique intimates"),
        ("11 Honoré", "11honore.com", "Plus Luxury", "Luxury designer fashion in extended sizes; curates from top designers; Patrick Herning founded"),
        ("Wray", "wfrray.com", "Inclusive Fashion", "Wrap dresses and bright prints in sizes XS-3X; Brooklyn-based; independent inclusive design"),
    ],

    "Clothing - Streetwear": [
        ("Supreme", "supremenewyork.com", "Streetwear Icon", "Thursday drops create lines around the block; box logo is currency; VF Corp acquired for $2.1B"),
        ("Off-White", "off---white.com", "Luxury Street", "Virgil Abloh's quotation marks and zip ties; bridged streetwear + high fashion; LVMH acquired"),
        ("A Bathing Ape (BAPE)", "bape.com", "Japanese Street", "Camo shark hoodie is iconic; Nigo founded; Japanese streetwear legend; BAPE STA shoes"),
        ("Stüssy", "stussy.com", "OG Streetwear", "Shawn Stussy's surfboard scrawl became global streetwear; 1980 origin; the tribe; OG of the genre"),
        ("Palace", "palaceskateboards.com", "London Street", "Triferg logo; skating roots; British humor in drops; collab with adidas, Ralph Lauren; anti-hype"),
        ("Noah", "noahny.com", "Conscious Street", "Brendon Babenzien (ex-Supreme); sustainability meets streetwear; Save the Whales tees; purposeful fashion"),
        ("Online Ceramics", "online-ceramics.com", "Art Street", "Grateful Dead-inspired tie-dye; each piece hand-dyed; limited runs; music festival culture meets art"),
        ("Brain Dead", "wearebraindead.com", "Creative Street", "Kyle Ng's creative collective; bold graphics; furniture, film, music, fashion; anti-brand brand"),
        ("Corteiz", "corfrteiz.com", "UK Street", "Clint419's London brand; 'Rules the World'; guerrilla marketing (scavenger hunts for drops); viral demand"),
        ("Eric Emanuel", "ericemanuel.com", "Basketball Shorts", "Mesh shorts with wild prints became streetwear staple; NBA crossover; $50-100 shorts sell instantly"),
        ("Rhude", "rhude.com", "Luxury Street", "Rhuigi Villaseñor; LA meets Manila; bandana shorts; Puma creative director; $100M+ revenue"),
        ("Amiri", "amiri.com", "Luxury Street", "Mike Amiri's hand-distressed jeans ($1,000+); music industry cult; bone joggers; LA-based luxury"),
        ("Casablanca", "casablancaparis.com", "Tennis Luxury", "Charaf Tajer; silk shirts and tennis-inspired luxury; New Balance 327 collab; Paris meets Morocco"),
        ("Gallery Dept.", "gallerydept.com", "Repurposed Fashion", "Josué Thomas hand-reworks vintage clothing; each piece is unique; LeBron James wore it; $1,000+ flared jeans"),
        ("Represent", "representclo.com", "UK Luxury Street", "Manchester brothers George and Mike Heaton; Owners Club collection; $100M+ revenue; premium British streetwear"),
    ],

    "Clothing - Sustainable Fashion": [
        ("Reformation", "thereformation.com", "Sustainable Fashion", "Tracks CO2, water, waste per garment; RefScale on every product; LA-made; celeb-loved eco-fashion"),
        ("Eileen Fisher", "eileenfisher.com", "Circular Fashion", "Renew program takes back old garments; Circle design principles; 30+ year sustainability pioneer"),
        ("Stella McCartney", "stellamccartney.com", "Luxury Sustainable", "Luxury fashion without leather or fur since 2001; mushroom leather Mylo; LVMH partnership"),
        ("Veja", "veja-store.com", "Eco Sneakers", "Wild rubber from Amazon, organic cotton from Brazil; no ads budget (puts money into materials instead)"),
        ("Pangaia", "thepangaia.com", "Bio-Tech Fashion", "FLWRDWN (wildflower down alternative); seaweed fiber; bio-based nylon; science materials meets streetwear"),
        ("Christy Dawn", "christydawn.com", "Deadstock Fashion", "Dresses made from deadstock fabric; Farm-to-Closet regenerative cotton; Dawn Dress is iconic"),
        ("Whimsy + Row", "whimsyandrow.com", "Zero Waste", "Zero-waste pattern cutting; deadstock fabric; LA-made; sustainable basics; small-batch production"),
        ("Tonlé", "tonle.com", "Zero Waste", "Truly zero-waste fashion — uses every scrap; employs artisans in Cambodia; handmade; circular production"),
        ("People Tree", "peopletree.co.uk", "Fair Trade Fashion", "World's first Fair Trade fashion company; organic cotton; hand-woven textiles; 30+ year pioneer"),
        ("Amour Vert", "amourvert.com", "French Eco", "Plants a tree for every tee sold; made in USA; sustainable fabrics; French name = 'Green Love'"),
        ("For Days", "fordays.com", "Circular Fashion", "Take Back Bag program; buy a tee, return old clothes; everything gets recycled or upcycled; closed loop"),
        ("Outerknown", "outerknown.com", "Sustainable Surf", "Kelly Slater co-founded; ECONYL recycled nylon; S.E.A. Jeans (Socially, Environmentally Advanced)"),
        ("Nudie Jeans", "nudiejeans.com", "Organic Denim", "Free repairs for life; Repair Shops worldwide; 100% organic cotton denim; Swedish sustainability"),
        ("Kotn", "kotn.com", "Egyptian Cotton", "Direct-trade Egyptian cotton basics; funds schools in cotton-growing communities; Canadian brand"),
        ("Frank And Oak", "frankandoak.com", "Eco Canadian", "B Corp; recycled, organic, upcycled materials; Climate+ offset program; Montreal-based; $100M+ revenue"),
    ],

    "Home - Kitchen Appliances": [
        ("KitchenAid", "kitchenaid.com", "Stand Mixers", "Iconic stand mixer in 60+ colors; Artisan model unchanged for decades; wedding registry essential"),
        ("Vitamix", "vitamix.com", "Professional Blenders", "Used by every top restaurant; 10-year warranty; will blend anything; $500+ price justified by durability"),
        ("Breville", "breville.com", "Premium Appliances", "Barista Express espresso machine democratized home espresso; Smart Oven; Australian engineering"),
        ("Instant Pot", "instantpot.com", "Multi-Cooker", "7-in-1 pressure cooker created an obsessive community; 300M+ Facebook group; Amazon #1 selling item"),
        ("Ninja", "ninjakitchen.com", "Kitchen Systems", "Creami ice cream maker went viral; Foodi line; air fryer leader; aggressive marketing vs legacy brands"),
        ("Traeger Grills", "traeger.com", "Pellet Grills", "Invented wood pellet grills; WiFIRE app control; Joe Traeger's 1985 invention; $500M+ revenue"),
        ("Solo Stove", "solostove.com", "Smokeless Fire Pit", "Airflow engineering eliminates 70% of smoke; Snoop Dogg 'giving up smoke' campaign; $400M+ revenue"),
        ("Weber", "weber.com", "Grills", "Kettle grill inventor (1952); $2B+ revenue; American grilling icon; Weber Connect smart technology"),
        ("Ooni", "ooni.com", "Pizza Ovens", "Portable pizza oven reaches 950°F; Kickstarter to $100M+; made restaurant-quality pizza at home accessible"),
        ("Balmuda", "us.balmuda.com", "Japanese Design", "The Toaster adds steam for bakery-quality toast; $300 toaster justified by results; Japanese precision"),
        ("De'Longhi", "delonghi.com", "Italian Espresso", "La Specialista espresso machine; Magnifica auto-espresso; Italian heritage meets home barista culture"),
        ("Nespresso", "nespresso.com", "Coffee Pods", "George Clooney ambassador; Vertuo system; luxury pod coffee; aluminum capsule recycling program"),
        ("Smeg", "smeg.com", "Retro Appliances", "1950s-inspired Italian design; $2,000 refrigerator as kitchen art; Dolce & Gabbana collab; status appliance"),
        ("Big Green Egg", "biggreenegg.com", "Kamado Grill", "Ceramic kamado grill; cult EGGhead community; lasts a lifetime; $1,000+ grills; versatile cooking"),
        ("Thermomix", "thermomix.com", "All-in-One Cooker", "12 appliances in 1; heats, steams, blends, kneads; $1,500; cult following especially in Europe and Australia"),
    ],

    "Home - Air & Water": [
        ("Dyson", "dyson.com", "Air Purifiers", "Purifier Hot+Cool: fan, heater, purifier in one; HEPA H13 filtration; real-time air quality display"),
        ("Levoit", "levoit.com", "Air Purifiers", "Amazon bestselling air purifier brand; Core 300 is $100 workhorse; owned by VeSync; 10M+ units sold"),
        ("Coway", "cowaymega.com", "Air & Water", "South Korea's #1 air/water purifier; Airmega 400 covers 1,560 sq ft; rental model in Korea; design awards"),
        ("Blueair", "blueair.com", "Swedish Air", "HEPASilent technology; Blue Pure series is whisper-quiet; Swedish design; $200M+ revenue; Unilever owned"),
        ("Molekule", "molekule.com", "PECO Technology", "Photo Electrochemical Oxidation destroys pollutants at molecular level (vs HEPA which just traps); unique tech"),
        ("Mila", "milacares.com", "Smart Air Purifier", "App-controlled purifier that learns your patterns; real-time AQI; auto-adjusts; beautiful design"),
        ("Canopy", "getcanopy.co", "No-Mist Humidifier", "No visible mist (evaporative, not ultrasonic); dishwasher-safe; anti-mold tech; aroma add-on kit"),
        ("Berkey", "berkeyfilters.com", "Gravity Filter", "Gravity-fed water purification; used by aid organizations; removes 200+ contaminants; no electricity needed"),
        ("Brita", "brita.com", "Water Filtration", "Most recognized water filter brand; pitcher, faucet, bottle filters; $500M+ revenue; changed tap water trust"),
        ("Hydroviv", "hydroviv.com", "Custom Water Filter", "Customizes filter to YOUR water supply data; uses EPA water quality report; no two filters are the same"),
        ("AquaTru", "aquatru.com", "Countertop RO", "Countertop reverse osmosis purifier; no installation; removes 82 contaminants; certified NSF"),
        ("LifeStraw", "lifestraw.com", "Personal Filter", "Drink directly from rivers/streams; saves lives in developing countries; every purchase funds clean water access"),
        ("ZeroWater", "zerowater.com", "5-Stage Filter", "5-stage filtration vs Brita's 2-stage; comes with TDS meter; removes virtually all dissolved solids"),
        ("Waterdrop", "waterdropfilter.com", "RO System", "Tankless reverse osmosis system; compact; 400GPD; smart faucet with TDS monitor; modern water tech"),
        ("LARQ", "lfrqfrco.com", "Self-Cleaning Bottle", "UV-C light self-cleaning water bottle; purifies water and bottle in 60 seconds; $95 bottle; innovative tech"),
    ],

    "Fitness Equipment": [
        ("Peloton", "onepeloton.com", "Connected Fitness", "Bike+ and Tread; instructor celebrities; 6.7M members; content + community; $44B peak valuation"),
        ("Tonal", "tonal.com", "Smart Strength", "200 lbs of digital weight on a wall-mounted cable system; AI adjusts resistance; personal trainer AI"),
        ("Mirror", "mirror.co", "Home Fitness", "Full-length mirror that streams workouts; Lululemon acquired for $500M; became Lulu Studio"),
        ("Hydrow", "hydrow.com", "Connected Rowing", "Outdoor Reality — filmed on actual water; electromagnetic drag; quieter than Concept2; premium"),
        ("Ergatta", "ergatta.com", "Game-Based Rowing", "Water rower with game-based workouts; 'race' feature; beautiful cherry wood design; gamification"),
        ("NordicTrack", "nordictrack.com", "Home Cardio", "iFIT-powered treadmills and bikes; trainer-controlled incline/speed; Google Maps runs; $1B+ revenue"),
        ("Bowflex", "bowflex.com", "Home Gym", "SelectTech dumbbells adjust from 5-52 lbs; one set replaces 15; space-saving; home gym essential"),
        ("Rogue Fitness", "roguefitness.com", "Gym Equipment", "Official equipment of CrossFit Games; $500M+ revenue; made in Columbus, Ohio; American manufacturing"),
        ("REP Fitness", "repfitness.com", "Home Gym", "Best value home gym equipment; racks, benches, dumbbells at 30-50% less than competitors"),
        ("Titan Fitness", "titanfitness.com", "Budget Gym", "Budget home gym equipment; Rogue quality at half the price; $100M+ revenue; value positioning"),
        ("TRX", "trxtraining.com", "Suspension Training", "Navy SEAL Randy Hetrick invented it from jiu-jitsu belt and parachute webbing; bodyweight anywhere"),
        ("Concept2", "concept2.com", "Rowing Machine", "The rowing machine — used by every Olympic rower, CrossFit box, and home gym; Model D is legendary"),
        ("AssaultBike", "assaultfitness.com", "Air Bike", "The Assault Bike — 'the most brutal cardio machine'; CrossFit staple; unlimited resistance via fan"),
        ("Hyperice", "hyperice.com", "Recovery", "Hypervolt percussion gun used by every pro team; NBA/NFL/MLB partner; recovery as performance"),
        ("Therabody", "therabody.com", "Recovery Tech", "Theragun Elite; percussive therapy inventor; Jason Wersland invented after motorcycle accident; $170M revenue"),
    ],

    "Digital Products & Apps": [
        ("Calm", "calm.com", "Meditation App", "Sleep Stories (Matthew McConaughey, Harry Styles); $2B valuation; Apple App of the Year; 100M+ downloads"),
        ("Headspace", "headspace.com", "Mindfulness App", "Andy Puddicombe's guided meditation; Netflix series; $3B valuation; corporate wellness; animation style"),
        ("Duolingo", "duolingo.com", "Language App", "Green owl mascot has 33M+ TikTok followers; gamified learning; $700M+ revenue; free tier + premium"),
        ("Notion", "notion.so", "Productivity", "All-in-one workspace; killed Evernote's dominance; $10B valuation; template community; second brain tool"),
        ("Canva", "canva.com", "Design Tool", "Democratized design; 130M+ monthly users; $26B valuation; anyone can design like a pro"),
        ("Figma", "figma.com", "Design Tool", "Browser-based design tool; real-time collaboration; Adobe tried to acquire for $20B; design industry standard"),
        ("Slack", "slack.com", "Team Communication", "Changed how teams communicate; $27.7B Salesforce acquisition; killed internal email; #channels revolution"),
        ("Discord", "discord.com", "Community", "Started for gamers, became everyone's community platform; $15B valuation; servers replace forums"),
        ("Spotify", "spotify.com", "Music Streaming", "Spotify Wrapped is the most viral year-end campaign; 600M+ users; $30B+ market cap; podcast empire"),
        ("Audible", "audible.com", "Audiobooks", "Amazon's audiobook platform; 1 credit/month model; 200K+ titles; made audiobooks mainstream"),
        ("Blinkist", "blinkist.com", "Book Summaries", "15-minute book summaries; 5,500+ titles; learn key insights without reading full books; $160M+ revenue"),
        ("Strava", "strava.com", "Fitness Social", "'If it's not on Strava, it didn't happen'; social network for athletes; segments, KOMs; 100M+ users"),
        ("MyFitnessPal", "myfitnesspal.com", "Calorie Tracking", "Largest food database (14M+ foods); barcode scanning; $345M UA acquisition; calorie counting standard"),
        ("Whoop", "whoop.com", "Health Analytics", "No screen, subscription model ($30/mo); strain/recovery/sleep; Patrick Mahomes, LeBron; $3.6B valuation"),
        ("Oura", "ouraring.com", "Health Ring", "Sleep/activity ring; NBA used for COVID detection; $2.55B valuation; most discrete health tracker"),
    ],

    "Skincare - Anti-Aging & Clinical": [
        ("SkinCeuticals", "skinceuticals.com", "Clinical Skincare", "C E Ferulic serum is the gold standard vitamin C; $180/bottle; dermatologist offices worldwide; L'Oréal owned"),
        ("Obagi", "obagi.com", "Professional Skin", "Tretinoin-based Nu-Derm system; prescribed by dermatologists; aggressive anti-aging; clinical results"),
        ("ZO Skin Health", "zoskinhealth.com", "Medical Grade", "Dr. Zein Obagi's second brand; professional-grade skincare; sold through medical offices; growth factor complex"),
        ("iS Clinical", "isclinical.com", "Medical Aesthetics", "Active Serum is a holy grail; pharmaceutical-grade; used by aestheticians; clinical efficacy"),
        ("Jan Marini", "janmarini.com", "Age Intervention", "Bioglycolic line; skin care management system; professional results; dermatologist-recommended"),
        ("PCA Skin", "pcaskin.com", "Professional Peels", "The peel brand; used by 60K+ estheticians; Hyaluronic Acid Boosting Serum; professional treatments at home"),
        ("AlumierMD", "alumiermd.com", "Medical Skincare", "Pharmaceutical-grade skincare sold through physicians; customizable regimens; Canadian brand"),
        ("Revision Skincare", "revisionskincare.com", "Clinical", "Intellishade SPF is the #1 physician-dispensed tinted moisturizer; professional-grade anti-aging"),
        ("Neocutis", "neocutis.com", "Bio-Restorative", "Bio-restorative skincare with proprietary PSP (Processed Skin Cell Proteins); wound healing technology applied to anti-aging"),
        ("DefenAge", "defenage.com", "Defensins", "Uses Age-Repair Defensins to stimulate new skin cell production; patented technology; clinical innovation"),
        ("Augustinus Bader", "augustinusbader.com", "Stem Cell", "Professor's TFC8 technology; $265 cream; Hailey Bieber, Victoria Beckham endorse; backed by stem cell science"),
        ("Environ", "environ.com", "Vitamin A Skincare", "Dr. Des Fernandes' vitamin A step-up system; South African brand; gradually increases retinol tolerance"),
        ("Medik8", "medik8.com", "CSA Philosophy", "Vitamin C, Sunscreen, Vitamin A philosophy; British skincare; Crystal Retinal (stabilized retinaldehyde); clinical results"),
        ("Dr. Barbara Sturm", "drsturm.com", "Blood Cream", "Molecular Cosmetics; 'Vampire Facial' pioneer; $300+ products; A-list celebrity clientele; blood plasma science"),
        ("Murad", "murad.com", "Connected Beauty", "Dr. Howard Murad coined 'inclusive health'; Rapid Age Spot treatment; city skin supplements; science-led"),
    ],

    "Skincare - Natural & Organic": [
        ("Tata Harper", "tataharperskincare.com", "Farm-to-Face Luxury", "100% natural, non-toxic; own farm in Vermont grows ingredients; $90+ products; luxury natural pioneer"),
        ("Indie Lee", "indielee.com", "Clean Skincare", "Founded after being diagnosed with brain tumor linked to environmental toxins; clean beauty advocate"),
        ("Herbivore Botanicals", "herbivorebotanicals.com", "Natural Skincare", "Blue Tansy mask is Instagram's most Instagrammed skincare; 100% natural; Seattle-made"),
        ("Juice Beauty", "juicebeauty.com", "Organic Skincare", "Gwyneth Paltrow was creative director; certified organic farm-to-beauty; clinical results from plants"),
        ("Drunk Elephant", "drunkelephant.com", "Biocompatible", "'Suspicious 6' free philosophy; $845M Shiseido acquisition; TikTok 'smoothie' mixing trend"),
        ("Osea Malibu", "oseamalibu.com", "Seaweed Skincare", "Family-owned 25+ years before going viral; Malibu seaweed; Ocean Cleanser; anti-trend longevity"),
        ("Wildling", "wildling.com", "Gua Sha", "Elevated gua sha practice with stone tools + botanical serums; facial yoga; Chinese medicine meets modern beauty"),
        ("May Lindstrom", "maylindstrom.com", "Ultra Natural", "Handmade in small batches; The Blue Cocoon face balm is cult; $180 products; artisanal skincare"),
        ("Pai Skincare", "paiskincare.com", "Sensitive Skin", "UK brand for ultra-sensitive skin; certified organic; Rosehip BioRegenerate oil; dermatologically tested"),
        ("Dr. Hauschka", "drhauschka.com", "Biodynamic", "Biodynamic farming for skincare since 1967; Rose Day Cream; anthroposophic medicine principles"),
        ("Weleda", "weleda.com", "Anthroposophic", "Skin Food is a $16 cult moisturizer used by supermodels; 100+ year heritage; biodynamic ingredients"),
        ("REN Clean Skincare", "renskincare.com", "Clean Skincare", "Ready Steady Glow tonic; zero waste by 2025 goal; recycled ocean plastic packaging; Unilever owned"),
        ("Vintner's Daughter", "vintnersdaughter.com", "Luxury Face Oil", "Active Botanical Serum ($185) has 22 botanical ingredients; wine country science; one-product brand initially"),
        ("True Botanicals", "truebotanicals.com", "Clinical Natural", "Made Safe certified; Chebula Extreme Cream; outperformed La Mer in clinical trials; Olivia Wilde ambassador"),
        ("Kora Organics", "koraorganics.com", "Organic Beauty", "Miranda Kerr's certified organic skincare; noni fruit superfood; crystal-infused products; Australian"),
    ],

    "Fashion - Denim": [
        ("Levi's", "levi.com", "Heritage Denim", "501 jeans invented 1873; 150+ year heritage; $6B+ revenue; 'buy better, wear longer' sustainability push"),
        ("Wrangler", "wrangler.com", "Western Denim", "Cowboy heritage since 1947; 13MWZ is the original cowboy cut; $2B+ revenue; Kontoor Brands"),
        ("Lee", "lee.com", "American Denim", "Invented the zipper fly jean; Buddy Lee doll; workwear heritage; $1.5B+ revenue"),
        ("AG Jeans", "agjeans.com", "Premium LA Denim", "Adriano Goldschmied 'the godfather of denim'; LA-made premium; $200+ jeans; sustainable denim practices"),
        ("AGOLDE", "agolde.com", "90s Denim", "90s straight-leg revival; the editor/influencer jean; organic cotton; LA-made; owned by Citizens of Humanity"),
        ("Citizens of Humanity", "citizensofhumanity.com", "Luxury Denim", "Jerome Dahan's premium denim; sustainability leader; organic cotton; $250+ jeans"),
        ("FRAME", "frame-store.com", "Franco-American", "Erik Torstensson and Jens Grede (SKIMS co-founder); Le Garcon boyfriend jean; $500M+ revenue"),
        ("MOTHER", "motherdenim.com", "Rock & Roll Denim", "The Hustler ankle fray is 'the' jean; rock & roll meets California; vintage washes; $200+"),
        ("Rag & Bone", "rag-bone.com", "NYC Denim", "British tailoring meets NYC downtown cool; Fit 2 slim jean; Marcus Wainwright's vision"),
        ("DL1961", "dl1961.com", "Eco Denim", "Uses 50% less water and energy; OEKO-TEX certified; family-owned denim expertise; sustainable innovation"),
        ("7 For All Mankind", "7forallmankind.com", "Premium Denim", "Pioneered $200+ jeans in early 2000s; made premium denim mainstream; $600M peak revenue"),
        ("Hudson Jeans", "hudsonjeans.com", "LA Denim", "Peter Kim founded; Barbara high-rise is bestseller; LA-designed; celebrity following"),
        ("Nudie Jeans", "nudiejeans.com", "Swedish Denim", "Free repairs for life at their Repair Shops; 100% organic cotton; Swedish sustainability pioneer"),
        ("G-Star RAW", "g-star.com", "Dutch Denim", "3D denim construction; Pharrell Williams co-owned; raw denim specialists; Amsterdam design"),
        ("Boyish Jeans", "boyish.com", "Vintage Eco Denim", "Named after icons (The Mikey, The Billy); recycled and deadstock denim; LA sustainability"),
    ],

    "Watches & Smartwatches": [
        ("Apple Watch", "apple.com/watch", "Smartwatch", "40%+ smartwatch market share; ECG, fall detection save lives; Ultra for extreme sports; $30B+ segment revenue"),
        ("Samsung Galaxy Watch", "samsung.com", "Smartwatch", "Wear OS; body composition analysis; BIA sensor; sleep coaching; best Android smartwatch"),
        ("Garmin", "garmin.com", "GPS Watch", "Fenix 8 dominates outdoor; $5B+ revenue; 32GB music; solar charging; multiband GPS; military-grade"),
        ("Whoop", "whoop.com", "Fitness Band", "No screen; $30/mo subscription; strain/recovery/sleep scores; pro athletes swear by it; $3.6B valuation"),
        ("Oura Ring", "ouraring.com", "Health Ring", "Gen 3 ring; sleep/activity/readiness; temperature trend; $6/mo subscription; $2.55B valuation"),
        ("Polar", "polar.com", "Heart Rate Pioneer", "Invented the wireless heart rate monitor; Vantage V3; 45+ years of sports science; Finnish precision"),
        ("Suunto", "suunto.com", "Outdoor Watch", "Finnish outdoor watches; Suunto 9 Peak Pro; military-grade durability; 120+ hours GPS; dive computers"),
        ("Amazfit", "amazfit.com", "Budget Smartwatch", "Zepp Health; GTR 4 at $200 rivals $500+ watches; blood oxygen, GPS; best value smartwatch"),
        ("Fossil", "fossil.com", "Fashion Watch", "Licensed brands (Michael Kors, Diesel, Emporio Armani); Gen 6 smartwatch; $1.5B+ revenue"),
        ("Tissot", "tissotwatches.com", "Swiss Affordable", "PRX line revived affordable Swiss mechanical watches; $500 automatic; Swatch Group; sporty elegance"),
        ("Hamilton", "hamiltonwatch.com", "Movie Watches", "Featured in 500+ Hollywood films; Khaki Field is icon; American heritage, Swiss made; Swatch Group"),
        ("Seiko", "seikowatches.com", "Japanese Precision", "Grand Seiko rivals Swiss at fraction of price; Spring Drive movement; Prospex dive watches; $2B+ revenue"),
        ("Casio G-Shock", "gshock.com", "Tough Watch", "Dropped from 10m and still works; 40+ year heritage; CasiOak (GA-2100) went viral; $200M+ G-Shock revenue"),
        ("Timex", "timex.com", "Classic American", "Weekender is $35 icon; 'takes a licking and keeps on ticking'; 170+ year heritage; most accessible watch brand"),
        ("Swatch", "swatch.com", "Swiss Pop", "Saved Swiss watch industry in the '80s; MoonSwatch x Omega collab crashed servers worldwide; $1B+ revenue"),
    ],

    "Snacks - Healthy & Protein": [
        ("RXBAR", "rxbar.com", "Whole Food Bars", "Ingredient list IS the packaging design; 'No B.S.'; Kellogg's acquired for $600M; egg white protein"),
        ("KIND", "kindsnacks.com", "Nut Bars", "See-through wrapper shows whole nuts; $5B Mars acquisition; 'ingredients you can see and pronounce'"),
        ("Clif Bar", "clifbar.com", "Energy Bars", "Named after founder's dad Clifford; organic; employee-owned until $2.9B Mondelēz acquisition; adventure fuel"),
        ("Perfect Bar", "perfectbar.com", "Fresh Bars", "Refrigerated protein bars; fresh peanut butter base; $200M+ revenue; sold from a cooler, not a shelf"),
        ("GoMacro", "gomacro.com", "Plant Bars", "Mother-daughter founded after cancer diagnosis; plant-based, organic; macrobiotic principles"),
        ("Barebells", "barebells.com", "Protein Bars", "Swedish protein bars that taste like candy; 20g protein, no added sugar; viral on TikTok; premium"),
        ("Built Bar", "builtbar.com", "Protein Bars", "Real chocolate-covered protein bars; 130 cal, 17g protein; unique texture; $100M+ revenue"),
        ("Quest Nutrition", "questnutrition.com", "Keto Protein", "Quest Bar has 20g protein, 1g sugar; keto-friendly; $1B+ revenue; Simply Good Foods acquired"),
        ("One Bar", "one1brands.com", "Protein Bars", "1g sugar, 20g protein; birthday cake flavor is bestseller; Hershey's acquired"),
        ("Larabar", "larabar.com", "Fruit & Nut", "Each bar is 2-9 ingredients (just dates + nuts); no added sugar; General Mills owned; simple clean fuel"),
        ("Epic Provisions", "epicbar.com", "Meat Bars", "Grass-fed beef, bison, venison bars; animal welfare standards; General Mills acquired; paleo-friendly"),
        ("Chomps", "chomps.com", "Meat Sticks", "Whole30 approved; grass-fed beef sticks; $200M+ revenue; bootstrapped; no outside funding"),
        ("Country Archer", "countryarcher.com", "Jerky", "Grass-fed jerky and meat sticks; craft jerky revival; sold in every major retailer; quality protein"),
        ("Wilde Chips", "wildechips.com", "Protein Chips", "Chicken breast protein chips; 10g protein; Shark Tank Mark Cuban investment; unique category creation"),
        ("Whisps", "whisps.com", "Cheese Crisps", "100% real cheese baked into crisps; keto, gluten-free; $100M+ revenue; Costco bestseller"),
    ],

    "Miscellaneous DTC 2": [
        ("Brooklinen", "brooklinen.com", "Luxury Sheets", "Kickstarter to $200M+ revenue; luxury sheets 50% below retail; 'Really, Really Good Sheets' tagline"),
        ("Ruggable", "ruggable.com", "Washable Rugs", "Machine-washable 2-piece rug system; solved 'rugs are impossible to clean' problem; $200M+ revenue"),
        ("Calpak", "calpaktravel.com", "Travel Accessories", "Luka Mini Duffel went TikTok viral; affordable fashion luggage ($50-200); packing cubes queen"),
        ("Ooni", "ooni.com", "Pizza Ovens", "Portable pizza oven reaching 950°F; Kickstarter to $100M+ revenue; made Neapolitan pizza at home real"),
        ("BlendJet", "blendjet.com", "Portable Blender", "10M+ sold; USB-rechargeable; $20 portable blender; TikTok recipe content drives sales; 50% margins"),
        ("Nugget", "nuggetcomfort.com", "Play Couch", "Kids play couch; 100K+ waitlist; limited color drops; $100M+ revenue; parent community cult status"),
        ("Solo Stove", "solostove.com", "Smokeless Fire Pit", "Airflow engineering = no smoke; Snoop Dogg 'giving up smoke' ad campaign; $400M+ revenue"),
        ("Ember", "ember.com", "Temperature Mug", "App-controlled mug keeps coffee at exact temp; $130; Apple Store featured; the smart mug category creator"),
        ("Fellow", "fellowproducts.com", "Coffee Equipment", "Stagg EKG kettle is the pour-over standard; SF specialty coffee aesthetic; design award winner"),
        ("Peak Design", "peakdesign.com", "Camera Gear", "$32M+ Kickstarter raised; innovative quick-release system; lifetime guarantee; travel tripod"),
        ("Moment", "shopmoment.com", "Mobile Photo", "Mobile lenses rivaling DSLRs; built creator community; content creator gear ecosystem; $30M+ revenue"),
        ("Loop Earplugs", "loopearplugs.com", "Noise Reduction", "Stylish earplugs that look like jewelry; reduce noise without muffling; $100M+ revenue; concert essential"),
        ("Bellroy", "bellroy.com", "Slim Carry", "Slim your wallet philosophy; hidden features; Australian design; expanded to bags, phone cases, tech"),
        ("Ridge Wallet", "ridgewallet.com", "Metal Wallet", "#1 podcast-advertised product; titanium RFID blocking; 'ditch the bulge'; $100M+ revenue; bootstrapped"),
        ("Anker", "anker.com", "Charging", "Amazon-first to $2B+; PowerCore, Soundcore; trust = reviews strategy; category king in charging"),
        ("Dyson", "dyson.com", "Engineering", "5,127 prototypes; Airwrap year-long waitlists; bladeless fans; Supersonic hair dryer; $7.7B revenue"),
        ("Therabody", "therabody.com", "Recovery", "Invented percussion therapy category; Theragun changed recovery; $170M revenue; used by every pro team"),
        ("Hydro Flask", "hydroflask.com", "Water Bottles", "The VSCO girl water bottle; TempShield insulation; became Gen Z cultural icon; sticker culture"),
        ("Stanley", "stanley1913.com", "Drinkware", "100-year brand went from $70M to $750M via TikTok Quencher virality; women resurrected a men's brand"),
        ("YETI", "yeti.com", "Premium Outdoor", "Built brand on hunting/fishing then crossed mainstream; $1.6B+ revenue; coolers as lifestyle status symbols"),
    ],

    "Wellness - Sleep Tech": [
        ("Eight Sleep", "eightsleep.com", "Smart Mattress", "Pod cover heats/cools your bed; used by 200+ pro athletes; 'the Tesla of sleep'; $500M+ valuation; AI sleep coaching"),
        ("Pillow Cube", "pillowcube.com", "Side Sleeper Pillow", "Solved side-sleeping with a cube-shaped pillow; viral TikTok ads; '$50 pillow that fixes your neck'"),
        ("Coop Home Goods", "coophomegoods.com", "Adjustable Pillow", "Adjustable fill shredded memory foam pillow; Amazon #1 pillow for years; customize firmness yourself"),
        ("Sleep Number", "sleepnumber.com", "Smart Beds", "Each side adjusts firmness individually (couples); SleepIQ technology tracks and adjusts; $2B+ revenue"),
        ("Tempur-Pedic", "tempurpedic.com", "Memory Foam", "Originally developed by NASA; TEMPUR material adapts to body; premium ($2K-5K); owned by Tempur Sealy"),
        ("Manta Sleep", "mantasleep.com", "Sleep Masks", "Modular eye cups with zero pressure on eyes; Kickstarter origin; best-selling premium sleep mask"),
        ("Dodow", "mydodow.com", "Sleep Aid", "Light metronome device that guides breathing to fall asleep; no drugs; 500K+ users; French invention"),
        ("Hatch", "hatch.co", "Sunrise Alarm", "Restore 2 is sound machine + sunrise alarm + wind-down light; app-controlled; replaced 3 bedside devices"),
        ("Loftie", "byloftie.com", "Alarm Clock", "Phone-free bedroom alarm clock; nature sounds, white noise, stories; reduces phone dependency before bed"),
        ("BedJet", "bedjet.com", "Bed Climate", "Forced air climate system for beds; heating and cooling; dual-zone for couples; $400 alternative to Pod"),
        ("ChiliSleep", "chilisleep.com", "Bed Cooling", "Water-based mattress pad that cools to 55°F or heats to 115°F; Dock Pro system; $500-700"),
        ("Molecule", "onmolecule.com", "Recovery Sleep", "Mattress with Air-Engineered foam for athletes; recovery-focused sleep; cooling technology"),
        ("Bear Mattress", "bearmattress.com", "Recovery Mattress", "Celliant cover clinically proven to increase blood oxygen; athlete-focused; NFL/NBA partnerships"),
        ("Nolah", "nolahmattress.com", "Air Foam Mattress", "AirFoam = 4x more pressure relief than memory foam; eco-friendly; 10x more durable; competitive pricing"),
        ("Birch Living", "birchliving.com", "Natural Mattress", "Helix's organic line; GOTS certified; natural latex + organic wool + cotton; $1,300 for true natural sleep"),
    ],

    "Wellness - Women's Health": [
        ("Love Wellness", "lovewellness.com", "Women's Wellness", "Lo Bosworth founded; vaginal health supplements (The Killer, Good Girl Probiotics); broke taboo"),
        ("Rae Wellness", "raewellness.co", "Target Wellness", "Affordable ($15) women's vitamins and supplements at Target; pre-natal, mood, energy; accessible wellness"),
        ("Ritual", "ritual.com", "Prenatal & Vitamins", "Visible capsule; Essential Prenatal became #1 OB-GYN recommended prenatal; 'the visible supply chain'"),
        ("Natalist", "natalist.com", "Fertility", "Fertility and pregnancy tests with modern design; ovulation tests, prenatal vitamins; TTC community"),
        ("Stix", "getstix.co", "Pregnancy Tests", "Discreet, modern pregnancy and UTI tests shipped to your door; stigma-free health testing"),
        ("Everlywell", "everlywell.com", "At-Home Testing", "FDA-authorized at-home lab tests (food sensitivity, thyroid, STI); $500M+ valuation; Shark Tank"),
        ("LetsGetChecked", "letsgetchecked.com", "Home Health Tests", "STI, fertility, cholesterol tests at home; nurse consultations; $500M+ valuation; telehealth add-on"),
        ("Modern Fertility", "modernfertility.com", "Fertility Testing", "Fertility hormone test for $159 (vs $1,500+ at clinic); Ro acquired; empowering women with data"),
        ("Perelel", "perelel.com", "Trimester Vitamins", "OB-GYN created vitamins by trimester (not one-size-fits-all pregnancy); 1st, 2nd, 3rd trimester specific packs"),
        ("Needed", "thisisneeded.com", "Prenatal Nutrition", "Whole-food prenatal optimizing 25+ nutrients; created by functional nutritionist; fills prenatal gaps"),
        ("Loom", "wearloom.com", "Pelvic Health", "Pelvic floor strengthening device + app; postpartum recovery; physical therapy made accessible at home"),
        ("Elvie", "elvie.com", "Women's Tech", "Silent wearable breast pump + pelvic floor trainer; in-bra pumping freedom; $100M+ revenue"),
        ("Frida Mom", "frida.com", "Postpartum Care", "Honest postpartum care (perineal foam, cooling pads, breast care); viral Super Bowl ad showing real birth recovery"),
        ("Willow", "willowpump.com", "Breast Pump", "In-bra pump with leak-proof bags; pump while doing anything; total freedom; 2 patents on design"),
        ("Canopie", "mycanopie.com", "Perinatal Mental Health", "Maternal mental health therapy + support; 1 in 5 mothers affected; specialized perinatal therapists"),
    ],

    "Wellness - Mental Health": [
        ("BetterHelp", "betterhelp.com", "Online Therapy", "Largest online therapy platform; 30K+ licensed therapists; $800M+ revenue; made therapy accessible remotely"),
        ("Talkspace", "talkspace.com", "Text Therapy", "Text, audio, video therapy; Michael Phelps ambassador; IPO'd; employer benefits integration"),
        ("Cerebral", "cerebral.com", "Online Psychiatry", "Prescriptions + therapy online; $5B valuation; medication management for anxiety, depression; rapid scale"),
        ("Calm", "calm.com", "Meditation", "Sleep Stories voiced by Harry Styles, Matthew McConaughey; $2B valuation; 100M+ downloads; Apple App of Year"),
        ("Headspace", "headspace.com", "Mindfulness", "Andy Puddicombe's guided meditation; Netflix series; $3B valuation; animations make meditation approachable"),
        ("Woebot Health", "woebothealth.com", "AI Therapy", "AI chatbot using CBT; FDA breakthrough device for substance use; 2M+ users; Stanford-developed"),
        ("Happify", "happify.com", "Mental Wellness App", "Science-based activities to reduce stress; positive psychology; used by employers for workforce wellbeing"),
        ("Sanvello", "sanvello.com", "CBT App", "Clinically validated CBT/DBT tools; mood tracking; health plan coverage; UnitedHealth Group acquired"),
        ("Brightside Health", "brightside.com", "Depression Care", "Combines therapy + psychiatry + medication; clinical outcomes 3x better than industry average"),
        ("Ginger", "ginger.com", "On-Demand Mental Health", "Text-based coaching escalating to therapy/psychiatry; merged with Headspace; enterprise mental health"),
        ("Spring Health", "springhealth.com", "Employer Mental Health", "Precision mental health platform for employers; AI matches to right care; $2.5B valuation"),
        ("Lyra Health", "lyrahealth.com", "Workforce Mental Health", "Mental health benefits for companies; 15M+ members; evidence-based matching; eBay, Morgan Stanley clients"),
        ("Two Chairs", "twochairs.com", "Matched Therapy", "AI matches you with the right therapist from day 1; outcome tracking; SF Bay Area + virtual; quality-first"),
        ("Alma", "helloalma.com", "Therapist Network", "Connects you with therapists who take your insurance; 15K+ providers; simplified mental health access"),
        ("NOCD", "nocd.com", "OCD Treatment", "Specialized OCD therapy (ERP — Exposure Response Prevention); first app focused specifically on OCD; $100M+ raised"),
    ],

    "Fashion - Athletic Shoes": [
        ("Nike", "nike.com", "Athletic Footwear", "$51B+ revenue; Just Do It is most recognized slogan; Air Jordan $5B+ alone; SNKRS app creates hype"),
        ("Adidas", "adidas.com", "Athletic Footwear", "Boost technology; Yeezy partnership was $2B+ until split; Samba and Gazelle retro revival; $24B revenue"),
        ("New Balance", "newbalance.com", "Dad Shoes to Cool", "990 went from 'dad shoe' to fashion icon; JJJJound, Aimé Leon Dore collabs; 'the anti-Nike'; $6B+ revenue"),
        ("ASICS", "asics.com", "Running Shoes", "Gel-Kayano is #1 stability shoe; 75+ year Japanese heritage; 'Anima Sana In Corpore Sano' (healthy mind, body)"),
        ("Brooks Running", "brooksrunning.com", "Running Shoes", "Ghost 15 is #1 running shoe in specialty retail; 'Run Happy' ethos; Berkshire Hathaway owned"),
        ("Saucony", "saucony.com", "Running Heritage", "Endorphin Pro racing shoe competes with Nike Vaporfly; Jazz Original is retro icon; Wolverine Worldwide"),
        ("HOKA", "hoka.com", "Maximalist Running", "Oversized midsole trend-setter; Bondi and Clifton bestsellers; $1.8B revenue; ultrarunner to fashion crossover"),
        ("On Running", "on.com", "Swiss Innovation", "CloudTec cushioning; Roger Federer investor; IPO'd at $8B+; fastest-growing running brand; Swiss engineering"),
        ("Salomon", "salomon.com", "Trail Running", "XT-6 shoe crossed from trail to fashion; Advanced Chassis; French Alps heritage; Amer Sports owned"),
        ("Merrell", "merrell.com", "Hiking Shoes", "Moab hiking shoe is 'Mother Of All Boots'; 40M+ pairs sold; trail-to-town versatility"),
        ("Keen", "keenfoot.com", "Outdoor Shoes", "Sandal with a toe bumper created a new category; Newport sandal; Portland-based outdoor"),
        ("Birkenstock", "birkenstock.com", "Heritage Sandals", "250+ year heritage; Arizona sandal is ubiquitous; IPO'd at $8.6B; went from hippie to Hermès-level luxury"),
        ("Crocs", "crocs.com", "Casual Shoes", "From 'ugly' to $4B+ revenue via collaborations (Bad Bunny, Justin Bieber, Balenciaga); Jibbitz charms"),
        ("Vans", "vans.com", "Skate Shoes", "Off The Wall since 1966; Old Skool side stripe is iconic; $3.5B+ revenue; VF Corp; skate culture legend"),
        ("Converse", "converse.com", "Classic Sneakers", "Chuck Taylor All Star — 1B+ pairs sold; the most iconic sneaker ever made; Nike owned; cultural staple"),
    ],

    "Beauty - Haircare Expanded": [
        ("Dyson", "dyson.com", "Hair Tools", "Supersonic dryer ($430) has year-long waitlists; Airwrap ($600) does curls/waves/dry; engineering meets beauty"),
        ("ghd", "ghd.com", "Hair Styling", "Gold styler is salon professional standard; Helios dryer; British brand; $500M+ revenue; used by every hairdresser"),
        ("T3 Micro", "t3micro.com", "Hair Tools", "Cura Luxe dryer with IonAir technology; SinglePass straightener; tech-forward styling tools"),
        ("Bio Ionic", "bioionic.com", "Mineral Tech", "NanoIonic mineral-infused styling tools; 10X dryer; moisturizing heat technology; salon-grade"),
        ("Revlon", "revlon.com", "One-Step Dryer", "One-Step Volumizer brush dryer sold 10M+ units; $50 tool that dried and styled simultaneously; game changer"),
        ("Olaplex", "olaplex.com", "Bond Repair", "Patented bis-aminopropyl diglycol dimaleate molecule; salon treatment in a bottle; $15B IPO valuation"),
        ("K18", "k18hair.com", "Peptide Repair", "Patented bioactive peptide reverses hair damage in 4 minutes; disrupted entire salon treatment market"),
        ("Moroccanoil", "moroccanoil.com", "Argan Oil", "Blue bottle argan oil treatment pioneered the hair oil category; $500M+ revenue; salon-to-consumer"),
        ("Oribe", "oribe.com", "Luxury Haircare", "Dry Texturizing Spray is cult; gold packaging; scent alone makes people obsessed; Lauder acquired"),
        ("Bumble and Bumble", "bumbleandbumble.com", "NYC Haircare", "Surf Spray created 'beachy waves' category; NYC salon heritage; Estée Lauder owned"),
        ("Ouai", "theouai.com", "Influencer Hair", "Jen Atkin (celebrity hairstylist) brand; Wave Spray bestseller; P&G acquired; social media-first"),
        ("Color Wow", "colorwowhair.com", "Color Care", "Root Cover Up powder is genius for between-salon visits; Dream Coat anti-humidity spray went viral"),
        ("Redken", "redken.com", "Pro Haircare", "Acidic Bonding Concentrate line rivals Olaplex at salon level; NYC-born; L'Oréal Professional"),
        ("Pureology", "pureology.com", "Color-Safe Vegan", "100% vegan color care; sulfate-free pioneer; ZeroSulfate shampoo; concentrated formulas last longer"),
        ("UNITE Hair", "unitehair.com", "Salon Professional", "7SECONDS leave-in is salon gold; BLONDA shampoo; BOOSTA volumizing spray; salon-exclusive quality"),
    ],

    "Home - Bedding & Linens Expanded": [
        ("Casper", "casper.com", "Mattress", "The OG bed-in-a-box; 100-night trial pioneer; subway ads everywhere; showed DTC the playbook; IPO'd"),
        ("Purple", "purple.com", "GelFlex Grid", "Hyper-Elastic Polymer; raw egg test video = 1B+ views; science + humor; unique material = unique brand"),
        ("Helix Sleep", "helixsleep.com", "Quiz Mattress", "Sleep quiz matches you to ideal mattress from 12+ models; personalization in commodity category"),
        ("Saatva", "saatva.com", "Luxury DTC Mattress", "White-glove delivery + old mattress removal; targets affluent buyers; $500M+ revenue; eco-friendly luxury"),
        ("Leesa", "leesa.com", "Social Impact Mattress", "Donates 1 mattress for every 10 sold; 40K+ mattresses donated; B Corp; foam + pocket spring hybrid"),
        ("Tuft & Needle", "tuftandneedle.com", "OG DTC Mattress", "Two engineers' response to $3,000 mattresses; T&N Adaptive Foam; merged with Serta; pioneer"),
        ("Nectar", "nectarsleep.com", "365-Night Trial", "Longest trial period + forever warranty; aggressive marketing; memory foam; $1B+ revenue; Resident"),
        ("DreamCloud", "dreamcloudsleep.com", "Luxury Hybrid", "Cashmere-blend cover hybrid at $800; luxury feel at disruptor price; Resident Home brand"),
        ("Brooklyn Bedding", "brooklynbedding.com", "Factory Direct", "Own their factory; Signature hybrid at $1,000; 'the internet's favorite mattress'; Titan for heavy people"),
        ("WinkBeds", "winkbeds.com", "Handcrafted Hybrid", "Handcrafted in the USA; designed for different body types; Plus model for 300+ lbs; high-quality materials"),
        ("GhostBed", "ghostbed.com", "Cooling Mattress", "Ghost Ice fabric is cool to the touch; Venus Williams ambassador; 101-night trial; cooling technology focus"),
        ("Zinus", "zinus.com", "Budget Mattress", "Amazon bestselling mattress brand; $200 memory foam mattress; green tea infused; value leader"),
        ("Linenly", "linenly.com.au", "French Flax Linen", "Australian French flax linen sheets; naturally temperature-regulating; gets softer with every wash"),
        ("Piglet in Bed", "pigletinbed.com", "Stonewashed Linen", "UK linen specialist; naturally wrinkled look is the style; no ironing needed; earthy color palette"),
        ("Bedfolk", "bedfolk.com", "Considered Bedding", "British DTC bedding; honest pricing; 'less, but better' philosophy; cotton + linen specialists"),
    ],

    "Clothing - Outdoor & Adventure": [
        ("Patagonia", "patagonia.com", "Eco Outdoor", "Donated entire company to fight climate change; Worn Wear program; $1.5B revenue; most trusted outdoor"),
        ("Arc'teryx", "arcteryx.com", "Technical Outdoor", "GORE-TEX mastery; military special forces use; $1B+ revenue; acquired by Amer Sports for premium"),
        ("The North Face", "thenorthface.com", "Outdoor Heritage", "Nuptse puffer became streetwear icon; $3.6B revenue; VF Corp; exploration meets everyday"),
        ("Columbia", "columbia.com", "Outdoor Value", "Omni-Heat reflective technology; $3.6B revenue; Portland-based; family-owned (Boyle family); great value"),
        ("REI Co-op", "rei.com", "Outdoor Retail", "Consumer co-op with 23M+ members; #OptOutside closes on Black Friday; own-brand gear rivals premium"),
        ("Marmot", "marmot.com", "Mountain Gear", "PreCip rain jacket is legendary; UC Santa Cruz dorm room origin; $500M+ revenue; performance outdoor"),
        ("Black Diamond", "blackdiamondequipment.com", "Climbing Gear", "Employee-owned; BD headlamp is every hiker's essential; Utah-based; climbing heritage since 1989"),
        ("Outdoor Research", "outdoorresearch.com", "Seattle Outdoor", "Infinite Guarantee on products; Helium rain jacket; glove specialists; made for climbers and alpinists"),
        ("Rab", "rab.equipment", "British Mountain", "Sheffield, UK mountain gear since 1981; Microlight Alpine jacket; down specialist; alpine heritage"),
        ("Mountain Hardwear", "mountainhardwear.com", "Technical Gear", "Ghost Whisperer ultralight down jacket; climbing and skiing focus; MHW brand beloved by alpinists"),
        ("prAna", "prana.com", "Yoga Outdoor", "Sustainable outdoor + yoga apparel; Fair Trade; hemp blends; Boulder, Colorado lifestyle"),
        ("Cotopaxi", "cotopaxi.com", "Colorful Outdoor", "Del Día one-of-a-kind colorways from factory remnants; B Corp; Questival adventure races"),
        ("Kühl", "kuhl.com", "Rugged Outdoor", "Founded by climber Kevin Boyle; ARTILEKT technology; Salt Lake City; rugged but refined outdoor apparel"),
        ("Outdoor Voices", "outdoorvoices.com", "Recreation", "'Doing Things' philosophy; Exercise Dress became iconic; exercise for fun not competition"),
        ("Fjällräven", "fjallraven.com", "Swedish Heritage", "Kånken backpack = global icon; G-1000 fabric is self-repairable; 60+ year Arctic Fox heritage"),
    ],

    "Snacks & Beverages - Expanded 2": [
        ("LMNT", "drinklmnt.com", "Electrolytes", "No sugar, 1,000mg sodium; Robb Wolf co-founded; every major podcast sponsors it; keto community favorite"),
        ("Liquid Death", "liquiddeath.com", "Canned Water", "Water with heavy metal branding; $1.4B valuation; merch outsells water; 'Murder Your Thirst'"),
        ("Celsius", "celsius.com", "Fitness Energy", "Clinically proven metabolism boost; $1.3B revenue; #3 energy brand behind Monster and Red Bull"),
        ("GHOST", "ghostlifestyle.com", "Licensed Flavors", "Sour Patch Kids, Warheads, Chips Ahoy protein/energy; transparent labels; gaming/lifestyle crossover"),
        ("Ryse", "rysesupps.com", "Licensed Supps", "Kool-Aid, Ring Pop licensed flavors; $200M+ revenue; taste innovation in supplements; 'fuel your greatness'"),
        ("3D Energy", "3denergy.com", "Energy Drink", "Christian Guzman's energy drink; clean aesthetics; gym lifestyle; social media-driven growth"),
        ("Alani Nu", "alaninu.com", "Women's Energy", "Katy Hearn's brand; $200M+ revenue; energy drinks targeting women specifically (rare in energy market)"),
        ("Bucked Up", "buckedup.com", "Energy & Supps", "Deer antler velvet pre-workout (unique ingredient); aggressive marketing; Utah-based; $200M+ revenue"),
        ("C4 Energy", "cellucor.com", "Pre-Workout Energy", "#1 pre-workout brand globally; Starburst and Skittles flavors; energy drink expansion; Nutrabolt owned"),
        ("Reign", "reignbodyfuel.com", "Performance Energy", "Monster's fitness-focused energy line; BCAAs, CoQ10, B vitamins; 300mg caffeine; gym-targeted"),
        ("ZOA Energy", "zoaenergy.com", "Clean Energy", "Dwayne Johnson's brand; natural caffeine from green tea; 'healthy warrior' positioning; $100M+ revenue"),
        ("Hint Water", "drinkhint.com", "Flavored Water", "Fruit-infused water, no sugar, no sweeteners; founded by Kara Goldin; $150M+ revenue; just water + fruit"),
        ("Spindrift", "drinkspindrift.com", "Real Fruit Sparkling", "Only sparkling water made with real squeezed fruit; you can see pulp; anti-LaCroix positioning"),
        ("Topo Chico", "topochicousa.com", "Mexican Mineral Water", "Mexican mineral water with cult following; Coca-Cola acquired; bar/restaurant essential; OG sparkling"),
        ("Waterloo Sparkling", "waterloowater.com", "Austin Sparkling", "Austin-born sparkling water; bold fruit flavors; grew to $100M+ competing against LaCroix and Perrier"),
    ],

    "Clothing - Basics & Essentials": [
        ("Uniqlo", "uniqlo.com", "Japanese Basics", "Heattech and AIRism technology innovations; $21B+ revenue; 'LifeWear' philosophy; basics perfected"),
        ("Everlane", "everlane.com", "Transparent Fashion", "'Radical Transparency' shows factory and markup; ethical factories; $100M+ revenue; basics with a conscience"),
        ("Pact", "wearpact.com", "Organic Cotton", "GOTS certified organic cotton basics; Fair Trade factory; $50M+ revenue; earth-friendly essentials"),
        ("Alternative Apparel", "alternativeapparel.com", "Soft Basics", "Eco-Tri-Blend fabric is whisper-soft; 25+ year heritage; sustainable basics; Hanes acquired"),
        ("Los Angeles Apparel", "losangelesapparel.com", "LA Made", "Dov Charney's post-American Apparel brand; Made in USA; blank wholesale + retail; garment district heritage"),
        ("Kotn", "kotn.com", "Egyptian Cotton", "Direct-trade Egyptian cotton; funds schools in farming communities; Canadian brand; ethical supply chain"),
        ("Colorful Standard", "colorfulstandard.com", "Colorful Basics", "41 colors of organic cotton basics; each piece dyed in same color; Danish; capsule wardrobe concept"),
        ("Asket", "asket.com", "Permanent Collection", "No seasonal collections, no sales — 'The Pursuit of Less'; impact receipt shows environmental cost per garment"),
        ("Sunspel", "sunspel.com", "British Basics", "James Bond's t-shirt brand (Daniel Craig in Casino Royale); 160+ year heritage; Sea Island cotton"),
        ("Entireworld", "theentireworld.com", "Color System", "Scott Sternberg (ex-Band of Outsiders) built color-coded basics system; playful numbering; organic cotton"),
        ("Buck Mason", "buckmason.com", "Men's Essentials", "Venice Beach; Curved Hem Tee hero product; 'less, better' philosophy; one of each essential perfected"),
        ("Marine Layer", "marinelayer.com", "Soft Tees", "Re-Spun program recycles old tees into new fabric; 'absurdly soft' tagline; SF heritage"),
        ("Vuori", "vuori.com", "Performance Casual", "Encinitas surf culture; SoftBank invested $400M at $4B; fills the men's activewear gap; versatile"),
        ("Faherty", "faherty.com", "Coastal Style", "Twin brothers; sun-washed, surf-inspired; Faherty Sunwashed proprietary fabric; Hamptons meets SoCal"),
        ("Alex Mill", "alexmill.com", "Modern Basics", "J.Crew alumni; garment-dyed, washed-in softness; $50-150 basics; 'makes getting dressed easy'"),
    ],

    "Beauty - Men's Skincare Expanded": [
        ("Clinique for Men", "clinique.com", "Men's Skincare", "First major prestige brand with dedicated men's line; allergy tested; 3-step system adapted for men"),
        ("Kiehl's", "kiehls.com", "Apothecary Men's", "Facial Fuel energizing scrub and moisturizer; 170+ year NYC apothecary heritage; credible for male shoppers"),
        ("Lab Series", "labseries.com", "Clinical Men's", "Science-backed men's skincare since 1987; Anti-Age Max LS moisturizer; serious skincare for serious men"),
        ("Bulldog Skincare", "bulldogskincare.com", "Natural Men's", "B Corp men's skincare with natural ingredients; affordable ($8-12); British brand; Edgewell acquired"),
        ("Tiege Hanley", "tifrege.com", "Subscription Men's", "Complete skincare system in monthly box; AM/PM moisturizers, eye cream, scrub; $29/month simplicity"),
        ("Cardon", "carfrdon.com", "Korean Men's", "K-beauty inspired men's skincare; cactus extract hydration; simple 2-3 product routines for men"),
        ("Aesop", "aesop.com", "Luxury Unisex", "Parrot Aloe cream is cult; In Two Minds cleanser; gender-neutral luxury; $2.5B L'Oréal acquisition"),
        ("ASYSTEM", "asystem.com", "Performance Men's", "Radical Relief pain patches and skincare; targets 'high-performance men'; system approach"),
        ("Malin + Goetz", "malinandgoetz.com", "Apothecary", "NYC apothecary; Rum body wash is cult scent; Vitamin E moisturizer; gender-neutral; unisex luxury"),
        ("Rugged & Dapper", "ruggedanddapper.com", "Natural Men's", "Age Defense face moisturizer SPF; Amazon bestseller in men's; plant-based; affordable premium"),
        ("Brickell Men's", "brickellmens.com", "Natural Premium", "Organic and natural men's skincare; founded in Miami; Daily Essential Face Moisturizer bestseller"),
        ("Buttah Skin", "buttahskin.com", "Melanin Men's", "Dorion Renaud founded for Black men's skin; shea-butter based; addresses specific melanin skin needs"),
        ("The Ordinary", "theordinary.com", "Budget Clinical", "Same $5-10 clinical ingredients work for all genders; Niacinamide 10% became universal skincare staple"),
        ("CeraVe", "cerave.com", "Derm Recommended", "3 ceramides; $15 moisturizer recommended by every dermatologist on TikTok; no-nonsense approach"),
        ("Jack Black", "getjackblack.com", "Men's Premium", "Double-Duty SPF 20 moisturizer is a men's cult classic; performance ingredients; Edgewell acquired"),
    ],

    "Pets - Expanded 2": [
        ("BarkBox", "barkbox.com", "Dog Subscription", "Themed monthly boxes; 2M+ subscribers; Super Chewer for aggressive chewers; BARK IPO'd; $500M+"),
        ("Wild One", "wildone.com", "Modern Pet", "Pet products that look like design objects; matching sets; harness, leash, carrier in coordinating colors"),
        ("Fi Collar", "tryfi.com", "Smart Collar", "GPS + LTE dog collar; tracks activity, sleep, escapes; Series 3; know where your dog is always"),
        ("Whistle", "whistle.com", "Pet Tracker", "GPS health + location monitor; vet chat built in; Mars Petcare owned; activity tracking for pets"),
        ("PrettyLitter", "prettylitter.com", "Health Litter", "Color-changing litter detects UTIs, kidney issues; silica crystal; subscription; $100M+ revenue"),
        ("Litter Robot", "litter-robot.com", "Auto Litter", "Self-cleaning litter box; $700 but saves hours; WiFi app; cult cat owner following; $100M+ revenue"),
        ("Farmer's Dog", "thefarmersdog.com", "Fresh Dog Food", "Super Bowl ad = massive signups; $1B+ valuation; human-grade fresh food; vet-developed recipes"),
        ("Sundays", "sundaysfordogs.com", "Air-Dried Food", "New category between kibble and fresh: air-dried; USDA-grade beef; Michael Buble investor; premium"),
        ("Kong", "kongcompany.com", "Dog Toys", "Kong Classic is the indestructible rubber dog toy; 50+ year heritage; vet-recommended; $100M+ revenue"),
        ("Outward Hound", "outwardhound.com", "Enrichment Toys", "Nina Ottosson puzzle toys for dogs; mental stimulation; hide-and-seek toys; smart pet enrichment"),
        ("Petcube", "petcube.com", "Pet Camera", "Pet camera with laser toy; play with cat/dog remotely; treat dispensing; 2-way audio; $50M+ revenue"),
        ("Fable", "ffrble.com", "Modern Pet Gear", "The Game enrichment toy keeps dogs busy; The Carrier is travel-ready; beautiful functional pet gear"),
        ("Open Farm", "openfarmpet.com", "Ethical Pet Food", "Scan QR code to trace every ingredient to its farm source; humane certifications; B Corp; transparent"),
        ("Stella & Chewy's", "stellaandchewys.com", "Raw Pet Food", "Freeze-dried raw pioneer; Marie Moody started it when her rescue dog healed on raw food; premium raw"),
        ("Wisdom Panel", "wisdompanel.com", "Dog DNA", "350+ breed, 200+ health condition screening; most comprehensive DNA test; Mars Petcare owned"),
    ],

    "Home & Kitchen - Expanded 2": [
        ("Le Creuset", "lecreuset.com", "French Cookware", "Enameled cast iron in signature colors; $100M+ annual revenue; wedding registry icon; 100+ year heritage"),
        ("Staub", "staub-usa.com", "French Cocotte", "Self-basting lid spike system; matte black enamel interior; Zwilling owned; chef's choice cast iron"),
        ("All-Clad", "all-clad.com", "American Cookware", "Bonded stainless steel cookware used by professional chefs; Made in Pennsylvania; the gold standard"),
        ("Cuisinart", "cuisinart.com", "Kitchen Pioneer", "Food processor pioneer; Carl Sontheimer introduced French tech to US; $1B+ brand; Conair owned"),
        ("KitchenAid", "kitchenaid.com", "Stand Mixer Icon", "Artisan mixer in 60+ colors; unchanged design for decades; wedding registry essential; Whirlpool owned"),
        ("Zwilling", "zwilling.com", "German Knives", "290+ year heritage; twin man logo; J.A. Henckels tradition; professional-grade at fair price"),
        ("Wüsthof", "wusthof.com", "Solingen Steel", "Made in Solingen, Germany since 1814; Classic 8-inch chef's knife is industry standard; 7th generation"),
        ("Shun", "shun.kaiusa.com", "Japanese Knives", "Japanese VG-MAX steel; hand-sharpened; Kai Group; the prosumer Japanese knife brand; Damascus patterns"),
        ("Chemex", "chemexcoffeemaker.com", "Pour-Over Icon", "In the MoMA permanent collection; borosilicate glass; invented 1941; design icon that makes great coffee"),
        ("Hario", "hario-usa.com", "Japanese Coffee", "V60 pour-over is specialty coffee standard; Japanese heat-resistant glass; 100+ year glassware heritage"),
        ("AeroPress", "aeropress.com", "Coffee Maker", "Invented by frisbee-inventor and Stanford lecturer; World AeroPress Championship; $30 brewer; cult following"),
        ("Lodge", "lodgecastiron.com", "Cast Iron", "Family-owned since 1896 in Tennessee; pre-seasoned; $15-40 skillets; buy-it-for-life; American manufacturing"),
        ("Instant Pot", "instantpot.com", "Multi-Cooker", "7-in-1 cooker; 300M+ member Facebook fan group; sold out on Prime Day; $1B brand; Corelle Brands"),
        ("Ninja", "ninjakitchen.com", "Kitchen Systems", "Creami TikTok viral; Foodi combo cookers; air fryer leader; undercut incumbents with innovation"),
        ("Our Place", "fromourplace.com", "DTC Cookware", "Always Pan replaces 8 pieces; $145; Selena Gomez collab; Instagram darling; $200M+ revenue"),
    ],
}
