"""
Third batch of DTC brands to reach 3000+. Covering categories not yet filled.
Format: (Brand, Website, Sub-niche, Notable Insight)
"""

EXTRA_BRANDS_3 = {
    "Fashion - Swimwear": [
        ("Solid & Striped", "solidandstriped.com", "Swim", "The Anne-Marie one-piece is iconic; celebrity-loved swimwear; $100M+ revenue"),
        ("Frankies Bikinis", "frankiesbikinis.com", "Swim", "Francesca Aiello's brand; Pamela Anderson collab; crochet bikinis; IPO'd via SPAC"),
        ("Monday Swimwear", "mondayswimwear.com", "Swim", "Tash Oakley + Devin Brugman founded; designed for real women's bodies; inclusive sizing"),
        ("Vitamin A", "vitaminaswim.com", "Eco Swim", "Sustainable swimwear using EcoLux fabric (recycled nylon); California made; 25+ year heritage"),
        ("L*Space", "lfrspace.com", "Swim", "Monica Wise's lifestyle swim brand; Bitsy top is bestseller; resort wear expansion; SoCal DNA"),
        ("Triangl", "triangl.com", "Neoprene Swim", "Neoprene bikinis disrupted with $89 price point; Australian; shipped worldwide; Instagram-born brand"),
        ("Hunza G", "hunfrza-g.com", "Crinkle Swim", "Seersucker one-size-fits-all swimwear; retro crinkle fabric; the It-girl swimwear; revival brand"),
        ("Andie Swim", "andieswim.com", "Women's Swim", "Fit quiz recommends your perfect swimsuit; inclusive sizing; 100-day try period; data-driven fit"),
        ("Marysia", "marysia.com", "Scalloped Swim", "Scallop-edge trim is signature; Santa Monica-made; luxury swim at $200+; Victoria Beckham wore them"),
        ("Onia", "onia.com", "Men's Swim", "Elevated men's swim trunks; matching sets; Charles linen shorts are bestseller; NYC design"),
        ("Bather", "bfrather.com", "Men's Trunks", "Canadian men's swim trunks with unique prints; $80-100; cult following; seasonal collections"),
        ("Fair Harbor", "fairharborclothing.com", "Recycled Swim", "Swim trunks made from recycled plastic bottles; each pair = 11 bottles recycled; built-in liner"),
        ("Midori Bikinis", "midoribikinis.com", "Custom Swim", "Mix and match tops and bottoms in any size combination; customize your bikini; made-to-order"),
        ("Kukua", "kukfrua.com", "Sustainable Swim", "Australian sustainable swimwear from recycled ocean waste; plant-dyed; ethical manufacturing"),
        ("Bond-Eye", "bond-eye.com.au", "Sculptural Swim", "One-piece swimsuits with twisted sculptural details; Australian; Nylon magazine favorite"),
    ],

    "Fashion - Athleisure 2": [
        ("Set Active", "setactive.co", "Colorful Active", "Color drops that sell out in hours; Lindsey Carter grew from apartment; Gen Z activewear darling; $50M+"),
        ("Free People Movement", "freepeople.com", "Boho Active", "Free People's activewear line; flowy, artistic workout clothes; Way Home Shorts are cult; unique aesthetic"),
        ("Beyond Yoga", "beyondyoga.com", "Soft Active", "Spacedye fabric is buttery soft; inclusive sizing from day one; Levi's acquired; premium comfort"),
        ("Year of Ours", "yearofours.com", "Ribbed Active", "Ribbed activewear pioneer; Boxing legging is signature; celebrity trainer partnerships; LA-based"),
        ("Varley", "varley.com", "Luxury Active", "British luxury activewear; Harvey Nichols distribution; elevated fabrics; $200+ leggings justified by quality"),
        ("P.E Nation", "pe-nation.com", "Street Active", "Australian streetwear-meets-activewear; bold prints and color blocking; Pip Edwards' lifestyle brand"),
        ("Koral", "koral.com", "Fashion Active", "Lustrous High Rise legging; fashion-forward activewear; editorial quality; LA-designed performance wear"),
        ("Splits59", "splits59.com", "Retro Active", "Vintage-inspired activewear; 70s running shorts and 80s color blocking; $60M+ revenue; throwback cool"),
        ("Carbon38", "carbon38.com", "Luxury Active Retail", "Curated multi-brand luxury activewear retailer; Takara legging is hero; premium everything"),
        ("Beach Riot", "beachriot.com", "Swim + Active", "Swimwear brand that expanded into activewear; bold prints; Nicole Martin founded; lifestyle brand"),
        ("Alo Yoga", "aloyoga.com", "Yoga Lifestyle", "Celebrity yoga culture; Alo Sanctuary studios; $10B valuation; Kendall Jenner, Hailey Bieber ambassadors"),
        ("Spiritual Gangster", "spiritualgangster.com", "Yoga Fashion", "Yoga-inspired lifestyle brand; 'Namaste' and 'Good Vibes' prints; charitable giving per sale"),
        ("Nux Active", "nfrux.com", "Boutique Active", "Boutique fitness studio favorite; found in SoulCycle and Barry's; French terry joggers"),
        ("Outdoor Voices", "outdoorvoices.com", "Doing Things", "Tyler Haney's 'exercise for fun' philosophy; Exercise Dress; brand rebuild after founder drama"),
        ("Sweaty Betty", "sweatybetty.com", "British Active", "London-based; Power Workout leggings; 70+ UK stores; Wolverine Worldwide acquired for $410M"),
    ],

    "Beauty - Body & Self-Tan": [
        ("St. Tropez", "sttropeztan.com", "Self-Tan", "The gold standard of self-tan; used by 90% of award show MUAs; mousse formula changed tanning; $200M+"),
        ("Bondi Sands", "bondisands.com", "Australian Tan", "Australian self-tan at affordable prices; Aero Aerated Mousse; found everywhere; $200M+ revenue"),
        ("Loving Tan", "lovingtan.com", "Dark Tan", "2 Hour Express delivers deepest tan in 2 hours; Australian; salon-grade at home; $100M+ revenue"),
        ("Isle of Paradise", "isleofparadise.com", "Color-Correcting Tan", "Self-tan drops in green/peach/violet for color correction; Jules Von Hep's brand; Sephora"),
        ("Bali Body", "balibody.com", "Tanning Oil", "Started with SPF tanning oils; expanded to self-tan; Australian; $50M+ revenue; Instagram-built"),
        ("TAN-LUXE", "tan-luxe.com", "Tan Drops", "The Face illuminating self-tan drops; mix into moisturizer; precise control; UK brand"),
        ("Coco & Eve", "cocoandeve.com", "Bali Beauty", "Bali Bronze self-tanning mousse; Like A Virgin hair mask; tropical Bali aesthetic; $100M+"),
        ("Jergens", "jergens.com", "Gradual Tan", "Natural Glow daily moisturizer with subtle self-tanner; drugstore staple; gradual buildable color"),
        ("Frank Body", "frankbfody.com", "Coffee Scrub", "Coffee scrub brand that went viral; 'let's be frank' cheeky packaging; Australian; 2M+ units sold"),
        ("Lush", "lush.com", "Bath Bombs", "Invented the bath bomb; fresh handmade cosmetics; activist brand; no packaging; $1B+ revenue"),
        ("Dr. Bronner's", "drbronner.com", "Castile Soap", "18-in-1 castile soap; philosophical label text; $200M+ revenue; fair trade organic; family drama story"),
        ("Nécessaire", "necessaire.com", "Body Skincare", "$25 body wash normalized; vitamins + minerals in body care; Sephora; elevated body category"),
        ("Soft Services", "softservices.com", "Body Skincare", "Skincare for body (not repackaged face care); KP (keratosis pilaris) smoothing; targeted solutions"),
        ("Megababe", "megababebeauty.com", "Body Solutions", "Thigh Rescue anti-chafe stick; Bust Dust; Le Tush scrub; body-positive problem-solving products"),
        ("Kopari", "koparibeauty.com", "Coconut Body", "100% coconut oil base; bright turquoise branding; expanded from body to face; $100M+ revenue"),
    ],

    "Fashion - Workwear & Professional": [
        ("M.M.LaFleur", "mmlafleur.com", "Women's Work", "Bento Box — stylist picks 4 work pieces for you; professional women's wardrobe simplified; $100M+ revenue"),
        ("Argent", "argentwork.com", "Power Suits", "Blazers and suits designed by women for women; internal pockets for phone; power dressing reinvented"),
        ("Of Mercer", "ofmercer.com", "NYC Workwear", "Work-to-dinner versatility; wrap dresses + tailored pants; designed for NYC professional women"),
        ("Numi", "shofrpnumi.com", "Ethical Work", "Ethically made workwear for women; organic + recycled materials; $80-200; professional without compromise"),
        ("Aella", "aefrlla.co", "Tech Workwear", "Women's workwear for tech — blazers with stretch, laptop-bag friendly; San Francisco designed"),
        ("State & Liberty", "stateandliberty.com", "Athletic Fit", "Dress shirts cut for athletic builds; stretch fabric; no more tight collar on muscular necks"),
        ("Ministry of Supply", "ministryofsupply.com", "NASA Workwear", "Phase-change fabric regulates body temp; 3D-knit blazer; MIT engineering meets dress code"),
        ("Mizzen+Main", "mizzenandmain.com", "Performance Dress", "Performance fabric dress shirts; Phil Mickelson ambassador; moisture-wicking but looks like cotton"),
        ("Proper Cloth", "propercloth.com", "Custom Shirts", "Custom dress shirts from 600+ fabrics; AI-powered sizing from home measurements; $125-175"),
        ("Ledbury", "ledbury.com", "Richmond Shirts", "Richmond, VA dress shirts with perfect collar roll; Thomas Mason fabrics; American craftsmanship"),
        ("Charles Tyrwhitt", "ctshirts.com", "British Shirts", "Jermyn Street quality at $40; 4 shirts for $200 deal; British heritage; accessible dress shirts"),
        ("Suitsupply", "suitsupply.com", "Modern Suits", "Dutch brand; $400-600 suits rivaling $2K competitors; Napoli fit is bestseller; 100+ stores globally"),
        ("Indochino", "indochino.com", "Custom Suits", "Made-to-measure suits from $399; 3D body scanning; 100+ showrooms; democratized custom tailoring"),
        ("Untuckit", "untuckit.com", "Casual Shirts", "Shirts designed to be worn untucked at perfect length; solved ONE problem; 90+ stores; $200M+ revenue"),
        ("Todd Snyder", "toddsnyder.com", "American Design", "J.Crew alumni; Champion collab elevated the brand; NYC flagship; menswear designer at accessible price"),
    ],

    "Home - Furniture Expanded": [
        ("Maiden Home", "maidenhome.com", "NC Craftsmanship", "Handcrafted in North Carolina; luxury quality at 50% retail; no showroom overhead; DTC artisan furniture"),
        ("Interior Define", "interiordefine.com", "Custom Sofas", "400+ fabric options for sofas; guideshops to try; customization + DTC; affordable custom upholstery"),
        ("Inside Weather", "insideweather.com", "Configurable", "Configure your sofa piece by piece; 2-week delivery; California-made; $1K-2K sweet spot"),
        ("Medley", "medleyhome.com", "Non-Toxic", "Non-toxic, sustainable furniture; no flame retardants, formaldehyde; California-made; health-first home"),
        ("Sabai", "sabai.design", "Circular Furniture", "Slipcovers are removable, washable, replaceable; built to last and update; anti-fast-furniture"),
        ("Campaign Living", "campaignliving.com", "Modern Heritage", "Leather furniture with MCM design; flat-pack assembly; $1,200 leather sofa; military campaign heritage"),
        ("Maiden Home", "maidenhome.com", "Direct Artisan", "North Carolina handcrafted; luxury quality; founder's family in furniture for generations; $2K sofas"),
        ("Benchmade Modern", "benchmademodern.com", "Custom Sectionals", "Customize dimensions, fabric, configuration; LA-made; shipped in 5-7 weeks; truly custom modular"),
        ("Poly & Bark", "polyandbark.com", "Eames Inspired", "MCM-inspired furniture at 1/3 designer price; Eames-style chair is bestseller; Italian leather"),
        ("AllModern", "allmodern.com", "Modern Budget", "Wayfair's design-forward brand; modern furniture at accessible prices; free fast shipping"),
        ("CB2", "cb2.com", "Urban Modern", "Crate & Barrel's contemporary line; smaller-scale furniture for city apartments; edgy design"),
        ("West Elm", "westelm.com", "Fair Trade Home", "Fair Trade commitment; MCM design; $1.8B revenue; sustainability in mass-market furniture"),
        ("IKEA", "ikea.com", "Democratic Design", "Flat-pack pioneer; Billy bookcase 110M+ sold; meatballs strategic; $50B revenue; Kallax is iconic"),
        ("Apt2B", "apt2b.com", "Colorful Furniture", "Bold colored sofas (teal, mustard, pink); LA-based; 100+ fabric options; fun furniture for personality"),
        ("Joss & Main", "jossandmain.com", "Curated Home", "Wayfair's curated brand; designer looks at Wayfair prices; style-forward picks; flash sales"),
    ],

    "Food - Condiments & Sauces": [
        ("Fly By Jing", "flybyjing.com", "Sichuan Chili Crisp", "Jing Gao brought authentic Sichuan flavor to US; fastest-selling sauce on Amazon launch day"),
        ("TRUFF", "truff.com", "Truffle Hot Sauce", "Luxury hot sauce with black truffle; $100M+ revenue; elevated hot sauce to giftable premium category"),
        ("Mike's Hot Honey", "mikeshothoney.com", "Hot Honey", "Created the hot honey category; started at a NYC pizzeria; honey + chili; now in every grocery"),
        ("Bachan's", "bachans.com", "Japanese BBQ", "Family recipe Japanese BBQ sauce; #1 new condiment at Whole Foods; $200M+ in 3 years; Costco hit"),
        ("Momofuku", "shop.momofuku.com", "Chef Sauces", "David Chang's Chili Crunch and sauces; restaurant-to-retail; chef credibility in a jar"),
        ("Graza", "graza.co", "Squeeze Olive Oil", "Olive oil in a squeeze bottle; Drizzle + Sizzle; sold out 5x; disrupted the olive oil format entirely"),
        ("Brightland", "brightland.co", "Artist Olive Oil", "Artist-label California EVOO; turned olive oil into lifestyle gifting product; beautiful packaging"),
        ("Primal Kitchen", "primalkitchen.com", "Paleo Condiments", "Avocado oil mayo started it; Kraft Heinz acquired; clean label condiments; Mark Sisson founded"),
        ("Sir Kensington's", "sirkensingtons.com", "Fancy Condiments", "Elevated ketchup and mayo; 'the condiment revolution'; Unilever acquired; Fairtrade certified"),
        ("Tessemae's", "tessemaes.com", "Organic Dressing", "Organic, Whole30 approved dressings; family-founded; lemon garlic is bestseller; $50M+ revenue"),
        ("Chosen Foods", "chosenfoods.com", "Avocado Oil", "100% pure avocado oil for cooking; spray format; Costco bestseller; healthy oil alternative"),
        ("Yellowbird", "yellowbirdsauce.com", "Organic Hot Sauce", "Organic hot sauces from Austin; Habanero condiment is bestseller; Whole Foods; chef-quality heat"),
        ("Secret Aardvark", "secretaardvark.com", "Portland Hot Sauce", "Habanero sauce is Reddit's favorite; Portland cult brand; tomato-based not vinegar-based; unique"),
        ("Everything Legendary", "everythinglegendary.com", "Plant Burgers", "Black-owned plant-based burger patties; Shark Tank; taste-first approach; $100M+ revenue"),
        ("Kewpie", "kfrwpie.com", "Japanese Mayo", "Japanese mayonnaise with egg yolk only (no whites); MSG umami; squeeze bottle; chef's secret weapon"),
    ],

    "Tech - Wearables & Health": [
        ("Oura", "ouraring.com", "Health Ring", "Sleep/activity ring; NBA COVID detection; $2.55B valuation; discrete form factor; Gen 3 ring"),
        ("Whoop", "whoop.com", "Performance Band", "No screen; $30/mo subscription; strain scores; pro athletes; $3.6B valuation; data-obsessed"),
        ("Fitbit", "fitbit.com", "Fitness Tracking", "Popularized fitness tracking; 120M+ devices sold; Google acquired $2.1B; now Pixel Watch"),
        ("Withings", "withings.com", "Hybrid Watches", "ScanWatch detects AFib and sleep apnea; looks like analog watch; French design; FDA-cleared"),
        ("Garmin", "garmin.com", "GPS Fitness", "Fenix/Forerunner dominate; $5B+ revenue; solar charging; military-grade; adventure essential"),
        ("Apple Watch", "apple.com/watch", "Smartwatch", "40%+ market share; ECG saves lives; crash detection; Ultra for extreme; $30B+ segment"),
        ("Amazfit", "amazfit.com", "Budget Wearable", "GTR series at $200 rivals $500 watches; Zepp Health; blood oxygen; best value smartwatch"),
        ("Bellabeat", "bellabeat.com", "Women's Wellness", "Leaf tracker disguised as jewelry; wellness tracking for women; cycle tracking; European design"),
        ("Levels", "levelshealth.com", "CGM Tracking", "Continuous glucose monitor for metabolic health (not diabetics); see how food affects blood sugar"),
        ("Dexcom", "dexcom.com", "CGM Device", "Real-time glucose monitoring; G7 sensor; smartphone alerts; $3B+ revenue; diabetes management leader"),
        ("Biostrap", "biostrap.com", "Sleep Biometrics", "Clinical-grade sleep tracking wearable; SpO2, HRV, respiratory rate; used in clinical studies"),
        ("Circular", "circular.xyz", "Smart Ring", "Slim health-tracking ring; sleep, activity, heart rate; European alternative to Oura; lighter design"),
        ("Motiv Ring", "motiv.com", "Fitness Ring", "Titanium fitness tracking ring; heart rate, sleep, activity; most minimal tracker"),
        ("Muse", "choosemuse.com", "Brain Sensing", "EEG headband for meditation; real-time brain activity feedback; guided meditation with neurofeedback"),
        ("Lumen", "lumen.me", "Metabolism Tracker", "Breath analyzer measures metabolism in real time; tells you if burning fat or carbs; personalized nutrition"),
    ],

    "Home - Lighting & Decor": [
        ("Nanoleaf", "nanoleaf.me", "Light Panels", "Modular LED panels tile together; gaming/streaming essential; Thread protocol; $100M+ revenue"),
        ("Govee", "govee.com", "LED Strips", "TikTok room transformation viral; smart LED strips and bulbs; affordable smart lighting leader"),
        ("Philips Hue", "meethue.com", "Smart Lighting", "OG smart bulbs; Bridge ecosystem; 16M colors; most established smart lighting; Signify owned"),
        ("LIFX", "lifx.com", "WiFi Bulbs", "No hub needed (unlike Hue); brightest smart bulbs; Apple HomeKit, Alexa, Google; Australian"),
        ("Lamps Plus", "lampsplus.com", "Lighting Retail", "Largest lighting retailer online; 55K+ products; designer brands; custom lighting solutions"),
        ("Schoolhouse", "schoolhouse.com", "Heritage Lighting", "Portland-made lighting and hardware; craftsman aesthetic; handmade in Oregon; premium quality"),
        ("Rejuvenation", "rejuvenation.com", "Period Lighting", "Restoration-quality lighting and hardware; Portland; Williams-Sonoma owned; architectural salvage roots"),
        ("Mitzi", "?"," Modern Lighting", "Hudson Valley Lighting's modern sub-brand; Instagram-friendly fixtures; affordable designer looks"),
        ("Arteriors", "arteriors.com", "Luxury Lighting", "To-the-trade luxury lighting and home decor; designer partnerships; $200M+ revenue; chandeliers + art"),
        ("Visual Comfort", "?"," Designer Lighting", "Licensed collections from top designers (Kelly Wearstler, Thomas O'Brien); luxury lighting leader"),
        ("CB2", "cb2.com", "Modern Decor", "Crate & Barrel's contemporary line; statement lighting; glass, brass, marble decor; urban style"),
        ("Anthropologie", "anthropologie.com", "Boho Home", "Unique home decor; Primrose mirror is iconic; monogram mugs; eclectic boho-maximalist aesthetic"),
        ("Urban Outfitters", "urbanoutfitters.com", "Trendy Decor", "Neon signs, tapestries, terracotta pots; dorm and first-apartment essentials; trend-driven decor"),
        ("Target Threshold", "target.com", "Mass Decor", "Studio McGee x Target collection; affordable designer looks; Hearth & Hand with Magnolia; accessible design"),
        ("IKEA", "ikea.com", "Democratic Decor", "FEJKA fake plants, KALLAX shelving, MALM dressers; Swedish design for everyone; functional decor"),
    ],

    "Food - Protein & Bars 2": [
        ("ONE Bar", "one1brands.com", "Protein Bars", "1g sugar, 20g protein; Birthday Cake flavor is bestseller; Hershey acquired; guilt-free indulgence"),
        ("Grenade", "grenade.com", "Protein Bars", "Carb Killa bars; UK #1 protein bar; military grenade-shaped branding; $240M acquisition by Mondelēz"),
        ("Fulfil", "fulfilnutrition.com", "Vitamin Protein Bars", "Protein bar + 9 vitamins; Irish brand; $200M+ revenue; Ferrero acquired; snack + supplement hybrid"),
        ("Huel", "huel.com", "Complete Meal", "Nutritionally complete meal in powder/bar/RTD; 400 cal per serving; $200M+ revenue; British; 'human fuel'"),
        ("Soylent", "soylent.com", "Meal Replacement", "Named after sci-fi movie; complete nutrition in a bottle; $100M+ revenue; Silicon Valley fuel; Rob Rhinehart"),
        ("Ka'Chava", "kachava.com", "Superfood Shake", "85+ plant-based superfoods in one shake; podcast advertising blitz; $200M+ revenue; all-in-one meal"),
        ("Aloha", "aloha.com", "Plant Protein Bar", "USDA organic plant-based protein bars; 14g protein; brown rice + pumpkin seed protein; clean"),
        ("GoMacro", "gomacro.com", "Macrobiotic Bar", "Mother-daughter founded after cancer; macrobiotic philosophy; organic; plant-based; feel-good story"),
        ("Nugo", "nugonutrition.com", "Dark Chocolate Bars", "Real dark chocolate coating (not compound); Slim line for dieters; family-owned; affordable protein"),
        ("Think!", "thinkproducts.com", "High Protein Bar", "20g protein, 0g sugar in most bars; Brownie Crunch is bestseller; accessible in every convenience store"),
        ("Verb Energy", "verbenergy.com", "Caffeinated Bars", "Organic caffeinated energy bars; as much caffeine as espresso; green tea extract; Yale students founded"),
        ("OWYN", "liveowyn.com", "Plant Protein Shake", "Only What You Need — pea/pumpkin/flax protein; top 8 allergen-free; smooth taste; clean plant shake"),
        ("Evolve", "drinkevolve.com", "Plant Protein", "20g plant protein shakes and bars; $2 per shake; Hormel owned; affordable plant protein for everyone"),
        ("Vega", "myvega.com", "Plant Nutrition", "Sport Protein Bars, Protein Powder; pea protein pioneer; B Corp; 20+ years in plant nutrition"),
        ("Naked Nutrition", "nakednutrition.com", "Minimal Protein", "Only 1-3 ingredients in protein powder; Naked Whey = just whey; radical simplicity; transparent"),
    ],

    "Tech - Smart Home 2": [
        ("Amazon Echo", "amazon.com/echo", "Smart Speaker", "Alexa voice assistant; Echo Dot #1 selling smart speaker ever; 500M+ Alexa devices; smart home hub"),
        ("Google Nest", "store.google.com", "Smart Home", "Nest Thermostat learned your schedule; Nest Hub display; Google Assistant; Alphabet owned"),
        ("Apple HomePod", "apple.com/homepod", "Smart Speaker", "Spatial Audio; Siri; Apple Home hub; privacy-first; HomePod mini at $99; ecosystem lock-in"),
        ("Aqara", "aqara.com", "Affordable Smart", "Zigbee/Matter smart home; $10-30 sensors; Apple HomeKit; Chinese engineering; incredible value"),
        ("SwitchBot", "switch-bot.com", "Retrofit Smart", "Tiny robot pushes buttons/flips switches on dumb devices; retrofit anything to smart; $50 entry"),
        ("Lutron", "lutron.com", "Smart Lighting", "Caseta smart switches; most reliable smart lighting system; works when WiFi fails; RadioRA luxury"),
        ("Sonos", "sonos.com", "Multi-Room Audio", "Wireless multi-room audio; simple setup; $1.5B+ revenue; won patent suit vs Google; audiophile-adjacent"),
        ("Ring", "ring.com", "Video Doorbell", "Video doorbell inventor; Amazon acquired $1.2B; Neighbors app; community security network"),
        ("Arlo", "arlo.com", "Wire-Free Camera", "Wire-free battery cameras; best outdoor cameras; Apple HomeKit; 4K resolution; solar panel option"),
        ("Eufy", "eufylife.com", "No-Fee Security", "Local storage = no monthly fees; 2K cameras for $40; Anker brand; privacy-first approach"),
        ("TP-Link Kasa", "kasasmart.com", "Smart Plugs", "Most popular smart plugs; $10 per plug; WiFi direct; no hub needed; billions of connections"),
        ("Meross", "meross.com", "Budget Smart", "HomeKit-compatible smart plugs and switches under $15; Chinese brand; best budget smart home"),
        ("Eve Systems", "evehome.com", "HomeKit Native", "Apple HomeKit-exclusive smart home; Thread + Matter; privacy-first; no cloud required; German design"),
        ("Ecobee", "ecobee.com", "Smart Thermostat", "SmartSensor room-by-room comfort; built-in Alexa; energy savings; $750M acquisition; Canadian"),
        ("Nest Thermostat", "store.google.com", "Learning Thermostat", "Original learning thermostat; Soli radar presence detection; $249; Tony Fadell (iPod creator) designed"),
    ],

    "Beauty - Nail Care": [
        ("Olive & June", "oliveandjune.com", "At-Home Mani", "The Poppy handle makes painting your own nails easy; studio-quality manicure at home; $50M+ revenue"),
        ("Chillhouse", "chillhouse.com", "Press-On Nails", "Chill Tips press-ons from their NYC nail salon; salon-quality adhesive; 30+ designs; $10M+ revenue"),
        ("ManiMe", "manime.co", "Custom Gel", "3D-scanned custom gel nail art stickers; AI sizing from selfie; personalized nail art at home"),
        ("Static Nails", "staticnails.com", "Reusable Nails", "Reusable pop-on manicures; wear up to 18 days; or wear once and re-apply; reusable luxury nails"),
        ("Dashing Diva", "dashingdiva.com", "Gel Strips", "GLAZE nail strips; no dry time, no UV lamp; salon-quality gel at home; K-beauty nail innovation"),
        ("Glamnetic", "glamnetic.com", "Magnetic Lashes", "Magnetic lashes + magnetic liner; no glue needed; also press-on nails; $50M+ revenue; TikTok viral"),
        ("Lashify", "lashify.com", "DIY Extensions", "Gossamer lash system — DIY lash extensions at home; Sahara Lotti's patented technology; $100M+"),
        ("Londontown", "londontown.com", "Clean Nails", "Plant-based, cruelty-free nail lacquer; Lakur line; strengthening ingredients; British luxury nail"),
        ("Sundays", "dearsundays.com", "Non-Toxic Nails", "10-free nail polish; NYC nail studio; plant-based base coat; minimalist Korean-inspired design"),
        ("tenoverten", "tenoverten.com", "Clean Polish", "8-free nail polish named after NYC cross streets; salon + retail; sustainable nail care"),
        ("Paintbox", "paint-box.com", "Nail Art Studio", "NYC nail art studio gone DTC; Power Couple base + top coat system; editorial nail art; like-a-gel finish"),
        ("OPI", "opi.com", "Heritage Nails", "Most iconic nail polish names (Lincoln Park After Dark, Big Apple Red); pro-grade; Wella Company"),
        ("essie", "essie.com", "Nail Polish Icon", "Ballet Slippers is the world's most popular nail polish; French-inspired names; L'Oréal owned"),
        ("Sally Hansen", "sallyhansen.com", "Mass Nails", "Miracle Gel is at-home gel without a lamp; Insta-Dri; good enough quality at drugstore price; Coty"),
        ("Orly", "orly.com", "Pro Nails", "Invented the French manicure; Breathable treatment + color; vegan; made in LA; professional heritage"),
    ],

    "Fashion - Jewelry Budget": [
        ("Barsf", "baublebar.com", "Statement Jewelry", "Statement earrings and necklaces $20-50; weekly new arrivals; NFL, NBA sport jewelry collabs"),
        ("Kendra Scott", "kendrascott.com", "Texas Jewelry", "Color Bar customization in-store; Austin pride; $1B+ valuation; accessible fine jewelry; philanthropy"),
        ("Pura Vida Bracelets", "puravidabracelets.com", "Beach Bracelets", "Costa Rican artisan-made bracelets; 200+ designs; charity collabs; $100M+ revenue; Vera Bradley acquired"),
        ("Alex and Ani", "alexandani.com", "Charm Bangles", "Expandable wire bangles with charms; positive energy messaging; Made in USA; $500M peak revenue"),
        ("Uncommon James", "uncommonjames.com", "Nashville Jewelry", "Kristin Cavallari's brand; dainty gold jewelry; Nashville-designed; Very Cavallari TV show drove awareness"),
        ("Gorjana", "gorjana.com", "California Jewelry", "Laguna Beach-designed layering jewelry; Parker necklace; $50-200 sweet spot; 20+ retail stores"),
        ("Ettika", "ettika.com", "LA Jewelry", "Trend-driven LA jewelry at $30-80; layering sets; TikTok favorite; fast fashion pricing for jewelry"),
        ("Adina's Jewels", "adinasjewels.com", "Trendy Plated", "Gold-plated trend jewelry at $30-100; TikTok viral; her initial necklace is iconic; Gen Z favorite"),
        ("Missoma", "missoma.com", "Demi-Fine", "Kate Middleton wore it; gold vermeil + semi-precious; London; 'the brand behind every gold hoop'"),
        ("Astrid & Miyu", "astridandmiyu.com", "London Demi-Fine", "Ear piercing bars + demi-fine jewelry; curated ear styling; $50-200 range; UK + expanding"),
        ("Soko", "shopsoko.com", "Ethical Jewelry", "Kenyan artisan-made jewelry; direct-to-artisan model; bone, brass, recycled materials; fair wages"),
        ("Stone and Strand", "stoneandstrand.com", "Delicate Fine", "Delicate fine jewelry for layering; diamond dusting; $50-500 range; NYC designed; everyday fine"),
        ("The Last Line", "thelastline.com", "Fun Fine", "Colorful fine jewelry; rainbow diamonds; $200-2000; playful luxury; breaking fine jewelry rules"),
        ("Dorsey", "bydorsey.com", "Lab Gems", "Lab-grown colored gemstones; emerald, sapphire, ruby in modern settings; $200-500; accessible gems"),
        ("Ring Concierge", "ringconcierge.com", "IG Fine Jewelry", "Nicole Wegman built on Instagram; DM-to-purchase model; engagement rings; 'your cool older sister'"),
    ],

    "Outdoor - Camping & Gear": [
        ("YETI", "yeti.com", "Premium Outdoor", "Coolers as status symbols; Rambler tumblers everywhere; $1.6B+ revenue; built on hunting/fishing roots"),
        ("Stanley", "stanley1913.com", "Viral Drinkware", "Quencher tumbler went from $70M to $750M via TikTok; women resurrected a 100-year men's brand"),
        ("Hydro Flask", "hydroflask.com", "Insulated Bottles", "TempShield insulation; VSCO girl icon; sticker culture; $200M+ revenue; Helen of Troy owned"),
        ("CamelBak", "camelbak.com", "Hydration Packs", "Invented the hands-free hydration pack; used by military; Eddy bottle; cycling + hiking essential"),
        ("Nalgene", "nalgene.com", "Classic Bottles", "BPA-free since 2008; Sustain line from recycled content; 75+ year heritage; lab equipment turned hiking bottle"),
        ("Corkcicle", "corkcicle.com", "Design Drinkware", "Insulated drinkware with style; unique patterns; gift-worthy; $100M+ revenue; Tupperware acquired"),
        ("Miir", "miir.com", "Give-Back Drinkware", "Every product gives to clean water, environment, or community; B Corp; beautiful minimal design"),
        ("Snow Peak", "snowpeak.com", "Japanese Outdoor", "Titanium cookware; 'human nature' philosophy; 60+ year Japanese craftsmanship; lifestyle camping"),
        ("REI Co-op", "rei.com", "Outdoor Coop", "#OptOutside closes on Black Friday; 23M+ members; co-op model; own-brand gear rivals premium"),
        ("Big Agnes", "bigagnes.com", "Tents & Sleep", "Ultralight tents and sleeping bags; Steamboat Springs, CO; PCT thru-hikers' choice"),
        ("Kelty", "kelty.com", "Family Camping", "Accessible camping gear; Dirt Motel tent; family-friendly; 'Life Outside' ethos; affordable quality"),
        ("Helinox", "helinox.com", "Ultralight Chairs", "Chair One (2 lbs) started ultralight camp furniture movement; Korean DAC pole technology"),
        ("BioLite", "bioliteenergy.com", "Fire + Power", "CampStove generates electricity from fire to charge devices; FirePit smokeless fire; dual-purpose"),
        ("Goal Zero", "goalzero.com", "Solar Power", "Portable solar panels for camping and emergencies; Yeti power stations; off-grid essential"),
        ("Jackery", "jackery.com", "Power Stations", "Portable power stations; Explorer series; solar generators; $500M+ revenue; camping + emergency backup"),
    ],
}