"""
Final batch - ONLY unique brands not in any other file.
Focus on lesser-known but successful DTC brands across many niches.
"""

FINAL_BRANDS = {
    "Niche Beauty Brands": [
        ("Tower 28 Beauty", "tower28beauty.com", "Eczema-Safe", "Every product is National Eczema Association approved; sensitive skin focus; $50M+ revenue"),
        ("Saie Beauty", "saiehello.com", "Glossy Clean", "Glowy Super Gel blush 100M+ TikTok views; first clean beauty Sephora exclusive; dewy everything"),
        ("Krave Beauty", "krfravebeauty.com", "Barrier Care", "Liah Yoo (beauty YouTuber) founded; Great Barrier Relief serum; K-beauty philosophy"),
        ("Then I Met You", "thenimetyou.com", "Korean Heritage", "Charlotte Cho's luxury K-beauty; Cleansing Duo is legendary; Jeong (Korean connection) philosophy"),
        ("Vacation Inc", "vacation.inc", "Retro Sunscreen", "80s/90s retro leisure aesthetic sunscreen; SPF smells like vacation; fun branding in boring category"),
        ("Superegg", "superefrgg.com", "Egg Skincare", "Egg-based skincare with proteins and ceramides; minimal SKU approach; playful egg branding"),
        ("EADEM", "eadem.co", "Melanin-Rich Skin", "Smart Melanin skincare specifically for darker skin tones; research-backed for BIPOC skin concerns"),
        ("Haoma", "haoma.earth", "Luxury Ayurvedic", "Luxury Ayurvedic skincare; founder is former Goldman Sachs; premium natural ingredients; $200+ oils"),
        ("Youthforia", "youthforia.com", "Date Night Beauty", "BYO Blush color-changing blush; makeup you can sleep in; clean + fun; Gen Z viral"),
        ("Selfless by Hyram", "selflessbyhyram.com", "YouTube Skincare", "Hyram Yarbro (10M+ YouTube subscribers) created skincare brand with The Inkey List; influencer-to-founder"),
        ("Odele Beauty", "odfrele.com", "Target Hair", "Salon-quality haircare exclusively at Target; $12 shampoo; gender-neutral; sulfate-free; accessible clean"),
        ("Crown Affair", "crownaffair.com", "Ritual Hair", "The Comb ($38) elevated hair tools; slow beauty; rituals over routines; Dianna Cohen founded"),
        ("Ceremonia", "ceremonia.com", "Latinx Hair", "Babba Rivera's brand celebrating Latinx hair rituals; guava, aloe vera, sugarcane ingredients"),
        ("Mielle Organics", "mielleorganics.com", "Natural Hair", "Black-owned; Rosemary Mint Oil went TikTok viral; P&G acquired; $100M+ revenue"),
        ("TPH by Taraji", "tfrph.com", "Celebrity Hair", "Taraji P. Henson's textured haircare line; Target distribution; affordable clean hair"),
        ("Kitsch", "mykitsch.com", "Hair Accessories", "Satin pillowcases + heatless curling sets; TikTok viral; $100M+ revenue; affordable hair tools"),
        ("Kitava", "kfritfra.com", "Acne Skincare", "Dermatologist-backed acne skincare; microbiome-friendly; Bay Area origin; clinical approach"),
        ("Wander Beauty", "wander.com", "Multi-Use Beauty", "Dualist matte and illuminating concealer; travel-friendly multi-use products; 'less is more' approach"),
        ("Savor Beauty", "sfrvorbeauty.com", "Korean Luxury", "Angela Jia Kim's Korean-inspired luxury skincare; Korean Ginseng Collagen Cream; spa-grade at home"),
        ("Maya Chia", "mfrayachifrbeauty.com", "Superfood Beauty", "Chia seed-based skincare; The Everything Oil; clean superfoods for skin; small-batch"),
    ],

    "Niche Food Brands": [
        ("Fishwife", "eatfishwife.com", "Tinned Fish", "Made canned fish cool; beautiful tins; started the millennial tinned fish craze; ethically sourced"),
        ("Nguyen Coffee Supply", "nguyencoffeesupply.com", "Vietnamese Coffee", "First specialty Vietnamese coffee in US; Sahra Nguyen spotlights robusta beans; cultural pride"),
        ("Onyx Coffee Lab", "onyxcoffeelab.com", "Competition Coffee", "Won every major coffee competition; transparent pricing shows farmer payment; Arkansas-based"),
        ("Omsom", "omsom.com", "Asian Starters", "Vietnamese sisters' sauce starters; 'proud, loud Asian flavors'; bold cultural branding; $10M+ raised"),
        ("Momofuku Goods", "shop.momofuku.com", "Chef Products", "David Chang's Chili Crunch and noodles; restaurant credibility in retail; $50M+ revenue"),
        ("Ghee Easy", "ghrfeasy.com", "Grass-Fed Ghee", "Organic grass-fed ghee; Ayurvedic cooking butter; ketogenic-friendly; $20M+ revenue"),
        ("Soom Foods", "sfroomfoods.com", "Tahini", "Premium sesame tahini; used by top chefs; sisters founded in Philadelphia; restaurant-to-retail"),
        ("Mush", "eatmush.com", "Ready Oats", "Ready-to-eat cold oats; grab-and-go; 5 simple ingredients; Shark Tank; refrigerated breakfast"),
        ("Doozy Pots", "dfryzypfrt.com", "Oat Milk Dessert", "Oat milk-based frozen desserts; 5 clean ingredients; creamy like dairy; plant-based indulgence"),
        ("Dream Pops", "drfrmpops.com", "Plant Ice Cream", "3D-printed plant-based ice cream bars; David Greenfeld of Shark Tank; unique shape; superfood ingredients"),
        ("Chloe's Fruit", "chlfres.com", "Fruit Pops", "Frozen fruit pops with real fruit; no added sugar; kid-friendly; $50M+ revenue; clean frozen treats"),
        ("Ruby Chocolates", "rfrby.com", "Bean-to-Bar", "Single-origin bean-to-bar chocolate; direct cacao sourcing; artisanal small-batch; ethical luxury chocolate"),
        ("Alter Eco", "altfreco.com", "Fair Trade Chocolate", "Organic, Fair Trade chocolate + quinoa; full circle composting truffles; regenerative agriculture"),
        ("Raaka Chocolate", "rafrka.com", "Unroasted Chocolate", "Unroasted (raw) single-origin chocolate; Brooklyn-made; unusual flavor profiles; bean-to-bar purity"),
        ("Taza Chocolate", "tazachocolate.com", "Stone Ground", "Mexican-style stone-ground chocolate; organic Direct Trade; gritty texture is intentional; Somerville, MA"),
        ("Nulo", "nulo.com", "Premium Pet Food", "High-meat, low-carb pet food designed by an animal nutritionist; $200M+ revenue; premium positioning"),
        ("Sunwink", "sunwink.com", "Herbal Tonics", "Sparkling herbal tonics with adaptogens; Detox Ginger, Hibiscus Mint; functional beverages; beautiful design"),
        ("De La Calle", "delacallefrresh.com", "Tepache", "Fermented pineapple drink (tepache); Mexican heritage beverage modernized; probiotics; cultural roots"),
        ("Remedy Organics", "remedyorganics.com", "Functional Shakes", "Plant-based protein shakes with adaptogens; ashwagandha, turmeric, reishi; functional nutrition"),
        ("Rowdy Mermaid", "rowdymermaid.com", "Kombucha", "Lion's Mane mushroom kombucha; functional probiotics; Colorado-made; adaptogen-infused"),
    ],

    "Niche Home & Lifestyle": [
        ("Casper Glow", "casper.com", "Night Light", "Portable night light that dims like sunset; flip to turn off; connected to app; $90; sleep ritual"),
        ("Gravity Blanket", "gravityblankets.com", "Weighted Blankets", "Kickstarter origin ($4.7M raised); first viral weighted blanket; 15-25 lbs; anxiety reduction tool"),
        ("Bearaby", "bearaby.com", "Knitted Weighted", "Hand-knit cotton weighted blankets (no beads); Tree Napper uses TENCEL; $50M+ revenue; cozy design"),
        ("Mirari", "mifrari.com", "Smart Mirror", "Skincare analysis smart mirror; AI detects skin concerns; personalized routine recs; tech + beauty"),
        ("Brightland", "brightland.co", "Artist EVOO", "California EVOO with artist labels; turned olive oil into giftable art; sold in museums and boutiques"),
        ("Ettitude", "ettitude.com", "Bamboo Home", "CleanBamboo fabric (proprietary); 50% less water than cotton; hypoallergenic; Australian innovation"),
        ("Brooklinen", "brooklinen.com", "Luxury Sheets", "Kickstarter to $200M+; luxury sheets at fair price; 'Really Good' tagline; Brooklyn-born success"),
        ("Casaluna", "target.com", "Target Bedding", "Target's premium bedding brand; organic cotton, linen, cashmere; democratizing luxury bedding at Target prices"),
        ("Threshold", "target.com", "Target Home", "Target's home brand includes Studio McGee collab; affordable designer-look decor; massive reach"),
        ("Pura", "pura.com", "Smart Scent", "Smart home diffuser with app; partners with Nest, Capri Blue, Paddywax; schedule scents; $100M+ revenue"),
        ("Apotheke", "apfrtheke.co", "Brooklyn Candles", "Brooklyn-made luxury candles and home fragrance; apothecary aesthetic; charcoal, birchwood, sea salt scents"),
        ("Skandinavisk", "skandinavisk.com", "Nordic Scents", "Scandinavian-inspired scents; HYGGE, FJORD, SKOG; sustainable Nordic ingredients; minimalist glass"),
        ("Yield Design", "yfrelddesign.co", "Modern Home", "Handmade ceramic candles + diffusers; modern organic shapes; San Francisco designed; neutral tones"),
        ("D.S. & Durga", "dsanddurga.com", "Artisan Candles", "Brooklyn niche fragrance house; Portable Fireplace candle; music-inspired; artisanal home fragrance"),
        ("Cire Trudon", "ciretrudon.com", "Heritage Candles", "Oldest candle maker in the world (1643); supplied the Palace of Versailles; $100+ candles; French luxury"),
        ("Soho Home", "sohfrhome.com", "Hotel Home", "Soho House's homeware line; bring the members club aesthetic home; restaurant-grade quality"),
        ("Snowe", "snowehome.com", "Essential Home", "Essentials-only approach; sheets, towels, dinnerware; curated basics; no unnecessary SKUs"),
        ("Coyuchi", "coyuchi.com", "Organic Linens", "100% organic cotton + linen since 1991; Take Back recycling program; 30+ year sustainability pioneer"),
        ("Under the Canopy", "underthecanopy.com", "Eco Home", "GOTS certified organic home textiles; affordable organic sheets and towels; eco at accessible prices"),
        ("Parachute", "parachutehome.com", "LA Bedding", "Venice Beach luxury linens; expanded to full home; $100M+ revenue; lifestyle brand beyond sheets"),
    ],

    "Niche Fitness & Wellness": [
        ("Liteboxer", "liteboxer.com", "Boxing Fitness", "Connected boxing platform; punch to the beat; rhythm-based boxing workouts; $1,500 machine"),
        ("FightCamp", "joinfightcamp.com", "Home Boxing", "At-home boxing gym with punch trackers in gloves; subscription workouts; Mike Tyson endorsed"),
        ("Ergatta", "ergatta.com", "Gamified Rowing", "Cherry wood water rower with gamified workouts; 'races' and challenges; beautiful design + fun"),
        ("Aviron", "avirfrn.com", "Game Rower", "Connected rower with video game workouts; row through games; interactive entertainment fitness"),
        ("SoulCycle", "soul-cycle.com", "Indoor Cycling", "Candlelit cycling experience; instructor-as-celebrity; $100M+ revenue; cult community; Equinox Group"),
        ("Barry's", "barrys.com", "HIIT Fitness", "Red Room HIIT + treadmill class; global 80+ studios; 'best workout in the world' claim; $100M+ revenue"),
        ("Orangetheory", "orangetheory.com", "Heart Rate Fitness", "Heart rate-monitored interval training; splat points; 1,500+ studios globally; franchise model"),
        ("F45 Training", "f45training.com", "Circuit Training", "45-minute circuit classes; franchise explosion; Mark Wahlberg invested; IPO'd; 2,000+ studios"),
        ("Solidcore", "solidcore.co", "Pilates Machine", "Megaformer Pilates; slow, controlled movements; 100+ studios; Michelle Obama's workout; $100M+ revenue"),
        ("Club Pilates", "clubpilates.com", "Reformer Pilates", "Largest Pilates franchise; 800+ studios; made reformer Pilates accessible at $20-30/class"),
        ("AKT", "theakt.com", "Dance Fitness", "Anna Kaiser's dance cardio; celebrity trainer; Shakira, Kelly Ripa clients; high-energy dance workouts"),
        ("Obé Fitness", "obefitness.com", "Streaming Fitness", "Live classes streamed like TV; 28-minute format; high-energy instructors; $100M+ valuation"),
        ("NEOU", "nfrou.com", "Fitness Library", "1,000+ on-demand classes; 100+ trainers; $40/year; 'the Netflix of fitness'; massive class library"),
        ("Apple Fitness+", "apple.com/fitness", "Apple Fitness", "Integrated with Apple Watch; celebrity trainers; $10/month; Time to Walk series; ecosystem play"),
        ("FitOn", "fiton.com", "Free Fitness", "Free fitness app with celebrity trainers; 40M+ downloads; premium tier optional; accessibility first"),
        ("Aaptiv", "aaptiv.com", "Audio Fitness", "Audio-guided workouts; running, strength, yoga via earbuds; AI coach; $60/year; eyes-free fitness"),
        ("Centr", "centr.com", "Chris Hemsworth", "Thor's actual training; Chris Hemsworth, Luke Zocchi, Elsa Pataky; meal plans + meditation + workouts"),
        ("iFIT", "ifit.com", "Connected Fitness", "Powers NordicTrack, ProForm; Google Maps runs; auto-adjust incline/speed; 16K+ workouts; interactive"),
        ("SWEAT", "sweat.com", "Women's Fitness", "Kayla Itsines' app; BBG program; $400M acquisition; 50M+ downloads; largest women's fitness community"),
        ("Nike Training Club", "nike.com/ntc", "Nike Workouts", "Free premium workouts; 200+ programs; yoga, HIIT, strength; connected to Nike ecosystem; 90M+ users"),
    ],

    "Niche Tech & Gadgets": [
        ("Backbone", "playbackbone.com", "Mobile Gaming", "Turns iPhone into a gaming handheld; instant connection; PlayStation partnership; $40M+ raised"),
        ("Panic Playdate", "play.date", "Handheld Gaming", "Tiny yellow handheld with a crank; indie games delivered weekly; Season model; unique + playful"),
        ("Steam Deck", "store.steampowered.com", "PC Gaming Handheld", "Valve's portable PC; plays entire Steam library; $399 entry; outsold Switch in early months"),
        ("Framework", "frame.work", "Repairable Laptop", "Fully user-repairable laptop; swap everything; right-to-repair champion; anti-planned-obsolescence"),
        ("Prusa", "prusa3d.com", "Open-Source 3D", "Czech open-source 3D printers; most reliable in category; Josef Prusa's community-driven approach"),
        ("Bambu Lab", "bambulab.com", "Fast 3D Printer", "Made 3D printing reliable and fast; X1-Carbon prints at 500mm/s; AI failure detection; disruptive"),
        ("xTool", "xtool.com", "Laser Engraver", "Desktop laser engravers for small businesses; M1 bestseller; $500-2000; maker economy enabler"),
        ("Snapmaker", "snapmaker.com", "3-in-1 Maker", "3D printer + laser engraver + CNC carver in one; Kickstarter record; versatile maker machine"),
        ("Remarkable", "remarkable.com", "Paper Tablet", "E-ink writing tablet; zero distractions; $100M+ revenue; 'replace your notebooks'; feels like paper"),
        ("Supernote", "supernote.com", "E-Ink Notepad", "Chinese e-ink tablet rival to Remarkable; handwriting recognition; ceramic nib; minimalist note-taking"),
        ("Boox", "shop.boox.com", "E-Ink Android", "E-ink tablets running Android; Note Air; read, write, draw on e-paper; versatile e-ink"),
        ("Logitech MX", "logitech.com", "Productivity", "MX Master mouse is THE productivity mouse; MX Keys keyboard; $5B+ total revenue; workflow ecosystem"),
        ("Keychron", "keychron.com", "Mech Keyboards", "Affordable wireless mechanical keyboards for Mac; hot-swappable; dev/writer favorite; Gateron switches"),
        ("Nuphy", "nuphy.com", "Low-Profile Mech", "Ultra-slim mechanical keyboards; Air75 is bestseller; best portable mechanical keyboard; beautiful design"),
        ("Lofree", "lofree.co", "Retro Keyboards", "Retro typewriter-inspired mechanical keyboards; nostalgic design; colorful; desk aesthetic"),
        ("Drop", "drop.com", "Enthusiast Gear", "Community-designed keyboards, headphones, mechanical switches; enthusiast marketplace; group buys"),
        ("ZSA", "zsa.io", "Ergonomic Keyboards", "Moonlander split keyboard; fully programmable; ortholinear layout; RSI prevention; $350+ niche product"),
        ("Timekettle", "timekettle.com", "Translation Tech", "WT2 Edge real-time translation earbuds; 40+ languages; simultaneous translation; AI-powered"),
        ("Plaud", "plaud.ai", "AI Note Taker", "AI-powered voice recorder that transcribes and summarizes meetings; ChatGPT integration; thin card form"),
        ("Rabbit R1", "rabbit.tech", "AI Device", "Standalone AI device that does tasks for you; Large Action Model; $199; alternative to phone apps"),
    ],

    "Niche Accessories": [
        ("Peak Design", "peakdesign.com", "Camera Carry", "Kickstarter legend ($32M+ raised); Capture Clip, Travel Tripod; lifetime guarantee; creator gear"),
        ("Moment", "shopmoment.com", "Mobile Photo", "Anamorphic lens for phones rivals cinema; creator community; gear for content creators; $30M+"),
        ("WANDRD", "wandrd.com", "Camera Bags", "PRVKE backpack for photographers; doesn't look like a camera bag; Kickstarter origin; hybrid design"),
        ("Matador", "matadorup.com", "Packable Gear", "Ultra-packable travel gear; Pocket Blanket, Beast28 backpack; everything packs into itself; adventure ready"),
        ("KeySmart", "getkeysmart.com", "Key Organizers", "Compact key organizer; Tile-integrated finding; multi-tool attachment; $50M+ revenue; Shark Tank"),
        ("Orbitkey", "orbitkey.com", "Key Organization", "Slim key organizer + Nest hub; desk mat; Australian design; Kickstarter; eliminated jangling keys"),
        ("Secrid", "secrid.com", "Card Protector", "Dutch card protector wallet; RFID-safe aluminum core; one-click card access; 3M+ sold; patented"),
        ("Bellroy", "bellroy.com", "Carry Ecosystem", "Slim wallets to travel bags; hidden features; Australian design; expanded to full carry ecosystem"),
        ("Aer", "aersf.com", "Gym-to-Work", "Bags for gym-to-office commute; shoe compartment; tech organization; SF designed; $30M+ revenue"),
        ("Nomatic", "nomatic.com", "Travel Organizer", "Kickstarter $5M+; travel packs with organization obsession; digital nomad bible; packing cubes"),
        ("Tom Bihn", "tombihn.com", "Thoughtful Bags", "Seattle-made; obsessive organization; O-ring accessories; made in USA; 30-year cult following"),
        ("Evergoods", "evergoods.us", "Crossover Packs", "Ex-Patagonia and ex-GORUCK designers; CPL24 crossover backpack; outdoor + urban; minimal, functional"),
        ("Black Ember", "blackember.com", "Modular Bags", "Modular attachment system; hex grid; weatherproof materials; urban tactical aesthetic; $200-400"),
        ("Able Carry", "ablecarry.com", "Hong Kong Bags", "Daily Backpack Max; X-Pac fabric; thoughtful organization; Hong Kong designed; minimal + functional"),
        ("Agazzi", "agazzi.co", "Colombian Bags", "Handcrafted Colombian leather bags; artisan-made; direct-to-consumer luxury; ethical sourcing"),
        ("Mujjo", "mujjo.com", "Leather Tech", "Full leather iPhone cases and touchscreen gloves; Dutch design; $50 cases; premium minimalism"),
        ("Nomad", "nomadgoods.com", "Tech Leather", "Horween leather iPhone cases and Apple Watch straps; MagSafe ecosystem; premium + functional"),
        ("Pad & Quill", "padandquill.com", "Leather Tech", "Leather MacBook sleeves and iPhone wallets; book-style cases; Minneapolis craftsmanship"),
        ("Woolnut", "woolnut.com", "Nordic Tech", "Swedish leather + wool laptop sleeves; MacBook-specific fit; Scandinavian minimalism; premium"),
        ("Native Union", "nativeunion.com", "Design Tech", "Marble Edition chargers; BELT cable; design-forward tech accessories; Paris-based; premium"),
    ],

    "Niche Wellness Brands": [
        ("Ned", "helloned.com", "Full Spectrum CBD", "Farmer-grown hemp CBD; USDA organic; high-quality full-spectrum oils; Colorado farm"),
        ("Cured Nutrition", "cfrured.com", "Functional Supps", "CBD + mushroom + adaptogen blends; Night Caps sleep formula; Colorado-based; holistic stack"),
        ("Reishi", "realfunghi.com", "Mushroom Coffee", "Mushroom-infused coffee and elixirs; functional fungi; adaptogenic mushrooms in every cup"),
        ("Rainbo", "mfrrainbo.com", "Mushroom Tinctures", "Canadian functional mushroom tinctures; 11:11 Super Multi Mushroom; alcohol-free extraction"),
        ("Host Defense", "hostdefense.com", "Paul Stamets Mushrooms", "Paul Stamets' mushroom brand; MyCommunity mushroom complex; mycological research foundation"),
        ("Om Mushrooms", "ommfrush.com", "Mushroom Powder", "Organic functional mushroom powders; Master Blend with 10 mushrooms; $50M+ revenue"),
        ("Real Mushrooms", "realmushrooms.com", "Extract Mushrooms", "100% mushroom extracts (no filler grains); beta-glucan tested; most transparent mushroom brand"),
        ("Clevr Blends", "clevrblends.com", "SuperLattes", "Meghan Markle invested; mushroom + adaptogen lattes; Golden SuperLatte; oat milk latte blends"),
        ("Apothékary", "apfrthekary.co", "Herbal Wellness", "Wine Down herbal blend went viral as alcohol alternative; plant-based wellness; functional herbs"),
        ("Cure Hydration", "curehydration.com", "Plant Electrolytes", "Coconut water-based hydration mix; WHO formula; plant-based; Lauren Picasso founded; clean label"),
        ("Drink Simple", "drinksimple.com", "Maple Water", "Organic maple water from Vermont trees; naturally occurring electrolytes; subtle sweetness; unique"),
        ("Harmless Harvest", "harmlessharvest.com", "Organic Coconut Water", "Fair Trade organic coconut water; naturally pink; Thailand-sourced; $100M+ revenue"),
        ("REBBL", "rebbl.co", "Super Herb Elixirs", "Plant-based elixirs with adaptogens; Reishi Chocolate, Maca Mocha; B Corp; fair trade sourcing"),
        ("Health-Ade Kombucha", "health-ade.com", "Kombucha", "Small-batch kombucha in glass bottles; Pink Lady Apple is bestseller; $100M+ revenue; LA-founded"),
        ("GT's Kombucha", "gfrtskombucha.com", "OG Kombucha", "Original commercial kombucha brand; GT Dave started at 15; Synergy line; $500M+ revenue; OG"),
        ("Brew Dr.", "brewdrkombucha.com", "Tea-Based Kombucha", "Portland tea house turned kombucha brand; organic whole leaf tea base; $50M+ revenue"),
        ("Olipop", "drinkolipop.com", "Prebiotic Soda", "Healthy soda with plant fiber + prebiotics; $200M+ revenue; 2,128% growth; 'vintage soda, new gut'"),
        ("Poppi", "drinkpoppi.com", "ACV Soda", "Apple cider vinegar soda; Shark Tank to PepsiCo ~$2B acquisition; Allison Ellsworth's comeback"),
        ("Waterloo", "drinkwaterloo.com", "Texas Sparkling", "Austin-born; bold fruit flavors; fastest-growing sparkling water; $100M+; compete with LaCroix"),
        ("Topo Chico", "topochicousa.com", "Mexican Mineral", "Monterrey mineral water with cult following; Coca-Cola acquired; bar/restaurant essential; OG fizz"),
    ],

    "Niche Fashion 2": [
        ("Buck Mason", "buckmason.com", "Venice Beach Basics", "Curved Hem Tee is hero; 'less, better' philosophy; Venice Beach origin; one of each essential perfected"),
        ("Marine Layer", "marinelayer.com", "Absurdly Soft", "Re-Spun program recycles old tees; proprietary soft fabric; SF heritage; sustainability + comfort"),
        ("Faherty", "faherty.com", "Coastal Brothers", "Twin brothers; sun-washed surf-inspired; Sunwashed fabric proprietary; Hamptons meets SoCal lifestyle"),
        ("Taylor Stitch", "taylorstitch.com", "Crowdfunded Fashion", "Every product crowdfunded (only makes what's pre-ordered); near-zero waste; responsible materials"),
        ("Iron and Resin", "ironandresin.com", "Moto Heritage", "Ventura, CA motorcycle-inspired workwear; camp collar shirts; vintage Americana; adventure ready"),
        ("Corridor", "corridornyc.com", "Brooklyn Menswear", "Hand-painted fabrics; Brooklyn artisan menswear; limited runs; collaborative design process"),
        ("18 East", "18eastfrshop.com", "Global Menswear", "Antonio Ciongoli's brand; Indian block prints, Japanese fabrics; global textile traditions modernized"),
        ("Bode", "bodenewyork.com", "Vintage Rework", "Emily Adams Bode reworks vintage textiles into new garments; LVMH Prize finalist; one-of-a-kind"),
        ("Story Mfg", "storymfg.com", "Hand-Dyed Fashion", "British brand; natural dyes, hand-weaving; anti-fast-fashion; meditation and craft philosophy"),
        ("Phipps", "phipps.international", "Eco Luxury", "Spencer Phipps' sustainable luxury sportswear; recycled materials; Pitti Uomo debut; eco-conscious luxury"),
        ("S.K. Manor Hill", "skmanorhill.com", "DC Menswear", "Washington DC-based menswear; workwear meets tailoring; American-made; small-batch production"),
        ("Kestin", "kestin.co", "Scottish Menswear", "Edinburgh-designed menswear; Scottish heritage fabrics; technical outdoor influence; emerging"),
        ("Universal Works", "universalworks.co.uk", "Nottingham Casual", "David Keyte's British casual wear; bakers' jackets, fatigue pants; 15+ year heritage"),
        ("Percival", "percivalclo.com", "London Menswear", "Great British menswear; bold prints on classic silhouettes; quality at £100-200 range"),
        ("A Kind of Guise", "akindofguise.com", "Munich Fashion", "German brand with global textile sourcing; Mediterranean influence; elevated casual wear"),
        ("De Bonne Facture", "debfrnfrtfrfr.com", "French Craft", "Made in France from exceptional materials; artisanal shirting; $300+ shirts; French manufacturing heritage"),
        ("Luca Faloni", "lucafaloni.com", "Italian Direct", "Italian cashmere, linen, cotton direct from artisans; $200-400; cutting out luxury markup"),
        ("Frescobol Carioca", "frescobolcarioca.com", "Brazilian Resort", "Rio de Janeiro-inspired resort wear; swim shorts and linen shirts; beach club aesthetic"),
        ("Orlebar Brown", "orlebarbrown.com", "Tailored Swim", "The tailored swim short; James Bond wore them in Skyfall; $250+ shorts; British resort luxury"),
        ("Vilebrequin", "vilebrequin.com", "St-Tropez Swim", "French luxury swim since 1971; father-son matching sets; $200+ trunks; Riviera heritage"),
    ],

    "Niche Pet 2": [
        ("Yummers", "yummers.com", "Meal Toppers", "Freeze-dried meal toppers; make kibble exciting; 'sprinkle some yum'; fun packaging"),
        ("Portland Pet Food", "portfrandpetfood.com", "Human-Grade", "Human-grade dog food made in Portland; grain-free toppers; local sourcing; $10M+ revenue"),
        ("Maev", "maev.com", "Raw Dog Food", "Raw food bars for dogs; human-grade ingredients; subscription model; 'because dogs deserve raw'"),
        ("Raised Right", "raisedright.com", "Human-Grade", "USDA human-grade pet food; gently cooked; veterinary-formulated; transparent sourcing"),
        ("Side by Side", "sidebysidepet.com", "Ancient Grain", "Ancient grain dog food with superfoods; veterinarian-created; heritage grains + modern nutrition"),
        ("Wag", "wagfood.com", "Amazon Brand", "Amazon's own dog food brand; $10-20 bags; competitive pricing; leveraging Amazon distribution"),
        ("Shameless Pets", "shamelesspets.com", "Upcycled Treats", "Dog treats from upcycled ingredients (surplus sweet potatoes, blueberries); sustainability + pets"),
        ("Bocce's Bakery", "bfrccfrs.com", "Bakery Treats", "Dog treats baked with 5 ingredients; wheat-free; bakery-quality for dogs; $50M+ revenue"),
        ("Portland Pet Food", "portlandpetfood.com", "Toppers", "Handmade dog food toppers; Hopkins Pork, Tuxedo's Chicken; Portland, Oregon artisanal pet food"),
        ("The Bear & The Rat", "befrrandrat.com", "Frozen Yogurt", "Frozen yogurt for dogs; probiotic-packed; cool treat; co-founders appeared on Shark Tank"),
        ("Earth Animal", "earthfranimal.com", "Holistic Pet", "Holistic pet wellness since 1979; No-Hide chews (first rawhide alternative); clean pet care pioneer"),
        ("Stella & Chewy's", "stellaandchewys.com", "Raw Pioneer", "Freeze-dried raw pioneer; Marie Moody's rescue dog inspiration; premium nutrition category creator"),
        ("Primal Pet Foods", "primalpetfoods.com", "Raw Frozen", "Frozen raw pet food; free-range proteins; organic produce; high-pressure processed for safety"),
        ("Vital Essentials", "vfritalfrrssfrntials.com", "Freeze-Dried Raw", "Single-ingredient freeze-dried treats and food; wild-caught, farm-raised proteins; simple raw"),
        ("Instinct", "instfrnctpetfood.com", "Raw Boost", "Raw Boost kibble topped with freeze-dried raw pieces; best of both worlds; Nature's Variety brand"),
    ],

    "Niche Home Electronics": [
        ("Sonos", "sonos.com", "Wireless Audio", "Multi-room speaker system; $1.5B+ revenue; won Google patent case; Trueplay room tuning"),
        ("Dyson", "dyson.com", "Home Tech", "Vacuum, fan, air purifier, hair tools empire; 5,127 prototypes; $7.7B revenue; engineering religion"),
        ("iRobot", "irobot.com", "Robot Vacuums", "Roomba created the category; $1.4B Amazon acquisition attempt; 40M+ robots sold; home cleaning AI"),
        ("Roborock", "roborock.com", "Robot Mop-Vac", "S8 Pro Ultra: vacuum + mop + self-wash + self-empty; LiDAR navigation; $500M+ revenue; Xiaomi-backed"),
        ("Dreametech", "dreametech.com", "Cleaning Robots", "L20 Ultra: mop raises when on carpet; hot water self-washing; Chinese engineering excellence"),
        ("Ecovacs", "ecovacs.com", "Deebot Robots", "DEEBOT X2 Omni: square design cleans corners; YIKO voice assistant; Chinese market leader; global expansion"),
        ("Tineco", "tineco.com", "Smart Floor Care", "FLOOR ONE S7 Pro: smart wet/dry vacuum with sensors; iLoop adjusts suction; TikTok cleaning favorite"),
        ("Narwal", "narwal.com", "Self-Cleaning Mop", "Freo: robot mop that washes and dries its own mop pads with clean water; hands-free floor care"),
        ("Eufy", "eufylife.com", "Local Smart", "No monthly fees; local storage; privacy-first security cameras; Anker brand; $50-200 price range"),
        ("Aqara", "aqara.com", "Smart Sensors", "Zigbee/Matter sensors for $10-30; door, motion, temperature; Apple HomeKit; incredible value"),
        ("Eve", "evehome.com", "Privacy Smart Home", "Apple HomeKit exclusive; no cloud; Thread + Matter; German engineering; privacy-first smart home"),
        ("Wiz", "wizconnected.com", "Budget Smart Light", "Signify's budget smart bulbs; WiFi direct; no hub; $8 bulbs; connected to Philips Hue ecosystem"),
        ("Meross", "meross.com", "Budget Smart Home", "HomeKit smart plugs under $15; garage door opener; smart switches; Chinese brand; best budget option"),
        ("Midea", "midea.com", "Smart Appliances", "$45B Chinese appliance giant; U-shaped window AC; smart home ecosystem; value meets innovation"),
        ("Anker", "anker.com", "Power & Audio", "PowerCore banks, Soundcore earbuds, eufy cameras; Amazon-first to $2B+; trust built on reviews"),
    ],
}