"""
Final batch 2 - only brands NOT in any other file.
"""

FINAL_BRANDS_2 = {
    "DTC Fashion - Emerging": [
        ("Pangaia", "thepangaia.com", "Bio Materials", "FLWRDWN insulation; seaweed fiber; $245M valuation; science materials for fashion; bio-tech meets streetwear"),
        ("Les Tien", "lfrsten.com", "LA Luxury Basics", "Heavyweight cotton basics; Yacht shorts, snap hoodies; celeb favorite; $100+ tees justified"),
        ("Entireworld", "theentireworld.com", "Color Basics", "Scott Sternberg (ex-Band of Outsiders); color-coded system; playful numbering; organic cotton"),
        ("Naked Cashmere", "nfrkfrdcfrshfrm.com", "Budget Cashmere", "Cashmere sweaters at $50-100 (vs $300+ traditional); direct sourcing; DTC cashmere disruptor"),
        ("Cos", "cosstores.com", "Modern Essential", "H&M Group elevated brand; Scandinavian minimalism; architectural stores; quality basics with design"),
        ("Arket", "arket.com", "Nordic Everyday", "H&M Group's 'modern-day market'; vegetable-tanned leather; transparent pricing; cafes in stores"),
        ("Toast", "tfrast.co.uk", "British Slow Fashion", "UK slow fashion; natural dyes; handwoven fabrics; 25+ year heritage; anti-trend timelessness"),
        ("Margaret Howell", "margarethowell.co.uk", "British Heritage", "British modernist design; quality fabrics; understated luxury; 50+ year heritage"),
        ("A.P.C.", "apc.fr", "French Minimal", "Jean Touitou's Parisian minimalism; raw denim is cult; Petit Standard; $200M+ revenue"),
        ("Norse Projects", "norseprojects.com", "Copenhagen Style", "Danish menswear; technical fabrics meet Scandinavian clean design; Gore-Tex collaborations"),
        ("Our Legacy", "ourlegacy.com", "Stockholm Fashion", "Swedish brand with artistic edge; Work Shop vintage concept; unique fabrics; growing cult"),
        ("Stine Goya", "stinegoya.com", "Danish Color", "Copenhagen color queen; bold prints and patterns; Scandi fashion that ISN'T minimal; joy dressing"),
        ("Ganni", "ganni.com", "Scandi Fun", "#GanniGirls; leopard print + smiley face; Scandi 2.0; $200M+ revenue; responsible fashion"),
        ("Samsøe Samsøe", "samsoe.com", "Danish Design", "Copenhagen everyday premium; clean lines; affordable luxury; 30+ year Scandinavian heritage"),
        ("Closed", "closed.com", "German Denim", "German slow fashion; Italian-made denim; sustainable since before it was trendy; 45+ year heritage"),
        ("Belstaff", "belstaff.com", "British Motor", "Waxed cotton jackets; motorcycle heritage since 1924; worn in James Bond; Che Guevara's brand"),
        ("Woolrich", "woolrich.com", "American Heritage", "Oldest outdoor clothing brand in US (1830); Arctic Parka; buffalo check; $500M+ revenue"),
        ("Pendleton", "pendleton-usa.com", "Wool Heritage", "Wool blankets and shirts since 1863; Native American-inspired designs; Portland, Oregon heritage"),
        ("Barbour", "barbour.com", "British Wax", "Waxed jacket royalty; Royal Warrants; 130+ year heritage; rewaxing service; $300M+ revenue"),
        ("Schott NYC", "schottnyc.com", "Leather Jackets", "Invented the motorcycle jacket in 1928 (Perfecto); James Dean, Marlon Brando; made in USA; heritage"),
    ],

    "DTC Health - Testing & Diagnostics": [
        ("Everlywell", "everlywell.com", "At-Home Tests", "FDA-authorized home lab tests; food sensitivity, thyroid, STI; Shark Tank; $500M+ valuation"),
        ("LetsGetChecked", "letsgetchecked.com", "Home Health", "STI, fertility, cholesterol home tests; nurse consultations; $500M+ valuation; telehealth"),
        ("Modern Fertility", "modernfertility.com", "Fertility Test", "Fertility hormone test for $159 vs $1,500+ at clinic; Ro acquired; empowering women with data"),
        ("23andMe", "23andme.com", "DNA Testing", "Consumer genetics pioneer; 12M+ customers; health + ancestry; FDA-authorized; $3.5B peak valuation"),
        ("AncestryDNA", "ancestry.com", "DNA Ancestry", "Largest DNA database (20M+); genealogy + health reports; family tree building; $3B+ revenue"),
        ("Viome", "viome.com", "Microbiome Test", "Gut microbiome testing + personalized supplements; AI analyzes your gut bacteria; $100M+ raised"),
        ("ZOE", "joinzoe.com", "Nutrition Science", "Personalized nutrition from continuous glucose + gut microbiome data; Tim Spector's science; $100M+ raised"),
        ("Vessel Health", "vesselhealth.com", "Urine Testing", "At-home wellness card tests nutrition deficiencies from urine; personalized supplement recs; app"),
        ("SiO Beauty", "sfrio.com", "Wrinkle Patches", "Medical-grade silicone patches smooth wrinkles overnight; clinically proven; dermatologist-backed"),
        ("Nutrisense", "nutrisense.io", "CGM Tracking", "Continuous glucose monitor + dietitian support; see how food affects blood sugar; metabolic health"),
        ("Levels", "levelshealth.com", "Metabolic Health", "CGM for non-diabetics; 'metabolic fitness'; see glucose spikes from food in real-time; $100M+ raised"),
        ("Lumen", "lumen.me", "Breath Metabolism", "Breath analyzer measures if burning fat or carbs; personalized nutrition from CO2 analysis; $80M+ raised"),
        ("Elo Health", "elo.health", "Smart Supplements", "Blood biomarker testing + AI-personalized supplements; adapt formula based on your data; dynamic"),
        ("Wild Health", "wildhealth.com", "Precision Medicine", "Genomics + continuous monitoring for personalized health optimization; concierge medicine + tech"),
        ("Function Health", "functionhealth.com", "Comprehensive Testing", "100+ lab tests for $500/year; track everything; Jonathan Hsu (Tribe Capital) founded; data-heavy"),
    ],

    "DTC Home - Outdoor Living": [
        ("Outer", "liveouter.com", "Outdoor Furniture", "Built-in OuterCover rolls up from sofa back; Neighborhood Showrooms in people's backyards; innovative"),
        ("Yardbird", "yardbird.com", "Recycled Outdoor", "Furniture from recycled ocean plastic; beautiful outdoor sets; DTC outdoor; $100M+ revenue"),
        ("Neighbor", "neighbor.com", "Outdoor Furniture", "Aluminum outdoor furniture that's modular; weather-resistant; $3K-6K sets; premium outdoor living"),
        ("Polywood", "polywood.com", "Recycled Furniture", "Furniture from recycled milk jugs; 250M+ jugs recycled; Adirondack chairs; 20-year warranty"),
        ("Loll Designs", "lfrlldesigns.com", "Recycled Outdoor", "Modern outdoor furniture from 100% recycled plastic; Duluth, Minnesota made; colorful; design-forward"),
        ("Solo Stove", "solostove.com", "Fire Pits", "Smokeless fire pit via airflow engineering; Snoop Dogg campaign; $400M+ revenue; backyard essential"),
        ("Breeo", "breeo.co", "Fire Pits", "Smokeless fire pit with sear plate attachment; X Series; grill directly on fire pit; multi-function"),
        ("BioLite", "bioliteenergy.com", "FirePit+", "Smokeless FirePit with Bluetooth fan control; also charges devices from fire; campfire reimagined"),
        ("Pit Barrel Cooker", "pitbarrelcooker.com", "Drum Smoker", "Vertical drum smoker; hang & forget method; $200; easiest BBQ smoker; great results with minimal effort"),
        ("Weber", "weber.com", "Grills", "Invented kettle grill (1952); Weber Connect smart grilling; $2B+ revenue; American grilling icon"),
        ("Traeger", "traeger.com", "Pellet Grills", "Invented wood pellet grills; WiFIRE app control; $500M+ revenue; Joe Traeger's 1985 innovation"),
        ("Ooni", "ooni.com", "Pizza Ovens", "Portable pizza oven reaches 950°F in 20 min; Kickstarter origin; $100M+ revenue; backyard pizzeria"),
        ("Bertello", "bertfrllo.com", "Pizza Oven", "Shark Tank pizza oven; multi-fuel (wood, charcoal, gas); $200 vs Ooni's $400; value play"),
        ("EGO Power+", "egopowerplus.com", "Battery Outdoor", "Battery-powered lawn mowers, blowers, chainsaws; 56V Arc Lithium; gas-performance, no emissions"),
        ("Greenworks", "greenworkstools.com", "Electric Outdoor", "Battery-powered outdoor tools; 40V/60V/80V platforms; commercial-grade; eco-friendly lawn care"),
    ],

    "DTC Baby - Expanded": [
        ("Babyganics", "babyganics.com", "Natural Baby", "Plant-based baby care; sunscreen, cleaning, skincare; SC Johnson owned; 'baby safe world' mission"),
        ("Hello Bello", "hellobello.com", "Kristen Bell Baby", "Kristen Bell + Dax Shepard's brand; premium diapers at Walmart prices; plant-based; accessible"),
        ("Dyper", "dyper.com", "Bamboo Diapers", "Bamboo viscose diapers; REDYPER compostable program; mail back used diapers; carbon-negative"),
        ("Kudos", "mykudos.com", "Plant-Based Diapers", "First-ever plant-based disposable diaper with cotton interior; better for baby skin + environment"),
        ("Rascal + Friends", "rascalandfriends.com", "Value Diapers", "New Zealand brand; premium quality at affordable price; fastest-growing diaper brand; $100M+"),
        ("Pipette", "pipette.com", "Baby Skincare", "Clean baby skincare from Amyris (biotech); sugarcane-derived squalane; same science as Biossance"),
        ("Puracy", "puracy.com", "Plant Baby Care", "Plant-based baby care; 99.96% natural; developed by PhD biochemists; Amazon #1 baby soap"),
        ("Kendamil", "kendamil.com", "European Formula", "English Lake District-made; whole milk formula; Royal Warrant; only British infant formula; $100M+"),
        ("Serenity Kids", "myserenitykids.com", "Meat Baby Food", "First-ever meat-based baby food pouches; ethically sourced proteins; savory baby food pioneer"),
        ("Square Baby", "squarebaby.com", "Balanced Baby", "100% Daily Nutrition baby food system; doctor-created; every meal is nutritionally complete"),
        ("Yumi", "helloyumi.com", "Fresh Baby Food", "Fresh organic baby food in jars; nutritionist-designed; glass packaging; $50M+ raised"),
        ("Amara", "amfrfrafrga.com", "Dried Baby Food", "Organic dried baby food — just add breast milk/water; preserves nutrients; no preservatives; lightweight"),
        ("Stokke", "stokke.com", "Scandinavian Baby", "Tripp Trapp chair grows from baby to adult; Sleepi crib; Norwegian design; $300+ items with lifetime value"),
        ("Clek", "clek.com", "Car Seats", "Canadian car seats; Foonf is most reviewed convertible; GREENGUARD Gold certified; safety + sustainability"),
        ("Nuna", "nunababy.com", "Dutch Baby", "Dutch-designed premium baby gear; RAVA car seat; MIXX stroller; minimalist European aesthetic"),
    ],

    "DTC Spirits & Cocktails": [
        ("Drizly", "drizly.com", "Alcohol Delivery", "Uber of alcohol delivery; 60-min delivery; Uber acquired for $1.1B; largest online alcohol marketplace"),
        ("Minibar Delivery", "minibardelivery.com", "Wine Delivery", "Same-day alcohol delivery; curated wine, spirits, beer; premium selection; $100M+ GMV"),
        ("Flaviar", "flaviar.com", "Spirits Club", "Quarterly spirits subscription; tasting boxes; 'the Netflix of spirits'; 150K+ members; education-driven"),
        ("Taster's Club", "tastersclub.com", "Whiskey Club", "Curated whiskey subscription; rare and limited editions; expert-selected; 50K+ members"),
        ("ReserveBar", "reservebar.com", "Premium Spirits", "Luxury spirits e-commerce; exclusive bottles; gift-ready packaging; Diageo, LVMH partnerships"),
        ("CaskCartel", "caskcartel.com", "Rare Spirits", "Rare and allocated spirits marketplace; hard-to-find whiskeys; premium secondary market"),
        ("Sipsmith", "sipsmith.com", "London Gin", "Copper-pot distilled London Dry Gin; first copper pot distillery in London in 200 years; Beam Suntory"),
        ("Hendrick's", "hendricksgin.com", "Cucumber Gin", "Infused with cucumber and rose; distinctly quirky branding; $500M+ revenue; Grant's family distillers"),
        ("Empress 1908", "empress1908.com", "Color-Changing Gin", "Butterfly pea flower turns gin purple; changes color with tonic; Instagram-famous; Victoria, BC"),
        ("Aviation Gin", "aviationgin.com", "Ryan Reynolds Gin", "Ryan Reynolds bought, marketed with humor, sold to Diageo for $610M; greatest celeb brand play"),
        ("Teremana", "teremana.com", "The Rock Tequila", "Dwayne Johnson's tequila; 600K cases in Year 1; fastest-growing spirits brand; accessible $30 price"),
        ("818 Tequila", "drink818.com", "Kendall Jenner", "Kendall Jenner's tequila; won World Tequila Awards before launch; 130K cases Year 1; controversial"),
        ("Código 1530", "codigo1530.com", "Artisanal Tequila", "George Strait co-owns; aged in French oak Napa wine barrels; ultra-premium small-batch tequila"),
        ("Cincoro", "cincoro.com", "NBA Tequila", "Michael Jordan + 4 NBA team owners created; luxury tequila; $60-1,600 range; ultra-premium positioning"),
        ("Casa Del Sol", "casadelsol.com", "Eva Longoria", "Eva Longoria's tequila; aged in cognac barrels; luxury reposado; female-founded premium spirits"),
    ],

    "DTC Jewelry - Fine & Lab": [
        ("VRAI", "vrai.com", "Lab Diamonds", "Diamond Foundry retail brand; Leo DiCaprio invested; zero-emission foundry; fully traceable"),
        ("Brilliant Earth", "brilliantearth.com", "Ethical Diamonds", "Beyond Conflict Free; virtual try-on AR; $400M+ revenue; IPO'd; most trusted online diamonds"),
        ("Clean Origin", "cleanorigin.com", "Lab-Only", "100% lab-grown diamonds; 20-40% less than mined; eco-friendly; conflict-free; modern bridal"),
        ("With Clarity", "withclarity.com", "Home Preview", "AI ring recommender; mail a replica ring to try at home before buying; personalized experience"),
        ("James Allen", "jamesallen.com", "360° Diamonds", "360° HD diamond photography; see every facet before buying; $500M+ revenue; Signet owned"),
        ("Blue Nile", "bluenile.com", "OG Online Diamonds", "Online diamond pioneer since 1999; saved buyers 20-40% vs retail; Signet acquired; $500M+"),
        ("Catbird", "catbirdnyc.com", "Brooklyn Fine", "Permanent jewelry (welded-on bracelets) pioneer; delicate, romantic; threadbare ring; Brooklyn-made"),
        ("Stone and Strand", "stoneandstrand.com", "Delicate Fine", "Delicate fine jewelry for everyday layering; diamond dusting technique; NYC-designed; $50-500"),
        ("The Last Line", "thelastline.com", "Colorful Fine", "Rainbow gemstone jewelry; breaking fine jewelry conventions; playful luxury; $200-2,000 range"),
        ("Dorsey", "bydorsey.com", "Lab Gemstones", "Lab-grown colored gemstones (emerald, sapphire, ruby); modern settings; affordable luxury $200-500"),
        ("Studs", "studs.com", "Piercing + Jewelry", "Reinvented ear piercing; earscape curation; clean studios; Gen Z piercing destination; NYC + expanding"),
        ("Maison Miru", "maisonmiru.com", "Ear Curation", "Ear curation jewelry designed for curated multi-piercing looks; NYC-based; starter sets"),
        ("Moon Magic", "moonmagic.com", "Moonstone Jewelry", "Moonstone and labradorite jewelry; rainbow flash stones; bohemian luxury; $50M+ revenue"),
        ("Mejuri", "mejuri.com", "Self-Purchase Fine", "Fine jewelry 'you don't need a man to buy'; self-purchase positioning; $100M+ revenue; gold vermeil to solid gold"),
        ("Foundrae", "foundrae.com", "Symbol Jewelry", "Each piece carries meaning (strength, protection, resilience); Beth Bugdaycay's 'modern heirlooms'; NYC"),
    ],

    "DTC Fitness Equipment 2": [
        ("Rogue Fitness", "roguefitness.com", "Gym Equipment", "CrossFit Games official; $500M+ revenue; Columbus, Ohio made; American manufacturing; barbells + racks"),
        ("REP Fitness", "repfitness.com", "Value Home Gym", "Best value gym equipment; power racks and benches at 30-50% less than Rogue; $100M+ revenue"),
        ("Titan Fitness", "titanfitness.com", "Budget Gym", "Budget home gym equipment; Rogue-quality for half the price; $100M+ revenue; value positioning"),
        ("Bells of Steel", "bellsofsteel.com", "Canadian Gym", "Canadian gym equipment brand; Blitz barbells; good quality at fair Canadian prices; $50M+"),
        ("Kabuki Strength", "kabfrukistrength.com", "Specialty Bars", "Duffalo Bar, Trap Bar, Kadillac Bar; specialty barbells for powerlifters; Chris Duffin's engineering"),
        ("EliteFTS", "elitefts.com", "Powerlifting", "Dave Tate's powerlifting equipment and education; S4 Compound; for serious strength athletes"),
        ("Sorinex", "sorinex.com", "Custom Gym", "Custom gym design for NFL, NCAA, military; handmade in South Carolina; premium commercial fitness"),
        ("GHD", "roguefitness.com", "Glute Machine", "Glute-ham developer; posterior chain essential; every CrossFit box has one; $400-800 machine"),
        ("Assault Fitness", "assaultfitness.com", "Air Bike", "AssaultBike = 'the most brutal cardio'; unlimited fan resistance; CrossFit Games staple"),
        ("Concept2", "concept2.com", "Rowing Machine", "Model D rower used by every Olympic team; SkiErg; BikeErg; the gold standard; Vermont-made"),
        ("WaterRower", "waterrower.com", "Wood Rower", "Ash wood water resistance rower; featured in House of Cards; beautiful furniture-grade design"),
        ("Schwinn IC4", "schwinn.com", "Indoor Bike", "Best value indoor cycling bike; Peloton app compatible; $800 vs $2,500; mainstream fitness"),
        ("NordicTrack", "nordictrack.com", "iFIT Connected", "iFIT-powered; auto-adjust incline/speed following trainers; treadmills, bikes, rowers; $1B+ revenue"),
        ("ProForm", "proform.com", "Value Connected", "NordicTrack's value brand; studio-quality at lower price; iFIT integration; $500-1,500 machines"),
        ("Life Fitness", "lifefitness.com", "Commercial Grade", "Most common commercial gym equipment; Hammer Strength brand; $1B+ revenue; gym industry standard"),
    ],

    "DTC Cleaning & Household": [
        ("Shark", "sharkclean.com", "Vacuum & Clean", "Navigator, Rocket vacuums; HydroVac mop; competitor to Dyson at lower price; $2B+ revenue"),
        ("Bissell", "bissell.com", "Carpet & Pet", "Little Green portable cleaner is cult; CrossWave; pet-focused cleaning; $1B+ revenue; family-owned"),
        ("Roomba", "irobot.com", "Robot Vacuum", "Created robot vacuum category; j7+ avoids obstacles (including pet waste); 40M+ sold; $1.4B Amazon deal"),
        ("Miele", "miele.com", "German Premium", "Vacuums, dishwashers, laundry last 20 years; $5B+ revenue; 'Immer Besser'; premium German engineering"),
        ("Clorox", "clorox.com", "Disinfecting", "$7B+ revenue; pandemic essential; Clorox wipes had year-long shortage; America's cleaning staple"),
        ("Lysol", "lysol.com", "Disinfecting", "Reckitt Benckiser's $2B+ brand; Laundry Sanitizer launched in pandemic; trusted for 130+ years"),
        ("Scrub Daddy", "scrubdaddy.com", "Sponge Innovation", "Shark Tank's most successful product ($250M+ revenue); temperature-responsive FlexTexture sponge"),
        ("The Pink Stuff", "thepinkstuff.com", "UK Cleaning Paste", "TikTok viral cleaning paste from UK; all-purpose; $100M+ revenue from social media virality alone"),
        ("Bar Keepers Friend", "bfrrkfrpfrs.com", "Powder Cleanser", "130+ year old oxalic acid cleanser; cleans stainless steel, copper, glass; $50M+ revenue; cult classic"),
        ("Dawn", "dawn.com", "Dish Soap", "Used to clean oil-spill wildlife; Powerwash dish spray went viral; $1B+ P&G brand; trusted"),
        ("Caldrea", "caldrea.com", "Premium Clean", "Luxury home care with complex scents; Mrs. Meyer's premium sister; SC Johnson; elevated cleaning"),
        ("MRS. SMITH'S", "mrfrsmfrrths.com", "Heritage Clean", "Traditional cleaning formulas with modern sustainability; UK heritage brand; trustworthy basics"),
        ("Attitude", "attitudeliving.com", "Canadian Clean", "EWG-verified natural cleaning; plant and mineral-based; CO2-neutral; Canadian; affordable eco"),
        ("Better Life", "betterlife.com", "Non-Toxic", "Founders' kids inspired non-toxic cleaning; What-EVER! all-purpose spray; plant-derived; safe"),
        ("Aunt Fannie's", "auntfannies.com", "Vinegar Clean", "Vinegar-based floor cleaner and cleaning wipes; $20M+ revenue; natural + effective"),
    ],

    "DTC Art & Prints": [
        ("Desenio", "desenio.com", "Scandi Prints", "Swedish poster prints and frames; gallery wall builder tool; $100M+ revenue; affordable art"),
        ("Juniper Print Shop", "jfrnipfrprintshop.com", "Curated Art", "Curated art prints from independent artists; gallery wall sets; affordable original art"),
        ("The Poster Club", "thefrstfrclub.com", "Design Prints", "Curated art poster shop; collaborations with artists worldwide; Danish design aesthetic"),
        ("King & McGaw", "kingfrndfrm.com", "Licensed Art", "Licensed art prints from Tate, V&A, British Museum; museum-quality reproductions; UK heritage"),
        ("20x200", "20x200.com", "Edition Prints", "Jen Bekman's art editions at $20, $200, $2,000; democratizing art collecting; limited editions"),
        ("Minted", "minted.com", "Community Art", "Crowdsourced designs voted on by community; limited edition prints; independent artists earn royalties"),
        ("Society6", "society6.com", "Artist Products", "Artists upload → printed on 80+ products; global artist marketplace; prints to phone cases to furniture"),
        ("Saatchi Art", "saatchiart.com", "Original Art", "World's largest online gallery; 1.5M+ original artworks; from $100 to $100K; gallery-quality online"),
        ("Artsy", "artsy.net", "Fine Art Market", "Online marketplace for galleries, auction houses, museums; 1M+ artworks; fine art democratized"),
        ("Etsy Art", "etsy.com", "Handmade Art", "Handmade and vintage art prints; independent creators; custom commissions; $13B+ total GMV platform"),
        ("Canvaspop", "canvaspop.com", "Photo Canvas", "Upload your photos → printed on premium canvas; hand-stretched; satisfaction guarantee"),
        ("Mixtiles", "mixtiles.com", "Stick-On Photos", "Photo tiles that stick to wall without damage; peel and re-stick; $8 per tile; $100M+ revenue"),
        ("Framebridge", "framebridge.com", "Custom Framing", "Mail art → get it framed and returned; 70% cheaper than local framers; democratized framing"),
        ("Level Frames", "levelframes.com", "Online Framing", "Upload → frame → ship; AR preview on wall; custom matting; starting at $39; simple process"),
        ("Artifact Uprising", "artifactuprising.com", "Premium Photo", "Premium photo books and prints; recycled materials; 'hold what matters'; quality keepsakes"),
    ],

    "DTC Food - Meal Kits & Delivery": [
        ("HelloFresh", "hellofresh.com", "Meal Kits", "World's #1 meal kit; $8B+ revenue; pre-portioned ingredients; 30+ recipes weekly; global scale"),
        ("Blue Apron", "blueapron.com", "OG Meal Kit", "Pioneered US meal kit delivery; $70M peak revenue; struggled post-IPO; culinary-focused recipes"),
        ("Home Chef", "homechef.com", "Kroger Meal Kit", "Kroger-owned; oven-ready and grill-ready options; 15-min meals; $1B+ revenue; grocery integration"),
        ("Green Chef", "greenchef.com", "Organic Meal Kit", "USDA-certified organic; keto, paleo, balanced options; HelloFresh owned; clean eating made easy"),
        ("EveryPlate", "everyplate.com", "Budget Meal Kit", "HelloFresh's $5/serving budget brand; simplified recipes; accessible meal kits for price-sensitive"),
        ("Dinnerly", "dinnerly.com", "Simple Meal Kit", "$5/serving; fewer ingredients per recipe (6 vs 10+); Marley Spoon brand; simplicity-first"),
        ("Gobble", "gobble.com", "15-Min Dinner", "Everything pre-prepped; 15-minute dinner kits; sous chef does the work; one-pan meals"),
        ("Freshly", "freshly.com", "Prepared Meals", "Ready-made meals — just microwave; Nestlé acquired; $430M revenue; convenience > cooking"),
        ("Factor", "factor75.com", "Chef Prepared", "Chef-prepared, dietitian-designed; keto, calorie smart, vegan; HelloFresh owned; fastest growing"),
        ("CookUnity", "cookunity.com", "Chef Marketplace", "Different chef creates each meal; restaurant quality at home; chef gets credited; $100M+ revenue"),
        ("Tovala", "tovala.com", "Smart Oven Meals", "Scan QR code → oven auto-cooks; $300 oven + weekly meal subscription; genius hardware + food pairing"),
        ("Methodology", "methodology.com", "Organic Premium", "100% organic prepared meals; Bay Area chefs; seasonal menus; premium healthy meal delivery"),
        ("Territory Foods", "territoryfoods.com", "Local Chef Meals", "Meals from local chefs; delivered fresh (not frozen); regional flavors; $30M+ revenue"),
        ("Snap Kitchen", "snapkitchen.com", "Macro Meals", "Macro-balanced prepared meals; keto, paleo, Whole30 options; ready in 2 minutes; fitness-focused"),
        ("Sunbasket", "sunbasket.com", "Organic Meal Kit", "USDA-certified organic meal kits; Mediterranean, paleo, pescatarian options; $400M+ peak revenue"),
    ],

    "DTC Home - Bathroom Products": [
        ("Jolie", "jolieskinco.com", "Shower Filter", "Filtered showerhead removes chlorine + heavy metals; better skin and hair; $165; influencer viral"),
        ("Brondell", "brondell.com", "Smart Bidet", "Bidet seats with heated water, dryer, heated seat; luxury bathroom technology; premium bath"),
        ("Kohler", "kohler.com", "Smart Bathroom", "Intelligent toilet + bidet in one; touchless faucets; $8B+ revenue; 150-year American heritage"),
        ("Moen", "moen.com", "Smart Faucets", "Flo smart water monitoring detects leaks; motion-sensor faucets; Fortune Brands; connected bathroom"),
        ("Poo-Pourri", "poopourri.com", "Toilet Spray", "'Spritz the bowl before you go'; eliminated bathroom odor taboo with humor; $100M+ revenue; viral ads"),
        ("Aqua Tru", "aquatru.com", "Countertop RO", "No-install reverse osmosis water purifier; removes 82 contaminants; NSF certified; clean water at home"),
        ("LARQ", "lfrq.com", "Self-Clean Bottle", "UV-C light purifies water and bottle in 60 seconds; $95; innovative tech water bottle"),
        ("Waterdrop", "waterdropfilter.com", "Tankless RO", "Compact tankless reverse osmosis; smart faucet with TDS display; modern water purification"),
        ("ZeroWater", "zerowater.com", "5-Stage Pitcher", "5-stage filtration removes virtually ALL dissolved solids; TDS meter included; purest filtered water"),
        ("Santevia", "santevia.com", "Alkaline Water", "Gravity water filter that adds minerals and alkalinity; 8-stage filtration; Canadian brand"),
        ("Clean Skin Club", "cleanskinclub.com", "Face Towels", "Disposable face towels to prevent bacteria (vs reusable towels); dermatologist-recommended; viral"),
        ("Kitsch", "mykitsch.com", "Shower Accessories", "Satin pillowcases, towel scrunchies, shampoo bars; affordable hair wellness accessories; TikTok viral"),
        ("Drybar", "thedrybar.com", "Blowout Tools", "Blowout bar turned product brand; Buttercup blow dryer; detangling brush; Alli Webb's empire"),
        ("Canopy", "getcanopy.co", "Bathroom Humidifier", "No-mist humidifier with aromatherapy; dishwasher-safe; beautiful design; anti-mold technology"),
        ("Vitruvi", "vitruvi.com", "Diffuser Design", "Stone-look ceramic diffuser; essential oil blends; elevated aromatherapy; decor-first approach"),
    ],

    "DTC Sports - Golf & Tennis": [
        ("Callaway", "callawaygolf.com", "Golf", "AI-designed drivers; $3.8B revenue after Topgolf acquisition; Apex irons; chrome balls; full ecosystem"),
        ("TaylorMade", "taylormadegolf.com", "Golf", "Stealth driver with carbon face; Tiger Woods, Rory McIlroy; $2B+ revenue; innovation leader"),
        ("Titleist", "titleist.com", "Golf", "Pro V1 is #1 ball in golf; used by more tour players than any other; Vokey wedges; $2B+ revenue"),
        ("Ping", "ping.com", "Golf", "Family-owned since 1959; G430 driver; custom fitting pioneer; engineering-first; Karsten Solheim legacy"),
        ("Cleveland Golf", "clevelandgolf.com", "Wedges", "RTX wedge line; CBX irons for mid-handicappers; SRI Sports owned; short game specialists"),
        ("Vice Golf", "vicegolf.com", "DTC Golf Balls", "Premium golf balls at half the price of Pro V1; direct-to-consumer; $15/dozen vs $50; disrupting"),
        ("Cut Golf", "cutgolf.com", "Value Golf Balls", "Tour-quality golf balls for $20/dozen; DTC model eliminates markup; 'the ball for the rest of us'"),
        ("Sunday Golf", "sundaygolf.com", "Lightweight Bags", "Ultralight golf bags for walking; 2 lb carry bags; making golf casual and fun; walk more, ride less"),
        ("Bad Birdie", "badbirdie.com", "Golf Fashion", "Bold print golf shirts; 'life's too short for boring shirts'; challenging country club dress codes"),
        ("Greyson", "greyson.com", "Golf Luxury", "Charlie Schaefer's modern golf fashion; Wolf logo; $200+ polos; the fashion-golf crossover"),
        ("Wilson", "wilson.com", "Tennis", "Blade, Pro Staff rackets; used by Federer (Pro Staff RF97); $1B+ revenue; sports equipment heritage"),
        ("Head", "head.com", "Tennis", "Speed, Radical, Extreme rackets; Djokovic uses Speed; Austrian brand; skiing + tennis; $400M+"),
        ("Babolat", "babolat.com", "French Tennis", "Pure Aero used by Nadal; oldest racket brand (1875); French heritage; 'Feel the Game'"),
        ("Yonex", "yonex.com", "Japanese Rackets", "EZONE and VCORE rackets; Osaka uses EZONE; Japanese precision engineering; badminton + tennis"),
        ("Prince", "prince.com", "Tennis Heritage", "Oversize racket inventor; Textreme technology; heritage brand revival; $100M+ revenue comeback"),
    ],

    "DTC Misc - Gifting & Unique": [
        ("Uncommon Goods", "uncommongoods.com", "Unique Gifts", "Brooklyn-based marketplace for creative, unique gifts; handmade focus; B Corp; $200M+ revenue"),
        ("Etsy", "etsy.com", "Handmade Market", "95M+ active buyers; 7M+ sellers; $13B+ GMV; 'keep commerce human'; powered the maker movement"),
        ("Giftagram", "giftagram.com", "App Gifting", "Send gifts via app/text; curated premium products; no address needed; modern gifting solution"),
        ("1-800-Flowers", "1800flowers.com", "Floral Gifting", "$2.2B revenue; Harry & David, Cheryl's Cookies portfolio; original gifting e-commerce; 1986 origin"),
        ("UrbanStems", "urbanstems.com", "Modern Flowers", "Same-day flower delivery; modern arrangements; Bumble + Vogue collabs; elevated floral gifting"),
        ("Bouqs", "bouqs.com", "Farm Flowers", "Farm-to-door flowers; volcano-grown roses; eco-friendly sourcing; subscription option; $100M+"),
        ("BloomsyBox", "bloomsybox.com", "Flower Sub", "Weekly/biweekly fresh flower subscription; direct from sustainable farms; farm-to-vase freshness"),
        ("Venus et Fleur", "venusetfleur.com", "Eternity Roses", "Roses that last a year+; luxury arrangements $300-500+; Kardashian-loved; preservation tech"),
        ("The Sill", "thesill.com", "Plant Gifting", "Indoor plants delivered safely; care guides; plant parent community; $50M+ revenue; 'plants make people happy'"),
        ("Terrain", "shopterrain.com", "Garden Living", "Anthropologie's garden + outdoor living brand; curated plants, tools, furniture; experiential retail"),
        ("Crate & Barrel", "crateandbarrel.com", "Home Gifting", "Wedding registry leader; European-inspired modern home; $1.5B+ revenue; 100+ stores; trusted quality"),
        ("Mark and Graham", "markandgraham.com", "Monogram Gifts", "Williams-Sonoma's personalization brand; monogrammed leather, accessories; premium personalized gifting"),
        ("Things Remembered", "thingsremembered.com", "Engraved Gifts", "Personalized engraved gifts; jewelry, frames, keepsakes; 30+ year heritage in personalization"),
        ("Shutterfly", "shutterfly.com", "Photo Gifts", "Photo books, cards, calendars, gifts; $2B+ revenue; Snapfish; largest custom photo product company"),
        ("Artifact Uprising", "artifactuprising.com", "Photo Keepsakes", "Premium photo books + prints; recycled materials; 'hold what matters'; quality > quantity approach"),
    ],
}