"""
Second batch of extra DTC brands to reach 3000+.
Format: (Brand, Website, Sub-niche, Notable Insight)
"""

EXTRA_BRANDS_2 = {
    "Fashion - Luxury DTC": [
        ("Anine Bing", "aninebing.com", "Scandi-LA", "Vintage rock meets Scandinavian minimalism; graphic tees + blazers; $100M+ revenue; influencer-founded"),
        ("Totême", "toteme-studio.com", "Quiet Luxury", "The Scarf Coat went viral; monogram silk scarf; Swedish quiet luxury; $100M+ revenue; Elin Kling"),
        ("Ganni", "ganni.com", "Scandi 2.0", "Not minimal but colorful; #GanniGirls community; leopard print + smiley face; Danish cool-girl brand"),
        ("Nanushka", "nanushka.com", "Vegan Leather", "Hungarian brand; chic vegan leather jackets and trench coats; sustainable luxury; plant-based materials"),
        ("Self-Portrait", "self-portrait-studio.com", "Occasion Wear", "Han Chong's $300-500 cocktail dresses; lace + structured; made designer-level occasion wear accessible"),
        ("Zimmermann", "zimmermann.com", "Australian Resort", "Resort wear for year-round; Paris runway; $2B+ valuation; Advent International acquired"),
        ("The Frankie Shop", "thefrankieshop.com", "Oversized Chic", "Oversized blazers and trousers; Bea and Gaelle Drevet; street-style darling; minimalist cool"),
        ("Rouje", "rouje.com", "French Fashion", "Jeanne Damas founded; Parisian cool-girl capsule; Gabin dress is bestseller; French Instagram queen"),
        ("Réalisation Par", "realisationpar.com", "Australian Fashion", "The Naomi silk skirt became the It-skirt; 90s-inspired prints; Australian co-founders"),
        ("House of Sunny", "houseofsunny.com", "London Fashion", "Hockney dress went viral on Kendall Jenner; London indie brand; prints and knits; TikTok-loved"),
        ("Rat & Boa", "ratandboa.com", "Going Out", "London brand for nights out; velvet, satin, bold prints; festival + party dressing; $50M+ revenue"),
        ("Meshki", "meshki.com.au", "Australian Trendy", "Melbourne-based; going-out dresses and bodysuits; Middle Eastern founders; huge Aus/UK following"),
        ("Dissh", "dissh.com.au", "Australian Minimal", "Australian everyday luxury; linen and cotton basics; rapid growth; clean minimal aesthetic"),
        ("Nagnata", "nagnata.com", "Luxury Active", "Australian luxury activewear + knitwear; sustainable organic cotton; resort yoga aesthetic; slow fashion"),
        ("Rixo", "rixo.co.uk", "Vintage-Inspired", "London brand; vintage-inspired prints in modern silhouettes; handmade in small batches; party dresses"),
    ],

    "Fashion - Sustainable 2": [
        ("Pangaia", "thepangaia.com", "Bio-Tech", "FLWRDWN wildflower insulation; seaweed fiber; bio-nylon; science materials + streetwear; $245M valuation"),
        ("Stella McCartney", "stellamccartney.com", "Luxury No-Leather", "No leather or fur since 2001; mushroom leather Mylo bags; LVMH partner; Paul McCartney's daughter"),
        ("Christy Dawn", "christydawn.com", "Deadstock Fashion", "Dresses from deadstock fabric; Farm-to-Closet regenerative cotton in India; Dawn Dress iconic"),
        ("Sézane", "sezane.com", "French Conscious", "First French fashion brand born online; DEMAIN recycled line; monthly drops create scarcity + desire"),
        ("Veja", "veja-store.com", "Eco Sneakers", "Wild rubber from Amazon; organic cotton; NO advertising budget (puts money into materials instead)"),
        ("Kotn", "kotn.com", "Egyptian Cotton", "Direct-trade Egyptian cotton; funds schools where cotton is grown; Canadian brand; community impact"),
        ("Ninety Percent", "ninetypercent.com", "Give-Back Fashion", "90% of profits distributed: 45% to employees, 45% to charity; most equitable fashion brand"),
        ("BEEN London", "beenlondon.com", "Upcycled Leather", "Luxury bags from upcycled leather waste; zero-waste; London design; circular luxury accessories"),
        ("Sheep Inc.", "sheepinc.com", "Carbon-Negative Knitwear", "World's first carbon-negative fashion brand; each sweater comes with an adopted sheep you can track"),
        ("MUD Jeans", "mudjeans.eu", "Circular Denim", "Lease-a-jeans model — rent jeans, return when done; 40% recycled denim; Dutch circular economy pioneer"),
        ("Rapanui", "rapanui.com", "Traceable Fashion", "Scan QR to trace garment to exact factory; wind + solar powered production; Isle of Wight, UK"),
        ("Nobody's Child", "nobodyschild.com", "Accessible Sustainable", "Sustainable fashion under $100; hemp, TENCEL, organic cotton; M&S invested; making eco affordable"),
        ("Finisterre", "finisterre.com", "Coastal Sustainable", "Cornwall surfwear from recycled ocean materials; ECONYL wetsuits; cold water surf culture"),
        ("Thinking Mu", "thinkingmu.com", "Spanish Eco", "Barcelona brand; hemp, organic cotton, recycled polyester; 'think different, buy different'"),
        ("Knowledge Cotton Apparel", "knowledgecottonapparel.com", "Danish Organic", "100% organic + recycled since 2008; PETA-approved vegan; oldest sustainable Danish fashion brand"),
    ],

    "Home - Cleaning & Laundry": [
        ("Seventh Generation", "seventhgeneration.com", "Eco Cleaning", "Plant-based since 1988; Unilever acquired; most recognized eco cleaning brand; $300M+ revenue"),
        ("Mrs. Meyer's", "mrsmeyers.com", "Garden Scent", "Garden-inspired scents (lavender, basil, peony); clean ingredients; SC Johnson brand; elevated drugstore"),
        ("Method", "methodhome.com", "Design Clean", "Beautiful bottles by Karim Rashid; plant-based; proved cleaning products can be art objects"),
        ("Caldrea", "caldrea.com", "Luxury Clean", "Premium plant-derived cleaning with complex scents; Mrs. Meyer's luxury sister brand; SC Johnson"),
        ("Common Good", "commongoodandco.com", "Refill Clean", "Refill stations at retail partners; beautiful glass bottles; concentrate refills; NYC-designed"),
        ("Supernatural", "supernatural.com", "Clean Clean", "Natural cleaning concentrates; glass bottles + aluminum caps; fills from tiny concentrate; beautiful"),
        ("Puracy", "puracy.com", "Plant Enzymes", "Plant-based enzyme cleaners; developed by PhD biochemists; baby-safe; 99.96% natural; Amazon bestseller"),
        ("AspenClean", "aspenclean.com", "Canadian Clean", "Canadian natural cleaning brand; EWG-verified; refillable; plant + mineral based; cleaning services too"),
        ("ECOS", "ecos.com", "Green Clean", "Family-owned 55+ years; carbon neutral + water neutral; Climate Positive; plant-powered; affordable green"),
        ("Nellie's", "nelliesclean.com", "Canadian Laundry", "Laundry soda and dryer balls; retro tin packaging; Canadian brand; no sulfates or toxic chemicals"),
        ("Tru Earth", "tru.earth", "Laundry Strips", "Ultra-concentrated laundry strips; no heavy jugs; compostable wrapper; Canadian invention; $100M+"),
        ("Molly's Suds", "mollyssuds.com", "Sensitive Laundry", "Created after daughter's eczema; EWG-verified laundry products; no fragrances for sensitive families"),
        ("The Laundress", "thelaundress.com", "Luxury Fabric Care", "Specialized detergents for delicate fabrics (silk, denim, cashmere, whites); Unilever acquired; $30 detergent"),
        ("Outlines", "outlineslaundry.com", "Modern Laundry", "Beautifully designed laundry products; concentrates reduce plastic; modern aesthetic for laundry room"),
        ("Supernatural", "supernatural.com", "Pretty Clean", "Gorgeous glass bottles with aluminum caps; concentrated plant cleaners; $8 refills; Instagram-worthy"),
    ],

    "Tech - Creator Economy": [
        ("Elgato", "elgato.com", "Streaming Gear", "Stream Deck = essential tool for creators; Key Light, Wave mic; Corsair owned; creator economy infrastructure"),
        ("Rode", "rode.com", "Microphones", "PodMic revolutionized podcast audio; Wireless GO changed video; NT1 is studio standard; Australian"),
        ("Shure", "shure.com", "Pro Audio", "SM7B is THE podcast mic (used by Joe Rogan, every major podcaster); 100-year heritage; $100M from SM7B alone"),
        ("Focusrite", "focusrite.com", "Audio Interfaces", "Scarlett 2i2 is the #1 audio interface for home studios; 10M+ Scarletts sold; UK heritage; democratized recording"),
        ("Blackmagic Design", "blackmagicdesign.com", "Cinema Cameras", "Pocket Cinema Camera 6K at $2,500 vs $20K+ competitors; DaVinci Resolve is free; democratized filmmaking"),
        ("DJI", "dji.com", "Drones", "80%+ global drone market; Mavic Mini made drones accessible; Osmo Pocket for vloggers; $4.5B+ revenue"),
        ("Insta360", "insta360.com", "360 Cameras", "Invisible selfie stick trick; ONE X3 made 360 mainstream; challenging GoPro with AI editing innovation"),
        ("GoPro", "gopro.com", "Action Cameras", "Created the action camera category; HERO line; user-generated content IS their marketing; $1.1B revenue"),
        ("Hollyland", "hollyland.tech", "Wireless Video", "Lark wireless mic system rivals Rode GO at lower price; Mars wireless video; growing creator brand"),
        ("Aputure", "aputure.com", "LED Lighting", "LS 600d Pro is affordable cinema lighting; democratized film lighting; Chinese engineering for Hollywood"),
        ("Godox", "godox.com", "Flash & Light", "Affordable studio lighting that works as well as Profoto at 1/5 price; V1 round flash; AD series"),
        ("Deity", "deitymic.com", "Budget Mics", "S-Mic 2 rivals $1K shotgun mics at $300; V-Mic D4 for cameras; incredible value in pro audio"),
        ("Røde", "rode.com", "Creator Audio", "VideoMicro changed on-camera audio; PodMic + RodeCaster Pro = podcasting ecosystem; Australian quality"),
        ("Loupedeck", "loupedeck.com", "Editing Console", "Tactile editing dial + buttons for Lightroom, Premiere; Finnish design; physical controls for digital editing"),
        ("Stream Deck", "elgato.com", "Macro Keypad", "Programmable LCD keys for streaming, productivity, smart home; 15-key or Pedal; creator must-have"),
    ],

    "Wellness - Gut Health": [
        ("Seed", "seed.com", "Synbiotic", "DS-01 Daily Synbiotic with 24 clinically studied strains; refillable glass jar; science-first; $500M+ valuation"),
        ("Just Thrive", "justthrivehealth.com", "Spore Probiotic", "Spore-based probiotic that survives stomach acid (most probiotics die); 1000x better survival rate"),
        ("Pendulum", "pendulumlife.com", "Akkermansia", "Only brand with Akkermansia muciniphila probiotic; targets metabolic health; $100M+ raised; clinical"),
        ("Synbiotic+", "ritual.com", "Ritual Probiotic", "Ritual's gut health supplement; 3-in-1 synbiotic (pre, pro, postbiotic); delayed-release capsule"),
        ("Athletic Greens AG1", "drinkag1.com", "Greens + Gut", "75 ingredients including probiotics; 'one scoop replaces 12 supplements'; podcast sponsorship king"),
        ("OLIPOP", "drinkolipop.com", "Prebiotic Soda", "Healthy soda with prebiotics + plant fiber + botanicals; $200M+ revenue; 'what soda should be'"),
        ("Poppi", "drinkpoppi.com", "ACV Soda", "Apple cider vinegar soda; Shark Tank; PepsiCo acquired ~$2B; gut health meets fun drinks"),
        ("Goli", "goli.com", "ACV Gummies", "Made apple cider vinegar palatable in gummy form; first-to-market ACV gummy; $300M+ revenue"),
        ("Culturelle", "culturelle.com", "Probiotic Capsules", "Most clinically studied probiotic strain (LGG); doctor-recommended; Haleon owned; trusted brand"),
        ("Align", "alignprobiotics.com", "Digestive Health", "Gastroenterologist-recommended; unique B. infantis 35624 strain; P&G owned; 20+ years of research"),
        ("Bio-K+", "bifrk-plus.com", "Liquid Probiotic", "50 billion CFUs in a drinkable format; clinically proven; 30+ published studies; Canadian origin"),
        ("Renew Life", "renewlife.com", "Digestive Wellness", "Ultimate Flora probiotics; digestive enzyme blends; Clorox acquired; gut health specialist since 1997"),
        ("Garden of Life", "gardenoflife.com", "Raw Probiotics", "Dr. Formulated Probiotics — 85B CFU; Nestlé owned; whole food probiotics; organic + non-GMO"),
        ("Sakara", "sakara.com", "Gut-Focused Meals", "Plant-based meals designed for gut health; $70+/day; probiotic chocolate; 'clean boutique' approach"),
        ("ZBiotics", "zbiotics.com", "Engineered Probiotic", "Genetically engineered probiotic designed to break down acetaldehyde (hangover compound); biotech meets wellness"),
    ],

    "Fashion - Accessories Expanded": [
        ("Lele Sadoughi", "lelesadoughi.com", "Headbands", "Padded headband became THE pandemic accessory; jeweled, beaded, velvet; Jill Biden wore one to inauguration"),
        ("Jennifer Behr", "jenniferbehr.com", "Hair Accessories", "Handmade crystal hair accessories; red carpet staple; bridal headpieces; Brooklyn studio"),
        ("Kitsch", "mykitsch.com", "Hair Accessories", "Satin pillowcases and scrunchies; heatless curling sets went viral on TikTok; affordable hair tools"),
        ("Teleties", "teleties.com", "Hair Ties", "Telephone cord hair ties that don't leave a crease; won't pull hair; $50M+ revenue; colorful coils"),
        ("Madewell", "madewell.com", "Leather Goods", "The Transport Tote is their bag icon; denim + leather; J.Crew's more successful sibling"),
        ("Clare V.", "clarev.com", "French-American Bags", "Flat Clutch with 'BONJOUR' is iconic; French-American leather goods; LA-made; effortless chic"),
        ("Polène", "polene-paris.com", "French Leather", "Direct-from-atelier French leather bags at 1/3 luxury price; Numéro line; $300-500 range; waitlists"),
        ("Strathberry", "strathberry.com", "Scottish Luxury", "Meghan Markle wore their bag; Edinburgh-crafted; bar closure signature; $200-500 range"),
        ("Mansur Gavriel", "mansurgavriel.com", "Minimal Bags", "Bucket bag kickstarted the minimalist bag trend; vegetable-tanned Italian leather; $600-1000"),
        ("Staud", "stfraud.com", "LA Fashion Bags", "Moreau bucket bag became It-bag; Sarah Staudinger; plastic beaded bags; fun LA fashion"),
        ("Cult Gaia", "cultfria.com", "Statement Bags", "Ark bag (bamboo) went viral on Instagram; Jasmin Larian; LA-based; sculptural accessories"),
        ("Hunting Season", "huntingseason.com", "Artisan Bags", "Colombian artisan-made bags; woven + leather; luxury craftsmanship; direct artisan partnerships"),
        ("Dragon Diffusion", "dragondiffusion.com", "Woven Leather", "Hand-woven leather bags; each takes 8 hours; Belgian design; artisanal luxury at $300-500"),
        ("Little Liffner", "littleliffner.com", "Swedish Bags", "Sculptural bags; Tulip bag; Swedish minimalism meets art; architectural shapes in leather"),
        ("DeMellier", "demellier.com", "London Bags", "For every bag sold, funds vaccines for children; Meghan Markle wore Nano Montreal; British luxury"),
    ],

    "Home - Smart Kitchen": [
        ("Thermomix", "thermomix.com", "All-in-One Cooker", "12 appliances in 1; heats, steams, blends, kneads; $1,500; cult following; 20M+ units sold globally"),
        ("Anova Culinary", "anovaculinary.com", "Sous Vide", "Precision Cooker made sous vide accessible at $150; app-controlled; Electrolux acquired; chef-quality at home"),
        ("Breville", "breville.com", "Smart Appliances", "Barista Express = home espresso revolution; Smart Oven Air; Australian engineering; $1B+ revenue"),
        ("Nespresso", "nespresso.com", "Pod Coffee", "George Clooney ambassador; Vertuo system reads barcode for perfect brew; aluminum pod recycling"),
        ("De'Longhi", "delonghi.com", "Italian Coffee", "La Specialista grinder + brewer combo; Magnifica auto espresso; Italian heritage meets convenience"),
        ("Smeg", "smeg.com", "Retro Design", "1950s Italian design appliances; $2,000 fridge is kitchen art; Dolce & Gabbana collab; status symbol"),
        ("Big Green Egg", "biggreenegg.com", "Kamado Grill", "Ceramic kamado cooker; cult EGGhead community; versatile (grill, bake, smoke, roast); $1,000+ lifetime investment"),
        ("Meater", "meater.com", "Smart Thermometer", "First wireless meat thermometer; no wires between oven and phone; AI cook time estimator; Traeger acquired"),
        ("Combustion Inc", "combustion.inc", "Predictive Thermometer", "8-sensor thermometer predicts when food is done; most advanced food thermometer; Kickstarter hit"),
        ("Yummly", "yummly.com", "Smart Thermometer", "Whirlpool's smart thermometer + recipe app; guided cooking; suggests recipes based on your ingredients"),
        ("June Oven", "juneoven.com", "Smart Oven", "Camera inside identifies food and auto-cooks it; $600 countertop oven; 100+ preset programs; AI cooking"),
        ("Tovala", "tovala.com", "Scan-to-Cook Oven", "Scan QR on their meal kits, oven auto-cooks perfectly; $300 oven + $70/week meals; genius pairing"),
        ("Miele", "miele.com", "German Appliances", "Test winner in every category; dishwashers last 20 years; $5B+ revenue; 'Immer Besser' (Forever Better)"),
        ("Balmuda", "us.balmuda.com", "Japanese Design", "The Toaster adds steam; The Kettle is pour-over ready; The Lantern is ambient light; $300 toaster justified"),
        ("Fellow", "fellowproducts.com", "Coffee Design", "Stagg EKG kettle = pour-over icon; Opus grinder; Atmos canister; SF craft coffee design ecosystem"),
    ],

    "Supplements - Longevity": [
        ("Elysium Health", "elysiumhealth.com", "NAD+ Longevity", "Basis supplement with NR (NAD+ precursor); Nobel Prize-winning scientist Leonard Guarente on board; MIT origin"),
        ("Timeline Nutrition", "timelinenutrition.com", "Mitopure", "Urolithin A (Mitopure) targets mitochondrial health; Swiss biotech origin; $100M+ raised; clinical studies"),
        ("InsideTracker", "insidetracker.com", "Blood Analytics", "Analyzes 43+ blood biomarkers; AI-powered recommendations; Tom Brady, David Sinclair customers"),
        ("Tru Niagen", "truniagen.com", "NR Supplement", "Nicotinamide riboside (NR) for NAD+; ChromaDex patented; Nobel Prize-backed science; cellular health"),
        ("Life Extension", "lifeextension.com", "Longevity Science", "40+ years of longevity research; 400+ supplements; Life Extension Foundation research; premium formulations"),
        ("Quicksilver Scientific", "quicksilverscientific.com", "Liposomal Delivery", "Liposomal glutathione and NAD+; superior absorption technology; Dr. Chris Shade PhD; advanced delivery"),
        ("Prolon", "prolonfast.com", "Fasting Mimicking Diet", "5-day fasting mimicking diet developed by Dr. Valter Longo at USC; triggers autophagy without full fasting"),
        ("Juvenon", "juvenon.com", "Mitochondrial Health", "Founded by Berkeley biochemist Dr. Bruce Ames; cellular energy support; alpha-lipoic acid pioneer"),
        ("Neurohacker Collective", "neurohacker.com", "Systems Approach", "Qualia Mind nootropic with 28 ingredients; systems biology approach; complex formulations; biohacker community"),
        ("LifeForce", "mylifeforce.com", "Peter Attia-Adjacent", "Longevity-focused diagnostics + supplements; blood testing; performance medicine; Tony Robbins co-founded"),
        ("Primeadine", "primeadine.com", "Spermidine", "Spermidine supplement for cellular renewal; Japanese fermented food-derived; autophagy activation"),
        ("DoNotAge", "donotage.org", "Pure Longevity", "NMN, resveratrol, fisetin at lowest prices; transparent lab testing; UK-based; longevity purists"),
        ("Renue By Science", "rfrenuebyscience.com", "Liposomal NMN", "Liposomal NMN and resveratrol for better absorption; science-forward; GMP certified; affordable"),
        ("Alive By Nature", "alivebynature.com", "NAD+ Stack", "NMN sublingual tablets; NAD+ stack protocols; science blog; David Sinclair protocol products"),
        ("ProHealth Longevity", "prohealthlongevity.com", "Longevity Supps", "Uthever NMN (99%+ pure); trans-resveratrol; 35+ year supplement heritage; quality testing"),
    ],

    "Wellness - Fitness Apps": [
        ("Peloton", "onepeloton.com", "Connected Fitness", "Content + community; instructors are celebrities; 6.7M members; $44B peak valuation; pandemic growth"),
        ("Apple Fitness+", "apple.com/fitness", "Apple Ecosystem", "Integrated with Apple Watch; celebrity trainers; $10/month; 3B+ potential users in Apple ecosystem"),
        ("Strava", "strava.com", "Social Fitness", "'If it's not on Strava, it didn't happen'; 100M+ athletes; segments and KOMs; social running/cycling"),
        ("Nike Training Club", "nike.com/ntc-app", "Free Workouts", "Free premium workouts from Nike trainers; yoga, strength, HIIT; 200+ programs; connected to Nike ecosystem"),
        ("SWEAT", "sweat.com", "Women's Fitness", "Kayla Itsines' app; BBG program; largest women's fitness community; acquired for $400M; 50M+ downloads"),
        ("Fitbod", "fitbod.me", "AI Strength", "AI generates gym workouts based on available equipment and muscle recovery; personalized every session"),
        ("Strong", "strong.app", "Workout Tracking", "Simple, powerful weightlifting tracker; 6M+ users; log sets, reps, weight; progress charts"),
        ("JEFIT", "jefit.com", "Gym Workouts", "1,400+ exercise database with animations; workout planner; community; free tier is generous"),
        ("Centr", "centr.com", "Chris Hemsworth", "Chris Hemsworth's fitness + meal planning app; Thor's actual workout routines; celebrity trainer access"),
        ("P.volve", "pvolve.com", "Functional Fitness", "Functional movement-based workouts; Jennifer Aniston partnership; anti-high-impact; patented P.ball equipment"),
        ("Obé Fitness", "obefitness.com", "Live Classes", "Live + on-demand fitness classes streamed like a TV show; high energy instructors; $100M+ valuation"),
        ("Future", "future.co", "1-on-1 Coaching", "$199/month personal trainer via Apple Watch + app; real human coach texts you daily; premium accountability"),
        ("Tempo", "tempo.fit", "AI Home Gym", "3D sensors track your form in real-time; AI form correction; beats Mirror/Tonal on form feedback"),
        ("Les Mills", "lesmills.com", "Group Fitness", "BODYPUMP, BODYCOMBAT in 21,000+ gyms; Les Mills+ app for home; 130K+ instructors; NZ-founded"),
        ("ClassPass", "classpass.com", "Fitness Marketplace", "One membership, access to 30K+ studios; credit-based system; $1B+ valuation; Mindbody acquired"),
    ],

    "Food & Drink - Specialty": [
        ("Momofuku", "shop.momofuku.com", "Chef DTC", "David Chang's restaurant empire went DTC; Chili Crunch, Soy Sauce, Noodles; chef-to-consumer pipeline"),
        ("Omsom", "omfrsom.com", "Asian Sauces", "Vietnamese-American sisters' Asian sauce starters; bold flavors; proud, loud Asian-American branding"),
        ("Bachan's", "bachfrns.com", "Japanese BBQ", "Japanese BBQ Sauce made from family recipe; #1 new condiment at Whole Foods; Costco bestseller"),
        ("Mike's Hot Honey", "mikfreshothfroney.com", "Hot Honey", "Created the hot honey category; honey + chili peppers; pizzeria origin; now in every grocery store"),
        ("Fishwife", "eatfishwife.com", "Tinned Fish", "Made canned fish cool and collectible; beautiful tins; tinned fish trend starter; millennial sardines"),
        ("Deux", "eatdeux.com", "Cookie Dough", "Functional cookie dough with adaptogens + collagen; Shark Tank; eat-raw-safe; dessert meets wellness"),
        ("Last Crumb", "lastcrumb.com", "Luxury Cookies", "$140/box of 12 cookies; drops sell out in seconds; luxury desert brand; each cookie is an experience"),
        ("Levain Bakery", "levainbakery.com", "Giant Cookies", "6-oz cookies from NYC bakery; Dark Chocolate Chocolate Chip is legendary; ship nationwide; cult following"),
        ("Milk Bar", "milkbarstore.com", "Creative Desserts", "Christina Tosi's cereal milk, crack pie, birthday cake; Momofuku origin; reimagined American desserts"),
        ("Goldbelly", "goldbelly.com", "Food Marketplace", "Ship iconic restaurant food nationwide (Katz's pastrami, Pat's cheesesteak); marketplace for regional food"),
        ("Imperfect Foods", "imperfectfoods.com", "Ugly Produce", "Rescues 'ugly' but perfectly good produce; 30-50% off grocery; reduces food waste; acquired Misfits"),
        ("Daily Harvest", "dailyharvest.com", "Frozen Meals", "Pre-portioned frozen smoothies, harvest bowls, flatbreads; $1.1B valuation; convenience + clean eating"),
        ("Factor", "factor75.com", "Prepared Meals", "Chef-prepared, dietitian-designed meals; keto, calorie smart, vegan options; HelloFresh acquired; fastest growing"),
        ("CookUnity", "cookunity.com", "Chef Meals", "Meals designed by different chefs each week; restaurant-quality at home; each meal credited to a real chef"),
        ("Methodology", "methodology.com", "Organic Meals", "100% organic prepared meals; Bay Area chefs; seasonal menus; premium healthy meal delivery"),
    ],

    "Home - Organization & Storage": [
        ("The Container Store", "containerstore.com", "Organization", "America's organization store; 10,000+ products; employee-first culture; $1B+ peak revenue"),
        ("Open Spaces", "getopenspaces.com", "Modern Storage", "Beautiful bins, shelf risers, drawer organizers in colors; Kondo-era organization with style"),
        ("Yamazaki Home", "yamazakihome.com", "Japanese Storage", "Minimalist Japanese storage and organization; Tower series; functional beauty; small-space solutions"),
        ("simplehuman", "simplehuman.com", "Smart Home", "Sensor trash cans, soap dispensers, mirrors; engineering-obsessed; $500M+ revenue; premium everyday tools"),
        ("Joseph Joseph", "josephjoseph.com", "Kitchen Design", "Intelligent kitchen design; nested bowls, chopping boards; British design; clever space-saving solutions"),
        ("mDesign", "mdesign.com", "Home Organization", "Affordable home organization products; Amazon marketplace success; bathroom, kitchen, closet solutions"),
        ("iDesign", "idesignlivesimply.com", "Modular Storage", "Modular storage bins and drawer organizers; The Home Edit collection; clear acrylic organizing"),
        ("The Home Edit", "thehomeedit.com", "Celebrity Organizing", "Netflix show; rainbow organizing aesthetic; product line at Walmart; Clea Shearer & Joanna Teplin"),
        ("Horderly", "horderly.com", "Organizing Service", "Professional organizing service; Jamie Hord's NYC-born business; focuses on sustainable organizing"),
        ("NEAT Method", "neatmethod.com", "Luxury Organizing", "Premium home organizing service; franchise model; Molly Graves founded; organizing as a luxury service"),
        ("Stasher", "stasherbag.com", "Silicone Storage", "Reusable silicone bags replacing Ziploc; Shark Tank; B Corp; 200M+ single-use bags replaced"),
        ("W&P", "wandpdesign.com", "Kitchen Accessories", "Porter bowl, Peak ice tray; design-forward kitchen accessories; Brooklyn-designed; $50M+ revenue"),
        ("Food52", "food52.com", "Kitchen Curation", "Amanda Hesser's food community + curated home shop; 5 Sided Cutting Board; Marquee Brands acquired"),
        ("Material Kitchen", "materialkitchen.com", "Essential Tools", "The reBoard cutting board and reNaked knife; designed by ex-elBulli chef; minimal SKU, max quality"),
        ("GIR (Get It Right)", "gfrr.co", "Silicone Tools", "Ultimate spatula in one piece of silicone (no seams); Heat-resistant; NSF certified; pro and home"),
    ],

    "Wellness - Supplements 2": [
        ("Athletic Greens AG1", "drinkag1.com", "All-in-One", "75 ingredients; every podcast sponsors it; Tim Ferriss early advocate; $1.2B valuation; morning ritual brand"),
        ("Ritual", "ritual.com", "Traceable Vitamins", "Visible capsule shows beadlets; traces every ingredient to source; Essential for Women; $250M+ revenue"),
        ("Care/of", "takecareof.com", "Quiz Vitamins", "Personalized vitamin packs; your name on the pack; Bayer acquired; quiz-based customization pioneer"),
        ("OLLY", "olly.com", "Gummy Vitamins", "Made vitamins fun; bold colorful packaging; gummy format; Unilever acquired; Target/CVS staple"),
        ("Vitafusion", "vitafusion.com", "Adult Gummies", "#1 gummy vitamin brand; made vitamins feel less like medicine; Church & Dwight owned"),
        ("Nature's Bounty", "naturesbounty.com", "Classic Vitamins", "Trusted vitamin brand since 1971; $3B+ parent company; found in every pharmacy; value + trust"),
        ("MegaFood", "megafood.com", "Whole Food Vitamins", "Vitamins made from real food; FoodState nutrients; B Corp; Women's One; farm-fresh ingredients"),
        ("New Chapter", "newchapter.com", "Fermented Vitamins", "Fermented vitamins for better absorption; whole-food complexed; B Corp; P&G acquired"),
        ("Rainbow Light", "rainbowlight.com", "Prenatal Vitamins", "Prenatal One multivitamin; food-based; easy to digest even on empty stomach; 30+ year heritage"),
        ("SmartyPants", "smartypantsvitamins.com", "Premium Gummies", "Omega-3 + D3 + B12 in one gummy; non-GMO; 1-for-1 nutrient grant program; Unilever acquired"),
        ("Naturelo", "naturelo.com", "Plant-Based Vitamins", "Whole food plant-based vitamins; Amazon #1 in multiple categories; clean label; vegan-friendly"),
        ("Pure Encapsulations", "pureencapsulations.com", "Hypoallergenic Supps", "Free from common allergens; prescribed by 60K+ healthcare practitioners; clinical-grade; Nestlé HSW"),
        ("Designs for Health", "designsforhealth.com", "Practitioner Grade", "Sold through healthcare practitioners; 300+ products; clinical dosing; science-first formulations"),
        ("Standard Process", "standardprocess.com", "Whole Food Supps", "Farm-owned organic ingredient sourcing; chiropractor and naturopath recommended; 95+ year heritage"),
        ("Metagenics", "metagenics.com", "Functional Medicine", "Founded on Jeffrey Bland's functional medicine principles; practitioner-exclusive; clinical nutrition"),
    ],

    "Beauty - Fragrance 2": [
        ("Snif", "snfrif.com", "Try-First Fragrance", "'Try before you buy' — free 2ml sample with $5 refundable deposit; accessible niche fragrance; DTC innovation"),
        ("Dossier", "dfrssier.co", "Dupe Fragrances", "Inspired-by versions of $300 fragrances for $29; transparent ingredient list; democratizing luxury scent"),
        ("Commodity", "commodity.com", "Scent Spectrum", "Each fragrance in 3 expressions (Personal, Expressive, Bold); choose your scent strength; unique concept"),
        ("Replica by Maison Margiela", "maisonmargiela.com", "Memory Scents", "Each scent recreates a memory — Beach Walk, By The Fireplace; olfactory storytelling at $150"),
        ("Ouai", "theouai.com", "Hair-to-Fragrance", "North Bondi, Melrose Place, Rue St. Honoré fragrances; Jen Atkin; hair products → full fragrance line"),
        ("Ellis Brooklyn", "ellisbrooklyn.com", "Clean Fragrance", "Sci-fi writer turned perfumer; Bee EDP; clean without compromising complexity; beautiful packaging"),
        ("Henry Rose", "henryrose.com", "Michelle Pfeiffer", "Michelle Pfeiffer's clean fragrance; EWG verified; Cradle to Cradle certified; transparency in scent"),
        ("Floral Street", "floralstreet.com", "Sustainable Scents", "Recyclable packaging; vegan; British perfumer; Neon Rose is bestseller; eco-forward fragrance"),
        ("Santal 33 by Le Labo", "lelabofragrances.com", "NYC Scent", "Became NYC's unofficial smell; hand-blended in every store; personalizable labels"),
        ("Baccarat Rouge 540", "franciskurkdjian.com", "TikTok Viral", "Most searched fragrance on TikTok; $325 bottle; saffron + ambergris; Maison Francis Kurkdjian"),
        ("NEST New York", "nestnewyork.com", "Home + Personal", "Grapefruit home fragrance is iconic; expanded from candles to fine fragrance; $300M+ revenue"),
        ("Clean Reserve", "cleanbeauty.com", "Sustainable Scent", "Skin, Sueded Oud, Rain; sustainable + clean formulas; responsible packaging; refillable bottles"),
        ("Juliette Has a Gun", "juliettehasagun.com", "Niche Provocative", "Not a Perfume has only one ingredient (Cetalox); French indie house; playful naming"),
        ("Byredo", "byredo.com", "Swedish Minimal", "Ben Gorham's 'beyond reason'; $800M+ valuation; Gypsy Water, Mojave Ghost; L'Oréal minority stake"),
        ("DS & Durga", "dsanddurga.com", "Brooklyn Niche", "Bowmakers, I Don't Know What; indie Brooklyn house; music-inspired compositions; cult following"),
    ],

    "Home - Bathroom & Fixtures": [
        ("Tushy", "hellotushy.com", "Bidet Attachment", "'Stop wiping your butt with dry paper'; $80 bidet; humor marketing master; $50M+ revenue; Jason Biggs ads"),
        ("Brondell", "brondell.com", "Bidet & Wellness", "Bidet seats + air purifiers + water filters; premium bidet technology; eco-friendly bathroom"),
        ("Bio Bidet", "biobidet.com", "Bidet Seats", "Heated bidet seats with remote control; warm water, dryer, heated seat; luxury bathroom at affordable price"),
        ("Kohler", "kohler.com", "Bathroom Fixtures", "Intelligent toilets with bidet; $8B+ revenue; 150-year heritage; smart bathroom innovation"),
        ("Moen", "moen.com", "Smart Faucets", "Smart water monitoring; Flo leak detection; touchless faucets; Fortune Brands; smart bathroom"),
        ("Delta Faucet", "deltafaucet.com", "Touch Technology", "Touch2O technology — tap anywhere to turn on; VoiceIQ works with Alexa; $3B+ parent company"),
        ("Squatty Potty", "squattypotty.com", "Toilet Stool", "Unicorn Rainbow Ice Cream video = 300M+ views; $30 stool; Shark Tank; $50M+ revenue; humor sells"),
        ("Lomi", "lomi.com", "Composter", "Countertop composter turns food waste into dirt overnight; Shark Tank; 100K+ units sold; $500 device"),
        ("Mill", "mill.com", "Kitchen Bin", "Smart kitchen bin dries and grinds food scraps; sends them to be turned into chicken feed; $33/month"),
        ("Jolie", "jolieskinco.com", "Shower Filter", "Filtered showerhead that removes chlorine and heavy metals; better skin/hair; $165; influencer-driven"),
        ("Canopy", "getcanopy.co", "Bathroom Humidifier", "No-mist humidifier with aromatherapy; dishwasher-safe; beautiful design; solves 'gross humidifier' problem"),
        ("Vitruvi", "vitruvi.com", "Stone Diffuser", "Matte ceramic diffuser = decor, not medical device; essential oil blends; elevated aromatherapy aesthetic"),
        ("Aēsop", "aesop.com", "Bathroom Luxury", "Resurrection Hand Wash in every Instagram bathroom; $30+ soap; architectural stores; L'Oréal acquired $2.5B"),
        ("Diptyque", "diptyqueparis.com", "Bathroom Fragrance", "Baies (Berries) candle in bathroom = ultimate flex; $72 candle; Parisian luxury; since 1961"),
        ("Byredo", "byredo.com", "Hand Care", "Rose Hand Wash $45; scented hand cream collection; luxury bathroom essentials; Swedish design"),
    ],

    "Fashion - Shoes Expanded": [
        ("Birkenstock", "birkenstock.com", "Heritage Sandals", "250+ year heritage; Arizona sandal is ubiquitous; IPO'd at $8.6B; from hippie to luxury (Hermès collab)"),
        ("Crocs", "crocs.com", "Casual Shoes", "From 'ugly' to $4B+ revenue; Bad Bunny, Bieber, Balenciaga collabs; Jibbitz charms; cultural phenomenon"),
        ("Dr. Martens", "drmartens.com", "British Boots", "1460 boot is punk/grunge icon; 75+ year heritage; IPO'd at $5B; subcultural identity in a boot"),
        ("Blundstone", "blundstone.com", "Chelsea Boots", "Australian chelsea boots since 1870; #500 is the iconic boot; pull-on, no laces; $300M+ revenue"),
        ("UGG", "ugg.com", "Sheepskin Boots", "Classic boot became 2000s phenomenon; Tom Brady wears them; $1.5B+ revenue; Deckers owned; platform now"),
        ("Teva", "teva.com", "Sport Sandals", "Original sport sandal (invented on Colorado River); Hurricane XLT2; outdoor-to-street crossover"),
        ("Chacos", "chacos.com", "Adventure Sandals", "Z-strap sandals for river and trail; lifetime warranty on straps; resoling program; Colorado-made"),
        ("Vivobarefoot", "vivobarefoot.com", "Barefoot Shoes", "Minimal sole lets feet move naturally; regenerative sourcing; 'natural movement' philosophy; growing cult"),
        ("Xero Shoes", "xeroshoes.com", "Minimalist Shoes", "5.5mm sole; 'feel the world'; Shark Tank alumni; barefoot running movement; $100M+ revenue"),
        ("On Running", "on.com", "Swiss Innovation", "CloudTec sole; Roger Federer invested; $8B+ IPO; fastest-growing running brand; Swiss precision"),
        ("HOKA", "hoka.com", "Maximalist", "Oversized midsole creator; Bondi and Clifton bestsellers; $1.8B revenue; trail-to-lifestyle crossover"),
        ("New Balance", "newbalance.com", "Heritage Cool", "990 went from dad shoe to fashion icon; JJJJound, ALD collabs; $6B+ revenue; made-in-USA heritage"),
        ("Salomon", "salomon.com", "Trail-to-Street", "XT-6 became fashion shoe; trail running heritage; French Alps DNA; Amer Sports owned"),
        ("ASICS", "asics.com", "Running Heritage", "Gel-Kayano 30; 75+ year Japanese heritage; Kiko Kostadinov collabs made them fashionable again"),
        ("Saucony", "saucony.com", "Running + Retro", "Endorphin Pro racing flat; Jazz Original retro runner; Boston origin; $500M+ revenue; Wolverine"),
    ],

    "Misc DTC 3": [
        ("Brilliant Earth", "brilliantearth.com", "Ethical Diamonds", "Beyond Conflict Free sourcing; virtual try-on AR; 30% of engagement rings bought online; IPO'd"),
        ("VRAI", "vrai.com", "Lab-Grown Diamonds", "Own the foundry (Diamond Foundry); Leonardo DiCaprio invested; zero-emission facility; traceable stones"),
        ("Quince", "onequince.com", "Factory Direct", "Mongolian cashmere at $50 vs $300; Italian leather; factory-direct pricing; the anti-markup brand"),
        ("Italic", "italic.com", "Unbranded Luxury", "Products from Prada/Burberry factories without the label; membership $60/year; radical unbranding"),
        ("Public Rec", "publicrec.com", "Men's Joggers", "All Day Every Day Pant — dress pant comfort, jogger look; $98; the WFH pant; perfect hybrid"),
        ("Vuori", "vuori.com", "Men's Activewear", "$4B valuation; Encinitas CA surf meets performance; filled men's activewear gap; SoftBank invested $400M"),
        ("Chubbies", "chubbies.com", "Short Shorts", "5.5-inch inseam shorts for men; 'Sky's out, thighs out'; fraternity culture turned DTC brand; $100M+"),
        ("Tracksmith", "tracksmith.com", "Running Culture", "Boston running heritage; old-school athletic aesthetic; Twilight 5K race series; no sponsored elites"),
        ("Janji", "janji.com", "Running + Impact", "Running apparel; each collection funds clean water projects; AFO trip for customers; purpose-driven running"),
        ("Satisfy Running", "satisfyrunning.com", "Luxury Running", "French; $200+ shorts; 'running is counterculture'; moth-eaten vintage aesthetic; anti-performance marketing"),
        ("Sorel", "sorel.com", "Fashion Boots", "Joan of Arctic boot is winter icon; moved from pure function to fashion-function; Columbia owned"),
        ("Hunter Boots", "hunterboots.com", "Rain Boots", "Wellington boot heritage since 1856; Royal Warrant; Kate Moss at Glastonbury made them fashion; British icon"),
        ("Sperry", "sperry.com", "Boat Shoes", "Paul Sperry invented the boat shoe in 1935 after watching his dog on ice; Top-Sider is preppy classic"),
        ("Cole Haan", "colehaan.com", "Innovation Shoes", "GrandPro sneaker combines dress shoe looks with sneaker comfort; Nike Air technology heritage; $600M+ revenue"),
        ("Allen Edmonds", "allenedmonds.com", "American Dress", "Recraftable shoes made in Wisconsin; every US president since 1981 wore them; buy-for-life dress shoes"),
    ],
}