"""
Batch 8 – HOME / BEDDING / ORGANIZER DTC Brands (Post-2018, Ecommerce-Native)
250+ unique brands NOT found in batches 1–7.
Each entry: (brand_name, website, sub_niche_tr, insight_tr, history_tr)
"""

BATCH_DATA = [
    # =====================================================================
    # 1. Yatak Çarşafı & Nevresim (10)
    # =====================================================================
    ("Scouted Home", "scouted.com.au", "Yatak Çarşafı & Nevresim",
     "Avustralya merkezli, %100 organik pamuklu çarşaf seti; Instagram reklamlarıyla büyüdü",
     "2020'de Melbourne'da kuruldu, Shopify üzerinden doğrudan tüketiciye satış yaparak Avustralya pazarında hızla yayıldı"),
    ("Flaxhome", "flaxhome.co", "Yatak Çarşafı & Nevresim",
     "Avrupa keteni kullanarak uygun fiyatlı keten çarşaf sunan DTC marka",
     "2021'de Londra'da kuruldu, Instagram ve TikTok üzerinden keten yatak takımı trendine öncülük etti"),
    ("Sojo Home", "sojohome.com", "Yatak Çarşafı & Nevresim",
     "Portekiz üretimi hemp-pamuk karışımı çarşaflar; antimikrobiyal özellikli",
     "2019'da Lizbon'da kuruldu, sürdürülebilir tekstil fuarlarında dikkat çekerek DTC büyüdü"),
    ("Dusk & Dawn", "duskanddawn.com.au", "Yatak Çarşafı & Nevresim",
     "Bambu ipeksi çarşaf setleri; termal düzenleme teknolojisi",
     "2020'de Sydney'de kuruldu, Facebook ve Instagram reklamlarıyla Avustralya genelinde yayıldı"),
    ("Looma", "loomahome.com", "Yatak Çarşafı & Nevresim",
     "Hindistan el dokuması organik pamuk çarşaflar; adil ticaret sertifikalı",
     "2019'da ABD'de kuruldu, Kickstarter kampanyasıyla başlayıp Shopify mağazasına geçti"),
    ("Linenly", "linenly.com.au", "Yatak Çarşafı & Nevresim",
     "Avustralya merkezli Fransız keten çarşaf; uygun fiyatlı lüks",
     "2019'da kuruldu, Avustralya'da keten çarşaf trendinde Instagram ile DTC hızla büyüdü"),
    ("Panda Life", "pandaLife.co.uk", "Yatak Çarşafı & Nevresim",
     "Bambu elyaf çarşaf ve nevresim; hipoalerjenik ve termoregüle",
     "2020'de İngiltere'de kuruldu, sosyal medya influencer işbirlikleriyle büyüdü"),
    ("Cloudpaper Linens", "cloudpaperlinens.com", "Yatak Çarşafı & Nevresim",
     "Tencel lyocell çarşaf; bulut gibi yumuşak doku vaadi",
     "2021'de kuruldu, TikTok unboxing videolarıyla viral olarak DTC satışa başladı"),
    ("Bedface", "bedface.com.au", "Yatak Çarşafı & Nevresim",
     "Avustralya'nın ilk online nevresim markası; minimalist tasarım",
     "2018'de kuruldu, doğrudan tüketiciye satış modeliyle perakende fiyatının yarısında premium çarşaf sundu"),
    ("Duvet Day", "duvetday.co.uk", "Yatak Çarşafı & Nevresim",
     "İngiltere merkezli cilt dostu ipek saten çarşaf seti",
     "2020'de Londra'da kuruldu, cilt bakımı ve uyku kesişiminde Instagram ile DTC büyüdü"),

    # =====================================================================
    # 2. Yorgan & Dolgulu Ürünler (10)
    # =====================================================================
    ("Vesta Home Living", "vestahome.co.uk", "Yorgan & Dolgulu Ürünler",
     "Geri dönüştürülmüş PET şişeden üretilen ekolojik yorgan",
     "2020'de Londra'da kuruldu, çevreci tüketicilere yönelik Meta reklamlarıyla büyüdü"),
    ("Hudsons Bay Duvet Co", "hudsonsduvet.com", "Yorgan & Dolgulu Ürünler",
     "Kanada kaz tüyü yorgan; 750+ fill power premium dolgu",
     "2019'da Vancouver'da kuruldu, Shopify üzerinden premium yorgan DTC satışı başlattı"),
    ("Souffle Duvet", "souffleduvet.com", "Yorgan & Dolgulu Ürünler",
     "Japon teknolojisiyle üretilen ultra hafif ama sıcak tutan yorgan",
     "2021'de Tokyo'dan ilham alınarak kuruldu, TikTok'ta 'bulut yorgan' olarak viral oldu"),
    ("Duvet Flip", "duvetflip.com", "Yorgan & Dolgulu Ürünler",
     "Çift taraflı sıcaklık ayarlı yorgan; yaz ve kış yüzü ayrı",
     "2020'de kuruldu, Indiegogo'da 500K$ topladıktan sonra Shopify'da satışa geçti"),
    ("Sloom", "sloom.co", "Yorgan & Dolgulu Ürünler",
     "Yeni Zelanda yünü dolgulu, tamamen doğal yorgan",
     "2019'da Auckland'da kuruldu, organik uyku ürünleri segmentinde Instagram ile büyüdü"),
    ("Aizome Bedding", "aizomebedding.com", "Yorgan & Dolgulu Ürünler",
     "Japon indigo boyama tekniğiyle üretilen antibakteriyel yorgan kapağı",
     "2018'de kuruldu, geleneksel Japon aizome tekniğini modern yorganlara uyarladı"),
    ("Woolshire Duvet", "woolshireduvet.co.uk", "Yorgan & Dolgulu Ürünler",
     "İngiliz yünü dolgulu dört mevsim yorgan; nem dengeleme özellikli",
     "2021'de kuruldu, İngiltere'de yerel üretim ve DTC model ile çevreci müşteri tabanı oluşturdu"),
    ("Terrera Sleep", "terrera.ca", "Yorgan & Dolgulu Ürünler",
     "Bambu elyaf dolgulu hipoalerjenik yorgan; Kanada menşeli",
     "2019'da kuruldu, bambu tekstil uzmanlığını uyku ürünlerine taşıyarak DTC büyüdü"),
    ("Tog24 Sleep", "tog24sleep.com", "Yorgan & Dolgulu Ürünler",
     "Outdoor teknolojisini yorgana uyarlayan İngiliz markası; tog dereceli dolgu",
     "2020'de İngiltere outdoor markasının spin-off'u olarak DTC uyku segmentine girdi"),
    ("Doona Collective", "doonacollective.com.au", "Yorgan & Dolgulu Ürünler",
     "Avustralya merkezli sürdürülebilir dolgulu yorgan; geri dönüştürülmüş malzeme",
     "2021'de Melbourne'da kuruldu, çevre bilinçli Z kuşağına Instagram ile ulaştı"),

    # =====================================================================
    # 3. Yastık & Uyku Aksesuarı (10)
    # =====================================================================
    ("Dosaze Pillow", "dosaze.com", "Yastık & Uyku Aksesuarı",
     "Kişiselleştirilebilir yükseklik ayarlı ergonomik yastık",
     "2020'de kuruldu, Facebook reklamlarıyla uyku problemine çözüm vaat ederek viral oldu"),
    ("Sleepgift", "sleepgift.com", "Yastık & Uyku Aksesuarı",
     "Bakır infüzyonlu antibakteriyel yastık kılıfı ve yastık",
     "2019'da kuruldu, Amazon'da hijyen odaklı uyku aksesuarı kategorisinde hızla yükseldi"),
    ("Nuzzle", "nuzzlepillow.com", "Yastık & Uyku Aksesuarı",
     "3 katmanlı ayarlanabilir yastık; yumuşaklık seviyesi kişiselleştirilebilir",
     "2021'de kuruldu, TikTok'ta uyku influencer'ları ile viral pazarlama stratejisi uyguladı"),
    ("Bear Mattress Pillow", "bearmattresspillow.com", "Yastık & Uyku Aksesuarı",
     "Sporcu odaklı soğutma jelli performans yastığı",
     "2019'da Bear markasının yastık uzantısı olarak DTC lansmanı yapıldı"),
    ("Kloudes", "kloudes.com", "Yastık & Uyku Aksesuarı",
     "Diz arası ergonomik yastık; yan yatanlar için özel tasarım",
     "2020'de kuruldu, Instagram'da hedefli reklamlarla niş uyku aksesuarı pazarına girdi"),
    ("Luff Sleep", "luffsleep.com", "Yastık & Uyku Aksesuarı",
     "Ayarlanabilir loft yastık; iç dolgu çıkarılıp eklenebilir",
     "2021'de kuruldu, Shopify üzerinden DTC satış ve TikTok ile büyüdü"),
    ("Groove Wellness", "groovewellness.co", "Yastık & Uyku Aksesuarı",
     "Boyun ağrısına özel kontur tasarımlı memory foam yastık",
     "2020'de kuruldu, Amazon'da ağrı kesici yastık kategorisinde 1 numara oldu"),
    ("Night Owl Pillow", "nightowlpillow.com", "Yastık & Uyku Aksesuarı",
     "Soğutma teknolojili gel-infused yastık; sıcak uyuyanlar için",
     "2019'da kuruldu, podcast reklamları ve Instagram ile DTC büyüme sağladı"),
    ("Peacelily Pillow", "peacelily.com.au", "Yastık & Uyku Aksesuarı",
     "Doğal lateks yastık; Avustralya'nın en çevreci uyku markası",
     "2018'de kuruldu, organik sertifikalı uyku ürünleriyle DTC Avustralya pazarını hedefledi"),
    ("Zen Bamboo Pillow", "zenbamboopillow.com", "Yastık & Uyku Aksesuarı",
     "Bambu kılıflı shredded memory foam yastık; hava sirkülasyonlu",
     "2019'da kuruldu, Amazon'da bambu yastık kategorisinde bestseller olarak DTC'ye genişledi"),

    # =====================================================================
    # 4. Ağırlıklı Battaniye (10)
    # =====================================================================
    ("Comma Home Weighted", "commahome.com", "Ağırlıklı Battaniye",
     "Elle Decor ödüllü minimalist tasarımlı ağırlıklı battaniye",
     "2019'da kuruldu, tasarım odaklı ev ürünleri platformu olarak Instagram'da büyüdü"),
    ("Hush Iced", "hushblankets.com/iced", "Ağırlıklı Battaniye",
     "Soğutma teknolojili ağırlıklı battaniye; sıcak iklimlere özel",
     "2018'de Kanada'da kuruldu, soğutma özellikli ağırlıklı battaniye nişinde DTC lider oldu"),
    ("Mela Weighted", "melacomfort.co.uk", "Ağırlıklı Battaniye",
     "İngiltere'nin en çok satan ağırlıklı battaniyesi; NHS onaylı",
     "2019'da Londra'da kuruldu, uyku sağlığı odaklı İngiliz DTC markası olarak büyüdü"),
    ("Calmzy", "calmzy.com", "Ağırlıklı Battaniye",
     "Hollanda merkezli cam boncuk dolgulu premium ağırlıklı battaniye",
     "2020'de Amsterdam'da kuruldu, Avrupa'da ağırlıklı battaniye trendinde DTC büyüdü"),
    ("Helix Weighted", "helixsleep.com/weighted", "Ağırlıklı Battaniye",
     "Uyku markasının ağırlıklı battaniye uzantısı; çift taraflı tasarım",
     "2020'de Helix Sleep'in ürün yelpazesi genişlemesi olarak DTC lansmanı yapıldı"),
    ("Kudd.ly Calm", "kuddly.co.uk/calm", "Ağırlıklı Battaniye",
     "Peluş minky kumaşlı ağırlıklı battaniye; İngiltere'de TikTok fenomeni",
     "2019'da İngiltere'de kuruldu, TikTok'ta #kuddly hashtag'iyle milyonlarca görüntülenme aldı"),
    ("Remy Sleep", "remysleep.com", "Ağırlıklı Battaniye",
     "Çocuklara özel hafif ağırlıklı battaniye; güvenlik sertifikalı",
     "2021'de kuruldu, ebeveyn influencer'ları ile Instagram'da büyüdü"),
    ("Dormu", "dormu.co.uk", "Ağırlıklı Battaniye",
     "İsveç tasarımlı İngiltere üretimi ağırlıklı battaniye; organik pamuk",
     "2019'da İsveç-İngiltere ortaklığıyla kuruldu, uyku kliniği tavsiyeleriyle DTC büyüdü"),
    ("Calm Touch", "calmtouch.co", "Ağırlıklı Battaniye",
     "Terapi odaklı ağırlıklı battaniye; farklı ağırlık seçenekleri",
     "2020'de kuruldu, mental sağlık farkındalığı kampanyalarıyla sosyal medyada büyüdü"),
    ("Luna Blanket", "lunablanket.com", "Ağırlıklı Battaniye",
     "Uygun fiyatlı ağırlıklı battaniye; Amazon'da 100K+ satış",
     "2018'de kuruldu, Amazon'da fiyat-performans odaklı stratejiyle kategorinin en çok satanı oldu"),

    # =====================================================================
    # 5. Battaniye & Throw (10)
    # =====================================================================
    ("Evangeline Linens", "evangelinelinens.com", "Battaniye & Throw",
     "Maine'de el dokuması merinos yünü throw; Amerikan zanaatkarlığı",
     "2019'da kuruldu, ABD'de yerel üretim ve Shopify DTC modeliyle premium throw pazarına girdi"),
    ("Tucca Blankets", "tuccablankets.com", "Battaniye & Throw",
     "Rüzgarda uçmayan plaj battaniyesi; patentli sabitleme sistemi",
     "2019'da İspanya'da kuruldu, Kickstarter'da viral olarak plaj battaniyesi nişinde DTC lider oldu"),
    ("Bohemian Mama Throw", "bohemianmamathrow.com", "Battaniye & Throw",
     "El yapımı Türk motifli boho throw battaniye",
     "2020'de kuruldu, Instagram'da boho ev dekorasyonu trendinde Etsy'den Shopify'a geçiş yaptı"),
    ("Sackcloth & Ashes Co", "sackclothandashes.com", "Battaniye & Throw",
     "Her satışta bir battaniye bağışlayan sosyal girişim",
     "2019'da Oregon'da kuruldu, 'buy one give one' modeliyle sosyal medyada büyüdü"),
    ("Nordifakt", "nordifakt.com", "Battaniye & Throw",
     "İskandinav tasarımlı geri dönüştürülmüş yün throw",
     "2020'de Danimarka'da kuruldu, sürdürülebilir İskandinav tasarım trendinde DTC satış yaptı"),
    ("Alicia Adams Alpaca", "aliciaadamsalpaca.com", "Battaniye & Throw",
     "Peru alpaka yünü lüks throw; el boyaması renkler",
     "2018'de kuruldu, lüks segment DTC stratejisiyle Instagram influencer'larıyla büyüdü"),
    ("Thula Blanket Co", "thulablankets.co.za", "Battaniye & Throw",
     "Güney Afrika el dokuması pamuklu battaniye; Afrika desenleri",
     "2019'da Cape Town'da kuruldu, etik üretim vurgusuyla global DTC satışa geçti"),
    ("Pendleton Heritage", "pendletonheritage.com", "Battaniye & Throw",
     "Amerikan mirası desenli modern throw koleksiyonu; DTC exclusive",
     "2020'de DTC exclusive koleksiyon olarak lansmanı yapıldı, genç kitleye Instagram ile ulaştı"),
    ("Calhoun Home", "calhounhome.com", "Battaniye & Throw",
     "Jacquard dokuma renkli throw battaniyeler; sanatçı iş birlikleri",
     "2019'da kuruldu, sanatçı kolaborasyonlarıyla Instagram'da dikkat çekti"),
    ("Wayfer Blanket", "wayferblanket.com", "Battaniye & Throw",
     "Seyahat boyutlu kompakt throw; taşınabilir battaniye konsepti",
     "2021'de kuruldu, TikTok'ta seyahat içerik üreticileriyle viral oldu"),

    # =====================================================================
    # 6. Giyilebilir Battaniye (10)
    # =====================================================================
    ("Snuggy UK", "snuggy.co.uk", "Giyilebilir Battaniye",
     "İngiltere'nin en popüler giyilebilir battaniye markası; cepli tasarım",
     "2019'da İngiltere'de kuruldu, TikTok ve Instagram reklamlarıyla İngiliz pazarında lider oldu"),
    ("Sienna Blanket Hoodie", "siennablankets.co.uk", "Giyilebilir Battaniye",
     "Sherpa astarlı kapüşonlu battaniye; uygun fiyat segmenti",
     "2020'de İngiltere'de kuruldu, Amazon UK'de bestseller olarak DTC'ye genişledi"),
    ("Lollipop Blankets", "lollipopblankets.com", "Giyilebilir Battaniye",
     "Çocuklara özel giyilebilir battaniye; eğlenceli desenler",
     "2021'de kuruldu, ebeveyn influencer'ları ile Instagram'da çocuk segmentinde büyüdü"),
    ("Menoverboard Blanket", "menoverboard.com.au", "Giyilebilir Battaniye",
     "Avustralya merkezli erkeklere özel giyilebilir battaniye",
     "2020'de kuruldu, Facebook reklamlarıyla hediye pazarında erkek segmentine odaklandı"),
    ("Oversize Hoodie UK", "oversizehoodieuk.com", "Giyilebilir Battaniye",
     "Ultra oversize kapüşonlu battaniye; sherpa iç yüzey",
     "2019'da İngiltere'de kuruldu, TikTok unboxing videolarıyla viral oldu"),
    ("Blanket Boss", "blanketboss.com.au", "Giyilebilir Battaniye",
     "Avustralya'nın kendi Oodie alternatifi; yerel üretim",
     "2021'de Melbourne'da kuruldu, Oodie alternatifi olarak uygun fiyatla DTC pazara girdi"),
    ("Cloud Blanket Co", "cloudblanketco.com", "Giyilebilir Battaniye",
     "Giyilebilir battaniye + cep telefonu cebi + su şişesi cebi",
     "2020'de kuruldu, Instagram'da pratik tasarım özellikleriyle dikkat çekti"),
    ("Firy Blanket", "firyblanket.com", "Giyilebilir Battaniye",
     "Isıtmalı giyilebilir battaniye; USB şarjlı ısıtma sistemi",
     "2021'de kuruldu, Kickstarter'da ısıtmalı giyilebilir battaniye olarak fon topladı"),
    ("Reductress Blanket", "reductressblanket.com", "Giyilebilir Battaniye",
     "Mizahi tasarımlı giyilebilir battaniye; pop kültür desenleri",
     "2020'de kuruldu, meme kültürü ve komik tasarımlarla sosyal medyada viral oldu"),
    ("Toasty Tek", "toastytek.com", "Giyilebilir Battaniye",
     "Teknoloji kumaşlı giyilebilir battaniye; grafen ısıtma teknolojisi",
     "2021'de kuruldu, Indiegogo'da grafen teknolojili giyilebilir battaniye olarak fon aldı"),

    # =====================================================================
    # 7. Havlu & Bornoz & Pestemal (10)
    # =====================================================================
    ("House of Jude Towels", "houseofjude.com", "Havlu & Bornoz & Pestemal",
     "Bambu havlu ve bornoz; antibakteriyel ve süper emici",
     "2019'da Kanada'da kuruldu, bambu tekstil odaklı DTC marka olarak Instagram'da büyüdü"),
    ("Canopy Towels", "canopytowels.co", "Havlu & Bornoz & Pestemal",
     "Gümüş iyon teknolojili koku önleyici havlu",
     "2020'de kuruldu, antimikrobiyal havlu nişinde Shopify DTC satışa başladı"),
    ("Hawkins & Brimble Bath", "hawkinsandbrimble.com/bath", "Havlu & Bornoz & Pestemal",
     "İngiliz berber markasının premium bornoz koleksiyonu",
     "2019'da İngiltere erkek bakım markasının ev tekstili uzantısı olarak DTC lansmanı yapıldı"),
    ("Goza Towels", "gozatowels.com", "Havlu & Bornoz & Pestemal",
     "Türk pamuğu pestemal ve havlu; geleneksel dokuma modern tasarım",
     "2019'da ABD'de Türk kökenli girişimci tarafından kuruldu, Shopify üzerinden DTC satış"),
    ("Lusso Cloud Towels", "lussocloud.com/towels", "Havlu & Bornoz & Pestemal",
     "Ultra yumuşak cloud-weave havlu; otel lüksü ev fiyatına",
     "2019'de kuruldu, terlik markasının havlu hattı olarak DTC genişleme yaptı"),
    ("Nisa Linen", "nisalinen.com", "Havlu & Bornoz & Pestemal",
     "Organik keten ve pamuk karışımı Türk hamam havlusu",
     "2020'de kuruldu, Etsy'de başarılı olduktan sonra kendi Shopify mağazasına geçti"),
    ("Everyday Sunday Towels", "everydaysunday.com.au", "Havlu & Bornoz & Pestemal",
     "Avustralya merkezli hızlı kuruyan microfiber plaj havlusu",
     "2020'de kuruldu, TikTok'ta plaj havlusu unboxing videolarıyla viral oldu"),
    ("Curated Cloth", "curatedcloth.com.au", "Havlu & Bornoz & Pestemal",
     "Avustralya merkezli organik pamuk havlu seti; otel kalitesi DTC fiyatı",
     "2020'de kuruldu, Facebook ve Instagram reklamlarıyla Avustralya'da hızla büyüdü"),
    ("Koza Home Pestemal", "kozahome.com", "Havlu & Bornoz & Pestemal",
     "Denizli üretimi el dokuması pestemal; global DTC satış",
     "2019'da Denizli'de kuruldu, Türk pestemal geleneğini modern e-ticaret ile global pazara taşıdı"),
    ("Harvest Bath", "harvestbath.com", "Havlu & Bornoz & Pestemal",
     "Waffle dokuma japon tarzı havlu ve bornoz; minimalist tasarım",
     "2020'de kuruldu, Japon banyo kültüründen ilham alarak DTC minimalist havlu sundu"),

    # =====================================================================
    # 8. Dolap & Giysi Organizeri (10)
    # =====================================================================
    ("Tylko Wardrobe", "tylko.com/wardrobe", "Dolap & Giysi Organizeri",
     "Polonya merkezli online konfigüre edilebilir dolap; AI tasarım aracı",
     "2019'da Varşova'da kuruldu, online mobilya özelleştirme aracıyla Avrupa'da DTC büyüdü"),
    ("Canyon Closets", "canyonclosets.com", "Dolap & Giysi Organizeri",
     "Modüler dolap sistemi; DIY kurulum kolay montaj",
     "2020'de kuruldu, YouTube montaj videoları ve Instagram ile DTC büyüdü"),
    ("Rackbuddy", "rackbuddy.com", "Dolap & Giysi Organizeri",
     "Danimarka tasarımlı endüstriyel boru askı sistemleri",
     "2018'de Danimarka'da kuruldu, İskandinav minimalizm trendinde Instagram ile büyüdü"),
    ("Neatsmith", "neatsmith.co.uk", "Dolap & Giysi Organizeri",
     "İngiltere'de ısmarlama gömme dolap çözümleri; online tasarım aracı",
     "2019'da kuruldu, online dolap tasarım aracıyla DTC modeli başlattı"),
    ("Stacked Closets", "stackedclosets.com", "Dolap & Giysi Organizeri",
     "İstiflenebilir modüler dolap kutuları; DIY montaj",
     "2020'de kuruldu, YouTube DIY dolap videoları ve Instagram ile DTC büyüdü"),
    ("Styleboard", "styleboardhome.com", "Dolap & Giysi Organizeri",
     "Görsel dolap planlama sistemi; outfit organizasyonu",
     "2021'de kuruldu, Instagram moda influencer'larıyla dolap organizasyonu trendi başlattı"),
    ("Tidy Wardrobe Co", "tidywardrobeco.com.au", "Dolap & Giysi Organizeri",
     "Avustralya merkezli velvet kaplı askı ve dolap aksesuar seti",
     "2020'de kuruldu, TikTok dolap dönüşüm videolarıyla Avustralya'da viral oldu"),
    ("Pretty Tidy", "prettytidy.co", "Dolap & Giysi Organizeri",
     "Estetik dolap bölücü ve etiketleme sistemi",
     "2021'de kuruldu, Instagram'da 'dolap estetiği' trendinde niş DTC marka olarak büyüdü"),
    ("Neat Method Shop", "neatmethod.com/shop", "Dolap & Giysi Organizeri",
     "Profesyonel organizasyon firmasının DTC ürün hattı",
     "2019'da organizasyon hizmet şirketinin ürün markası olarak DTC lansmanı yapıldı"),
    ("The Wardrobe Curator", "thewardrobecurator.com", "Dolap & Giysi Organizeri",
     "Kapsül gardırop organizasyon sistemi; modüler bölmeler",
     "2020'de kuruldu, kapsül gardırop trendinde Instagram'da niş kitleye ulaştı"),

    # =====================================================================
    # 9. Çekmece Düzenleyici (10)
    # =====================================================================
    ("Drawerganize Pro", "drawerganizepro.com", "Çekmece Düzenleyici",
     "Ayarlanabilir bambu çekmece bölücü; mutfak ve yatak odası uyumlu",
     "2020'de kuruldu, Amazon'da çekmece düzenleyici kategorisinde hızla yükseldi"),
    ("Minky Homecare", "minkyhomecare.co.uk", "Çekmece Düzenleyici",
     "İngiltere'nin ikonik ev düzenleme markası; çekmece organizatörleri",
     "2019'da DTC genişleme yaptı, Mrs Hinch etkisiyle Instagram'da patladı"),
    ("Orderly Home", "orderlyhome.co", "Çekmece Düzenleyici",
     "Özelleştirilebilir çekmece insert sistemi; 3D yazıcı teknolojisi",
     "2021'de kuruldu, 3D baskı teknolojisiyle kişiye özel çekmece çözümleri sundu"),
    ("Tidyboss", "tidyboss.com", "Çekmece Düzenleyici",
     "Silikon çekmece bölücü; esnek ve yıkanabilir tasarım",
     "2020'de kuruldu, TikTok'ta mutfak organizasyonu videolarıyla viral oldu"),
    ("Grid + Glam", "gridandglam.com", "Çekmece Düzenleyici",
     "Lüks kadife kaplı mücevher çekmece organizeri",
     "2019'da kuruldu, Instagram'da lüks organizasyon estetiğiyle DTC satış yaptı"),
    ("The Drawer Project", "thedrawerproject.com", "Çekmece Düzenleyici",
     "Sürdürülebilir geri dönüştürülmüş karton çekmece bölücü",
     "2021'de kuruldu, eko-bilinçli tüketicilere yönelik TikTok ile büyüdü"),
    ("Juvale Organizers", "juvale.com", "Çekmece Düzenleyici",
     "Uygun fiyatlı ev organizasyon ürünleri; Amazon private label başarısı",
     "2018'de kuruldu, Amazon private label stratejisiyle çekmece düzenleyici nişinde lider oldu"),
    ("Purse Drawer Org", "pursedrawerorg.com", "Çekmece Düzenleyici",
     "Çanta ve aksesuar için özel çekmece düzenleme sistemi",
     "2020'de kuruldu, Instagram'da lüks aksesuar organizasyonu nişinde DTC satış yaptı"),
    ("Tidio Drawer", "tidiodrawer.com", "Çekmece Düzenleyici",
     "Manyetik bağlantılı modüler çekmece organizeri; kolay yeniden düzenleme",
     "2021'de kuruldu, Kickstarter'da manyetik modüler sistem olarak fon topladı"),
    ("Luxe Drawer Co", "luxedrawerco.com.au", "Çekmece Düzenleyici",
     "Avustralya merkezli premium ahşap çekmece organizeri",
     "2020'de Sydney'de kuruldu, Instagram'da premium ev organizasyonu estetiğiyle büyüdü"),

    # =====================================================================
    # 10. Mutfak Organizasyonu (10)
    # =====================================================================
    ("Caraway Organizer", "carawayhome.com/storage", "Mutfak Organizasyonu",
     "Seramik tencere markasının mutfak organizasyon ürün hattı",
     "2020'de Caraway'in ürün genişlemesi olarak DTC lansmanı yapıldı"),
    ("Fridge No More Co", "fridgenomore.co", "Mutfak Organizasyonu",
     "Buzdolabı içi organizasyon kutuları; şeffaf stackable tasarım",
     "2021'de kuruldu, TikTok buzdolabı organizasyonu videolarıyla viral oldu"),
    ("Neat Fridge", "neatfridge.com", "Mutfak Organizasyonu",
     "Buzdolabı organizasyon seti; tarih etiketli saklama kutuları",
     "2020'de kuruldu, Instagram'da buzdolabı dönüşüm before/after paylaşımlarıyla büyüdü"),
    ("Kilner Pantry", "kilnerpantry.co.uk", "Mutfak Organizasyonu",
     "İngiliz cam kavanoz geleneğiyle modern mutfak organizasyonu",
     "2019'da İngiliz markasının DTC genişlemesi olarak Shopify'da satışa başladı"),
    ("Stacked Pantry Co", "stackedpantry.com.au", "Mutfak Organizasyonu",
     "Avustralya merkezli modüler kiler organizasyonu; bambu kapaklı",
     "2021'de kuruldu, Instagram'da kiler dönüşüm trendinde Avustralya'da viral oldu"),
    ("The Pantry Edit", "thepantryedit.com", "Mutfak Organizasyonu",
     "Etiketleme ve kiler organizasyon kiti; başlangıç seti konsepti",
     "2020'de kuruldu, TikTok pantry restock videolarıyla büyüdü"),
    ("Humble Crew Kitchen", "humblecrewkitchen.com", "Mutfak Organizasyonu",
     "Çocuk dostu mutfak organizasyonu; alçak raf ve kolay erişim",
     "2019'da kuruldu, Montessori mutfak trendinde Instagram ebeveyn topluluğuyla büyüdü"),
    ("Sorted Kitchen Co", "sortedkitchenco.com", "Mutfak Organizasyonu",
     "Baharat çekmecesi organizeri; etiketli cam kavanoz seti",
     "2020'de kuruldu, baharat organizasyonu nişinde TikTok ile viral oldu"),
    ("Stackup Kitchen", "stackupkitchen.com", "Mutfak Organizasyonu",
     "Dikey istiflenebilir mutfak rafı; tezgah üstü alan tasarrufu",
     "2021'de kuruldu, küçük mutfak çözümleri segmentinde Amazon'da başarılı oldu"),
    ("Prepd Pantry", "prepdpantry.co", "Mutfak Organizasyonu",
     "Meal prep odaklı mutfak organizasyonu; haftalık planlama panosu dahil",
     "2020'de kuruldu, fitness ve meal prep topluluğunda Instagram ile büyüdü"),

    # =====================================================================
    # 11. Banyo Organizasyonu (10)
    # =====================================================================
    ("Tooletries AU", "tooletries.com.au", "Banyo Organizasyonu",
     "Silikon yapışkanlı duş organizeri; delik açmadan montaj",
     "2018'de Avustralya'da kuruldu, erkek banyo organizasyonu nişinde Instagram ile viral oldu"),
    ("ShowerGem", "showergem.com", "Banyo Organizasyonu",
     "İrlanda tasarımlı paslanmaz duş rafı; güçlü vantuz sistemi",
     "2019'da İrlanda'da kuruldu, Kickstarter başarısından sonra DTC satışa geçti"),
    ("Designstuff", "designstuff.com.au", "Banyo Organizasyonu",
     "İskandinav tarzı banyo organizasyonu; Avustralya DTC seçkisi",
     "2019'da kuruldu, İskandinav tasarım küratörlüğüyle Avustralya'da DTC büyüdü"),
    ("Bath Bliss Pro", "bathblisspro.com", "Banyo Organizasyonu",
     "Profesyonel banyo organizasyonu çözümleri; modüler raf sistemi",
     "2020'de kuruldu, Instagram'da banyo dönüşüm before/after içerikleriyle büyüdü"),
    ("Clarity Bath", "claritybath.co", "Banyo Organizasyonu",
     "Şeffaf akrilik banyo organizeri; lüks otel görünümü",
     "2021'de kuruldu, TikTok'ta banyo organizasyonu ASMR videolarıyla viral oldu"),
    ("Navaris Bath", "navarisbath.com", "Banyo Organizasyonu",
     "Bambu banyo rafı ve organizeri; doğal malzeme odaklı",
     "2019'da Almanya'da kuruldu, Amazon Europe genelinde bambu banyo ürünlerinde lider oldu"),
    ("The Bath Edit", "thebathedit.com", "Banyo Organizasyonu",
     "Banyo organizasyon başlangıç kiti; etiket ve kutu seti",
     "2020'de kuruldu, Instagram'da banyo decluttering trendinde büyüdü"),
    ("Stick & Store", "stickandstore.co", "Banyo Organizasyonu",
     "Yapışkanlı banyo organizeri; kiracı dostu çözümler",
     "2021'de kuruldu, TikTok'ta kiracı dostu ev çözümleri nişinde viral oldu"),
    ("Splash Bath Org", "splashbathorg.com", "Banyo Organizasyonu",
     "Su geçirmez banyo organizasyonu; IPX7 korumalı kutular",
     "2020'de kuruldu, Amazon'da su geçirmez banyo organizasyonu nişinde hızla büyüdü"),
    ("Bamboo Bliss Bath", "bambooblissbath.com.au", "Banyo Organizasyonu",
     "Avustralya merkezli bambu banyo aksesuarı ve organizeri",
     "2019'da kuruldu, sürdürülebilir banyo ürünleri segmentinde Instagram ile büyüdü"),

    # =====================================================================
    # 12. Seyahat Organizeri (10)
    # =====================================================================
    ("Vasco Travel", "vascotravel.co", "Seyahat Organizeri",
     "Sıkıştırmalı packing cube seti; %60 daha fazla alan",
     "2019'da kuruldu, TikTok seyahat hack videolarıyla viral oldu"),
    ("Monos Compak", "monos.com/compak", "Seyahat Organizeri",
     "Premium seyahat organizeri; bavul markasının aksesuar hattı",
     "2020'de Kanada bavul markasının ürün genişlemesi olarak DTC lansmanı yapıldı"),
    ("Nomatic Packing", "nomatic.com/packing", "Seyahat Organizeri",
     "Teknoloji seyahati için özel organizerlar; kablo ve gadget cepler",
     "2019'da sırt çantası markasının seyahat organizasyon ürün hattı olarak genişledi"),
    ("Roam & Repack", "roamandrepack.com", "Seyahat Organizeri",
     "Sürdürülebilir geri dönüştürülmüş naylon seyahat organizeri",
     "2021'de kuruldu, çevreci seyahat topluluğunda Instagram ile büyüdü"),
    ("HiOrganize", "hiorganize.com", "Seyahat Organizeri",
     "Japon minimalizm ilhamıyla seyahat organizasyonu çözümleri",
     "2020'de kuruldu, Marie Kondo ilhamıyla seyahat organizasyonu nişinde DTC satış yaptı"),
    ("Stow London", "stowlondon.com", "Seyahat Organizeri",
     "İngiliz lüks deri seyahat organizeri; Business Class esintisi",
     "2018'de Londra'da kuruldu, premium seyahat aksesuarı segmentinde DTC büyüdü"),
    ("Outline Travel", "outlinetravel.co", "Seyahat Organizeri",
     "Ultralight seyahat organizeri; 30 gramlık packing cube",
     "2021'de kuruldu, ultralight seyahat topluluğunda Reddit ve Instagram ile büyüdü"),
    ("Ringke Travel", "ringketravel.com", "Seyahat Organizeri",
     "Kore tasarımlı kompakt seyahat organizeri; teknoloji aksesuarı",
     "2019'da Güney Kore'de kuruldu, Amazon global satışla DTC genişleme yaptı"),
    ("Tidy Globe", "tidyglobe.co", "Seyahat Organizeri",
     "Dünya gezgini için modüler seyahat organizasyon sistemi",
     "2020'de kuruldu, digital nomad topluluğunda Instagram ile niş büyüme sağladı"),
    ("Fly Wise Bags", "flywisebags.com", "Seyahat Organizeri",
     "TSA uyumlu seyahat organizeri; sıvı taşıma çözümü dahil",
     "2019'da kuruldu, Amazon'da TSA-uyumlu seyahat çantası kategorisinde bestseller oldu"),

    # =====================================================================
    # 13. Makyaj & Kozmetik Organizeri (10)
    # =====================================================================
    ("Acrylic Dream Org", "acrylicdreamorg.com", "Makyaj & Kozmetik Organizeri",
     "Premium akrilik makyaj organizeri; IKEA çekmece uyumlu modüler sistem",
     "2020'de kuruldu, IKEA hack trendinde TikTok ile viral olarak DTC büyüdü"),
    ("Tidy Palette", "tidypalette.com", "Makyaj & Kozmetik Organizeri",
     "Manyetik paleti duvar organizeri; makyaj koleksiyonu sergileme",
     "2021'de kuruldu, TikTok'ta makyaj koleksiyonu sergileme trendinde viral oldu"),
    ("Glow Up Organiser", "glowuporganiser.com.au", "Makyaj & Kozmetik Organizeri",
     "LED aydınlatmalı döner makyaj organizeri; akıllı ayna entegrasyonu",
     "2021'de kuruldu, TikTok'ta makyaj köşesi aydınlatma trendinde viral oldu"),
    ("Glam Vault", "glamvault.co", "Makyaj & Kozmetik Organizeri",
     "Döner makyaj kulesi; 360 derece erişimli organizasyon",
     "2019'da kuruldu, TikTok'ta makyaj organizasyonu transformation videolarıyla viral oldu"),
    ("Pretty Display Co", "prettydisplayco.com.au", "Makyaj & Kozmetik Organizeri",
     "Parfüm ve makyaj display organizeri; vitriner konsepti",
     "2020'de Avustralya'da kuruldu, Instagram'da parfüm koleksiyonu sergileme nişinde büyüdü"),
    ("Matte Black Organiser", "matteblackorganiser.com.au", "Makyaj & Kozmetik Organizeri",
     "Mat siyah akrilik makyaj organizeri; modern minimalist tasarım",
     "2021'de kuruldu, Instagram'da siyah banyo estetiği trendinde niş büyüme sağladı"),
    ("Skin Shelf", "skinshelf.co", "Makyaj & Kozmetik Organizeri",
     "Cilt bakım ürünleri için özel rafli organizer; rutin takip etiketi",
     "2020'de kuruldu, TikTok skincare şelfie trendinde viral oldu"),
    ("Beauty Stack", "beautystack.co.uk", "Makyaj & Kozmetik Organizeri",
     "İstiflenebilir modüler makyaj kutuları; renk kodlu sistem",
     "2019'da İngiltere'de kuruldu, makyaj sanatçıları ile Instagram'da büyüdü"),
    ("Glam Fridge", "glamfridge.com", "Makyaj & Kozmetik Organizeri",
     "Mini kozmetik buzdolabı organizeri; cilt bakım saklama çözümü",
     "2020'de kuruldu, TikTok'ta skincare fridge trendinde viral oldu"),
    ("Powder Room Co", "powderroomco.com.au", "Makyaj & Kozmetik Organizeri",
     "Avustralya merkezli lüks makyaj masası organizasyon seti",
     "2019'da kuruldu, Instagram'da powder room dönüşüm paylaşımlarıyla büyüdü"),

    # =====================================================================
    # 14. Ev Kokusu & Mum (10)
    # =====================================================================
    ("Dilo Candle", "dilocandle.com", "Ev Kokusu & Mum",
     "Nijerya ilhamıyla tropik kokulu soya mumu",
     "2019'da kuruldu, Afrika kokularını modern mum tasarımıyla buluşturarak DTC büyüdü"),
    ("Yield Design Candle", "yielddesign.co/candles", "Ev Kokusu & Mum",
     "Minimalist cam şişeli organik soya mumu; refill sistemi",
     "2020'de Florida tasarım markasının mum hattı olarak DTC genişleme yaptı"),
    ("Kobo Candles", "kobocandlesny.com", "Ev Kokusu & Mum",
     "New York merkezli soya mumu; eğlenceli isimler ve vintage tasarım",
     "2019'da Brooklyn'de kuruldu, vintage ambalaj tasarımıyla Instagram'da DTC büyüdü"),
    ("Aerangis Candles", "aerangiscandles.com", "Ev Kokusu & Mum",
     "Botanik ilhamıyla lüks kokulu mum; el yapımı",
     "2019'da kuruldu, Instagram'da botanik ev kokusu estetiğiyle büyüdü"),
    ("Bon Lux", "bonlux.com.au", "Ev Kokusu & Mum",
     "Avustralya merkezli vegan soya mumu; botanik kokular",
     "2019'da Melbourne'da kuruldu, vegan mum nişinde Instagram ile Avustralya DTC büyüdü"),
    ("Earl of East x Studio", "earlofeast.com/studio", "Ev Kokusu & Mum",
     "Londra atölye deneyimli artisanal ev kokusu markası",
     "2018'de Londra'da kuruldu, mum yapım atölyeleri ve DTC satışla büyüdü"),
    ("Scent Lab", "scentlab.com.au", "Ev Kokusu & Mum",
     "Kişiselleştirilebilir ev kokusu; online parfüm karışım aracı",
     "2020'de kuruldu, online koku özelleştirme konseptiyle DTC niş pazarda büyüdü"),
    ("Bala Home Scent", "balahomescent.com", "Ev Kokusu & Mum",
     "Bali ilhamıyla doğal balmumu mum ve tütsü",
     "2019'da Bali'de kuruldu, yoga ve wellness topluluğunda Instagram ile global DTC satışa geçti"),
    ("Posie Candles", "posiecandles.com.au", "Ev Kokusu & Mum",
     "Avustralya botanik bahçe ilhamıyla soya mumu koleksiyonu",
     "2019'da kuruldu, Instagram'da botanik estetik mum fotoğraflarıyla DTC büyüdü"),
    ("Homecoming Candle", "homecomingcandle.com", "Ev Kokusu & Mum",
     "Nostalji temalı kokulu mum; memleket kokuları serisi",
     "2020'de kuruldu, nostaljik koku konseptiyle Instagram'da duygusal pazarlama stratejisi uyguladı"),

    # =====================================================================
    # 15. Halı & Kilim (10)
    # =====================================================================
    ("Loloi x Amber Lewis", "loloiamberlewis.com", "Halı & Kilim",
     "Influencer kolaborasyonlu vintage tarzı halı koleksiyonu",
     "2019'da influencer iş birliği olarak lansmanı yapıldı, Instagram'da ev dekor trendinde viral oldu"),
    ("House of Rugs DTC", "houseofrugs.com.au", "Halı & Kilim",
     "Avustralya merkezli uygun fiyatlı modern halı; DTC model",
     "2019'da kuruldu, perakende marjını ortadan kaldırarak DTC uygun fiyatlı halı sundu"),
    ("Lilla Rugs", "lillarugs.com", "Halı & Kilim",
     "İngiltere merkezli vintage Türk ve Fas kilim küratörü",
     "2018'de kuruldu, Instagram'da vintage kilim estetiğiyle İngiltere DTC pazarında büyüdü"),
    ("Cyrus Artisan Rugs", "cyrusartisanrugs.com", "Halı & Kilim",
     "El dokuması İran ve Afgan halıları; online DTC satış",
     "2019'da kuruldu, geleneksel halı ticaretini DTC modeline taşıyarak online satışa geçti"),
    ("Sunday Citizen Rug", "sundaycitizen.com/rugs", "Halı & Kilim",
     "Kristal infüzyonlu wellness halı; yeni nesil ev tekstili",
     "2020'de battaniye markasının halı uzantısı olarak DTC lansmanı yapıldı"),
    ("Ones Studio Rugs", "onesstudio.com", "Halı & Kilim",
     "Güney Kore tasarımlı minimalist halı; modern Asya estetiği",
     "2021'de Seul'de kuruldu, K-interior trendinde Instagram ile global DTC satışa başladı"),
    ("Kalim Home", "kalimhome.co", "Halı & Kilim",
     "Fas'tan doğrudan temin edilen el dokuması kilimler",
     "2019'da kuruldu, Fas zanaatkarlarıyla doğrudan çalışarak DTC kilim satışı başlattı"),
    ("Nani Marquina DTC", "nanimarquina.com/dtc", "Halı & Kilim",
     "İspanyol tasarım halısı; online exclusive koleksiyonlar",
     "2020'de DTC kanalını açarak online exclusive tasarımlar sunmaya başladı"),
    ("Tribe Home", "tribehome.com.au", "Halı & Kilim",
     "Avustralya merkezli el dokuması jüt ve yün halı",
     "2018'de kuruldu, doğal malzeme trendinde Instagram ile Avustralya'da DTC büyüdü"),
    ("Layered Interior", "layeredinterior.com", "Halı & Kilim",
     "İsveç tasarımlı premium halı; online sipariş üzerine üretim",
     "2019'da Stockholm'de kuruldu, İskandinav tasarım halı segmentinde DTC satışla büyüdü"),

    # =====================================================================
    # 16. Perde & Ev Tekstili (10)
    # =====================================================================
    ("Wovn Curtains", "wovncurtains.co", "Perde & Ev Tekstili",
     "Online ölçüye özel perde; 200+ kumaş seçeneği",
     "2020'de kuruldu, online perde özelleştirme aracıyla DTC pazara girdi"),
    ("Deconovo Home", "deconovohome.com", "Perde & Ev Tekstili",
     "Amazon'da en çok satan karartma perde markası",
     "2018'de kuruldu, Amazon private label stratejisiyle perde kategorisinde lider oldu"),
    ("Stitched Custom", "stitchedcustom.co.uk", "Perde & Ev Tekstili",
     "İngiltere merkezli ölçüye özel online perde; sürdürülebilir kumaşlar",
     "2019'da kuruldu, online ölçü aracıyla İngiltere'de DTC perde satışı başlattı"),
    ("Sarita Handa Home", "saritahanda.com", "Perde & Ev Tekstili",
     "Hindistan el nakışlı lüks perde ve ev tekstili",
     "2018'de DTC genişleme yaparak global online satışa başladı"),
    ("Curtains Direct", "curtainsdirect.co.nz", "Perde & Ev Tekstili",
     "Yeni Zelanda merkezli online ölçüye özel perde hizmeti",
     "2019'da kuruldu, Yeni Zelanda'da online perde DTC modelini popülerleştirdi"),
    ("Tonic Living", "tonicliving.com", "Perde & Ev Tekstili",
     "Kanada merkezli tasarım kumaş ve perde; online özelleştirme",
     "2018'de kuruldu, Kanada'da online ev tekstili özelleştirme nişinde DTC büyüdü"),
    ("Spiffy Spools DTC", "spiffyspools.com/dtc", "Perde & Ev Tekstili",
     "Hindistan üretimi ölçüye özel perde; 1000+ kumaş",
     "2019'da DTC modelini genişleterek global online perde özelleştirme sunmaya başladı"),
    ("Barn & Willow Studio", "barnandwillow.com/studio", "Perde & Ev Tekstili",
     "Online tasarım danışmanlığıyla premium perde; ücretsiz kumaş numunesi",
     "2018'de kuruldu, online interior design danışmanlığıyla DTC perde satışında fark yarattı"),
    ("Eclipse Home", "eclipsehometextile.com", "Perde & Ev Tekstili",
     "Akıllı termal perde; enerji tasarrufu odaklı ev tekstili",
     "2020'de kuruldu, enerji tasarrufu trendinde Meta reklamlarıyla DTC büyüdü"),
    ("Drapify", "drapify.com", "Perde & Ev Tekstili",
     "AI destekli online perde tasarım aracı; oda fotoğrafından öneri",
     "2021'de kuruldu, AI perde öneri sistemiyle DTC pazara yenilikçi giriş yaptı"),

    # =====================================================================
    # 17. Dekoratif Yastık & Kırlent (10)
    # =====================================================================
    ("Edie Parker Home Pillow", "edieparkerhome.com/pillows", "Dekoratif Yastık & Kırlent",
     "Pop art tarzı akrilik aksesuar markasının dekoratif kırlent hattı",
     "2020'de moda aksesuar markasının ev dekor uzantısı olarak DTC lansmanı yapıldı"),
    ("Eny Home Pillows", "enyhome.com/pillows", "Dekoratif Yastık & Kırlent",
     "Güney Kore minimalist tasarım kırlent; doğal kumaşlar",
     "2019'da Seul'de kuruldu, K-home interior trendinde Instagram ile global satışa başladı"),
    ("The Citizenry Kırlent", "the-citizenry.com/pillows-new", "Dekoratif Yastık & Kırlent",
     "Zanaat odaklı global el yapımı dekoratif kırlent koleksiyonu",
     "2020'de yeni kırlent koleksiyonu ile DTC ürün hattını genişletti"),
    ("Block Print Studio", "blockprintstudio.com", "Dekoratif Yastık & Kırlent",
     "Hindistan blok baskı tekniğiyle el yapımı kırlent",
     "2019'da kuruldu, geleneksel Hint blok baskıyı modern kırlent tasarımına taşıdı"),
    ("St. Frank Pillow", "stfrankpillow.com", "Dekoratif Yastık & Kırlent",
     "Afrika kumaşlarından üretilen lüks dekoratif kırlent",
     "2018'de kuruldu, Afrika tekstil mirasını lüks ev dekoruna taşıyarak DTC büyüdü"),
    ("Justina Blakeney Kırlent", "justinablakeney.com/pillows-new", "Dekoratif Yastık & Kırlent",
     "Boho maksimalist tasarım kırlent; canlı renkler ve dokular",
     "2019'da Jungalow markasının genişlemesi olarak DTC kırlent koleksiyonu başlattı"),
    ("Leah Singh Pillows", "leahsingh.com", "Dekoratif Yastık & Kırlent",
     "El punch needle tekniğiyle yapılan sanatsal kırlent",
     "2018'de kuruldu, zanaat odaklı lüks kırlent nişinde Instagram ile DTC büyüdü"),
    ("Dusen Dusen Pillow", "dusendusen.com/pillows", "Dekoratif Yastık & Kırlent",
     "Grafik tasarım odaklı renkli pattern kırlentler",
     "2019'da moda markasının ev dekor uzantısı olarak DTC kırlent lansmanı yapıldı"),
    ("Pampa", "pampa.com.au", "Dekoratif Yastık & Kırlent",
     "Arjantin el dokuması kırlent; adil ticaret sertifikalı Güney Amerika zanaatı",
     "2018'de Avustralya'da kuruldu, Arjantin zanaatkarlarıyla çalışarak DTC sosyal girişim olarak büyüdü"),
    ("Bolé Home Pillows", "boleroadtextiles.com/pillows", "Dekoratif Yastık & Kırlent",
     "Etiyopya el dokuması pamuklu modern kırlent",
     "2019'da Etiyopya tekstil geleneğini modern kırlent tasarımına taşıyarak DTC genişledi"),

    # =====================================================================
    # 18. Bebek Uyku & Tekstil (10)
    # =====================================================================
    ("Kyte Baby Sleep", "kytebaby.com/sleep", "Bebek Uyku & Tekstil",
     "Bambu elyaf bebek uyku tulumu; TikTok'un en viral bebek markası",
     "2019'da kuruldu, TikTok anne topluluğunda bambu uyku tulumlarıyla viral oldu"),
    ("Gunamuna Sleep", "gunamuna.com/sleep", "Bebek Uyku & Tekstil",
     "Patentli fermuarlı bebek uyku tulumu; kolay bez değiştirme",
     "2019'da kuruldu, pratik tasarımıyla anne bloggerları aracılığıyla DTC büyüdü"),
    ("Burt's Bees Baby Sleep", "burtsbeesbaby.com/sleep", "Bebek Uyku & Tekstil",
     "Organik pamuk bebek uyku seti; çevreci ebeveynlere yönelik",
     "2019'da DTC uyku koleksiyonu genişlemesi olarak Shopify'da satışa başladı"),
    ("Ziggy Baby", "ziggybaby.com", "Bebek Uyku & Tekstil",
     "Modern desen bebek çarşafı ve uyku seti; unisex tasarım",
     "2020'de kuruldu, cinsiyet nötr bebek ürünleri trendinde Instagram ile büyüdü"),
    ("Bonsie Baby", "bonsiebaby.com", "Bebek Uyku & Tekstil",
     "Ten tene temas kolaylaştıran patentli bebek tulumu",
     "2019'da kuruldu, ten tene temas bilincini artıran ürünüyle anne forumlarında viral oldu"),
    ("Loulou Lollipop Sleep", "louloulollipop.com/sleep", "Bebek Uyku & Tekstil",
     "Kanada merkezli muslin bebek battaniye ve uyku aksesuarı",
     "2018'de kuruldu, Instagram'da renkli muslin tasarımlarıyla Kanada'da DTC büyüdü"),
    ("Goumi Baby Sleep", "goumikids.com/sleep", "Bebek Uyku & Tekstil",
     "Organik pamuk ve bambu karışımı bebek uyku giyim",
     "2019'da kuruldu, sürdürülebilir bebek giyim odaklı DTC marka olarak büyüdü"),
    ("Newton Baby Textile", "newtonbaby.com/textile", "Bebek Uyku & Tekstil",
     "Nefes alabilen bebek yatak çarşafı; güvenlik odaklı tasarım",
     "2020'de Newton Baby'nin tekstil uzantısı olarak DTC lansmanı yapıldı"),
    ("Mori Sleep", "babymori.com/sleep", "Bebek Uyku & Tekstil",
     "İngiliz merkezli organik bambu bebek uyku koleksiyonu",
     "2018'de Londra'da kuruldu, premium bebek uyku ürünleriyle İngiltere DTC pazarında lider oldu"),
    ("Boba Wrap Sleep", "bobawrap.com/sleep", "Bebek Uyku & Tekstil",
     "Bebek taşıyıcı markasının uyku tekstili uzantısı",
     "2020'de taşıyıcı markasının bebek uyku ürünlerine genişlemesi olarak DTC lansmanı yapıldı"),

    # =====================================================================
    # 19. Anne & Hamile Ürünleri (10)
    # =====================================================================
    ("Storq Maternity", "storq.com", "Anne & Hamile Ürünleri",
     "Minimalist hamile giyim; kapsül gardırop konsepti",
     "2018'de kuruldu, hamile kapsül gardırop trendinde Instagram ile DTC büyüdü"),
    ("Bodily Postpartum", "itsbodily.com", "Anne & Hamile Ürünleri",
     "Doğum sonrası iyileşme ürünleri; postpartum bakım kiti",
     "2020'de kuruldu, doğum sonrası bakım farkındalığıyla Instagram'da DTC büyüdü"),
    ("Kindred Bravely Plus", "kindredbravely.com/plus", "Anne & Hamile Ürünleri",
     "Plus size hamile ve emzirme giyim; kapsayıcı beden aralığı",
     "2019'da ürün hattını plus size'a genişleterek kapsayıcılık odaklı DTC büyüme sağladı"),
    ("Hatch Collection New", "hatchcollection.com/new", "Anne & Hamile Ürünleri",
     "Lüks hamile giyim ve doğum hazırlık ürünleri",
     "2019'da yeni ürün hatlarıyla DTC genişleme yaparak lüks anne segmentinde büyüdü"),
    ("Baobei Maternity", "baobeimaternity.com", "Anne & Hamile Ürünleri",
     "Asya-Amerikan tasarımlı modern hamile giyim",
     "2020'de kuruldu, çok kültürlü hamile giyim nişinde Instagram ile DTC büyüdü"),
    ("Kangaroo Care Co", "kangaroocareco.com", "Anne & Hamile Ürünleri",
     "Ten tene temas gömleği; bebek taşıma entegrasyonlu üst giyim",
     "2019'da kuruldu, kangaroo care trendinde anne topluluklarında viral oldu"),
    ("Partum Panties", "partumpanties.com", "Anne & Hamile Ürünleri",
     "Doğum sonrası iyileşme iç çamaşırı; tek kullanımlık premium",
     "2021'de kuruldu, doğum sonrası iç çamaşırı nişinde TikTok ile viral oldu"),
    ("Nyssa Care", "nyssacare.com", "Anne & Hamile Ürünleri",
     "Postpartum perine bakım ürünleri; buz paketi entegreli iç çamaşırı",
     "2020'de kuruldu, postpartum fiziksel iyileşme ürünleriyle DTC niş pazarda büyüdü"),
    ("Momkind", "momkind.com", "Anne & Hamile Ürünleri",
     "Avrupa merkezli doğum sonrası vücut bakım seti; belly wrap dahil",
     "2019'da Hollanda'da kuruldu, Avrupa'da postpartum bakım ürünleriyle DTC büyüdü"),
    ("Willow Pump Wear", "willowpump.com/wear", "Anne & Hamile Ürünleri",
     "Giyilebilir süt pompası uyumlu emzirme giyim",
     "2020'de pompa markasının giyim uzantısı olarak DTC lansmanı yapıldı"),

    # =====================================================================
    # 20. Ev Giyim & Loungewear (10)
    # =====================================================================
    ("Lunya Loungewear", "lunya.co", "Ev Giyim & Loungewear",
     "Washable silk loungewear; lüks ev giyim segmentinin lideri",
     "2018'de kuruldu, yıkanabilir ipek konseptiyle lüks loungewear nişinde DTC lider oldu"),
    ("Desmond & Dempsey", "desmondanddempsey.com", "Ev Giyim & Loungewear",
     "Londra merkezli tropikal baskılı lüks pijama; sanat ilhamı",
     "2018'de Londra'da kuruldu, sanatsal baskı tasarımlarıyla Instagram'da DTC viral büyüdü"),
    ("Lettfolk", "lettfolk.com", "Ev Giyim & Loungewear",
     "İskandinav tarzı minimalist loungewear; organik pamuk",
     "2020'de kuruldu, İskandinav minimalizm trendinde Instagram ile DTC büyüdü"),
    ("Cou Cou Intimates Home", "coucouintimated.com/home", "Ev Giyim & Loungewear",
     "Organik pamuk ev giyim seti; yastık kılıfıyla eşleşen pijama",
     "2019'da kuruldu, yatak-pijama eşleştirme konseptiyle Instagram'da viral oldu"),
    ("Richer Poorer Lounge", "richerpoorer.com/lounge", "Ev Giyim & Loungewear",
     "Çorap markasının loungewear genişlemesi; temel parçalar",
     "2019'da çorap markasının ev giyim hattı olarak DTC genişleme yaptı"),
    ("Clo Studios Home", "clostudios.com/home", "Ev Giyim & Loungewear",
     "Avustralya merkezli minimal kesim loungewear; nötr tonlar",
     "2020'de Avustralya moda markasının ev giyim uzantısı olarak DTC lansmanı yapıldı"),
    ("Sijo Lounge", "sijohome.com/lounge", "Ev Giyim & Loungewear",
     "Eucalyptus elyaf loungewear; çevreci lüks ev giyim",
     "2020'de yatak markasının loungewear genişlemesi olarak DTC lansmanı yapıldı"),
    ("Skims Cozy", "skims.com/cozy", "Ev Giyim & Loungewear",
     "Yumuşak örgü loungewear koleksiyonu; TikTok'ta mega viral",
     "2019'da Skims'in ev giyim hattı olarak lansmanı yapıldı, TikTok'ta milyonlarca görüntülenme"),
    ("Bare Home Lounge", "barehome.com/lounge", "Ev Giyim & Loungewear",
     "Bambu elyaf unisex loungewear; antibakteriyel ve nefes alır",
     "2021'de kuruldu, bambu tekstil trendinde DTC loungewear pazarına girdi"),
    ("Cocooning Home", "cocooning.co/home", "Ev Giyim & Loungewear",
     "Kaşmir karışım ev giyim; kış loungewear uzmanı",
     "2020'de kuruldu, premium kış loungewear nişinde Instagram ile DTC büyüdü"),

    # =====================================================================
    # 21. Terlik & Ev Ayakkabısı (10)
    # =====================================================================
    ("Mahabis V2", "mahabis.com", "Terlik & Ev Ayakkabısı",
     "Ayrılabilir tabanlı dış mekan uyumlu terlik; modüler tasarım",
     "2018'de yeniden lansmanı yapıldı, modüler terlik konseptiyle Instagram'da DTC büyüdü"),
    ("Nuvola Slippers", "nuvola.co", "Terlik & Ev Ayakkabısı",
     "İspanyol terlik markası; renkli boot tarzı ev ayakkabısı",
     "2019'da İspanya'da kuruldu, renkli terlik boot tasarımıyla Avrupa'da DTC büyüdü"),
    ("Socksss Slides", "socksss.com/slides", "Terlik & Ev Ayakkabısı",
     "Sanatçı kolaborasyonlu tasarım terlik; limitli üretim",
     "2019'da kuruldu, sanatçı kolaborasyonlarıyla terlik koleksiyonu DTC lansmanı yapıldı"),
    ("Nanga Slippers", "nanga.at", "Terlik & Ev Ayakkabısı",
     "Avusturya el yapımı yün keçe terlik; Alp geleneği modern tasarım",
     "2018'de Avusturya'da kuruldu, Avrupa keçe terlik geleneğini modern DTC satışa taşıdı"),
    ("Warmies Slippers", "warmies.com/slippers", "Terlik & Ev Ayakkabısı",
     "Mikrodalga ile ısıtılabilen lavanta dolgulu terlik",
     "2019'da İngiltere'de kuruldu, ısıtılabilir terlik konseptiyle Amazon ve DTC'de viral oldu"),
    ("Rivs Slippers", "rivs.co", "Terlik & Ev Ayakkabısı",
     "Avustralya merinos yünü terlik; minimalist İskandinav tasarım",
     "2020'de kuruldu, Avustralya yünü ve İskandinav tasarım birleşimiyle DTC büyüdü"),
    ("Tokyoes", "tokyoes.com", "Terlik & Ev Ayakkabısı",
     "Japon tarzı indoor terlik; washable ve koku önleyici",
     "2021'de kuruldu, Japon ev kültüründen ilham alarak Amazon'da DTC satışa başladı"),
    ("Woolybubs", "woolybubs.com", "Terlik & Ev Ayakkabısı",
     "Bebek ve çocuk yün terlik; organik boyama",
     "2019'da kuruldu, organik bebek terlik nişinde Instagram ebeveyn topluluğuyla büyüdü"),
    ("Laidback London Home", "laidbacklondon.com/home", "Terlik & Ev Ayakkabısı",
     "Hint el yapımı deri ve tekstil ev terliği",
     "2019'da sandalet markasının ev terliği uzantısı olarak DTC lansmanı yapıldı"),
    ("Snugtoes", "snugtoes.co.uk", "Terlik & Ev Ayakkabısı",
     "Isıtmalı terlik; USB şarjlı ayak ısıtma sistemi",
     "2020'de İngiltere'de kuruldu, kış aylarında Amazon UK'de bestseller oldu"),

    # =====================================================================
    # 22. Uyku Teknolojisi (10)
    # =====================================================================
    ("Bryte Bed", "brytebed.com", "Uyku Teknolojisi",
     "AI destekli akıllı yatak; gerçek zamanlı sertlik ayarı",
     "2019'da Silikon Vadisi'nde kuruldu, AI uyku teknolojisiyle premium DTC segment oluşturdu"),
    ("Muse Sleep Tracker", "musesleeptracker.com", "Uyku Teknolojisi",
     "EEG tabanlı uyku kalitesi ölçüm bandı; beyin dalgası takibi",
     "2019'da kuruldu, biofeedback uyku teknolojisiyle DTC wellness pazarına girdi"),
    ("Hatch Restore 2", "hatchwellness.com/restore2", "Uyku Teknolojisi",
     "Akıllı uyku lambası ve ses makinesi; uyku rutini oluşturucu",
     "2020'de kuruldu, uyku rutini cihazıyla TikTok'ta viral olarak DTC büyüdü"),
    ("Kokoon Sleep", "kokoon.io", "Uyku Teknolojisi",
     "Uyku odaklı noise-cancelling kulaklık; EEG uyku takibi",
     "2019'da İngiltere'de kuruldu, Kickstarter'da rekor fon toplayarak DTC satışa geçti"),
    ("Rise Science App", "risescience.com/device", "Uyku Teknolojisi",
     "Uyku borcu hesaplayan akıllı cihaz; sirkadiyen ritim optimizasyonu",
     "2020'de kuruldu, uyku bilimi tabanlı teknoloji ürünüyle DTC wellness pazarında büyüdü"),
    ("Loftie Clock", "byloftie.com", "Uyku Teknolojisi",
     "Telefonsuz uyku odası için akıllı alarm saati; beyaz gürültü",
     "2020'de kuruldu, digital detox trendinde Instagram ile DTC büyüdü"),
    ("Motion Pillow", "motionpillow.com", "Uyku Teknolojisi",
     "Horlama algılayan ve baş pozisyonunu ayarlayan akıllı yastık",
     "2019'da Güney Kore'de kuruldu, CES Innovation Award kazanarak global DTC satışa başladı"),
    ("Dreem 3", "dreem.com/3", "Uyku Teknolojisi",
     "EEG uyku optimizasyon bandı; derin uyku artırma teknolojisi",
     "2019'da Fransa'da kuruldu, klinik uyku araştırma teknolojisini tüketici DTC ürününe dönüştürdü"),
    ("Moona Pillow Pad", "moona.co", "Uyku Teknolojisi",
     "Sıcaklık ayarlı yastık pedi; uyku döngüsüne göre soğutma/ısıtma",
     "2019'da Fransa'da kuruldu, Kickstarter başarısından sonra DTC satışa geçti"),
    ("Elemind", "elemind.com", "Uyku Teknolojisi",
     "Nörostimülasyon uyku bandı; beyin dalgalarını senkronize eder",
     "2021'de kuruldu, MIT araştırmasından doğan uyku teknolojisi startup'ı olarak DTC lansmanı yaptı"),

    # =====================================================================
    # 23. Sürdürülebilir Ev Ürünleri (10)
    # =====================================================================
    ("Package Free Home", "packagefreeshop.com/home", "Sürdürülebilir Ev Ürünleri",
     "Sıfır atık ev ürünleri; plastik free alternatifler",
     "2018'de kuruldu, sıfır atık yaşam trendinde Instagram ile DTC büyüdü"),
    ("Pela Home", "pelacase.com/home", "Sürdürülebilir Ev Ürünleri",
     "Kompostlanabilir telefon kılıfı markasının ev ürünleri hattı",
     "2020'de kuruldu, kompostlanabilir malzeme uzmanlığını ev ürünlerine taşıdı"),
    ("Ethique Home Bar", "ethique.com/home", "Sürdürülebilir Ev Ürünleri",
     "Yeni Zelanda merkezli katı ev temizlik barları; plastiksiz",
     "2019'da katı şampuan markasının ev temizlik ürünlerine genişlemesi"),
    ("Aerende Home", "aerende.co.uk", "Sürdürülebilir Ev Ürünleri",
     "İngiltere'de sosyal girişim olarak el yapımı sürdürülebilir ev ürünleri",
     "2018'de kuruldu, dezavantajlı toplulukların el yapımı ürünlerini DTC satışa sundu"),
    ("If You Care Home", "ifyoucare.com/home", "Sürdürülebilir Ev Ürünleri",
     "Çevreci mutfak ve ev ürünleri; FSC sertifikalı",
     "2019'da DTC kanalını genişleterek online doğrudan satışa başladı"),
    ("Full Circle Clean", "fullcirclehome.com/clean", "Sürdürülebilir Ev Ürünleri",
     "Geri dönüştürülmüş malzemeden ev temizlik araçları",
     "2019'da kuruldu, sürdürülebilir temizlik araçlarıyla DTC pazara girdi"),
    ("LastObject Home", "lastobject.com/home", "Sürdürülebilir Ev Ürünleri",
     "Danimarka merkezli yeniden kullanılabilir ev ürünleri; kağıt havlu alternatifi",
     "2019'da Kopenhag'da kuruldu, LastTissue ve LastSwab başarısından sonra ev ürünlerine genişledi"),
    ("Brush & Green", "brushandgreen.com", "Sürdürülebilir Ev Ürünleri",
     "Bambu ev temizlik setleri; plastik free fırça koleksiyonu",
     "2020'de kuruldu, TikTok'ta plastik free ev temizliği trendinde viral oldu"),
    ("Kaia Naturals Home", "kaianaturals.com/home", "Sürdürülebilir Ev Ürünleri",
     "Doğal deodorant markasının sürdürülebilir ev ürünleri hattı",
     "2020'de kişisel bakım markasının ev ürünlerine genişlemesi olarak DTC lansmanı yapıldı"),
    ("Zero Co Home", "zeroco.com.au/home", "Sürdürülebilir Ev Ürünleri",
     "Avustralya merkezli refill sistemi ev temizlik ürünleri",
     "2020'de kuruldu, okyanus plastiğinden şişe ve refill modeliyle DTC viral büyüdü"),

    # =====================================================================
    # 24. Evcil Hayvan Yatak & Tekstil (10)
    # =====================================================================
    ("Topology Pet", "sleepetology.com", "Evcil Hayvan Yatak & Tekstil",
     "Modüler köpek yatağı; değiştirilebilir üst katman sistemi",
     "2019'da İngiltere'de kuruldu, modüler köpek yatağı konseptiyle DTC pet pazarına girdi"),
    ("Mog & Bone", "mogandbone.com.au", "Evcil Hayvan Yatak & Tekstil",
     "Avustralya merkezli tasarım odaklı köpek yatağı; ev dekoruna uyumlu",
     "2019'da Melbourne'da kuruldu, Instagram'da modern pet estetiği nişinde DTC büyüdü"),
    ("Pup & Kit Sleep", "pupandkit.com/sleep", "Evcil Hayvan Yatak & Tekstil",
     "Premium kedi ve köpek uyku ürünleri; ortopedik seçenekler",
     "2019'da kuruldu, premium pet uyku ürünleri segmentinde DTC büyüdü"),
    ("Pawd", "pawd.com", "Evcil Hayvan Yatak & Tekstil",
     "Modern kedi evi ve yatak; minimalist ev dekoruna uyumlu",
     "2020'de kuruldu, kedi mobilyası nişinde Instagram'da estetik tasarımlarıyla DTC büyüdü"),
    ("Charley Chau", "charleychau.com", "Evcil Hayvan Yatak & Tekstil",
     "İngiliz lüks köpek yatağı; el yapımı premium kumaşlar",
     "2018'de İngiltere'de kuruldu, lüks köpek yatağı nişinde DTC online satışa başladı"),
    ("Cloud7 Berlin", "cloud7.de", "Evcil Hayvan Yatak & Tekstil",
     "Berlin merkezli lüks köpek yatağı ve battaniye; Alman tasarım",
     "2019'da Berlin'de kuruldu, Alman tasarım kalitesiyle lüks pet segmentinde DTC büyüdü"),
    ("Dog Threads Bed", "dogthreads.com/beds", "Evcil Hayvan Yatak & Tekstil",
     "Eşleşen köpek-sahip pijama markasının köpek yatağı hattı",
     "2020'de köpek giyim markasının yatak uzantısı olarak DTC lansmanı yapıldı"),
    ("Barka Parka", "barkaparka.com", "Evcil Hayvan Yatak & Tekstil",
     "Lüks köpek yatağı ve outdoor pet tekstili; dayanıklı kumaş",
     "2019'da kuruldu, outdoor pet yatak nişinde Instagram ile DTC büyüdü"),
    ("Pawness", "pawness.com", "Evcil Hayvan Yatak & Tekstil",
     "Hollanda merkezli tasarım kedi ve köpek mobilyası",
     "2019'da Amsterdam'da kuruldu, Hollanda tasarım kalitesiyle lüks pet mobilya DTC satışı başlattı"),
    ("Fable Pets Bed", "fablepets.com/beds", "Evcil Hayvan Yatak & Tekstil",
     "Instagram'ın en estetik köpek yatağı; ev dekoruna entegre tasarım",
     "2020'de kuruldu, estetik pet ürünleri trendinde Instagram ile DTC viral büyüdü"),

    # =====================================================================
    # 25. Outdoor & Piknik Tekstil (10)
    # =====================================================================
    ("Rumpl x National Parks", "rumpl.com/nationalparks", "Outdoor & Piknik Tekstil",
     "Milli park temalı outdoor battaniye koleksiyonu",
     "2020'de milli park iş birliği olarak DTC lansmanı yapıldı, doğa severler arasında viral oldu"),
    ("Tesalate Outdoor", "tesalate.com/outdoor", "Outdoor & Piknik Tekstil",
     "Kum tutmayan plaj örtüsü; Avustralya DTC başarı hikayesi",
     "2018'de Avustralya'da kuruldu, kum tutmayan teknolojisiyle plaj örtüsü nişinde DTC lider oldu"),
    ("Nomadix Towel", "nomadix.co", "Outdoor & Piknik Tekstil",
     "Geri dönüştürülmüş malzemeden outdoor havlu; çabuk kuruyan",
     "2019'da kuruldu, sürdürülebilir outdoor havlu nişinde Instagram ile DTC büyüdü"),
    ("Kelty Outdoor Blanket", "kelty.com/blankets", "Outdoor & Piknik Tekstil",
     "Kamp battaniyesi; su geçirmez alt yüzey teknolojisi",
     "2019'da outdoor markasının DTC battaniye hattı olarak genişleme yaptı"),
    ("Wildtree Blanket", "wildtreeblanket.com", "Outdoor & Piknik Tekstil",
     "Doğa temalı outdoor battaniye; her satıştan ağaç dikimi",
     "2020'de kuruldu, çevreci outdoor topluluğunda sosyal medya ile DTC büyüdü"),
    ("Down Under Outdoors", "downunderoutdoors.com.au", "Outdoor & Piknik Tekstil",
     "Avustralya outdoor piknik battaniyesi; XXL boyut",
     "2019'da kuruldu, Amazon Avustralya'da piknik battaniyesi kategorisinde bestseller oldu"),
    ("Leisure Co Blanket", "leisurecoblanket.com", "Outdoor & Piknik Tekstil",
     "Kompakt katlanır piknik battaniyesi; su geçirmez ve taşınabilir",
     "2020'de kuruldu, Amazon'da outdoor battaniye kategorisinde hızla yükseldi"),
    ("Trek Light Hammock", "treklightgear.com/hammock-blanket", "Outdoor & Piknik Tekstil",
     "Hamak battaniye; hamak ve battaniye fonksiyonu bir arada",
     "2019'da outdoor markasının çok fonksiyonlu ürün hattı olarak DTC genişleme yaptı"),
    ("Laguna Beach Outdoor", "lagunabeachoutdoor.com", "Outdoor & Piknik Tekstil",
     "Lüks outdoor plaj battaniyesi; California yaşam tarzı",
     "2020'de plaj tekstili markasının outdoor hattı olarak DTC lansmanı yapıldı"),
    ("Maho Shades Outdoor", "mahoshades.com/outdoor", "Outdoor & Piknik Tekstil",
     "Outdoor güneş gölgelik ve piknik tekstili; UV koruma",
     "2021'de kuruldu, UV koruma teknolojili outdoor tekstil nişinde Instagram ile DTC büyüdü"),
]
